### ISSUE TITLE
SI 4.2.0 m1 pack xml mapper does not work

### ISSUE THREAD

**Issue by dnwick** [wso2/api-manager#1012]
### Description

it seems xml mapper does not work giving following class not found issue,

[2022-11-24 12:21:08,157] ERROR {org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer} - io.siddhi.core.exception.SiddhiAppCreationException: Error on 'ReceiveHTTPInXMLFormatWithDefaultMapping' @ Line: 57. Position: 21, near '@Source(type = 'http', receiver.url='http://localhost:8006/productionStream', basic.auth.enabled='false',
    @map(type='xml'))'. org/apache/axiom/om/DeferredParsingException org.wso2.carbon.streaming.integrator.core.internal.exception.SiddhiAppDeploymentException: io.siddhi.core.exception.SiddhiAppCreationException: Error on 'ReceiveHTTPInXMLFormatWithDefaultMapping' @ Line: 57. Position: 21, near '@Source(type = 'http', receiver.url='http://localhost:8006/productionStream', basic.auth.enabled='false',
    @map(type='xml'))'. org/apache/axiom/om/DeferredParsingException
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:132)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:358)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: io.siddhi.core.exception.SiddhiAppCreationException: Error on 'ReceiveHTTPInXMLFormatWithDefaultMapping' @ Line: 57. Position: 21, near '@Source(type = 'http', receiver.url='http://localhost:8006/productionStream', basic.auth.enabled='false',
    @map(type='xml'))'. org/apache/axiom/om/DeferredParsingException
	at io.siddhi.core.util.ExceptionUtil.populateQueryContext(ExceptionUtil.java:58)
	at io.siddhi.core.util.ExceptionUtil.populateQueryContext(ExceptionUtil.java:35)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSource(DefinitionParserHelper.java:388)
	at io.siddhi.core.util.SiddhiAppRuntimeBuilder.defineStream(SiddhiAppRuntimeBuilder.java:117)
	at io.siddhi.core.util.parser.SiddhiAppParser.defineStreamDefinitions(SiddhiAppParser.java:375)
	at io.siddhi.core.util.parser.SiddhiAppParser.parse(SiddhiAppParser.java:231)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:87)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:97)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:86)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:102)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: org/apache/axiom/om/DeferredParsingException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at io.siddhi.core.util.SiddhiClassLoader.loadClass(SiddhiClassLoader.java:33)
	at io.siddhi.core.util.SiddhiClassLoader.loadExtensionImplementation(SiddhiClassLoader.java:49)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSource(DefinitionParserHelper.java:354)
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.apache.axiom.om.DeferredParsingException cannot be found by siddhi-map-xml_5.2.2
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 28 more

### Steps to Reproduce

Start the server by adding following siddhi application to wso2/server/deployment/siddhi-files folder

@Source(type = 'http', receiver.url='http://localhost:8006/productionStream', basic.auth.enabled='false',
    @map(type='xml'))
define stream SweetProductionStream (name string, amount double);

@sink(type='log')
define stream LowProductionAlertStream (name string, amount double);

-- passthrough data in the SweetProductionStream into LowProducitonAlertStream
@info(name='query1')
from SweetProductionStream
select *
insert into LowProductionAlertStream;

### Affected Component

SI

### Version

4.2.0-m1

**Comment by dnwick** [comment]
Fix is sent via https://github.com/wso2/carbon-analytics/pull/1987 . Triggered jenkins build seems to be having a issue when trying to deploy the artifacts from maven. Sent a mail to Maheshika "Maven fail to deploy artifacts"

**Comment by dnwick** [comment]
This has been fixed hence closing
