### ISSUE TITLE
ERROR SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404

### ISSUE THREAD

**Issue by IsmailMona** [wso2/api-manager#1046]
### Description

First time I run api manager, I create an api via the publisher site, deploy and publish it via the default gateway. I subscribe to the API using the default application via devportal and try the API and everything is working fine.
If I restart the API manager after it, I get the below errors:

TID: [-1234] [] [2022-11-28 21:06:28,811] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404
TID: [-1234] [] [2022-11-28 21:06:28,827] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404
TID: [-1234] [] [2022-11-28 21:06:28,827]  WARN {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Failed retrieving /api-policies from remote endpoint: Error while retrieving subscription. Retrying after 15 seconds.
TID: [-1234] [] [2022-11-28 21:06:28,827]  WARN {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Failed retrieving /subscription-policies from remote endpoint: Error while retrieving subscription. Retrying after 15 seconds.

When I try to recall the API, I get the below:

{
    "code": "404",
    "type": "Status report",
    "message": "Not Found",
    "description": "The requested resource is not available."
}

### Steps to Reproduce

Create an api via the publisher site, deploy and publish it via the default gateway. 
Subscribe to the API using the default application via devportal and try the API and everything is working fine.
Restart the API manager after it, subscriptions, policies and applications retrieval errors.

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

CarbonCoreActivator Operating System : Windows Server 2019 10.0, amd64
CarbonCoreActivator Java Version     : 11.0.7

### Relevant Log Output

```shell
TID: [-1234] [] [2022-11-28 21:06:28,811] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404
TID: [-1234] [] [2022-11-28 21:06:28,811]  WARN {org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever} - Failed retrieving Blocking Conditions from remote endpoint:. Retrying after 15 seconds...
TID: [-1234] [] [2022-11-28 21:06:28,811]  INFO {org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.DBRetriever} - No artifacts available to deploy
TID: [-1234] [] [2022-11-28 21:06:28,811] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404
TID: [-1234] [] [2022-11-28 21:06:28,827]  INFO {org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener} - Synapse Artifacts deployed Successfully in the Gateway
TID: [-1234] [] [2022-11-28 21:06:28,827] ERROR {org.wso2.carbon.apimgt.throttle.policy.deployer.utils.PolicyUtil} - Error in retrieving throttle policies org.wso2.carbon.apimgt.throttle.policy.deployer.exception.ThrottlePolicyDeployerException: Event-Hub status code is : 404
	at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.getPolicies(PolicyRetriever.java:203)
	at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.getAllSubscriptionPolicies(PolicyRetriever.java:87)
	at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.PolicyUtil.deployAllPolicies(PolicyUtil.java:159)
	at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.ThrottlePolicyStartupListener.run(ThrottlePolicyStartupListener.java:76)
	at java.base/java.lang.Thread.run(Thread.java:834)

TID: [-1234] [] [2022-11-28 21:06:28,827] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404
TID: [-1234] [] [2022-11-28 21:06:28,827]  WARN {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Failed retrieving /api-policies from remote endpoint: Error while retrieving subscription. Retrying after 15 seconds.
TID: [-1234] [] [2022-11-28 21:06:28,827]  WARN {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Failed retrieving /subscription-policies from remote endpoint: Error while retrieving subscription. Retrying after 15 seconds.
TID: [-1234] [] [2022-11-28 21:06:28,827]  WARN {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Failed retrieving /apis?gatewayLabel=Default from remote endpoint: Error while retrieving subscription. Retrying after 15 seconds.
TID: [-1234] [] [2022-11-28 21:06:28,843] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404
TID: [-1234] [] [2022-11-28 21:06:28,843]  WARN {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Failed retrieving /application-policies from remote endpoint: Error while retrieving subscription. Retrying after 15 seconds.
TID: [-1234] [] [2022-11-28 21:06:28,843] ERROR {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404
TID: [-1234] [] [2022-11-28 21:06:28,843]  WARN {org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataLoaderImpl} - Failed retrieving /subscriptions from remote endpoint: Error while retrieving subscription. Retrying after 15 seconds.
TID: [-1234] [] [2022-11-28 21:06:28,843]  WARN {org.wso2.carbon.apimgt.impl.loader.KeyManagerConfigurationDataRetriever} - Failed retrieving Key Manager Configurations from remote endpoint. Retrying after 4 seconds...
TID: [-1234] [] [2022-11-28 21:06:28,843]  WARN {org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever} - Failed retrieving throttling data from remote endpoint. Retrying after 15 seconds...
TID: [-1234] [] [2022-11-28 21:06:28,874] ERROR {org.wso2.carbon.apimgt.gateway.APILoggerManager} - Could not retrieve subscriptions for tenantDomain : carbon.super
TID: [-1234] [] [2022-11-28 21:06:28,874] ERROR {org.wso2.carbon.apimgt.gateway.APILoggerManager} - Error while calling internal service API org.wso2.carbon.apimgt.api.APIManagementException: Error while retrieving subscription from /api-logging-configs
	at org.wso2.carbon.apimgt.gateway.APILoggerManager.invokeService_aroundBody10(APILoggerManager.java:140)
	at org.wso2.carbon.apimgt.gateway.APILoggerManager.invokeService(APILoggerManager.java:98)
	at org.wso2.carbon.apimgt.gateway.APILoggerManager.initializeAPILoggerList_aroundBody0(APILoggerManager.java:58)
	at org.wso2.carbon.apimgt.gateway.APILoggerManager.initializeAPILoggerList(APILoggerManager.java:56)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.completedServerStartup_aroundBody6(GatewayStartupListener.java:186)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.completedServerStartup(GatewayStartupListener.java:156)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyAfter(CarbonCoreServiceComponent.java:264)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:218)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:323)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:118)
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:234)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
	at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1164)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1117)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1010)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4957)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5264)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.wso2.carbon.tomcat.ext.service.ExtendedStandardService.startInternal(ExtendedStandardService.java:52)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.start(CarbonTomcat.java:113)
	at org.wso2.carbon.tomcat.internal.ServerManager$1.run(ServerManager.java:167)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Suggested Labels

priority

**Comment by jan-houcque** [comment]
We are facing the exact same issue.

**Comment by jan-houcque** [comment]
Seems similar to #818
