### ISSUE TITLE
[Integration-studio] Error when trying to load AmazonS3 connector operation properties

### ISSUE THREAD

**Issue by jayasithu** [wso2/api-manager#1051]
### Description

When trying to load the properties view for AWS S3 connector operations a null pointer exception is thrown from the integration studio.

### Steps to Reproduce

1. Unzip the [project.zip](https://github.com/wso2-enterprise/wso2-apim-internal/files/10042431/project.zip) and export the project to integration studio
2. Try to load the properties by right clicking on operation and selecting "show properties view"

### Affected Component

IntegrationStudio

### Version

8.1.0 with latest updates

### Relevant Log Output

```shell
java.lang.NullPointerException
	at org.wso2.integrationstudio.gmf.esb.presentation.EEFPropertyViewUtil.getAvailableConnectionEntriesList(EEFPropertyViewUtil.java:479)
	at org.wso2.integrationstudio.gmf.esb.presentation.ConnectorParameterRenderer.getConnectionEntriesList(ConnectorParameterRenderer.java:156)
	at org.wso2.integrationstudio.gmf.esb.presentation.ConnectorParameterRenderer.evaluateAttribute(ConnectorParameterRenderer.java:142)
	at org.wso2.integrationstudio.gmf.esb.presentation.ConnectorParameterRenderer.recursive(ConnectorParameterRenderer.java:103)
	at org.wso2.integrationstudio.gmf.esb.presentation.ConnectorParameterRenderer.recursive(ConnectorParameterRenderer.java:119)
	at org.wso2.integrationstudio.gmf.esb.presentation.ConnectorParameterRenderer.generate(ConnectorParameterRenderer.java:87)
	at org.wso2.integrationstudio.gmf.esb.presentation.ReferenceGroup.createControls(ReferenceGroup.java:70)
	at org.wso2.integrationstudio.gmf.esb.presentation.ReferenceGroup.createControls(ReferenceGroup.java:82)
	at org.wso2.integrationstudio.gmf.esb.parts.forms.CloudConnectorOperationPropertiesEditionPartForm.createConnectorParametersTableComposition(CloudConnectorOperationPropertiesEditionPartForm.java:449)
	at org.wso2.integrationstudio.gmf.esb.parts.forms.CloudConnectorOperationPropertiesEditionPartForm$1.addToPart(CloudConnectorOperationPropertiesEditionPartForm.java:233)
	at org.eclipse.emf.eef.runtime.ui.parts.PartComposer.composeDelegate(PartComposer.java:62)
	at org.eclipse.emf.eef.runtime.ui.parts.PartComposer.composeDelegate(PartComposer.java:66)
	at org.eclipse.emf.eef.runtime.ui.parts.PartComposer.compose(PartComposer.java:49)
	at org.eclipse.emf.eef.runtime.impl.parts.CompositePropertiesEditionPart.refresh(CompositePropertiesEditionPart.java:172)
	at org.eclipse.emf.eef.runtime.part.impl.SectionPropertiesEditingPart.refresh(SectionPropertiesEditingPart.java:171)
	at org.wso2.integrationstudio.gmf.esb.parts.forms.CloudConnectorOperationPropertiesEditionPartForm.refresh(CloudConnectorOperationPropertiesEditionPartForm.java:1341)
	at org.eclipse.ui.views.properties.tabbed.TabContents$6.run(TabContents.java:220)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.ui.views.properties.tabbed.TabContents.refresh(TabContents.java:223)
	at org.eclipse.ui.views.properties.tabbed.TabbedPropertySheetPage$SelectionChangedListener.selectionChanged(TabbedPropertySheetPage.java:231)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2130)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1176)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1205)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:263)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:421)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4565)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.ui.internal.views.properties.tabbed.view.TabbedPropertyList.select(TabbedPropertyList.java:842)
	at org.eclipse.ui.internal.views.properties.tabbed.view.TabbedPropertyViewer.setSelectionToWidget(TabbedPropertyViewer.java:134)
	at org.eclipse.jface.viewers.StructuredViewer.setSelectionToWidget(StructuredViewer.java:1702)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1658)
	at org.eclipse.jface.viewers.Viewer.setSelection(Viewer.java:376)
	at org.eclipse.ui.views.properties.tabbed.TabbedPropertySheetPage.setInput(TabbedPropertySheetPage.java:744)
	at org.eclipse.ui.views.properties.tabbed.TabbedPropertySheetPage.selectionChanged(TabbedPropertySheetPage.java:555)
	at org.eclipse.gmf.runtime.diagram.ui.properties.views.PropertiesBrowserPage.selectionChanged(PropertiesBrowserPage.java:254)
	at org.eclipse.ui.views.properties.PropertySheet.showSelectionAndDescription(PropertySheet.java:554)
	at org.eclipse.ui.views.properties.PropertySheet.partVisible(PropertySheet.java:427)
	at org.eclipse.ui.part.PageBookView$1.partVisible(PageBookView.java:1040)
	at org.eclipse.ui.internal.WorkbenchPage$17.run(WorkbenchPage.java:5230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.WorkbenchPage.firePartVisible(WorkbenchPage.java:5227)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partVisible(WorkbenchPage.java:258)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$5.run(PartServiceImpl.java:298)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartVisible(PartServiceImpl.java:295)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:111)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5172)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:660)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:624)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:787)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:758)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:680)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:675)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1252)
	at org.eclipse.ui.internal.WorkbenchPage.showPart(WorkbenchPage.java:1256)
	at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1244)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$11(WorkbenchPage.java:4262)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4260)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4242)
	at org.eclipse.gmf.runtime.common.ui.util.WorkbenchPartActivator$ShowViewRunnable.run(WorkbenchPartActivator.java:73)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5172)
	at org.eclipse.gmf.runtime.common.ui.util.WorkbenchPartActivator.showView(WorkbenchPartActivator.java:130)
	at org.eclipse.gmf.runtime.common.ui.util.WorkbenchPartActivator.showPropertySheet(WorkbenchPartActivator.java:180)
	at org.eclipse.gmf.runtime.diagram.ui.actions.ShowPropertiesViewAction.doRun(ShowPropertiesViewAction.java:68)
	at org.eclipse.gmf.runtime.common.ui.action.AbstractActionHandler.run(AbstractActionHandler.java:360)
	at org.eclipse.gmf.runtime.common.ui.action.ActionManager$1.run(ActionManager.java:226)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.gmf.runtime.common.ui.action.ActionManager.run(ActionManager.java:224)
	at org.eclipse.gmf.runtime.common.ui.action.AbstractActionHandler.runWithEvent(AbstractActionHandler.java:378)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4565)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4351)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3927)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by rosensilva** [comment]
Hi @jayasithu,

I tried the given project in the Integration Studio 8.2.0-alpha pack, but the issue was not reproduced. Hence will mark this as done. Please feel free to reopen if you have any concerns.
Thanks!
