### ISSUE TITLE
After Configuring Identity Server as IDP for SSO Gives Error when Signing In

### ISSUE THREAD

**Issue by YasasRangika** [wso2/api-manager#1075]
### Description

After configuring APIM with WSO2-IS for SSO as the documentation guided in [1], it gives the below exception when logging in to any portals.

```
ERROR - DefaultRequestCoordinator Exception in Authentication Framework
java.lang.NoClassDefFoundError: org/apache/xml/security/signature/XMLSignature
	at org.opensaml.xmlsec.signature.impl.SignatureUnmarshaller.unmarshall(SignatureUnmarshaller.java:66) ~[opensaml_3.3.1.wso2v6.jar:?]
	at org.opensaml.xmlsec.signature.impl.SignatureUnmarshaller.unmarshall(SignatureUnmarshaller.java:42) ~[opensaml_3.3.1.wso2v6.jar:?]
	at org.opensaml.core.xml.io.AbstractXMLObjectUnmarshaller.unmarshallChildElement(AbstractXMLObjectUnmarshaller.java:311) ~[opensaml_3.3.1.wso2v6.jar:?]
	at org.opensaml.core.xml.io.AbstractXMLObjectUnmarshaller.unmarshall(AbstractXMLObjectUnmarshaller.java:106) ~[opensaml_3.3.1.wso2v6.jar:?]
	at org.wso2.carbon.identity.application.authenticator.samlsso.util.SSOUtils.unmarshall(SSOUtils.java:413) ~[org.wso2.carbon.identity.application.authenticator.samlsso_5.6.2.jar:?]
	at org.wso2.carbon.identity.application.authenticator.samlsso.manager.DefaultSAML2SSOManager.processSAMLResponse(DefaultSAML2SSOManager.java:386) ~[org.wso2.carbon.identity.application.authenticator.samlsso_5.6.2.jar:?]
	at org.wso2.carbon.identity.application.authenticator.samlsso.manager.DefaultSAML2SSOManager.processResponse(DefaultSAML2SSOManager.java:340) ~[org.wso2.carbon.identity.application.authenticator.samlsso_5.6.2.jar:?]
	at org.wso2.carbon.identity.application.authenticator.samlsso.SAMLSSOAuthenticator.processAuthenticationResponse(SAMLSSOAuthenticator.java:287) ~[org.wso2.carbon.identity.application.authenticator.samlsso_5.6.2.jar:?]
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:92) ~[org.wso2.carbon.identity.application.authentication.framework_5.24.3.jar:?]
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:579) ~[org.wso2.carbon.identity.application.authentication.framework_5.24.3.jar:?]
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:548) ~[org.wso2.carbon.identity.application.authentication.framework_5.24.3.jar:?]
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:215) ~[org.wso2.carbon.identity.application.authentication.framework_5.24.3.jar:?]
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:194) ~[org.wso2.carbon.identity.application.authentication.framework_5.24.3.jar:?]
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:115) ~[org.wso2.carbon.identity.application.authentication.framework_5.24.3.jar:?]
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:190) ~[org.wso2.carbon.identity.application.authentication.framework_5.24.3.jar:?]
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:281) ~[org.wso2.carbon.identity.application.authentication.framework_5.24.3.jar:?]
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:57) ~[org.wso2.carbon.identity.application.authentication.framework_5.24.3.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-servlet-api_9.0.58.wso2v1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-servlet-api_9.0.58.wso2v1.jar:?]
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) ~[org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60) ~[?:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-servlet-api_9.0.58.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88) ~[csrfguard_3.1.0.wso2v4.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:68) ~[org.wso2.carbon.identity.captcha_1.7.1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119) ~[org.wso2.carbon.identity.context.rewrite.valve_1.7.1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:116) ~[org.wso2.carbon.identity.context.rewrite.valve_1.7.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:165) ~[org.wso2.carbon.identity.authz.valve_1.7.1.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:111) ~[org.wso2.carbon.identity.auth.valve_1.7.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat_9.0.58.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.xml.security.signature.XMLSignature cannot be found by opensaml_3.3.1.wso2v6
	... 70 more
```

[1] https://apim.docs.wso2.com/en/4.2.0/reference/customize-product/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso/#configuring-wso2-api-manager-as-service-provider-for-identity-server

### Steps to Reproduce

https://apim.docs.wso2.com/en/4.2.0/reference/customize-product/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso/#configuring-wso2-api-manager-as-service-provider-for-identity-server

### Affected Component

APIM

### Version

APIM-4.2.0-Alpha

**Comment by msm1992** [comment]
**Analysis so far**

* Checked opensaml_3.3.1.wso2v6 for imported packages. It does not list org.apache.xml.security.signature which contains the XMLSignature class mentioned in the stack trace.
```
org.apache.xml.security; version="2.3.0" <org.apache.santuario.xmlsec_2.3.0 [172]>
org.apache.xml.security.exceptions; version="2.3.0" <org.apache.santuario.xmlsec_2.3.0 [172]>
org.apache.xml.security.keys; version="2.3.0" <org.apache.santuario.xmlsec_2.3.0 [172]>
org.apache.xml.security.transforms; version="2.3.0" <org.apache.santuario.xmlsec_2.3.0 [172]>
org.apache.xml.security.transforms.params; version="2.3.0" <org.apache.santuario.xmlsec_2.3.0 [172]>
org.apache.xml.security.utils; version="2.3.0" <org.apache.santuario.xmlsec_2.3.0 [172]>
```

* APIM 4.2.0 has another opensaml_3.3.1.wso2v4 jar as well but, it has org.apache.xml.security.signature as an imported package.
```
org.apache.xml.security; version="1.5.6" <org.apache.santuario.xmlsec_1.5.6 [173]>
org.apache.xml.security.encryption; version="1.5.6" <org.apache.santuario.xmlsec_1.5.6 [173]>
org.apache.xml.security.exceptions; version="1.5.6" <org.apache.santuario.xmlsec_1.5.6 [173]>
org.apache.xml.security.keys; version="1.5.6" <org.apache.santuario.xmlsec_1.5.6 [173]>
org.apache.xml.security.signature; version="1.5.6" <org.apache.santuario.xmlsec_1.5.6 [173]>
org.apache.xml.security.transforms; version="1.5.6" <org.apache.santuario.xmlsec_1.5.6 [173]>
org.apache.xml.security.transforms.params; version="1.5.6" <org.apache.santuario.xmlsec_1.5.6 [173]>
org.apache.xml.security.utils; version="1.5.6" <org.apache.santuario.xmlsec_1.5.6 [173]>
```

* WSO2 IS 6.0.0 also has the opensaml_3.3.1.wso2v6 jar but it has org.apache.xml.security.signature as an imported package. Could not yet figure out a logical reason as to why that is missing in APIM.

**Comment by msm1992** [comment]
**Meeting Notes** (08/12/2022)

**Attendees** : Chamila, Dushani, Tharika, Sachini

**Notes** :
- Since a specific reason for the above behaviour could not be found, it was decided to try out below steps and see.
- Try to use a specific version of xmlsec in orbit opensaml v6
- During the meeting we tried to remove opensaml_3.3.1.wso2v4 from APIM 4.2.0, but this gave startup errors as this version was used in some of the components used in APIM, hence it was decided to upgrade those components first and remove the opensaml_3.3.1.wso2v4 from 4.2.0, because the errornous behaviour might be due to having two versions of the same component.

**Comment by msm1992** [comment]
**Status Update**

- Removed xmlsec 1.5.6 version from APIM 4.2.0 and upgraded xmlsec versions in wso2-wss4j, wso2-rampart and identity-agent-entitlement-proxy components. This resolved the issue with `org.apache.xml.security.signature` being missing.

- I have sent PRs to below components for the xmlsec upgrade. Need to upgrade wss4j, rampart, entitlement.proxy versions in product-apim as well once these PRs are merged.
wso2-wss4j : https://github.com/wso2/wso2-wss4j/pull/89
wso2-rampart : https://github.com/wso2/wso2-rampart/pull/112
identity-agent-entitlement-proxy : https://github.com/wso2-extensions/identity-agent-entitlement-proxy/pull/36
