### ISSUE TITLE
[EI-6.2.0] Unexpected symbol: END_OBJECT when "force.json.message.validation" parameter is set

### ISSUE THREAD

**Issue by imedyaosandi** [wso2/api-manager#1081]
### Description

When processing a json payload larger than 16KB(io buffer size) with "force.json.message.validation" parameter set in passthru-http.properties and if we have content aware mediation which builds json payload in xml we can observe the below error.

```
ERROR - SequenceMediator javax.xml.stream.XMLStreamException: Unexpected symbol: END_OBJECT
org.apache.axiom.om.OMException: javax.xml.stream.XMLStreamException: Unexpected symbol: END_OBJECT
    at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
    at org.apache.axiom.om.impl.llom.OMElementImpl.buildNext(OMElementImpl.java:653)
    at org.apache.axiom.om.impl.llom.OMNodeImpl.getNextOMSibling(OMNodeImpl.java:122)
    at org.apache.axiom.om.impl.llom.OMElementImpl.getNextOMSibling(OMElementImpl.java:343)
    at org.apache.axiom.om.impl.traverse.OMChildrenIterator.getNextNode(OMChildrenIterator.java:36)
    at org.apache.axiom.om.impl.traverse.OMAbstractIterator.hasNext(OMAbstractIterator.java:58)
    at org.jaxen.util.DescendantAxisIterator.hasNext(DescendantAxisIterator.java:101)
    at org.jaxen.expr.DefaultStep.evaluate(DefaultStep.java:152)
    at org.jaxen.expr.DefaultLocationPath.evaluate(DefaultLocationPath.java:140)
    at org.jaxen.expr.DefaultAbsoluteLocationPath.evaluate(DefaultAbsoluteLocationPath.java:113)
    at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:102)
    at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:677)
    at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:216)
    at org.jaxen.BaseXPath.evaluate(BaseXPath.java:175)
    at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:405)
    at org.apache.synapse.mediators.builtin.PropertyMediator.getResultValue(PropertyMediator.java:371)
    at org.apache.synapse.mediators.builtin.PropertyMediator.mediate(PropertyMediator.java:110)
    at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
    at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
    at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
    at org.apache.synapse.rest.Resource.process(Resource.java:351)
    at org.apache.synapse.rest.API.process(API.java:417)
    at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:123)
    at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:101)
    at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
    at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
    at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
    at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
    at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:365)
    at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:411)
    at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:179)
    at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.stream.XMLStreamException: Unexpected symbol: END_OBJECT
    at org.apache.synapse.commons.staxon.core.base.AbstractXMLStreamReader.hasNext(AbstractXMLStreamReader.java:448)
    at org.apache.synapse.commons.staxon.core.base.AbstractXMLStreamReader.next(AbstractXMLStreamReader.java:455)
    at javax.xml.stream.util.StreamReaderDelegate.next(Unknown Source)
    at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
    at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
```

### Steps to Reproduce

1. Set the "force.json.message.validation=true" parameter in passthru-http.properties file and restart the EI server
2. Deploy the below API.
```
<?xml version="1.0" encoding="UTF-8"?>
<api xmlns="http://ws.apache.org/ns/synapse"
     name="NetidClaim-RestApi-_esb_version_"
     context="/sample">
   <resource methods="POST" uri-template="/search">
      <inSequence>
         <log>
            <property xmlns:ns="http://org.apache.synapse/xsd"
                      name="SF JSON-Payload"
                      expression="json-eval($)"/>
         </log>
         <log>
            <property name="SF JSON-Payload" value="===================1"/>
         </log>
         <property name="payload" expression="$body"/>
         <log>
            <property name="SF JSON-Payload" value="===================2"/>
         </log>
         <respond/>
      </inSequence>
      <outSequence/>
      <faultSequence/>
   </resource>
</api>
```
4. Use the below curl command(use a payload larger than 16kb) and invoke the API.
`curl -v  -H "Content-Type:application/json;charset=UTF-8" -H "Transfer-Encoding: chunked" -d@payload.json "http://localhost:8280/sample/search"`

### Affected Component

MI

### Version

6.2.0

### Suggested Labels

bug

**Comment by Tharsanan1** [comment]
Already fixed with: https://github.com/wso2/wso2-synapse/pull/1632
