### ISSUE TITLE
Intermittently getting error when invoking GQL subscriptions via Devportal

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#1085]
```
[2022-12-05 16:56:19,757] ERROR - InboundWebsocketSourceHandler Endpoint not found for port : 8099 tenant domain : null
```

**Comment by wasuradananjith** [comment]
I am getting the whole below stacktrace intermittently

**Comment by BLasan** [comment]
Hi,

Built carbon-mediation with logs in the corresponding place[1] which throw the exception. Product-apim is still building with the snapshot version of the carbon-mediation.
[1] https://github.com/wso2/carbon-mediation/blob/master/components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java#L184

Thanks,
Benura

**Comment by BLasan** [comment]
Hi,

Reproduced the issue today and this error message was getting when executing the query via graphiql (when establishing connection) . When invoking the curl command on the backend no errors getting produced.

Thanks,
Benura

**Comment by BLasan** [comment]
Hi,

Started debugging the `WebSocketInboundHandler` class in carbon-apimgt and `InboundWebSocketSourceHandler` class in carbon-mediation repositories. Different issues are showing up based on the browsers tried out (safari, chrome). In safari via graphiql, web socket connection is not properly working and it does not print the response in the graphiql UI. But in chrome, it gives both certificate issue and the aforementioned issue when invoking the initial request (connection_init one).

```[2023-01-18 16:45:26,805] ERROR - InboundWebsocketSourceHandler Error encountered while processing inbound websocket connection
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480) ~[io.netty.codec_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[io.netty.codec_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.common_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.common_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.common_4.1.79.Final.jar:4.1.79.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:340) ~[?:?]
	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:186) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:681) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:636) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433) ~[?:?]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637) ~[?:?]
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:296) ~[io.netty.handler_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1343) ~[io.netty.handler_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[io.netty.handler_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[io.netty.handler_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[io.netty.codec_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[io.netty.codec_4.1.79.Final.jar:4.1.79.Final]```

```[2023-01-18 16:45:26,805] ERROR - InboundWebsocketSourceHandler Error encountered while processing inbound websocket connection
org.apache.synapse.SynapseException: Endpoint not found for port : 8099 tenant domain : null
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.handleException(InboundWebsocketSourceHandler.java:649) ~[org.wso2.carbon.inbound.endpoint_4.7.161.SNAPSHOT.jar:?]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.channelInactive(InboundWebsocketSourceHandler.java:185) ~[org.wso2.carbon.inbound.endpoint_4.7.161.SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[io.netty.handler_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.MessageAggregator.channelInactive(MessageAggregator.java:436) ~[io.netty.codec_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.MessageAggregator.channelInactive(MessageAggregator.java:436) ~[io.netty.codec_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) ~[io.netty.codec_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:357) ~[io.netty.codec_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) ~[io.netty.codec_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:357) ~[io.netty.codec_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1075) ~[io.netty.handler_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.common_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.common_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.common_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[io.netty.transport_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.common_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.common_4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.common_4.1.79.Final.jar:4.1.79.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]```

Still debugging the two repositories to find out the place which throws the error when initiating the connection.

Thanks,
Benura

**Comment by BLasan** [comment]
Hi,

Tried the `wscat` to reproduce the issue and this error was not getting thrown. When invoked the command, it hits the `channelRead`and `write` functions in the carbon-apimgt and connection was getting initiated without an issue. However, when calling the backend server using `curl` command, `wscat` console does not show the received one as expected. This scenario was carried in one of peer's machine as well, but the same behavior was observed.

Thanks,
Benura

**Comment by BLasan** [comment]
Hi,

Based on the current analysis this is a browser specific issue which occurs in Google Chrome. It gives the `certificate_unknown` even after accepting the certificate via the browser tab. Also, even after accepting when we hit the URL in the browser (endpoint of the API which is deployed in the gateway), APIM logs the following warning message.

```
[2023-01-22 23:04:35,089]  WARN - SourceHandler I/O error: Received fatal alert: certificate_unknown
[2023-01-22 23:04:35,114]  WARN - AccessConfiguration Error loading properties from file: access-log.properties
```
The same issue occurs during the SSL handshake and it causes recieving the aforementioned error message (one mentioned in the ticket description) when initiating the connection via graphiql.

Thanks,
Benura

**Comment by BLasan** [comment]
Hi,

Parking this issue since this is not a `priority/high` issue.

Thanks,
Benura

**Comment by BathiyaL** [comment]
tried this on 3064 pack by with below documentation, but not getting the expected response. 
https://apim.docs.wso2.com/en/latest/tutorials/create-and-publish-a-graphql-api/#step-4-invoke-the-graphql-api-subscription-endpoint

response 
{
  "servlet": "Stapler",
  "message": "No valid crumb was included in the request",
  "url": "/graphql",
  "status": "403"
}

console output
[2023-02-07 15:22:33,701]  WARN - SourceHandler I/O error: Received fatal alert: certificate_unknown

**Comment by dushaniw** [comment]
@BathiyaL What is the browser you tested this in ?

**Comment by dushaniw** [comment]
I have tested in 4.2.0 pre beta release pack with carbon-apimgt version 9.28.71 and didnt get the above issue. Subscriptions worked in graphqil ui without an issue. Worked with chrome with the above backend error printed in the log which @BLasan has mentioned.

**Comment by dushaniw** [comment]
> Hi,
> 
> Based on the current analysis this is a browser specific issue which occurs in Google Chrome. It gives the `certificate_unknown` even after accepting the certificate via the browser tab. Also, even after accepting when we hit the URL in the browser (endpoint of the API which is deployed in the gateway), APIM logs the following warning message.
> 
> ```
> [2023-01-22 23:04:35,089]  WARN - SourceHandler I/O error: Received fatal alert: certificate_unknown
> [2023-01-22 23:04:35,114]  WARN - AccessConfiguration Error loading properties from file: access-log.properties
> ```
> 
> The same issue occurs during the SSL handshake and it causes recieving the aforementioned error message (one mentioned in the ticket description) when initiating the connection via graphiql.
> 
> Thanks, Benura

Tests GraphiQL client with Chrome (Version 110.0.5481.77 official build) and Ubuntu 20.04 with a valid certificate. Its working as expected without any backend errors when initiating the handshake.

1. Generate a simple CA signed certificate for `example.localhost.com, localhost` domains using minica. Ref : https://github.com/jsha/minica, https://letsencrypt.org/docs/certificates-for-localhost/
        `./minica --domains localhost.example.com,localhost`

2. Convert the root and leaf `.pem` files to `.crt` as follows.
       `openssl crl2pkcs7 -nocrl -certfile minica.pem | openssl pkcs7 -print_certs -out minica-cert.crt`
       `openssl crl2pkcs7 -nocrl -certfile cert.pem | openssl pkcs7 -print_certs -out localhost-cert.crt`

3. Convert root and leaf key `.pem` files to `.key` as follows.
      `openssl pkey -in minica-key.pem -out minica-cert.key`
      `openssl pkey -in key.pem -out localhost-cert.key`

4. Follow https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/configuring-keystores/keystore-basics/creating-new-keystores/#creating-a-keystore-using-an-existing-certificate.'
               a. Export the entries of a trust chain into a keystore of .pfx format. Give `wso2carbon` as password.
`openssl pkcs12 -export -in locahost-cert.crt -inkey localhost-cert.key -name "wso2carbon" -certfile minica-cert.crt -out wso2carbon.pfx`
               b. Convert the PKCS12/PFX formatted keystore to a Java keystore.
`keytool -importkeystore -srckeystore wso2carbon.pfx -srcstoretype pkcs12 -destkeystore wso2carbon.jks -deststoretype JKS`
               c. Migrate jks to PKCS12.
`keytool -importkeystore -srckeystore wso2carbon.jks -destkeystore wso2carbon.jks -deststoretype pkcs12`
`keytool -import -alias localhost-minca -file /home/dushani/go/bin/localhost.example.com/wso2/minica-cert.crt -keystore client-truststore.jks -storepass wso2carbon`

5. Replace the `<wso2_home>/repository/resources/security/wso2carbon.jks` with the newly created one.
6. Import the generated leaf cert and the root cert into `<wso2_home>/repository/resources/security/client-trustore.jk`.
`keytool -import -alias localhost -file /home/dushani/go/bin/localhost.example.com/wso2/locahost-cert.crt -keystore client-truststore.jks -storepass wso2carbon`

7. Change the deployment.toml's hostname, internal hostname and other url pointing to `localhost.example.com` hostname.
```
[server]
hostname = "localhost.example.com"
internal_hostname = "localhost.example.com"

....
[[apim.gateway.environment]]
...
ws_endpoint = "ws://localhost.example.com:9099"
wss_endpoint = "wss://localhost.example.com:8099"
....
```

8. Import `wso2carbon.pfx` generated in Step3 b) to the Chrome browser.
![image](https://user-images.githubusercontent.com/12208083/217778930-5c8a7f62-7f8c-4e94-ba5a-4f90dfb7f6d1.png)


9. Add entry to `/etc/hosts`.
```
127.0.0.1       localhost.example.com
```
