### ISSUE TITLE
APIM 4.2.0-SNAPSHOT distribution server startup error

### ISSUE THREAD

**Issue by prasa7** [wso2/api-manager#1093]
### Description

[2022-12-06 16:55:19,454] ERROR - StreamInterceptorsLoader Error creating Interceptor for class name : org.wso2.carbon.apimgt.gateway.handlers.streaming.sse.interceptors.SseResponseStreamInterceptor
java.lang.ClassNotFoundException: org.wso2.carbon.apimgt.gateway.handlers.streaming.sse.interceptors.SseResponseStreamInterceptor cannot be found by synapse-nhttp-transport_4.0.0.wso2v1
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.apache.synapse.transport.passthru.util.StreamInterceptorsLoader.createInterceptor(StreamInterceptorsLoader.java:110) ~[synapse-nhttp-transport_4.0.0.wso2v1.jar:?]
	at org.apache.synapse.transport.passthru.util.StreamInterceptorsLoader.loadInterceptors(StreamInterceptorsLoader.java:93) ~[synapse-nhttp-transport_4.0.0.wso2v1.jar:?]
	at org.apache.synapse.transport.passthru.util.StreamInterceptorsLoader.getInterceptors(StreamInterceptorsLoader.java:68) ~[synapse-nhttp-transport_4.0.0.wso2v1.jar:?]
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.init(PassThroughHttpSender.java:212) ~[synapse-nhttp-transport_4.0.0.wso2v1.jar:?]
	at org.apache.axis2.context.ConfigurationContextFactory.initTransportSenders(ConfigurationContextFactory.java:300) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.apache.axis2.context.ConfigurationContextFactory.init(ConfigurationContextFactory.java:231) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:93) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.wso2.carbon.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:65) ~[org.wso2.carbon.core_4.8.0.m1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:415) ~[org.wso2.carbon.core_4.8.0.m1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) ~[org.wso2.carbon.core_4.8.0.m1.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) ~[org.wso2.carbon.core_4.8.0.m1.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
[2022-12-06 16:55:19,454] FATAL - CarbonServerManager WSO2 Carbon initialization Failed
java.lang.RuntimeException: Error creating Interceptor for class name : org.wso2.carbon.apimgt.gateway.handlers.streaming.sse.interceptors.SseResponseStreamInterceptor
	at org.apache.synapse.transport.passthru.util.StreamInterceptorsLoader.handleException(StreamInterceptorsLoader.java:157) ~[synapse-nhttp-transport_4.0.0.wso2v1.jar:?]
	at org.apache.synapse.transport.passthru.util.StreamInterceptorsLoader.createInterceptor(StreamInterceptorsLoader.java:112) ~[synapse-nhttp-transport_4.0.0.wso2v1.jar:?]
	at org.apache.synapse.transport.passthru.util.StreamInterceptorsLoader.loadInterceptors(StreamInterceptorsLoader.java:93) ~[synapse-nhttp-transport_4.0.0.wso2v1.jar:?]
	at org.apache.synapse.transport.passthru.util.StreamInterceptorsLoader.getInterceptors(StreamInterceptorsLoader.java:68) ~[synapse-nhttp-transport_4.0.0.wso2v1.jar:?]
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.init(PassThroughHttpSender.java:212) ~[synapse-nhttp-transport_4.0.0.wso2v1.jar:?]
	at org.apache.axis2.context.ConfigurationContextFactory.initTransportSenders(ConfigurationContextFactory.java:300) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.apache.axis2.context.ConfigurationContextFactory.init(ConfigurationContextFactory.java:231) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:93) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.wso2.carbon.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:65) ~[org.wso2.carbon.core_4.8.0.m1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:415) ~[org.wso2.carbon.core_4.8.0.m1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) ~[org.wso2.carbon.core_4.8.0.m1.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) ~[org.wso2.carbon.core_4.8.0.m1.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.apimgt.gateway.handlers.streaming.sse.interceptors.SseResponseStreamInterceptor cannot be found by synapse-nhttp-transport_4.0.0.wso2v1
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.apache.synapse.transport.passthru.util.StreamInterceptorsLoader.createInterceptor(StreamInterceptorsLoader.java:110) ~[synapse-nhttp-transport_4.0.0.wso2v1.jar:?]
	... 13 more

### Steps to Reproduce

Start the pack after the synapse update

### Affected Component

APIM

### Version

4.2.0

**Comment by prasa7** [comment]
HI All, 

After debugging and analysing the rout cause for the issue was found. It was due to the following commons io version upgrade[1].
[1] - https://github.com/wso2/wso2-synapse/pull/1993/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R1546

Further it lead to a  and API Innovation issue and an out of memory issue.
<img width="1512" alt="Screen Shot 2022-12-12 at 5 10 39 PM" src="https://user-images.githubusercontent.com/805274/207502708-6eb940ed-a77e-4db9-92b4-712b7fe91ec1.png">


Then this update was reverted using the following PR .
https://github.com/wso2/wso2-synapse/pull/2035/files

With the above changes wso2-synapse v4.0.0-wso2v5 was released

https://github.com/wso2/wso2-synapse/tree/v4.0.0-wso2v5

When trying to release the carbon-mediation, release build got failed for three times due to intermittent issues in jenkins.
<img width="851" alt="Screenshot 2022-12-14 at 09 33 31" src="https://user-images.githubusercontent.com/805274/207503003-885b0d47-8e3d-48a3-a2d0-d46a1108d33d.png">

Currently releasing the carbon-mediation.

Tasks to follow
Release carbon-apimgt
Release product-apim

Thanks
@prasa7

**Comment by prasa7** [comment]
Fixed afte reverting commons io update.
