### ISSUE TITLE
Error importing openapi definition using url

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#1134]
### Description

There is an issue when importing an openAPI definition using a url. File upload works fine. The following error is logged.

```
[2022-12-14 20:03:45,904] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433) ~[json_3.0.0.wso2v1.jar:?]
	at org.json.JSONObject.<init>(JSONObject.java:194) ~[json_3.0.0.wso2v1.jar:?]
	at org.json.JSONObject.<init>(JSONObject.java:321) ~[json_3.0.0.wso2v1.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.removeUnsupportedBlocksFromResources_aroundBody120(OASParserUtil.java:1723) ~[org.wso2.carbon.apimgt.impl_9.28.19.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.removeUnsupportedBlocksFromResources(OASParserUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.19.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.validateAPIDefinitionByURL_aroundBody64(OASParserUtil.java:1065) ~[org.wso2.carbon.apimgt.impl_9.28.19.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.validateAPIDefinitionByURL(OASParserUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.19.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.restapi.publisher.ApisApiServiceImplUtils.validateOpenAPIDefinition_aroundBody20(ApisApiServiceImplUtils.java:610) ~[org.wso2.carbon.apimgt.impl_9.28.19.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.restapi.publisher.ApisApiServiceImplUtils.validateOpenAPIDefinition(ApisApiServiceImplUtils.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.19.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.validateOpenAPIDefinition(ApisApiServiceImpl.java:3491) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.validateOpenAPIDefinition(ApisApiServiceImpl.java:2736) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.validateOpenAPIDefinition(ApisApi.java:1814) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[?:?]
```

### Steps to Reproduce

Import an API using an open api url

### Affected Component

APIM

### Version

4.2.0-SNAPSHOT

**Comment by tharikaGitHub** [comment]
This is solved when providing the raw content url if the api definition is obtained from Github. Therefore this issue is invalid.
