### ISSUE TITLE
[4.0.0] - The secondary userstore users cannot create a new SSE API

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/api-manager#1137]
### Description

The secondary userstore user cannot deploy SSE API (Streaming API -  Server-Sent Events API). The API creation failed with the authorization issue.

### Steps to Reproduce

- Configured APIM with the secondary userstore ( Read Only LDAP). The user store domain is B2E. We used WSO2 IS 5.11.0 server's LDAP userstore in this case.
- Created a new user in the LDAP userstore and assign the below roles to that user via the IS server's carbon management console.
   - B2E/ADAM_CREATOR
   - B2E/ADAM_PUBLISHER
   - B2E/ADAM_SUBSCRIBER
- Then mapped the relevant internal user roles to the above roles via the admin portal.
    - B2E/ADAM_CREATOR   - > Internal/creator
    - B2E/ADAM_PUBLISHER  - > Internal/publisher
    - B2E/ADAM_SUBSCRIBER  - > Internal/subscriber
- Then log in to the publisher portal using the secondary userstore user credential and deployed a sample REST API.
- We were able to deploy the REST API without any issues.
- Then tried to deploy an SSE API (Streaming API -  Server-Sent Events API) and it failed with the below error trace.

### Affected Component

APIM

### Version

4.0.0

### Relevant Log Output

```shell
[2022-12-13 18:03:58,808] ERROR - Repository Failed to add new resource. User B2E/test does not have authorization to update the collection /_system/governance/apimgt/applicationdata/provider/B2E/test.
[2022-12-13 18:03:58,809] ERROR - APIUtil Error while adding AsyncApi Definition for test-v1
org.wso2.carbon.registry.core.exceptions.RegistryException: Unable to put resource Failed to add new resource. User B2E/test does not have authorization to update the collection /_system/governance/apimgt/applicationdata/provider/B2E/test.
at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:299) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:808) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.session.UserRegistry.access$900(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.session.UserRegistry$10.run(UserRegistry.java:798) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.session.UserRegistry$10.run(UserRegistry.java:795) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:795) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.apimgt.impl.definitions.AsyncApiParserUtil.saveAPIDefinition_aroundBody8(AsyncApiParserUtil.java:149) [org.wso2.carbon.apimgt.impl_9.0.174.245.jar:?]
at org.wso2.carbon.apimgt.impl.definitions.AsyncApiParserUtil.saveAPIDefinition(AsyncApiParserUtil.java:132) [org.wso2.carbon.apimgt.impl_9.0.174.245.jar:?]
at org.wso2.carbon.apimgt.impl.APIProviderImpl.saveAsyncApiDefinition_aroundBody502(APIProviderImpl.java:8409) [org.wso2.carbon.apimgt.impl_9.0.174.245.jar:?]
at org.wso2.carbon.apimgt.impl.APIProviderImpl.saveAsyncApiDefinition(APIProviderImpl.java:8405) [org.wso2.carbon.apimgt.impl_9.0.174.245.jar:?]
at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.saveAsyncApiDefinition(UserAwareAPIProvider.java:1) [org.wso2.carbon.apimgt.impl_9.0.174.245.jar:?]
at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.PublisherCommonUtils.addAPIWithGeneratedSwaggerDefinition(PublisherCommonUtils.java:820) [org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.236.jar:?]
at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.createAPI(ApisApiServiceImpl.java:311) [classes/:?]
at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.createAPI(ApisApi.java:265) [classes/:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.5.0.jar:3.5.0]
at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.5.0.jar:3.5.0]
at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.5.0.jar:3.5.0]
at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.5.0.jar:3.5.0]
at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.5.0.jar:3.5.0]
at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.5.0.jar:3.5.0]
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) [cxf-core-3.5.0.jar:3.5.0]
at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.5.0.jar:3.5.0]
at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) [tomcat-servlet-api_9.0.52.wso2v1.jar:?]
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.52.wso2v2.jar:?]
at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) [org.wso2.carbon.identity.context.rewrite.valve_1.4.25.jar:?]
at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.25.jar:?]
at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:112) [org.wso2.carbon.identity.auth.valve_1.4.25.16.jar:?]
at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101) [org.wso2.carbon.tomcat.ext_4.6.2.168.jar:?]
at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.2.168.jar:?]
at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.2.168.jar:?]
at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.2.168.jar:?]
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [tomcat_9.0.52.wso2v2.jar:?]
at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:59) [org.wso2.carbon.tomcat.ext_4.6.2.168.jar:?]
at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) [org.wso2.carbon.tomcat.ext_4.6.2.168.jar:?]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat_9.0.52.wso2v2.jar:?]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.52.wso2v2.jar:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to add new resource. User B2E/test does not have authorization to update the collection /_system/governance/apimgt/applicationdata/provider/B2E/test.
at org.wso2.carbon.registry.core.jdbc.Repository.addEmptyCollection(Repository.java:1167) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.jdbc.Repository.addEmptyCollection(Repository.java:1156) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.jdbc.Repository.add(Repository.java:1013) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.jdbc.Repository.put(Repository.java:305) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:717) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:292) ~[org.wso2.carbon.registry.core_4.6.2.jar:?]
... 72 more
```

**Comment by PasanT9** [comment]
Issue is not producible in master.
