### ISSUE TITLE
EI rsa-sha2 support for SFTP

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/api-manager#1160]
### Problem

As the current EI-6.6.0 implementation does not support rsa-sha2 keys to connect with SFTP servers, please provide the support.

### Solution

 provide the support to rsa-sha2 keys to connect with SFTP servers

### Affected Component

APIM

### Version

EI-6.6.0

**Comment by GihanAyesh** [comment]
The fix is done to the EI-6.6.0

However, it will not be added to public repo as it can be resolved by using system variables in the startup
`-Djsch.server_host_key= ssh-rsa,ssh-dss`

**Comment by HemantSingh087** [comment]
We are getting this error on SFTP file search now after patching update from level 82 to 151

TID: [-1234] [] [2023-05-04 10:00:37,050] ERROR {org.wso2.carbon.connector.FileSearch} - Unable to search a file. org.apache.commons.vfs2.FileSystemException: Could not connect to SFTP server at "{org.apache.commons.vfs2.provider.ftp.FtpFileSystem.org.apache.commons.vfs2.provider.ftp.FtpFileSystemConfigBuilder.PASSIVE=true, org.apache.commons.vfs2.provider.ftp.FtpFileSystem.org.apache.commons.vfs2.provider.ftp.FtpFileSystemConfigBuilder.SO_TIMEOUT=100000, org.apache.commons.vfs2.provider.sftp.SftpFileSystem.avoidpermissioncheck=null, org.apache.commons.vfs2.provider.sftp.SftpFileSystem.org.apache.commons.vfs2.provider.sftp.SftpFileSystemConfigBuilder.STRICT_HOST_KEY_CHECKING=no, org.apache.commons.vfs2.provider.sftp.SftpFileSystem.org.apache.commons.vfs2.provider.sftp.SftpFileSystemConfigBuilder.TIMEOUT=100000, org.apache.commons.vfs2.provider.sftp.SftpFileSystem.org.apache.commons.vfs2.provider.sftp.SftpFileSystemConfigBuilder.USER_DIR_IS_ROOT=false}".
        at org.apache.commons.vfs2.provider.sftp.SftpClient.ensureSession(SftpClient.java:106)
        at org.apache.commons.vfs2.provider.sftp.SftpClient.<init>(SftpClient.java:42)
        at org.apache.commons.vfs2.provider.sftp.SftpFileSystem.<init>(SftpFileSystem.java:60)
        at org.apache.commons.vfs2.provider.sftp.SftpFileProvider.doCreateFileSystem(SftpFileProvider.java:71)
        at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.getFileSystem(AbstractOriginatingFileProvider.java:158)
        at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:112)
        at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:82)
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:778)
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:658)
        at org.wso2.carbon.connector.FileSearch.search(FileSearch.java:75)
        at org.wso2.carbon.connector.FileSearch.connect(FileSearch.java:54)
        at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)
        at org.apache.synapse.mediators.ext.ClassMediator.updateInstancePropertiesAndMediate(ClassMediator.java:177)
        at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:97)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:135)
        at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:148)
        at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:84)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.mediators.MediatorWorker.run(MediatorWorker.java:88)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not connect to SFTP server at "sftp.macmillan.co.uk".
        at org.apache.commons.vfs2.provider.sftp.SftpClientFactory.createConnection(SftpClientFactory.java:187)
        at org.apache.commons.vfs2.provider.sftp.SftpClient.ensureSession(SftpClient.java:100)
        ... 25 more
Caused by: com.jcraft.jsch.JSchException: Session.connect: java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 2048 (inclusive)
        at com.jcraft.jsch.Session.connect(Session.java:579)
        at com.jcraft.jsch.Session.connect(Session.java:194)
        at org.apache.commons.vfs2.provider.sftp.SftpClientFactory.createConnection(SftpClientFactory.java:185)
        ... 26 more
Caused by: java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 2048 (inclusive)
        at com.sun.crypto.provider.DHKeyPairGenerator.initialize(DHKeyPairGenerator.java:120)
        at java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:674)
        at java.security.KeyPairGenerator.initialize(KeyPairGenerator.java:411)
        at com.jcraft.jsch.jce.DH.getE(DH.java:59)
        at com.jcraft.jsch.DHGEX.next(DHGEX.java:139)
        at com.jcraft.jsch.Session.connect(Session.java:340)
        ... 28 more
