### ISSUE TITLE
Error while updating lifecycle of API

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/api-manager#1167]
### Description

Using the 199 updated pack of the APIM 3.2.0 product recently observed the below error trace when publishing a new API via both the APICTL tool and the publisher portal.

### Steps to Reproduce

Reproducing steps

- Publish a sample API.
- Then manually change one of the url_pattern to null by directly modifying the database record.  
- Login to the carbon management console and enable the send notification feature.
- Browse the registry DB via the carbon management console and locate the tenant-conf.json file (/_system/config/apimgt/applicationdata/tenant-conf.json).
- Then modify the tenant-conf.json by setting the NotificationsEnabled parameter to true. "NotificationsEnabled": "true"
- Save the changes.
- Then try to publish a new API using the same user and got the above error trace.

### Affected Component

APICTL

### Version

3.2.0

### Relevant Log Output

```shell
[2022-11-29 18:00:20,097] ERROR - GovernanceArtifactImpl Invoking lifecycle action "Publish" failed. An exception occurred while executing handler chain. null
org.wso2.carbon.registry.core.exceptions.RegistryException: An exception occurred while executing handler chain. null
at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.invokeAspect(HandlerManager.java:2818) ~[org.wso2.carbon.registry.core_4.6.0.94.jar:?]
at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.invokeAspect(HandlerLifecycleManager.java:518) ~[org.wso2.carbon.registry.core_4.6.0.94.jar:?]
at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.invokeAspect(EmbeddedRegistry.java:2607) ~[org.wso2.carbon.registry.core_4.6.0.94.jar:?]
at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.invokeAspect(CacheBackedRegistry.java:510) ~[org.wso2.carbon.registry.core_4.6.0.94.jar:?]
at org.wso2.carbon.registry.core.session.UserRegistry.invokeAspect(UserRegistry.java:1964) ~[org.wso2.carbon.registry.core_4.6.0.94.jar:?]
at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:829) [org.wso2.carbon.governance.api_4.8.19.jar:?]

Caused by: java.lang.NullPointerException
at org.wso2.carbon.apimgt.api.model.URITemplate.hashCode(URITemplate.java:377) ~[org.wso2.carbon.apimgt.api_6.7.206.337.jar:?]
at java.util.HashMap.hash(HashMap.java:339) ~[?:?]
at java.util.HashMap.put(HashMap.java:607) ~[?:?]
at java.util.HashSet.add(HashSet.java:220) ~[?:?]
at java.util.AbstractCollection.addAll(AbstractCollection.java:352) ~[?:?]
at java.util.LinkedHashSet.<init>(LinkedHashSet.java:169) ~[?:?]
at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getURITemplatesOfAPI_aroundBody324(ApiMgtDAO.java:7477) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getURITemplatesOfAPI(ApiMgtDAO.java:7414) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAPI_aroundBody2(APIUtil.java:505) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAPI(APIUtil.java:404) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getAPI_aroundBody110(UserAwareAPIProvider.java:472) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getAPI(UserAwareAPIProvider.java:471) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIsByProvider_aroundBody8(APIProviderImpl.java:359) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIsByProvider(APIProviderImpl.java:340) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getAPIsByProvider(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
at org.wso2.carbon.apimgt.impl.APIProviderImpl.getOldPublishedAPIList_aroundBody130(APIProviderImpl.java:2651) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
at org.wso2.carbon.apimgt.impl.APIProviderImpl.getOldPublishedAPIList(APIProviderImpl.java:2649) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
at org.wso2.carbon.apimgt.impl.APIProviderImpl.sendEmailNotification_aroundBody132(APIProviderImpl.java:2684) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
at org.wso2.carbon.apimgt.impl.APIProviderImpl.sendEmailNotification(APIProviderImpl.java:2670) ~[org.wso2.carbon.apimgt.impl_6.7.206.354.jar:?]
```

**Comment by lakshithagunasekara** [comment]
Fix is already sent for patches. Public fix missing
