### ISSUE TITLE
Gateway subscriptions map does not include application and api UUID for subscriptions

### ISSUE THREAD

**Issue by lakshithagunasekara** [wso2/api-manager#1168]
### Description

The gateway subscriptions map includes all the subscriptions details however for each subscription, apiUUID and applicationUUID is missing. This is populated when the map is updated from the gateway events, however when we pull the subscription information at the gateway startup, these fields of every subscription left as null. 

These values are used in the gateway REST API operation (GET https://localhost:9443/api/am/gateway/v2/subscriptions?apiUUID=<APIUUID>&appUUID=<APP_UUID>&tenantDomain=<TENANT>) and due to this issue, subscriptions that are loaded at the startup returns a 500 Internal server error response and a NPE logged in the logs.

This is due to an error in the mapping from the GET  /subscriptions internal REST API response to the subscriptions map. The gson library that does the mapping cannot correlate applicationUUID and apiUUID from the response to appUUID and apiUUId in the subscriptions DTO.

### Steps to Reproduce

Steps

1. Publish API and subscribe to it using an application. (get the application uuid and api uuid )
2. Restart the server
3. Invoke following gateway rest API (replace apiUUID and appUUID with the values taken from step 1)

```
curl -k -H "Authorization: Basic YWRtaW46YWRtaW4=" "https://localhost:9443/api/am/gateway/v2/subscriptions?apiUUID=<api_uuid>&appUUID=<app_id>&tenantDomain=carbon.super"
```

### Affected Component

APIM

### Version

4.0.0, 4.1.0

### Relevant Log Output

```shell
2022-12-21 06:38:40,918] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
        at org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl.getSubscriptionByUUID_aroundBody82(SubscriptionDataStoreImpl.java:709) ~[org.wso2.carbon.apimgt.keymgt_9.0.174.216.jar:?]
        at org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl.getSubscriptionByUUID(SubscriptionDataStoreImpl.java:705) ~[org.wso2.carbon.apimgt.keymgt_9.0.174.216.jar:?]
        at org.wso2.carbon.apimgt.rest.api.gateway.impl.SubscriptionsApiServiceImpl.subscriptionsGet(SubscriptionsApiServiceImpl.java:31) ~[classes/:?]
        at org.wso2.carbon.apimgt.rest.api.gateway.SubscriptionsApi.subscriptionsGet(SubscriptionsApi.java:49) ~[classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.5.0.jar:3.5.0]
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.5.0.jar:3.5.0]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.5.0.jar:3.5.0]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.5.0.jar:3.5.0]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.5.0.jar:3.5.0]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.5.0.jar:3.5.0]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) [cxf-core-3.5.0.jar:3.5.0]
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.5.0.jar:3.5.0]
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
```

**Comment by lakshithagunasekara** [comment]
The fix is already sent via patches. Need to add to master

**Comment by lakshithagunasekara** [comment]
Changes are already added to the master
