### ISSUE TITLE
Webocket Topic with a space to the end prevents endpoint from deploying

### ISSUE THREAD

**Issue by 1akshitha** [wso2/api-manager#118]
### Description:
If we accidentally added a space to the end of websocket API, during the deployment, endpoint specific to this topic will not deploy and there will be errors.

``` 
[2022-05-25 11:24:53,464]  INFO - DependencyTracker Endpoint : WebSocket--v1.0.0_APIproductionEndpoint_template__rooms_(roomID)  was added to the Synapse configuration successfully
[2022-05-25 11:25:09,035]  INFO - DependencyTracker Endpoint : WebSocket--v1.0.0_APIsandboxEndpoint_template__rooms_(roomID)  was added to the Synapse configuration successfully
[2022-05-25 11:26:26,613] ERROR - EndpointAdminServiceProxy Error deleting endpoint from gateway
java.lang.NullPointerException: null
	at org.wso2.carbon.endpoint.service.EndpointAdmin.deleteEndpoint(EndpointAdmin.java:297) ~[org.wso2.carbon.endpoint_4.7.131.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint_aroundBody2(EndpointAdminServiceProxy.java:82) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint(EndpointAdminServiceProxy.java:76) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:693) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:98) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:87) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.lambda$0_aroundBody12(GatewayJMSMessageListener.java:154) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.lambda$0(GatewayJMSMessageListener.java:131) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[2022-05-25 11:26:26,634] ERROR - InMemoryAPIDeployer Error deploying 7ba4ce48-68ff-45c6-ba19-b3ec4e4fd00f in Gateway
org.apache.axis2.AxisFault: Error while deleting the endpoint filenull
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint_aroundBody2(EndpointAdminServiceProxy.java:88) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint(EndpointAdminServiceProxy.java:76) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:693) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:98) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:87) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.lambda$0_aroundBody12(GatewayJMSMessageListener.java:154) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.lambda$0(GatewayJMSMessageListener.java:131) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.endpoint.service.EndpointAdmin.deleteEndpoint(EndpointAdmin.java:297) ~[org.wso2.carbon.endpoint_4.7.131.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint_aroundBody2(EndpointAdminServiceProxy.java:82) ~[org.wso2.carbon.apimgt.gateway_9.20.74.5.jar:?]
	... 8 more
[2022-05-25 11:26:26,634] ERROR - GatewayJMSMessageListener Error in deploying artifacts for 7ba4ce48-68ff-45c6-ba19-b3ec4e4fd00fin the Gateway
```

In the REST APIs, we are validating the input and we don't allow spaces in the resources. We need to add the same validation for websocket APIs.

If we fix this from the code base, when we check for endpoints availability, we trim the endpoint name. However during the delete step, we don't and this has been the reason for this inconsistent behavior. 

[1] - https://github.com/wso2/carbon-mediation/blob/master/components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/service/EndpointAdmin.java#L1078
[2] - https://github.com/wso2/carbon-mediation/blob/master/components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/service/EndpointAdmin.java#L291

### Steps to reproduce:
Create a websocket api and add a space to the topic.

### Affected product version:
4.1.0

### Affected component:
Websocket

**Comment by shnrndk** [comment]
Already Fixed 
<img width="1498" alt="Screenshot 2022-09-29 at 11 06 29" src="https://user-images.githubusercontent.com/43110114/192947854-6aec65c8-4174-45ea-abf8-43608e977578.png">
