### ISSUE TITLE
Subscription blocking functionality of Publisher Portal is not working as expected

### ISSUE THREAD

**Issue by JanithaSampathBandara** [wso2/api-manager#1185]
### Description

Trying to block the subscription from Publisher Portal but ended up with an Internal server error. As per the investigation, **this happens when the subscriber’s username includes dashes(eg: janitha-bandara)** within it.

### Steps to Reproduce

1. Create and publish an API.
2. Create a user with an **Internal/subscriber** role whose name has dashes(eg: janitha-bandara) from the carbon console.
3. Log into Devportal with newly created user credentials.
4. Subscribe to the newly created API using DefaultApplication.
5. Log into Publisher Portal using admin credentials.
6. Select the API and navigate to **Subscriptions** section under **Portal Configurations**.
7. Click on **Block Production Only** or **Block All** for the particular user record.

### Notes

1. Regardless of the Publisher Portal selection(Block Production Only/Block All), it is always trying to add block conditions for production keys only[1].

2. When the username is **janitha-bandara** and application name is **DefaultApplication**, value of **applicationIdentifier**[2] will be **janitha-bandara-DefaultApplication**. Then, **appOwner** and **appName** variables getting assigned by splitting[3] the **applicationIdentifier** as below.
```
String[] app = applicationIdentifier.split("-", 2);
String appOwner = app[0];
String appName = app[1];
```
Since the limit for the split function is 2, **janitha** will be taken as **appOwner** and **bandara-DefaultApplication** will be taken as **appName**. Hence, this condition[4] which is to validate the application is getting failed.

[1]https://github.com/wso2/carbon-apimgt/blob/14aa6c57649815b7d45916da075acacf55d5bc1d/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/SubscriptionsApiServiceImpl.java#L124

[2]https://github.com/wso2/carbon-apimgt/blob/14aa6c57649815b7d45916da075acacf55d5bc1d/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java#L12674

[3]https://github.com/wso2/carbon-apimgt/blob/14aa6c57649815b7d45916da075acacf55d5bc1d/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java#L12676

[4]https://github.com/wso2/carbon-apimgt/blob/14aa6c57649815b7d45916da075acacf55d5bc1d/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java#L12694

### Affected Component

APIM

### Version

4.0.0

### Relevant Log Output

```shell
ERROR - SubscriptionsApiServiceImpl Error while blocking the subscription 3495ad23-6646-4a26-8c70-8b11d3fe0cb1
org.wso2.carbon.apimgt.api.APIManagementException: **Couldn't Save Subscription Block Condition Due to Invalid Application name bandara-DefaultApplication from Application Owner janitha**
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addBlockConditions_aroundBody580(ApiMgtDAO.java:12737) ~[org.wso2.carbon.apimgt.impl_9.0.174.247.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addBlockConditions(ApiMgtDAO.java:12656) ~[org.wso2.carbon.apimgt.impl_9.0.174.247.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addBlockCondition_aroundBody342(APIProviderImpl.java:6670) ~[org.wso2.carbon.apimgt.impl_9.0.174.247.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addBlockCondition(APIProviderImpl.java:6658) ~[org.wso2.carbon.apimgt.impl_9.0.174.247.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addBlockCondition(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.0.174.247.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.SubscriptionsApiServiceImpl.blockSubscription(SubscriptionsApiServiceImpl.java:126) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.SubscriptionsApi.blockSubscription(SubscriptionsApi.java:56) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_341]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_341]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_341]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.5.0.jar:3.5.0]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.5.0.jar:3.5.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.5.0.jar:3.5.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.5.0.jar:3.5.0]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.5.0.jar:3.5.0]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.5.0.jar:3.5.0]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) [cxf-core-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:696) [tomcat-servlet-api_9.0.52.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) [cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.52.wso2v2.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) [org.wso2.carbon.identity.context.rewrite.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:112) [org.wso2.carbon.identity.auth.valve_1.4.25.16.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101) [org.wso2.carbon.tomcat.ext_4.6.2.168.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.2.168.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.2.168.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.2.168.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [tomcat_9.0.52.wso2v2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:59) [org.wso2.carbon.tomcat.ext_4.6.2.168.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) [org.wso2.carbon.tomcat.ext_4.6.2.168.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat_9.0.52.wso2v2.jar:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.52.wso2v2.jar:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_341]
```

**Comment by lakshithagunasekara** [comment]
Closing as the update is released for APIM 4.0.0
