### ISSUE TITLE
MI Dashboard server startup error when MI has synapse artefacts with long descriptions

### ISSUE THREAD

**Issue by AyeshUvindu** [wso2/api-manager#1189]
### Description

MI Dashboard throws errors in server startup when MI has synapse artifacts with long descriptions.

### Steps to Reproduce

- Get an updated MI 4.1.0 pack and MI dashboard 4.1.0 pack.
- Configure the Dashboard with the MI server.
- Deploy a Data service that has a long description (more than 5000 characters)
- You will see below errors in MI dashboard

```
Exception in thread "pool-6-thread-13" org.wso2.ei.dashboard.core.exception.DashboardServerException: Error occurred while inserting test information.
	at org.wso2.ei.dashboard.core.db.manager.JDBCDatabaseManager.insertArtifact(JDBCDatabaseManager.java:119)
	at org.wso2.ei.dashboard.micro.integrator.MiArtifactsManager.insertArtifact(MiArtifactsManager.java:193)
	at org.wso2.ei.dashboard.micro.integrator.MiArtifactsManager.processArtifacts(MiArtifactsManager.java:170)
	at org.wso2.ei.dashboard.micro.integrator.MiArtifactsManager.lambda$runFetchAllExecutorService$0(MiArtifactsManager.java:98)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.jdbc.JdbcSQLDataException: Value too long for column "DETAILS CHARACTER VARYING(5000)": "'{""operations"":[],""serviceGroupName"":""test"",""resources"":[{""resourceQuery"":""GetEm... (10199)"; SQL statement:
INSERT INTO DATA_SERVICES VALUES (?,?,?,?) [22001-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:525)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.getValueTooLongException(DbException.java:341)
	at org.h2.value.Value.getValueTooLongException(Value.java:2572)
	at org.h2.value.Value.convertToVarchar(Value.java:1261)
	at org.h2.value.Value.convertTo(Value.java:1117)
	at org.h2.value.Value.convertForAssignTo(Value.java:1092)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369)
	at org.h2.table.Table.convertInsertRow(Table.java:931)
	at org.h2.command.dml.Insert.insertRows(Insert.java:167)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:61)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.wso2.ei.dashboard.co
```

### Affected Component

MIDashboard

### Version

4.1.0

**Comment by PasanT9** [comment]
This is is not reproducible in master since there is no persistent layer.
