### ISSUE TITLE
[4.2.0] Error while deploying the API when a custom key manager is used

### ISSUE THREAD

**Issue by Ashi1993** [wso2/api-manager#1270]
### Description

Getting below error when getting this when deploying an API with a custom key manager. 
```
[2023-01-13 16:04:34,588] ERROR - ApiMgtDAO Unable to find the API with UUID : 33962fb9-2bd3-49be-92db-f9f650bfb2f4 in the database
[2023-01-13 16:04:34,591] ERROR - ApisApiServiceImpl Error while adding new API Revision for API : 9750b08e-84cf-46c5-9c85-3bd111bb8c35
org.wso2.carbon.apimgt.api.APIManagementException: Unable to find the API with UUID : 33962fb9-2bd3-49be-92db-f9f650bfb2f4 in the database
```
Even though the error throws, a revision is created but cannot deploy that revision getting below error.

`[2023-01-13 16:05:53,229] ERROR - GlobalThrowableMapper Failed to attach labels`

This error only occurs when a custom key manager is engaged. Working fine with resident key manager.

### Steps to Reproduce

- Create a custom key manager and enable it.
- Disable the resident key manager.
- Try to deploy an API to the gateway.

### Affected Component

APIM

### Version

4.2.0

### Relevant Log Output

```shell
[2023-01-13 16:04:34,588] ERROR - ApiMgtDAO Unable to find the API with UUID : 33962fb9-2bd3-49be-92db-f9f650bfb2f4 in the database
[2023-01-13 16:04:34,591] ERROR - ApisApiServiceImpl Error while adding new API Revision for API : 9750b08e-84cf-46c5-9c85-3bd111bb8c35
org.wso2.carbon.apimgt.api.APIManagementException: Unable to find the API with UUID : 33962fb9-2bd3-49be-92db-f9f650bfb2f4 in the database
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getAPIID_aroundBody298(ApiMgtDAO.java:6875) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getAPIID(ApiMgtDAO.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getAPIID_aroundBody296(ApiMgtDAO.java:6853) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getAPIID(ApiMgtDAO.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.setOperationPolicies_aroundBody886(ApiMgtDAO.java:18831) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.setOperationPolicies(ApiMgtDAO.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getURITemplatesOfAPI_aroundBody312(ApiMgtDAO.java:7211) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getURITemplatesOfAPI(ApiMgtDAO.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.populateAPIInformation_aroundBody130(AbstractAPIManager.java:1156) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.populateAPIInformation(AbstractAPIManager.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIbyUUID_aroundBody376(APIProviderImpl.java:4731) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIbyUUID(APIProviderImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getAPIbyUUID(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.ImportExportAPIServiceImpl.exportAPI(ImportExportAPIServiceImpl.java:120) ~[?:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPIRevision_aroundBody422(APIProviderImpl.java:5315) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPIRevision(APIProviderImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPIRevision(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.createAPIRevision(ApisApiServiceImpl.java:3596) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.createAPIRevision(ApisApi.java:339) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[?:?]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[?:?]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[?:?]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[?:?]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) ~[?:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-servlet-api_9.0.58.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[?:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119) ~[org.wso2.carbon.identity.context.rewrite.valve_1.7.1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:116) ~[org.wso2.carbon.identity.context.rewrite.valve_1.7.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38) ~[org.wso2.carbon.tomcat.ext_4.8.0.alpha.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:165) ~[org.wso2.carbon.identity.authz.valve_1.7.1.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:111) ~[org.wso2.carbon.identity.auth.valve_1.7.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106) ~[org.wso2.carbon.tomcat.ext_4.8.0.alpha.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) ~[org.wso2.carbon.tomcat.ext_4.8.0.alpha.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67) ~[org.wso2.carbon.tomcat.ext_4.8.0.alpha.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152) ~[org.wso2.carbon.tomcat.ext_4.8.0.alpha.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63) ~[org.wso2.carbon.tomcat.ext_4.8.0.alpha.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137) ~[org.wso2.carbon.tomcat.ext_4.8.0.alpha.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat_9.0.58.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by GDLMadushanka** [comment]
Tried adding IS as a key manager and its  failing due to expired certificates. Will check again

**Comment by GDLMadushanka** [comment]
I tried with configuring Okta and couldn't reproduce this issue.
Since this happens with some OB keymanager. Could you please provide specific instructions to reproduce.

**Comment by Ashi1993** [comment]
Please find the steps I followed.

- Create a custom key manager and enable it. (We have added a custom key manager type for OB)
- Disable the resident key manager.
- Try to deploy an API to the gateway.

Please note this is an intermittent issue we are getting

**Comment by GDLMadushanka** [comment]
getting when loggin with both APIM 4.2.0 and 4.1.0 
https://localhost:9443/publisher/services/auth/callback/login?error_description=Server+error+occurred+while+performing+authorization&state=%2F&error=server_error

**Comment by GDLMadushanka** [comment]
Reproduced the error (intermittent), dubugging for the root cause

**Comment by Tharsanan1** [comment]
The problem happens because of the following reason.

When calling APIMgtDAO#checkAPIUUIDIsARevisionUUID method we are unable to retrieve existing revisions intermittently. The behavior is caused because intermittently we get a database connection that has autocommit=0. (Means the code that set autocommit=0 did not commit the connection after the execution). When we have a database with transaction isolation level set to REPEATABLE_READ, the inserted revision is not visible to the connection. 


Look at the attached file.
In the file, 
line num: 3595, connection 263, set autocommit=0, at time: 2023-02-02T11:48:59.217009Z
line num: 4553, connection 261, insert the revision data, at time: 2023-02-02T11:49:02.290289Z
line num: 4661, connection 263, query the revision data, at time: 2023-02-02T11:49:02.325559Z

we are trying to access the data using a connection that is already in autocommit=0 . Which cannot be done when the database isolation level is REPEATABLE-READ. 

[mysql-access-log.txt](https://github.com/wso2/api-manager/files/10659939/mysqlgen.txt)

**Comment by Tharsanan1** [comment]
Based on the investigation the above-mentioned behavior is there because we use `defaultAutoCommit=false` in the OB setup and we don't call `setAutoCommit(true)` before the database lookup in the specified method above. I believe if we set `defaultAutoCommit=false` in the config we should call `setAutoCommit(true)` before each database lookup to support REPEATABLE_READ isolation level (to get the visibility over other transactions changes). For now, if there is no particular reason for having the `defaultAutoCommit=false` config in OB setup, we can simply make it `true` to prevent the erroneous behavior. I tried to reproduce it with `defaultAutoCommit=true`, but I am unable to reproduce the issue, since it's an intermittent issue and happens rarely I cannot confirm 100% whether this solves the issue. @Ashi1993 Please check your setup with `defaultAutoCommit=true` and let me know.
