### ISSUE TITLE
[MSSQL] Cannot add new API Revisions for APIs

### ISSUE THREAD

**Issue by binodmx** [wso2/api-manager#1318]
### Description

Cannot add new API revisions for APIs when APIM has MSSQL DB setup. The logs are mentioned below.

### Steps to Reproduce

1. Take the latest release APIM 4.2.0 (alpha).
2. Setup MSSQL as the database.
3. Start the server.
4. Try to deploy Sample Pizza Shack API.

### Affected Component

APIM

### Version

4.2.0

### Relevant Log Output

```shell
[2023-01-25 13:13:20,441] ERROR - ApiMgtDAO Failed to add API Revision entry of API UUID 5113e4b1-5083-477b-b95f-0caeaa7241f8
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'FALSE'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265) ~[mssql-jdbc-11.2.2.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676) ~[mssql-jdbc-11.2.2.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620) ~[mssql-jdbc-11.2.2.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540) ~[mssql-jdbc-11.2.2.jre11.jar:?]
...

[2023-01-25 13:13:20,442] ERROR - ApisApiServiceImpl Error while adding new API Revision for API : 5113e4b1-5083-477b-b95f-0caeaa7241f8
org.wso2.carbon.apimgt.api.APIManagementException: Failed to add API Revision entry of API UUID 5113e4b1-5083-477b-b95f-0caeaa7241f8
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.handleException_aroundBody308(ApiMgtDAO.java:7088) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.handleException(ApiMgtDAO.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addAPIRevision_aroundBody778(ApiMgtDAO.java:16491) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addAPIRevision(ApiMgtDAO.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPIRevision_aroundBody422(APIProviderImpl.java:5311) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPIRevision(APIProviderImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPIRevision(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.23.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.createAPIRevision(ApisApiServiceImpl.java:3596) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.createAPIRevision(ApisApi.java:339) ~[?:?]
...

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'FALSE'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265) ~[mssql-jdbc-11.2.2.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676) ~[mssql-jdbc-11.2.2.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620) ~[mssql-jdbc-11.2.2.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540) ~[mssql-jdbc-11.2.2.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627) ~[mssql-jdbc-11.2.2.jre11.jar:?]
```

**Comment by BLasan** [comment]
Hi,

Reproduced this issue. Working on the fix.

Thanks,
Benura
