### ISSUE TITLE
Repetitive error on Traffic Manager 

### ISSUE THREAD

**Issue by akila95fernando** [wso2/api-manager#1319]
### Description

```
ERROR - QueueWorker Error in passing events null to subscribers [org.wso2.carbon.event.input.adapter.wso2event.internal.ds.WSO2EventAdapterServiceDS$1@39d6a702] []
java.lang.Error: Maximum permit count exceeded
	at java.util.concurrent.Semaphore$Sync.tryReleaseShared(Semaphore.java:192)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1341)
	at java.util.concurrent.Semaphore.release(Semaphore.java:426)
	at org.wso2.carbon.databridge.core.internal.queue.EventBlockingQueue.poll(EventBlockingQueue.java:87)
	at org.wso2.carbon.databridge.core.internal.queue.EventBlockingQueue.poll(EventBlockingQueue.java:33)
	at org.wso2.carbon.databridge.core.internal.queue.QueueWorker.run(QueueWorker.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

2.5.0

### Related Issues

https://github.com/wso2/carbon-analytics-common/issues/792

### Suggested Labels

apim-2.5.0

**Comment by PasanT9** [comment]
Fixed with https://github.com/wso2/carbon-analytics-common/pull/852
