### ISSUE TITLE
MI 4.1.0 - Google Firebase Connector Error with update-level=31

### ISSUE THREAD

**Issue by NadunKulatunge** [wso2/api-manager#1362]
### Description

Hi Team,

I have configured integration with Firebase Cloud Messaging to send push notifications using Google Firebase Connector v.1.0.2. And it works as expected when using Micro Integrator 4.1.0 with update-level=0. When updated MI to update-level=31 I start to receive the following error (Mentioned in Relevant Log Output)

Please let me know if you require any further details regarding this issue.

Thanks & Regards,
Nadun

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/google-firebase-connector/google-firebase-overview/

### Steps to Reproduce

1. Setup Google firebase by following the steps mentioned in the documentation [1]
2. Setup a Google Firebase Environment
3. Run Google Firebase Connector Example
4. When deployed to MI 4.1.0 with update-level=0 success response can be observed and after updating to update-level=31 the above-mentioned error can be observed.

### Affected Component

MI

### Version

4.1.0 - U2 31

### Relevant Log Output

```shell
2023-01-24 14:43:29,396 ERROR [NativeWorkerPool] - Uncaught exception
java.lang.NoClassDefFoundError: com/google/api/client/json/gson/GsonFactory
at com.google.api.client.googleapis.util.Utils.getDefaultJsonFactory(Utils.java:34) ~[?:?]
at com.google.firebase.FirebaseOptions$Builder.(FirebaseOptions.java:234) ~[?:?]
at com.google.firebase.FirebaseOptions.builder(FirebaseOptions.java:209) ~[?:?]
at org.wso2.carbon.connector.googlefirebase.FirebaseConfig.connect(FirebaseConfig.java:85) ~[?:?]
at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32) ~[?:?]
at org.apache.synapse.mediators.ext.ClassMediator.updateInstancePropertiesAndMediate(ClassMediator.java:178) ~[?:?]
at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:97) ~[?:?]
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110) ~[?:?]
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72) ~[?:?]
at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:136) ~[?:?]
at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:170) ~[?:?]
at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:93) ~[?:?]
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110) ~[?:?]
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72) ~[?:?]
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) ~[?:?]
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214) ~[?:?]
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110) ~[?:?]
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72) ~[?:?]
at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:171) ~[?:?]
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110) ~[?:?]
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:242) ~[?:?]
at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.mediateFromContinuationStateStack(Axis2SynapseEnvironment.java:820) ~[?:?]
at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:322) ~[?:?]
at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:627) ~[?:?]
at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:208) ~[?:?]
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[?:?]
at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:298) ~[?:?]
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: com.google.api.client.json.gson.GsonFactory cannot be found by google-api-client_1.33.1.wso2v1
at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512) ~[?:?]
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[?:?]
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[?:?]
at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
... 31 more
```

**Comment by SanojPunchihewa** [comment]
Orbit PR: https://github.com/wso2/orbit/pull/921
