### ISSUE TITLE
SI Tooling Sample Event genarator won't work with XML data type

### ISSUE THREAD

**Issue by AnuGayan** [wso2/api-manager#1373]
### Description

The following error will be thrown when generating XML sample event for a stream via SI tooling distribution
```
[2023-02-02 09:18:30,213]  WARN {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Unmapped exception java.lang.ExceptionInInitializerError
	at org.wso2.carbon.siddhi.editor.core.util.SampleEventGenerator.generateXMLEvent(SampleEventGenerator.java:50)
	at org.wso2.carbon.siddhi.editor.core.internal.EditorMicroservice.getDefaultSampleStreamEvent(EditorMicroservice.java:1457)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$58(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: org.apache.axiom.locator.DefaultOMMetaFactoryLocator cannot be cast to org.apache.axiom.om.OMMetaFactoryLocator
	at org.apache.axiom.om.OMAbstractFactory.<clinit>(OMAbstractFactory.java:106)
	... 13 more
```

### Steps to Reproduce

1. Deploy the following Siddhi App, 
    ```sql
    @App:name("SiddhiApp")

    @App:description("Description of the plan")
    
    @Source(type = 'http', receiver.url='http://localhost:8006/productionStream', basic.auth.enabled='false',
        @map(type='xml'))
    define stream SweetProductionStream (name string, amount double);
    
    @sink(type='log') 
    define stream sampleStream(name string, amount double);
    
    from SweetProductionStream 
    select *
    insert into sampleStream

    ```
2. Generate a Sample event(tools -> Sample Event Generator) in XML format for  SweetProductionStream.

### Affected Component

SI

### Version

4.x.x

### Relevant Log Output

```shell
[2023-02-02 09:18:14,009]  INFO {org.wso2.carbon.siddhi.editor.core.internal.EditorConsoleService} - Connected with user : f4d488fffe88b748-00012490-00000009-ca0ea90202477bb0-fb31eb22
[2023-02-02 09:18:30,213]  WARN {org.wso2.msf4j.internal.MSF4JHttpConnectorListener} - Unmapped exception java.lang.ExceptionInInitializerError
	at org.wso2.carbon.siddhi.editor.core.util.SampleEventGenerator.generateXMLEvent(SampleEventGenerator.java:50)
	at org.wso2.carbon.siddhi.editor.core.internal.EditorMicroservice.getDefaultSampleStreamEvent(EditorMicroservice.java:1457)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$58(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: org.apache.axiom.locator.DefaultOMMetaFactoryLocator cannot be cast to org.apache.axiom.om.OMMetaFactoryLocator
	at org.apache.axiom.om.OMAbstractFactory.<clinit>(OMAbstractFactory.java:106)
	... 13 more
```

### Suggested Labels

Component/SI

**Comment by AnuGayan** [comment]
This only occurred in JAVA 11+ versions because the axiom-impl  and axiom-api related classes cannot be accessed together in the same method. when considering adding the wso2 axiom, few of the classes uses in the source are not present in wso2 axioms. As the solution, the easiest thing is to replace the logic as we have in other places to use common axiom classes.

**Comment by AnuGayan** [comment]
Closing Since the issue has been stale for a long time.
