### ISSUE TITLE
[EI-6.3.0] VFS property to ignore setting last modified timestamp 

### ISSUE THREAD

**Issue by dinuka10** [wso2/api-manager#1378]
### Description

I got below error when I try to send a file from local file system to sftp location ( Connected via private key )

```
[2023-01-25 14:56:53,108] [-1234] [] [pool-120-thread-1] INFO {org.apache.commons.vfs2.provider.sftp.SftpClientFactory} - Next authentication method: publickey
[2023-01-25 14:56:53,297] [-1234] [] [pool-120-thread-1] INFO {org.apache.commons.vfs2.provider.sftp.SftpClientFactory} - Authentication succeeded (publickey).
[2023-01-25 14:56:54,050] [-1234] [] [pool-120-thread-1] ERROR {org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer} - Error moving file : file:///srv/devel/it/integration/une/projects/nabdirect/outbound/19012023EFT.aba.asc to sftp://UONE01AU@164.53.139.162:9022/DTDC/?transport.vfs.AvoidPermissionCheck=true
org.apache.commons.vfs2.FileSystemException: Could not set the last modified timestamp of "sftp://UONE01AU@164.53.139.162:9022/DTDC/19012023EFT.aba.asc".
at org.apache.commons.vfs2.provider.DefaultFileContent.setLastModifiedTime(DefaultFileContent.java:180)
at org.apache.commons.vfs2.provider.AbstractFileObject.moveTo(AbstractFileObject.java:1616)
at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.moveOrDeleteAfterProcessing(FilePollingConsumer.java:825)
at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.directoryHandler(FilePollingConsumer.java:538)
at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.poll(FilePollingConsumer.java:213)
at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.execute(FilePollingConsumer.java:133)
at org.wso2.carbon.inbound.endpoint.protocol.file.FileTask.taskExecute(FileTask.java:47)
at org.wso2.carbon.inbound.endpoint.common.InboundTask.execute(InboundTask.java:45)
at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
at org.apache.commons.vfs2.provider.sftp.SftpFileObject.doSetLastModifiedTime(SftpFileObject.java:193)
at org.apache.commons.vfs2.provider.DefaultFileContent.setLastModifiedTime(DefaultFileContent.java:176)
... 15 more
```
This issue should be resolved after adding below parameter. But there are some changes  needs to be done in the code level to apply this parameter ( This issue is fixed in EI 6.6 and MI ).

`<parameter name="transport.vfs.UpdateLastModified">false</parameter>
`

### Steps to Reproduce

1.) Set up SFTP location with private-key

2.) Download EI 6.3 and update it to update level 55 

3.) For the scenario, use inbound endpoint configuration like below example : 

```
<inboundEndpoint
	xmlns="http://ws.apache.org/ns/synapse" name="file_inbound" sequence="request" onError="fault" protocol="file" suspend="false">
	<parameters>
		<parameter name="interval">1000</parameter>
		<parameter name="sequential">true</parameter>
		<parameter name="transport.vfs.FileURI">file:////home/dinuka/test/in</parameter>
		<!-- CHANGE -->
		<parameter name="transport.vfs.ContentType">text/xml</parameter>
		<parameter name="transport.vfs.FileNamePattern">.*\.xml</parameter>
		<parameter name="transport.vfs.SFTPIdentities">/home/dinuka/Downloads/CheckIssues/UNESUB210/KMISUBprivate.ppk</parameter>
		<parameter name="transport.vfs.MoveAfterProcess">sftp://wso2support@20.xx.xx.x9x:22/c/wso2support</parameter>
		<!-- CHANGE -->
		<parameter name="transport.vfs.MoveAfterFailure">file:///home/dinuka/test/original</parameter>
		<!-- CHANGE -->
		<parameter name="transport.vfs.ActionAfterProcess">MOVE</parameter>
		<parameter name="transport.vfs.ActionAfterFailure">MOVE</parameter>
	</parameters>
</inboundEndpoint>
```

4.) Then save this file as an xml file.

5.) Then put that file in <EI_HOME> /repository/deployment/server/synapse-configs/default/inbound-endpoints directory and start the server

6.) Then create xml file with below content ( ex: test.xml ) 

```
<soapenv:Envelope
	xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:wsa="http://www.w3.org/2005/08/addressing">
	<soapenv:Body>
		<m0:getQuote
			xmlns:m0="http://services.samples">
			<m0:request>
				<m0:symbol>IBM</m0:symbol>
			</m0:request>
		</m0:getQuote>
	</soapenv:Body>
</soapenv:Envelope>
```

7.) Then copy that to the directory mentioned in inbound endpoint configuration ( Under transport.vfs.FileURI parameter )

If a working scenario this test.xml file should move to mentioned ( In inbound endpoint configuration)  sftp location directory . But instead it gives above error

### Affected Component

MI

### Version

EI 6.3.0.55

**Comment by senthuran16** [comment]
Closing this as the public fixes are already available
  - https://github.com/wso2/wso2-commons-vfs/pull/92
  - https://github.com/wso2/wso2-synapse/pull/1814
  - https://github.com/wso2/carbon-mediation/pull/1553
