### ISSUE TITLE
[MSSQL] Error while retrieving correlation configs | Cannot create API

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#1380]
Observed following in pre beta back - carbon-apimgt v9.28.71
```
[2023-02-05 23:43:10,728] ERROR - APIManagerComponent Error while initializing the API manager component
org.wso2.carbon.apimgt.api.APIManagementException: Error while retrieving correlation configs
	at org.wso2.carbon.apimgt.impl.dao.CorrelationConfigDAO.isConfigExist_aroundBody6(CorrelationConfigDAO.java:193) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.CorrelationConfigDAO.isConfigExist(CorrelationConfigDAO.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.addDefaultCorrelationConfigs_aroundBody854(APIUtil.java:9938) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.addDefaultCorrelationConfigs(APIUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.internal.APIManagerComponent.activate_aroundBody0(APIManagerComponent.java:284) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.internal.APIManagerComponent.activate(APIManagerComponent.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
...
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'AM_CORRELATION_CONFIGS'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262) ~[mssql-jdbc-7.4.1.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1624) ~[mssql-jdbc-7.4.1.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:594) ~[mssql-jdbc-7.4.1.jre11.jar:?]
```

This was followed by
```
[2023-02-05 23:44:06,594] ERROR - Framework FrameworkEvent ERROR
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.common.gateway.util.CommonAPIUtil.getHttpClient(CommonAPIUtil.java:84) ~[org.wso2.carbon.apimgt.common.gateway_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getHttpClient_aroundBody402(APIUtil.java:5124) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getHttpClient(APIUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.correlation.CorrelationConfigManager.invokeService(CorrelationConfigManager.java:161) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.correlation.CorrelationConfigManager.initializeCorrelationComponentList(CorrelationConfigManager.java:74) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]

```
Because of the above, publisher fails to create an API with following error.

```
[2023-02-05 23:48:29,817] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.common.gateway.util.CommonAPIUtil.getHttpClient(CommonAPIUtil.java:84) ~[org.wso2.carbon.apimgt.common.gateway_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getHttpClient_aroundBody402(APIUtil.java:5124) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getHttpClient(APIUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.loader.KeyManagerConfigurationDataRetriever.run_aroundBody0(KeyManagerConfigurationDataRetriever.java:56) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.loader.KeyManagerConfigurationDataRetriever.run(KeyManagerConfigurationDataRetriever.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.factory.KeyManagerHolder.getTenantKeyManagerDto_aroundBody14(KeyManagerHolder.java:260) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.factory.KeyManagerHolder.getTenantKeyManagerDto(KeyManagerHolder.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.factory.KeyManagerHolder.getTenantKeyManagers_aroundBody2(KeyManagerHolder.java:125) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.factory.KeyManagerHolder.getTenantKeyManagers(KeyManagerHolder.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.validateSharedScopes_aroundBody356(APIProviderImpl.java:4530) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.validateSharedScopes(APIProviderImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.validateSharedScopes(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.PublisherCommonUtils.validateScopes(PublisherCommonUtils.java:773) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.PublisherCommonUtils.addAPIWithGeneratedSwaggerDefinition(PublisherCommonUtils.java:844) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.28.71.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.createAPI(ApisApiServiceImpl.java:170) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.createAPI(ApisApi.java:319) ~[?:?]

```

**Comment by dushaniw** [comment]
This is due to having the db created from db scripts from an old build. Resolving the issue as it is invalid.
