### ISSUE TITLE
Query complexity and depth doesnt work properly for GraphQL subscriptions

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#1431]
### Description

If max complexity is > current query complexity, an error is thrown in backend and graphiql ui seems to be continuously sending requests in a loop.

### Steps to Reproduce

1. Create starwars graphql api
2. Create a subscription policy with max complexity 2
3. Invoke gql subscription using graphiql with following query.
```
subscription MySubscription {
  reviewAdded(episode: JEDI) {
    commentary
  }
}
```

### Affected Component

APIM

### Version

4.2.0-beta

### Environment Details (with versions)

Browser - Chrome

### Relevant Log Output

```shell
[2023-02-13 10:48:33,154] ERROR - GraphQL Execution 'f5e84f59-290a-4cff-89c8-e6fe3f645e55' threw exception when executing : query : 'subscription MySubscription {
  reviewAdded(episode: JEDI) {
    commentary
  }
}
'. variables '{}'
java.util.concurrent.CompletionException: graphql.AssertException: Your data fetcher must return a Publisher of events when using graphql subscriptions
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:683) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094) ~[?:?]
	at graphql.execution.SubscriptionExecutionStrategy.createSourceEventStream(SubscriptionExecutionStrategy.java:96) ~[graphQL_19.2.0.wso2v2.jar:?]
	at graphql.execution.SubscriptionExecutionStrategy.execute(SubscriptionExecutionStrategy.java:57) ~[graphQL_19.2.0.wso2v2.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:159) ~[graphQL_19.2.0.wso2v2.jar:?]
	at graphql.execution.Execution.execute(Execution.java:105) ~[graphQL_19.2.0.wso2v2.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:645) ~[graphQL_19.2.0.wso2v2.jar:?]
	at graphql.GraphQL.lambda$parseValidateAndExecute$11(GraphQL.java:564) ~[graphQL_19.2.0.wso2v2.jar:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235) ~[?:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:559) ~[graphQL_19.2.0.wso2v2.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:527) ~[graphQL_19.2.0.wso2v2.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:453) ~[graphQL_19.2.0.wso2v2.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:324) ~[graphQL_19.2.0.wso2v2.jar:?]
	at org.wso2.carbon.apimgt.common.gateway.graphql.QueryAnalyzer.analyseQueryComplexity(QueryAnalyzer.java:114) ~[org.wso2.carbon.apimgt.common.gateway_9.28.75.jar:?]
	at org.wso2.carbon.apimgt.common.gateway.graphql.QueryAnalyzer.analyseQueryMutationComplexity(QueryAnalyzer.java:151) ~[org.wso2.carbon.apimgt.common.gateway_9.28.75.jar:?]
	at org.wso2.carbon.apimgt.gateway.inbound.websocket.request.GraphQLRequestProcessor.validateQueryComplexity_aroundBody14(GraphQLRequestProcessor.java:277) ~[org.wso2.carbon.apimgt.gateway_9.28.75.jar:?]
	at org.wso2.carbon.apimgt.gateway.inbound.websocket.request.GraphQLRequestProcessor.validateQueryComplexity(GraphQLRequestProcessor.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.75.jar:?]

```
```


### Related Issues

_No response_

### Suggested Labels

_No response_

**Comment by dushaniw** [comment]
same issue reported previously. library only supports non empty subscription response types (Eg: `Review!` from the schema.

```
type Subscription {
  reviewAdded(episode: Episode): Review!
}
```
