### ISSUE TITLE
Enabling Choreo Analytics throws error during server startup

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#1432]
After generating an on prem key from `https://console.choreo.dev/` and adding it in deployment.toml got the following error in server startup.

```
[2023-02-13 13:38:31,127] ERROR - gateway [SCR] Error while trying to bind reference Reference[name = api.manager.config.service, interface = org.wso2.carbon.apimgt.impl.APIManagerConfigurationService, policy = dynamic, cardinality = 1..1, target = null, bind = setAPIManagerConfigurationService, unbind = unsetAPIManagerConfigurationService]
    Details:
    Problematic reference = Reference[name = api.manager.config.service, interface = org.wso2.carbon.apimgt.impl.APIManagerConfigurationService, policy = dynamic, cardinality = 1..1, target = null, bind = setAPIManagerConfigurationService, unbind = unsetAPIManagerConfigurationService]
    of service component = org.wso2.carbon.apimgt.handlers
    component implementation class = org.wso2.carbon.apimgt.gateway.internal.APIHandlerServiceComponent
    located in bundle with symbolic name = org.wso2.carbon.apimgt.gateway
    bundle location = reference:file:../plugins/org.wso2.carbon.apimgt.gateway_9.28.75.jar
java.lang.reflect.InvocationTargetException: null
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]

....
Caused by: java.lang.NullPointerException: name
    at feign.Util.checkNotNull(Util.java:123) ~[io.github.openfeign.feign-core_11.9.1.jar:?]
    at feign.Target$HardCodedTarget.<init>(Target.java:78) ~[io.github.openfeign.feign-core_11.9.1.jar:?]
    at feign.Target$HardCodedTarget.<init>(Target.java:73) ~[io.github.openfeign.feign-core_11.9.1.jar:?]
    at feign.Feign$Builder.target(Feign.java:201) ~[io.github.openfeign.feign-core_11.9.1.jar:?]
    at org.wso2.am.analytics.publisher.auth.AuthClient.getSASToken(AuthClient.java:58) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
    at org.wso2.am.analytics.publisher.client.EventHubProducerClientFactory.getSASToken(EventHubProducerClientFactory.java:95) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
    at org.wso2.am.analytics.publisher.client.EventHubProducerClientFactory.create(EventHubProducerClientFactory.java:55) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
    at org.wso2.am.analytics.publisher.client.EventHubClient.createProducerWithRetry(EventHubClient.java:108) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
    at org.wso2.am.analytics.publisher.client.EventHubClient.<init>(EventHubClient.java:86) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
    at org.wso2.am.analytics.publisher.reporter.cloud.DefaultAnalyticsMetricReporter.<init>(DefaultAnalyticsMetricReporter.java:63) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
    at org.wso2.am.analytics.publisher.reporter.MetricReporterFactory.createMetricReporter(MetricReporterFactory.java:52) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
    at org.wso2.carbon.apimgt.common.analytics.publishers.impl.AnalyticsDataPublisher.initialize(AnalyticsDataPublisher.java:120) ~[org.wso2.carbon.apimgt.common.analytics_9.28.75.jar:?]
    at org.wso2.carbon.apimgt.common.analytics.AnalyticsServiceReferenceHolder.setConfigurations(AnalyticsServiceReferenceHolder.java:46) ~[org.wso2.carbon.apimgt.common.analytics_9.28.75.jar:?]
    at org.wso2.carbon.apimgt.gateway.internal.APIHandlerServiceComponent.setAPIManagerConfigurationService_aroundBody12(APIHandlerServiceComponent.java:244) ~[?:?]
    at org.wso2.carbon.apimgt.gateway.internal.APIHandlerServiceComponent.setAPIManagerConfigurationService(APIHandlerServiceComponent.java:1) ~[?:?]
```

**Comment by dushaniw** [comment]
This was due to configuration issue.
