### ISSUE TITLE
apiContext is missing in metric data for pizzashack example when invoking the api after enabling analytics

### ISSUE THREAD

**Issue by chamikasudusinghe** [wso2/api-manager#1435]
### Description

When the default post request is executed from the dev portal, the following error popped up.

ERROR - ParallelQueueWorker Builder instance is not duly filled. Event building failed
org.wso2.am.analytics.publisher.exception.MetricReportingException: apiContext is missing in metric data. This metric event will not be processed further.
	at org.wso2.am.analytics.publisher.reporter.cloud.DefaultResponseMetricEventBuilder.validate(DefaultResponseMetricEventBuilder.java:62) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
	at org.wso2.am.analytics.publisher.reporter.AbstractMetricEventBuilder.build(AbstractMetricEventBuilder.java:32) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
	at org.wso2.am.analytics.publisher.reporter.cloud.ParallelQueueWorker.run(ParallelQueueWorker.java:56) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

### Steps to Reproduce

Steps

- Enabled analytics
- Started the pack
- Deployed PizzaShack
- Invoke API calls from dev portal

### Affected Component

APIM

### Version

4.2.0

**Comment by chamikasudusinghe** [comment]
Date: 13 of February 2023

Update: Tested for APIs which were manually created other than for the pizzashack example. Although these APIs were defined with a context in the publisher, the same error poped up in the logs.

**Comment by dushaniw** [comment]
Observing the same when testing graphql APIs with Choreo analytics.

```
[2023-02-16 16:27:43,086] ERROR - ParallelQueueWorker Builder instance is not duly filled. Event building failed
org.wso2.am.analytics.publisher.exception.MetricReportingException: apiContext is missing in metric data. This metric event will not be processed further.
	at org.wso2.am.analytics.publisher.reporter.cloud.DefaultResponseMetricEventBuilder.validate(DefaultResponseMetricEventBuilder.java:62) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
	at org.wso2.am.analytics.publisher.reporter.AbstractMetricEventBuilder.build(AbstractMetricEventBuilder.java:32) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
	at org.wso2.am.analytics.publisher.reporter.cloud.ParallelQueueWorker.run(ParallelQueueWorker.java:56) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[2023-02-16 16:27:43,095] ERROR - ParallelQueueWorker Builder instance is not duly filled. Event building failed
org.wso2.am.analytics.publisher.exception.MetricReportingException: apiContext is missing in metric data. This metric event will not be processed further.
	at org.wso2.am.analytics.publisher.reporter.cloud.DefaultResponseMetricEventBuilder.validate(DefaultResponseMetricEventBuilder.java:62) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
	at org.wso2.am.analytics.publisher.reporter.AbstractMetricEventBuilder.build(AbstractMetricEventBuilder.java:32) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
	at org.wso2.am.analytics.publisher.reporter.cloud.ParallelQueueWorker.run(ParallelQueueWorker.java:56) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by chamikasudusinghe** [comment]
Date: 14th & 15th February

Update: The issue happened due to removing some of the lines in ELK which remove both apiContext and username adding into the root level from the properties. For Chreo analytics, we have not previous added these to the root level. But in the newly introduced validator, we are checking apiContext in the root level which causes the error. 

This was fixed with adding the necessary lines to the code. But when the jar was added to the dropins folder, it causes another error and when starting the api-manager it causes another error.

[2023-02-15 12:22:40,506]  WARN - CarbonServerManager Carbon initialization is delayed due to the following unsatisfied items:
[2023-02-15 12:22:40,506]  WARN - CarbonServerManager Waiting for required OSGiAxis2Service: org.wso2.carbon.apimgt.gateway-9.28.86.SNAPSHOT

To resolve this, initially analytics-common was added to the gateway pom imports and it did not resolve it. Then

**Comment by chamikasudusinghe** [comment]
Date: 16th February

Update: It was not possible to test this using the latest version of the [apim-analytics-publisher](https://github.com/wso2/apim-analytics-publisher) tool. Yet after going through the previous releases it was found that this can be tested using the 1.1.3 version. Only for that version when the jar is added into dropins the product starts without an issue. For other versions it keeps giving the "WARN - CarbonServerManager Waiting for required OSGiAxis2Service: org.wso2.carbon.apimgt.gateway-9.28.86.SNAPSHOT" warning when jar is added.

The fix was tested and works fine and now the pack is starting without an issue. It was tested both for pizzashack and another custom API that was created. 

Fix for Choreo: Hence apiContext was brought into the root level to enable the validation check. Further, it was noted that the userName was available there and it was removed from the eventMap due to privacy concerns.

Fix for ELK: Here, the content in the properties was brought into the root level in the builder. But, the validator runs before the builder. Hence, the content has to be brought into the builder when the validator runs.

**Comment by dushaniw** [comment]
- [ ] Need to update analytics.publisher.client version in both product-apim and carbon-apimgt to latest
