### ISSUE TITLE
Enabling ELK based Analytics throws error when Invoking an API

### ISSUE THREAD

**Issue by Tharanidk** [wso2/api-manager#1443]
### Description

After configuring details to check ELK analytics, when invoking an API, the following error is coming in the server.

```
[2023-02-13 15:57:26,585] ERROR - AbstractRequestDataPublisher Error occurred when publishing event.
org.wso2.am.analytics.publisher.exception.MetricReportingException: apiContext is missing in metric data. This metric event will not be processed further.
	at org.wso2.am.analytics.publisher.reporter.elk.ELKMetricEventBuilder.validate(ELKMetricEventBuilder.java:80) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
	at org.wso2.am.analytics.publisher.reporter.AbstractMetricEventBuilder.build(AbstractMetricEventBuilder.java:32) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
	at org.wso2.am.analytics.publisher.reporter.elk.ELKCounterMetric.incrementCount(ELKCounterMetric.java:46) ~[org.wso2.am.analytics.publisher.client_1.1.3.jar:?]
	at org.wso2.carbon.apimgt.common.analytics.publishers.impl.AbstractRequestDataPublisher.publish(AbstractRequestDataPublisher.java:73) ~[org.wso2.carbon.apimgt.common.analytics_9.28.75.jar:?]
	at org.wso2.carbon.apimgt.common.analytics.collectors.impl.SuccessRequestDataCollector.collectData(SuccessRequestDataCollector.java:95) ~[org.wso2.carbon.apimgt.common.analytics_9.28.75.jar:?]
	at org.wso2.carbon.apimgt.common.analytics.collectors.impl.GenericRequestDataCollector.collectData(GenericRequestDataCollector.java:46) ~[org.wso2.carbon.apimgt.common.analytics_9.28.75.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.AnalyticsMetricsHandler.handleResponseOutFlow_aroundBody8(AnalyticsMetricsHandler.java:95) ~[org.wso2.carbon.apimgt.gateway_9.28.75.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.AnalyticsMetricsHandler.handleResponseOutFlow(AnalyticsMetricsHandler.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.75.jar:?]
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:188) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:574) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:123) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.api.Resource.process(Resource.java:342) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.api.API.process(API.java:416) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:54) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:63) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:346) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:644) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:219) ~[synapse-core_4.0.0.wso2v13.jar:4.0.0-wso2v13]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:298) ~[synapse-nhttp-transport_4.0.0.wso2v13.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v83.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
```

### Steps to Reproduce

1.  Configure API Manager and ELK according to the[ documentation](https://apim.docs.wso2.com/en/latest/api-analytics/on-prem/elk-installation-guide/).
2. Invoke an API.

### Affected Component

APIM

### Version

4.2.0-beta

**Comment by chamikasudusinghe** [comment]
Update: This issue is fixed along with the same behavior for Choreo analytics.

https://github.com/wso2/apim-analytics-publisher/pull/92
