### ISSUE TITLE
Changing ownership through developer admin portal gives an error

### ISSUE THREAD

**Issue by dilshanfa** [wso2/api-manager#1461]
### Description

When we tries to update the application owner of an application whose app owner has been already deleted there is an error. Reproducing steps are as below.

### Steps to Reproduce

1. Created a new user in carbon console. (User-A)
2. Then login to the store portal with User-A and create an application.
3. Generate keys.
4. Created a new user in carbon console. (User-B)
5. Then login to the store portal with User-B (to add the role subscribe.)
6. Login to the carbon console again with admin user and deleted the User-A.
7. Login to the admin portal and change the ownership of the relevant app to User - B

Then the Following ERROR will occur.

`
[2023-02-13 18:46:02,416]  WARN - DataEndpointGroup No receiver is reachable at URL Endpoint/Endpoints [tcp://<IP>], will try to reconnect every 30 sec [2023-02-13 18:46:02,416]  WARN - DataEndpointGroup No receiver is reachable at URL Endpoint/Endpoints [tcp://<IP>], will try to reconnect every 30 sec [2023-02-13 18:46:02,668]  INFO - DataBridge user admin connected [2023-02-13 18:46:02,678]  INFO - DataBridge user admin connected [2023-02-13 18:46:03,542]  WARN - ApplicationManagementServiceImpl Illegal Access! User userx does not have access to the application userx_user-x-application_PRODUCTION [2023-02-13 18:46:03,545] ERROR - APIUtil Error occurred while creating ServiceProvider for app userx_user-x-application_PRODUCTION org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error occurred while updating the application: userx_user-x-application_PRODUCTION. User not authorized at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.updateApplication(ApplicationManagementServiceImpl.java:625) ~[org.wso2.carbon.identity.application.mgt_5.14.97.8.jar:?] at org.wso2.carbon.apimgt.keymgt.service.APIKeyMgtSubscriberService.updateOAuthApplicationOwner_aroundBody6(APIKeyMgtSubscriberService.java:593) [org.wso2.carbon.apimgt.keymgt_6.5.349.59.jar:?] at org.wso2.carbon.apimgt.keymgt.service.APIKeyMgtSubscriberService.updateOAuthApplicationOwner(APIKeyMgtSubscriberService.java:527) [org.wso2.carbon.apimgt.keymgt_6.5.349.59.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.
`

### Affected Component

APIM

### Version

wso2am-3.0.0

**Comment by YasasRangika** [comment]
According to comment [1], the public fix has already been added. Therefore, closing this issue.

[1] https://github.com/wso2-enterprise/wso2-apim-internal/issues/1962#issuecomment-1433292316
