### ISSUE TITLE
[Patch]-ClassNotFoundException when using Redis connector with 'redisClusterEnabled' true

### ISSUE THREAD

**Issue by Kirishikesan** [wso2/api-manager#1464]
### Description

When using redis connector with redis cluster configuration enabled we can observe the below error during runtime.

### Steps to Reproduce

1. Deploy the redis connector version 2.2.0[1] and add jedis-3.6.0 jar[2]

2. Deploy the below API on EI-6.5.0

<?xml version="1.0" encoding="UTF-8"?>
<api xmlns="http://ws.apache.org/ns/synapse" name="RedisGetAPI" context="/RedisGet">
    <resource methods="POST GET">
        <inSequence>
            <property name="UNIQUEKEY" expression="json-eval($.key)"/>
            <redis.init>
                <redisClusterEnabled>true</redisClusterEnabled>
                <clusterNodes>10.50.13.42:6379,10.205.155.73:6379,10.205.155.73:6380,10.205.155.74:6379,10.205.155.74:6380,10.205.155.75:6379,10.205.155.75:6380</clusterNodes>
                <redisTimeout>5000</redisTimeout>
            </redis.init>
            

            <redis.hGetAll>
                <redisKey>{$ctx:UNIQUEKEY}</redisKey>
            </redis.hGetAll>

            <property name="result" expression="get-property('result')" scope="default" type="STRING"/>
            <log level="custom">
                <property name="test" expression="get-property('result')"/>
            </log>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>

3. Invoke the API

It seems even though the org.apache.commons.pool2_2.4.2.jar is shipped with wso2ei-6.5.0, the bundle info entry for this jar is missing. Hence, this jar is not active in OSGI mode.

### Affected Component

MI

### Version

6.5.0

### Relevant Log Output

```shell
ERROR - NativeWorkerPool Uncaught exception
java.lang.NoClassDefFoundError: org/apache/commons/pool2/impl/GenericObjectPoolConfig
	at org.wso2.carbon.connector.operations.RedisServer.createJedisCluster(RedisServer.java:183)
	at org.wso2.carbon.connector.operations.RedisServer.getJedisCluster(RedisServer.java:194)
	at org.wso2.carbon.connector.operations.HGetAll.connect(HGetAll.java:40)
	at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:94)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:135)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:148)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:84)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:370)
	at org.apache.synapse.rest.API.process(API.java:441)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:338)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:383)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: Class Not found : org.apache.commons.pool2.impl.GenericObjectPoolConfig
	at org.apache.axis2.deployment.DeploymentClassLoader.findClass(DeploymentClassLoader.java:95)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.axis2.deployment.DeploymentClassLoader.loadClass(DeploymentClassLoader.java:276)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 28 more
```

**Comment by Kirishikesan** [comment]
Closing this as it is fixed.
