### ISSUE TITLE
NullPointerException while invoking a service

### ISSUE THREAD

**Issue by dinuka10** [wso2/api-manager#1466]
### Description

Below error log is printing when we invoke an API with the correct tenant name after invoking the same API with the incorrect tenant name ( Only the case of the tenant name is different, example : test.com and Test.com)

```
[2023-02-07 16:31:37,785] ERROR - ServerWorker Error processing GET request for : /t/test.com/pizzashack/1.0.0/menu. 
java.lang.NullPointerException: null
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:48) ~[synapse-core_2.1.7.wso2v183_17.jar:2.1.7-wso2v183.17]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v41_13.jar:?]
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRESTRequest(MultitenantMessageReceiver.java:701) ~[org.wso2.carbon.core_4.6.0.84.jar:?]
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doNhttpREST(MultitenantMessageReceiver.java:603) ~[org.wso2.carbon.core_4.6.0.84.jar:?]
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doREST(MultitenantMessageReceiver.java:412) ~[org.wso2.carbon.core_4.6.0.84.jar:?]
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:260) ~[org.wso2.carbon.core_4.6.0.84.jar:?]
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:88) ~[org.wso2.carbon.core_4.6.0.84.jar:?]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v41_13.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367) [synapse-nhttp-transport_2.1.7.wso2v183_14.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:188) [synapse-nhttp-transport_2.1.7.wso2v183_14.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41_13.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_345]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_345]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_345]
```

### Steps to Reproduce

Start the APIM server.

Create a tenant(test.com) and tenant API(Pizzashack).

Invoke the API with the correct cases of the tenant name(test.com).
https://localhost:8243/t/test.com/pizzashack/1.0.0/menu

Invoke the same API with different cases of the tenant name(Test.com).
https://localhost:8243/t/Test.com/pizzashack/1.0.0/menu

Again invoke the same or different API from the same tenant with the correct letter cases for the tenant name before the tenant gets unloaded.

Below is the NPE observed in the carbon log.

### Affected Component

APIM

### Version

3.2.0

**Comment by dinuka10** [comment]
Hi All/ @senthuran16  / @SanojPunchihewa ,


As per the offline discussion and as mentioned in the Informatica War Room, we have shared the previous ETA below with the customer, requesting them to ignore any further auto-generated ETAs. (I have put this comment on 2023-02-17 14:56:20 in the ticket after the offline discussion.) Because there were multiple auto-generated ETAs due to the hotfix ETA and official fix at that time, which confused the customer.


```
ETA for the hotfixes ,

Best case - 2023-02-17 ( Today)
Most likely - 2023-02-20 (Monday)
Worst case - 2023-02-21 (Tuesday)



ETA for the Official fix ( Previously shared ETA ) ,

Product: wso2am-3.2.0
Public git issue: https://github.com/wso2/api-manager/issues/1466
Best Case Estimate: 2023-02-22
Most Likely Estimate: 2023-02-24
Worst Case Estimate: 2023-02-27

If you're using the older WUM model, the ETA for the fix will be as follows.

Best Case Estimate: 2023-02-24
Most Likely Estimate: 2023-02-26
Worst Case Estimate: 2023-03-01
```



Kindly ignore any additional auto generated ETAs in this case.


Now we have shared a new ETA as below , Since this issue is an already escalated account customer may get frustrated because of this new ETA So could you please look in to this 


```
ETA information for the fix will be as follows.

Product: wso2am-3.2.0
Public git issue: https://github.com/wso2/api-manager/issues/1466
Best Case Estimate: 2023-02-27
Most Likely Estimate: 2023-03-03
Worst Case Estimate: 2023-03-10

If you're using the older WUM model, the ETA for the fix will be as follows.

Best Case Estimate: 2023-02-28
Most Likely Estimate: 2023-03-04
Worst Case Estimate: 2023-03-11
```

Thanks and Regards,
Dinuka

**Comment by SanojPunchihewa** [comment]
Fixed with following PRs:

4.6.x - https://github.com/wso2/carbon-kernel/pull/3524
4.8.x - https://github.com/wso2/carbon-kernel/pull/3525
4.9.x - https://github.com/wso2/carbon-kernel/pull/3826

5.x series don't contain the updated code block. Hence closing this issue.
