### ISSUE TITLE
Error in siddhi app while starting the SI-4.2.0-beta 

### ISSUE THREAD

**Issue by malshaniS** [wso2/api-manager#1481]
### Description

Observed the below siddhi error in SI-4.2.0-beta server start up.

[2023-02-16 12:30:21,690] ERROR {org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer} - io.siddhi.core.exception.SiddhiAppCreationException: Error on 'APIRawDataSubmissionApp' @ Line: 16. Position: 50, near '@source(type='wso2event',  @map(type='wso2event'))'. org/apache/log4j/Logger org.wso2.carbon.streaming.integrator.core.internal.exception.SiddhiAppDeploymentException: io.siddhi.core.exception.SiddhiAppCreationException: Error on 'APIRawDataSubmissionApp' @ Line: 16. Position: 50, near '@source(type='wso2event',  @map(type='wso2event'))'. org/apache/log4j/Logger
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:132)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:358)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: io.siddhi.core.exception.SiddhiAppCreationException: Error on 'APIRawDataSubmissionApp' @ Line: 16. Position: 50, near '@source(type='wso2event',  @map(type='wso2event'))'. org/apache/log4j/Logger
	at io.siddhi.core.util.ExceptionUtil.populateQueryContext(ExceptionUtil.java:58)
	at io.siddhi.core.util.ExceptionUtil.populateQueryContext(ExceptionUtil.java:35)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSource(DefinitionParserHelper.java:388)
	at io.siddhi.core.util.SiddhiAppRuntimeBuilder.defineStream(SiddhiAppRuntimeBuilder.java:117)
	at io.siddhi.core.util.parser.SiddhiAppParser.defineStreamDefinitions(SiddhiAppParser.java:375)
	at io.siddhi.core.util.parser.SiddhiAppParser.parse(SiddhiAppParser.java:231)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:87)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:97)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:86)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:102)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at org.wso2.extension.siddhi.map.wso2event.source.WSO2SourceMapper.<clinit>(WSO2SourceMapper.java:98)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.siddhi.core.util.SiddhiClassLoader.loadClass(SiddhiClassLoader.java:33)
	at io.siddhi.core.util.SiddhiClassLoader.loadExtensionImplementation(SiddhiClassLoader.java:49)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSource(DefinitionParserHelper.java:354)
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger cannot be found by siddhi-map-wso2event_5.0.2
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 30 more

[2023-02-16 12:30:21,719] ERROR {org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer} - io.siddhi.core.exception.SiddhiAppCreationException: Error on 'APILatencyRawDataApp' @ Line: 16. Position: 50, near '@source(type='wso2event',  @map(type='wso2event'))'. Could not initialize class org.wso2.extension.siddhi.map.wso2event.source.WSO2SourceMapper org.wso2.carbon.streaming.integrator.core.internal.exception.SiddhiAppDeploymentException: io.siddhi.core.exception.SiddhiAppCreationException: Error on 'APILatencyRawDataApp' @ Line: 16. Position: 50, near '@source(type='wso2event',  @map(type='wso2event'))'. Could not initialize class org.wso2.extension.siddhi.map.wso2event.source.WSO2SourceMapper
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:132)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:358)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: io.siddhi.core.exception.SiddhiAppCreationException: Error on 'APILatencyRawDataApp' @ Line: 16. Position: 50, near '@source(type='wso2event',  @map(type='wso2event'))'. Could not initialize class org.wso2.extension.siddhi.map.wso2event.source.WSO2SourceMapper
	at io.siddhi.core.util.ExceptionUtil.populateQueryContext(ExceptionUtil.java:58)
	at io.siddhi.core.util.ExceptionUtil.populateQueryContext(ExceptionUtil.java:35)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSource(DefinitionParserHelper.java:388)
	at io.siddhi.core.util.SiddhiAppRuntimeBuilder.defineStream(SiddhiAppRuntimeBuilder.java:117)
	at io.siddhi.core.util.parser.SiddhiAppParser.defineStreamDefinitions(SiddhiAppParser.java:375)
	at io.siddhi.core.util.parser.SiddhiAppParser.parse(SiddhiAppParser.java:231)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:87)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:97)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:86)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:102)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.wso2.extension.siddhi.map.wso2event.source.WSO2SourceMapper
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.siddhi.core.util.SiddhiClassLoader.loadClass(SiddhiClassLoader.java:33)
	at io.siddhi.core.util.SiddhiClassLoader.loadExtensionImplementation(SiddhiClassLoader.java:49)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSource(DefinitionParserHelper.java:354)
	... 21 more

### Steps to Reproduce

Configure SI-4.2.0-beta pack and start the server.

### Affected Component

SI

### Version

4.2.0-beta

### Environment Details (with versions)

DB: MySQL 8
JDK: temurin-11.0.18.jdk
OS: Mac OS X 12.2.1

**Comment by DedunuKarunarathne** [comment]
Issue is fixed in SI-4.2.0.

**Comment by malshaniS** [comment]
Verified as Fixed
