### ISSUE TITLE
Run HTTP Test suite for MI 4.2.0 Beta testing

### ISSUE THREAD

**Issue by rosensilva** [wso2/api-manager#1488]
### Description

Run HTTP Test suite for MI 4.2.0 Beta testing in public Jenkins to verify the HTTP-related CPU spinning test cases are passing

### Affected Component

MI

**Comment by rosensilva** [comment]
Public Jenkins is failing due to org.wso2.micro.integrator.http.backend.test.SlowReadingBackendTestCase.testSlowReadingBackend (from TestSuite)

Stacktrace
java.util.concurrent.ExecutionException: java.lang.AssertionError: Invalid HTTP Status code received expected [200] but found [500]
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.wso2.micro.integrator.http.backend.test.HTTPCoreBackendTest.invokeHTTPCoreBETestAPI(HTTPCoreBackendTest.java:141)
	at org.wso2.micro.integrator.http.backend.test.SlowReadingBackendTestCase.testSlowReadingBackend(SlowReadingBackendTestCase.java:53)
Caused by: java.lang.AssertionError: Invalid HTTP Status code received expected [200] but found [500]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.wso2.micro.integrator.http.backend.test.HTTPCoreBackendTest.assertHTTPStatusCode(HTTPCoreBackendTest.java:265)
	at org.wso2.micro.integrator.http.backend.test.HTTPCoreBackendTest.assertHTTPStatusCodeEquals200(HTTPCoreBackendTest.java:234)
	at org.wso2.micro.integrator.http.backend.test.SlowReadingBackendTestCase.validateResponse(SlowReadingBackendTestCase.java:60)
	at org.wso2.micro.integrator.http.backend.test.HTTPCoreBackendTest$1.onResponseReceived(HTTPCoreBackendTest.java:135)
	at org.wso2.micro.integrator.http.utils.MultiThreadedHTTPClient.call(MultiThreadedHTTPClient.java:62)
	at org.wso2.micro.integrator.http.utils.MultiThreadedHTTPClient.call(MultiThreadedHTTPClient.java:44)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by rosensilva** [comment]
Closing issue as failing test case is passing in local env
