### ISSUE TITLE
Publisher portal unified search count and pagination doesn't work as expected

### ISSUE THREAD

**Issue by Lakith-Rambukkanage** [wso2/api-manager#1491]
## Problem 
Issue 1 : Search count is incorrect when documents are found in the search result

![](https://user-images.githubusercontent.com/44548749/219657604-e13f5c25-570a-45ca-8038-a7217f84afae.png)

![](https://user-images.githubusercontent.com/44548749/219662527-637b86b1-064c-445c-aea0-46bdc9943d89.png)

Issue 2: Pagination does not work as expected 

- Items per page is set to 10 but 7 is shown

![Image](https://user-images.githubusercontent.com/44548749/220293458-7e362e58-443e-4c0b-ab13-04b2f646459d.png)

- Pagination repeats result items over pages

![Image](https://user-images.githubusercontent.com/44548749/220293702-9daac024-20c1-446a-82f4-07ca7235322f.png)

![Image](https://user-images.githubusercontent.com/44548749/220293725-fbf7bad7-6ef1-4874-bdb0-5a5960b7f037.png)

Issue 3 : an Error is logged when the query includes characters like `[`, `{`

```
[2023-02-17 18:22:17,837] ERROR - ContentBasedSearchService Invalid Search Query, query contains invalid characters
org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse '*adpd]*': Lexical error at line 1, column 6.  Encountered: "]" (93), after : ""
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:212) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:333) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:216) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2637) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:227) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:214) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:1003) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:1018) ~[solr_8.11.1.wso2v7.jar:?]
	at org.wso2.carbon.registry.indexing.solr.SolrClient.query(SolrClient.java:647) ~[org.wso2.carbon.registry.indexing_4.8.13.jar:?]
	at org.wso2.carbon.registry.indexing.solr.SolrClient.query(SolrClient.java:562) ~[org.wso2.carbon.registry.indexing_4.8.13.jar:?]
	at org.wso2.carbon.registry.indexing.service.ContentBasedSearchService.searchContentInternal(ContentBasedSearchService.java:166) ~[org.wso2.carbon.registry.indexing_4.8.13.jar:?]
	at org.wso2.carbon.registry.indexing.service.ContentBasedSearchService.searchByAttribute(ContentBasedSearchService.java:279) ~[org.wso2.carbon.registry.indexing_4.8.13.jar:?]
	at org.wso2.carbon.apimgt.persistence.RegistryPersistenceImpl.searchContentForPublisher(RegistryPersistenceImpl.java:1402) ~[org.wso2.carbon.apimgt.persistence_9.28.75.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.searchPaginatedContent_aroundBody412(APIProviderImpl.java:5081) ~[org.wso2.carbon.apimgt.impl_9.28.75.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.searchPaginatedContent(APIProviderImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.75.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.searchPaginatedContent(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.75.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.SearchApiServiceImpl.search(SearchApiServiceImpl.java:68) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.SearchApi.search(SearchApi.java:56) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor980.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[?:?]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[?:?]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[?:?]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[?:?]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222) ~[?:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:670) ~[tomcat-servlet-api_9.0.70.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[?:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119) ~[org.wso2.carbon.identity.context.rewrite.valve_1.7.1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:116) ~[org.wso2.carbon.identity.context.rewrite.valve_1.7.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38) ~[org.wso2.carbon.tomcat.ext_4.8.0.beta.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:165) ~[org.wso2.carbon.identity.authz.valve_1.7.1.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:111) ~[org.wso2.carbon.identity.auth.valve_1.7.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106) ~[org.wso2.carbon.tomcat.ext_4.8.0.beta.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) ~[org.wso2.carbon.tomcat.ext_4.8.0.beta.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67) ~[org.wso2.carbon.tomcat.ext_4.8.0.beta.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152) ~[org.wso2.carbon.tomcat.ext_4.8.0.beta.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63) ~[org.wso2.carbon.tomcat.ext_4.8.0.beta.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137) ~[org.wso2.carbon.tomcat.ext_4.8.0.beta.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat_9.0.70.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.solr.search.SyntaxError: Cannot parse '*adpd]*': Lexical error at line 1, column 6.  Encountered: "]" (93), after : ""
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:274) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:49) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.search.QParser.getQuery(QParser.java:174) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:162) ~[solr_8.11.1.wso2v7.jar:?]
	... 70 more
Caused by: org.apache.solr.parser.TokenMgrError: Lexical error at line 1, column 6.  Encountered: "]" (93), after : ""
	at org.apache.solr.parser.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1572) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.parser.QueryParser.jj_ntk(QueryParser.java:815) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.parser.QueryParser.Term(QueryParser.java:381) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:278) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:162) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:131) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:270) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:49) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.search.QParser.getQuery(QParser.java:174) ~[solr_8.11.1.wso2v7.jar:?]
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:162) ~[solr_8.11.1.wso2v7.jar:?]
	... 70 more
```

**Comment by Lakith-Rambukkanage** [comment]
Created separate issues to track each issue

https://github.com/wso2/api-manager/issues/1510
https://github.com/wso2/api-manager/issues/1511
https://github.com/wso2/api-manager/issues/1512
