### ISSUE TITLE
Invalid subprotocol. Actual: graphql-ws. Expected one of: null

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#1494]
The issue can be observed only in tenant space when using a backend which sends graphql sub protocol for every connection initialization Eg: Hasura. This has no impact for the functionality yet the error is logged when closing the connection

We have previously fixed such error for super tenant scenario.

```
[2023-02-21 17:04:24,430] ERROR - WebSocketClientHandler Error encountered while processing the response
io.netty.handler.codec.http.websocketx.WebSocketClientHandshakeException: Invalid subprotocol. Actual: graphql-ws. Expected one of: null
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker.finishHandshake(WebSocketClientHandshaker.java:389) ~[io.netty.codec-http_4.1.86.Final.jar:4.1.86.Final]
	at org.wso2.carbon.websocket.transport.WebSocketClientHandler.handleHandshake(WebSocketClientHandler.java:184) ~[org.wso2.carbon.websocket.transport_4.7.165.jar:?]
	at org.wso2.carbon.websocket.transport.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:404) ~[org.wso2.carbon.websocket.transport_4.7.165.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
...
[2023-02-21 17:04:24,430] ERROR - AsyncCallback Invalid subprotocol. Actual: graphql-ws. Expected one of: null
io.netty.handler.codec.http.websocketx.WebSocketClientHandshakeException: Invalid subprotocol. Actual: graphql-ws. Expected one of: null
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker.finishHandshake(WebSocketClientHandshaker.java:389) ~[io.netty.codec-http_4.1.86.Final.jar:4.1.86.Final]
	at org.wso2.carbon.websocket.transport.WebSocketClientHandler.handleHandshake(WebSocketClientHandler.java:184) ~[org.wso2.carbon.websocket.transport_4.7.165.jar:?]
	at org.wso2.carbon.websocket.transport.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:404) ~[org.wso2.carbon.websocket.transport_4.7.165.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
```

**Comment by Arshardh** [comment]
[Update: 28/02/2023]

- Went through the history of this issue and what has been delivered earlier. 
- Managed to reproduce the issue using a Hasura back end. But it is only reproducible at the moment if there is an error in the flow. Once an error occurs in the flow, the Hasura back end sends a close frame to the API Manager, which in turn closes the target side of the connection. This triggers a new handshake once another frame is sent from the client. This new handshake fails and gives the above error. If this is in fact the error reported, we need to figure out if we need to close the client connection in case Hasura sends a close frame, or if we need to do a fix so that the relevant subprotocols are available for the second handshake.
