### ISSUE TITLE
Can't invoke the WebSocket API after enabling the open tracing.

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/api-manager#1550]
### Description

Can't invoke the WebSocket API after enabling the open tracing with the custom implementation. The WebSocket invocation failed with an NPE.

### Steps to Reproduce

- Deploy a WebSocket API [1].
- Enable the Open Tracing with the custom implementation[2].
- Invoke the deployed WebSocket API.

[1] https://apim.docs.wso2.com/en/3.2.0/learn/tutorials/create-and-publish-websocket-api/
[2] https://apim.docs.wso2.com/en/3.2.0/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing/#use-custom-tracer-implementation

### Affected Component

APIM

### Version

3.2.0

### Relevant Log Output

```shell
[2023-02-28 23:51:27,646] ERROR - InboundWebsocketSourceHandler Error encountered while processing inbound websocket connection
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.gateway.utils.GatewayUtils.setTracingId_aroundBody78(GatewayUtils.java:1104) ~[org.wso2.carbon.apimgt.gateway_6.7.206.383.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.GatewayUtils.setTracingId(GatewayUtils.java:1100) ~[org.wso2.carbon.apimgt.gateway_6.7.206.383.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.GatewayUtils.setRequestRelatedTags_aroundBody80(GatewayUtils.java:1125) ~[org.wso2.carbon.apimgt.gateway_6.7.206.383.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.GatewayUtils.setRequestRelatedTags(GatewayUtils.java:1112) ~[org.wso2.carbon.apimgt.gateway_6.7.206.383.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.common.APIMgtLatencySynapseHandler.handleRequestInFlow_aroundBody0(APIMgtLatencySynapseHandler.java:50) ~[org.wso2.carbon.apimgt.gateway_6.7.206.383.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.common.APIMgtLatencySynapseHandler.handleRequestInFlow(APIMgtLatencySynapseHandler.java:38) ~[org.wso2.carbon.apimgt.gateway_6.7.206.383.jar:?]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.invokeHandlers(Axis2SynapseEnvironment.java:1129) ~[synapse-core_2.1.7.wso2v183_22.jar:2.1.7-wso2v183.22]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:1040) ~[synapse-core_2.1.7.wso2v183_22.jar:2.1.7-wso2v183.22]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.injectToSequence(InboundWebsocketSourceHandler.java:747) ~[org.wso2.carbon.inbound.endpoint_4.7.61.33.jar:?]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.handleHandshake(InboundWebsocketSourceHandler.java:297) ~[org.wso2.carbon.inbound.endpoint_4.7.61.33.jar:?]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.channelRead(InboundWebsocketSourceHandler.java:161) ~[org.wso2.carbon.inbound.endpoint_4.7.61.33.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at org.wso2.carbon.apimgt.gateway.handlers.WebsocketInboundHandler.channelRead_aroundBody4(WebsocketInboundHandler.java:273) [org.wso2.carbon.apimgt.gateway_6.7.206.383.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.WebsocketInboundHandler.channelRead(WebsocketInboundHandler.java:155) [org.wso2.carbon.apimgt.gateway_6.7.206.383.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [io.netty.handler_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [io.netty.common_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.common_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.common_4.1.86.Final.jar:4.1.86.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by tgtshanika** [comment]
@BLasan Please add public fix and patch ID information here.
