### ISSUE TITLE
Mock Implementation with API Gateway not working as expected

### ISSUE THREAD

**Issue by ashera96** [wso2/api-manager#1578]
### Description

API deployment fails according to the server logs, but the UI shows that the deployment is successful. Due to this, the API invocation fails. Also, the steps that were followed were based on our [official documentation](https://apim.docs.wso2.com/en/latest/design/prototype-api/create-mocked-js-api/). We need to check why the deployment fails and either fix the product-level issue or amend the doc to show valid steps that showcase a working use case.

Server logs are as follows:

```
[2023-03-09 11:27:46,136]  INFO - CommonUtil Creation of folder is successful. Directory Name : MockImplApi-1
[2023-03-09 11:27:46,137]  INFO - CommonUtil Creation of folder is successful. Directory Name : Definitions
[2023-03-09 11:27:46,209]  INFO - DependencyTracker Local entry : 55d593ad-0e22-4383-abff-46b7a10ca11a was removed from the Synapse configuration successfully
[2023-03-09 11:27:46,210]  INFO - DependencyTracker Local entry : 55d593ad-0e22-4383-abff-46b7a10ca11a was added to the Synapse configuration successfully
[2023-03-09 11:27:46,427] ERROR - InMemoryAPIDeployer Error deploying 55d593ad-0e22-4383-abff-46b7a10ca11a in Gateway
org.apache.axis2.AxisFault: Error while publishing API to the Gateway. Exception initializing inline script
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi_aroundBody0(RESTAPIAdminServiceProxy.java:55) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi(RESTAPIAdminServiceProxy.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:760) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:97) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run_aroundBody0(GatewayJMSMessageListener.java:176) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run(GatewayJMSMessageListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.synapse.SynapseException: Exception initializing inline script
	at org.apache.synapse.mediators.bsf.ScriptMediator.initInlineScript(ScriptMediator.java:465) ~[synapse-extensions_4.0.0.wso2v20.jar:?]
	at org.apache.synapse.mediators.bsf.ScriptMediator.<init>(ScriptMediator.java:189) ~[synapse-extensions_4.0.0.wso2v20.jar:?]
	at org.apache.synapse.mediators.bsf.ScriptMediatorFactory.createSpecificMediator(ScriptMediatorFactory.java:109) ~[synapse-extensions_4.0.0.wso2v20.jar:?]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:251) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:53) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createAnonymousSequence(SequenceMediatorFactory.java:70) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.rest.ResourceFactory.configureSequences(ResourceFactory.java:109) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.rest.ResourceFactory.createResource(ResourceFactory.java:51) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:98) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApi(RestApiAdmin.java:854) ~[org.wso2.carbon.rest.api_4.7.175.jar:?]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiFromString(RestApiAdmin.java:112) ~[org.wso2.carbon.rest.api_4.7.175.jar:?]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiForTenant(RestApiAdmin.java:138) ~[org.wso2.carbon.rest.api_4.7.175.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi_aroundBody0(RESTAPIAdminServiceProxy.java:52) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	... 12 more
Caused by: javax.script.ScriptException: org.mozilla.javascript.EvaluatorException: missing } in compound statement (<Unknown Source>#33)
	at com.sun.phobos.script.javascript.RhinoScriptEngine.compile(RhinoScriptEngine.java:341) ~[bsf-all_3.0.0.wso2v5.jar:?]
	at com.sun.phobos.script.javascript.RhinoScriptEngine.compile(RhinoScriptEngine.java:323) ~[bsf-all_3.0.0.wso2v5.jar:?]
	at org.apache.synapse.mediators.bsf.ScriptMediator.initInlineScript(ScriptMediator.java:454) ~[synapse-extensions_4.0.0.wso2v20.jar:?]
	at org.apache.synapse.mediators.bsf.ScriptMediator.<init>(ScriptMediator.java:189) ~[synapse-extensions_4.0.0.wso2v20.jar:?]
	at org.apache.synapse.mediators.bsf.ScriptMediatorFactory.createSpecificMediator(ScriptMediatorFactory.java:109) ~[synapse-extensions_4.0.0.wso2v20.jar:?]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:251) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:53) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createAnonymousSequence(SequenceMediatorFactory.java:70) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.rest.ResourceFactory.configureSequences(ResourceFactory.java:109) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.rest.ResourceFactory.createResource(ResourceFactory.java:51) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:98) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApi(RestApiAdmin.java:854) ~[org.wso2.carbon.rest.api_4.7.175.jar:?]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiFromString(RestApiAdmin.java:112) ~[org.wso2.carbon.rest.api_4.7.175.jar:?]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiForTenant(RestApiAdmin.java:138) ~[org.wso2.carbon.rest.api_4.7.175.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi_aroundBody0(RESTAPIAdminServiceProxy.java:52) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	... 12 more
Caused by: org.mozilla.javascript.EvaluatorException: missing } in compound statement (<Unknown Source>#33)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:64) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.addError(Parser.java:188) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.addError(Parser.java:166) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.reportError(Parser.java:223) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.reportError(Parser.java:217) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.mustMatchToken(Parser.java:388) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.mustMatchToken(Parser.java:378) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.block(Parser.java:1689) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1010) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.statement(Parser.java:901) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.ifStatement(Parser.java:1082) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:947) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.statement(Parser.java:901) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.parse(Parser.java:540) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Parser.parse(Parser.java:502) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Context.compileImpl(Context.java:2350) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Context.compileReader(Context.java:1296) ~[js_1.7.0.R4wso2v1.jar:?]
	at org.mozilla.javascript.Context.compileReader(Context.java:1268) ~[js_1.7.0.R4wso2v1.jar:?]
	at com.sun.phobos.script.javascript.RhinoScriptEngine.compile(RhinoScriptEngine.java:337) ~[bsf-all_3.0.0.wso2v5.jar:?]
	at com.sun.phobos.script.javascript.RhinoScriptEngine.compile(RhinoScriptEngine.java:323) ~[bsf-all_3.0.0.wso2v5.jar:?]
	at org.apache.synapse.mediators.bsf.ScriptMediator.initInlineScript(ScriptMediator.java:454) ~[synapse-extensions_4.0.0.wso2v20.jar:?]
	at org.apache.synapse.mediators.bsf.ScriptMediator.<init>(ScriptMediator.java:189) ~[synapse-extensions_4.0.0.wso2v20.jar:?]
	at org.apache.synapse.mediators.bsf.ScriptMediatorFactory.createSpecificMediator(ScriptMediatorFactory.java:109) ~[synapse-extensions_4.0.0.wso2v20.jar:?]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:251) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:53) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createAnonymousSequence(SequenceMediatorFactory.java:70) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.rest.ResourceFactory.configureSequences(ResourceFactory.java:109) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.rest.ResourceFactory.createResource(ResourceFactory.java:51) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:98) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApi(RestApiAdmin.java:854) ~[org.wso2.carbon.rest.api_4.7.175.jar:?]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiFromString(RestApiAdmin.java:112) ~[org.wso2.carbon.rest.api_4.7.175.jar:?]
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiForTenant(RestApiAdmin.java:138) ~[org.wso2.carbon.rest.api_4.7.175.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi_aroundBody0(RESTAPIAdminServiceProxy.java:52) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	... 12 more
[2023-03-09 11:27:46,427] ERROR - GatewayJMSMessageListener Error in deploying artifacts for 55d593ad-0e22-4383-abff-46b7a10ca11ain the Gateway
```

### Steps to Reproduce

1. Follow steps 1 and 2 mentioned under [1].
2. Try step 3 and notice that the deployment is successful according to the UI. Check the server logs after the UI success message. The above reported stack trace should appear.
3. API invocation fails due to the fact that API deployment has failed.

[1] https://apim.docs.wso2.com/en/latest/design/prototype-api/create-mocked-js-api/

### Affected Component

APIM

### Version

4.2.0

**Comment by ashera96** [comment]
Note: This issue is not reproduced for APIs that are created from scratch.

**Comment by rmsamitha** [comment]
This is reproduced for OAS3 APIs only
