### ISSUE TITLE
API invocation failure when basic auth is used as the security type when OAuth2 also enabled

### ISSUE THREAD

**Issue by ashera96** [wso2/api-manager#1579]
### Description

API invocation fails when basic auth is used. Response that we receive for the curl is as follows:

```
<soapenv:Reason xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Text xml:lang="en-US">class java.lang.ThreadLocal cannot be cast to class java.lang.String (java.lang.ThreadLocal and java.lang.String are in module java.base of loader 'bootstrap')</soapenv:Text></soapenv:Reason>%  
```

Server logs the following error log:
```
[2023-03-09 13:51:25,582] ERROR - ServerWorker Error processing GET request for : /t/a.com/pizzashack/1.0.0/menu. 
java.lang.ClassCastException: class java.lang.ThreadLocal cannot be cast to class java.lang.String (java.lang.ThreadLocal and java.lang.String are in module java.base of loader 'bootstrap')
	at org.wso2.carbon.apimgt.gateway.handlers.security.basicauth.BasicAuthAuthenticator.extractBasicAuthHeader_aroundBody10(BasicAuthAuthenticator.java:302) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.basicauth.BasicAuthAuthenticator.extractBasicAuthHeader(BasicAuthAuthenticator.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.basicauth.BasicAuthAuthenticator.authenticate_aroundBody6(BasicAuthAuthenticator.java:125) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.basicauth.BasicAuthAuthenticator.authenticate(BasicAuthAuthenticator.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate_aroundBody56(APIAuthenticationHandler.java:546) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate(APIAuthenticationHandler.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody46(APIAuthenticationHandler.java:416) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.112.jar:?]
	at org.apache.synapse.api.API.process(API.java:403) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:108) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:128) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:60) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:76) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:346) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) ~[synapse-core_4.0.0.wso2v20.jar:4.0.0-wso2v20]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRESTRequest(MultitenantMessageReceiver.java:686) ~[org.wso2.carbon.core_4.8.1.jar:?]
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doNhttpREST(MultitenantMessageReceiver.java:588) ~[org.wso2.carbon.core_4.8.1.jar:?]
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doREST(MultitenantMessageReceiver.java:397) ~[org.wso2.carbon.core_4.8.1.jar:?]
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:247) ~[org.wso2.carbon.core_4.8.1.jar:?]
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:87) ~[org.wso2.carbon.core_4.8.1.jar:?]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:379) ~[synapse-nhttp-transport_4.0.0.wso2v20.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:193) ~[synapse-nhttp-transport_4.0.0.wso2v20.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v83.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[2023-03-09 13:51:25,582]  WARN - RelayUtils Server encountered an error, the request message will be consumed and discarded, , CLIENT_ADDRESS = /127.0.0.1:56872, Correlation ID = e580efab-c8c6-4bf0-ae01-8a01a161db76
```

### Steps to Reproduce

1. Follow the steps mentioned in [1]. Make sure to enable both `OAuth2` and `Basic` under `Application Level Security`.
<img width="964" alt="image" src="https://user-images.githubusercontent.com/30475839/223958866-472b18df-3919-496a-80ab-c347cbba29ca.png">

3. Deploy and publish the API.
4. Try invoking the API using Basic Authentication. Refer to the sample curl.

```
curl -X 'GET' \
  "<API_URL>" \
  -H 'accept: application/json' \
  -H 'Authorization: Basic base64(username:password)' -k
```

Response we receive for the above curl is as follows:
```
<soapenv:Reason xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Text xml:lang="en-US">class java.lang.ThreadLocal cannot be cast to class java.lang.String (java.lang.ThreadLocal and java.lang.String are in module java.base of loader 'bootstrap')</soapenv:Text></soapenv:Reason>%   
```

Note: This issue is not reproducible when just `Basic` is enabled at the Runtime Configurations -> Application Level Security. Refer to the screenshots attached below. A similar behaviour should be observed when both `OAuth2` and `Basic` are enabled. Note that the reported flow is what we have shared in our documentation [1].

<img width="964" alt="image" src="https://user-images.githubusercontent.com/30475839/223959637-374e1007-1ba0-462c-b5dc-c66a57b43875.png">

<img width="964" alt="image" src="https://user-images.githubusercontent.com/30475839/223959680-c8460da3-c239-424a-806d-a44d53053766.png">

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/30475839/223959833-31e8d408-2b5f-4893-9dc0-77bb572d5eeb.png">

[1] https://apim.docs.wso2.com/en/latest/design/api-security/api-authentication/secure-apis-using-basic-authentication/#securing-apis-with-basic-authentication

### Affected Component

APIM

### Version

4.2.0

**Comment by rmsamitha** [comment]
This is occurred due to missing fix line merged in https://github.com/wso2/carbon-apimgt/pull/11856.

Fixed in https://github.com/wso2/carbon-apimgt/pull/11920
