### ISSUE TITLE
APIM 4.1.0 API connection timeout Issue

### ISSUE THREAD

**Issue by GihanAyesh** [wso2/api-manager#1591]
### Description

Description

- The first issue is advanced endpoint configuration number fields take invalid inputs such as "e,E,-,+". 
- The second issue is when saved as an empty field for connection timeout duration field, an error is returned in the carbon logs
- The third issue is FIrefox and Safari web engines allow English characters in the advanced configuration number fields.

<img width="1239" alt="git issue" src="https://user-images.githubusercontent.com/47550159/224248604-cfa6c525-4520-4745-bc91-12d2fec98f4c.png">

### Steps to Reproduce

1. Go to advanced endpoint configuration
2. Go to connection timeout duration field
3. Try pressing keys "e,E,-,+"
4. Save and deploy the configuration

### Affected Component

APIM

### Version

4.1.0

### Relevant Log Output

```shell
[2023-03-03 17:56:32,432] ERROR - SynapseArtifactGenerator Error while creating Synapse configurations
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:1.8.0_352]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_352]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_352]
	at com.google.gson.JsonPrimitive.getAsDouble(JsonPrimitive.java:161) ~[com.google.gson_2.9.0.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils.getUpdatedEndpointConfig(ImportUtils.java:1095) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils.preProcessEndpointConfig(ImportUtils.java:1051) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils.processRetrievedDefinition(ImportUtils.java:972) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils.retrievedAPIDtoJson(ImportUtils.java:941) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils.retrievedAPIDto(ImportUtils.java:1000) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.SynapseArtifactGenerator.generateGatewayArtifact(SynapseArtifactGenerator.java:94) ~[?:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.RuntimeArtifactGeneratorUtil.generateRuntimeArtifact_aroundBody0(RuntimeArtifactGeneratorUtil.java:57) ~[org.wso2.carbon.apimgt.impl_9.20.74.99.jar:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.RuntimeArtifactGeneratorUtil.generateRuntimeArtifact(RuntimeArtifactGeneratorUtil.java:49) ~[org.wso2.carbon.apimgt.impl_9.20.74.99.jar:?]
	at org.wso2.carbon.apimgt.internal.service.impl.RuntimeArtifactsApiServiceImpl.runtimeArtifactsGet(RuntimeArtifactsApiServiceImpl.java:51) ~[?:?]
	at org.wso2.carbon.apimgt.internal.service.RuntimeArtifactsApi.runtimeArtifactsGet(RuntimeArtifactsApi.java:47) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor551.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[?:?]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[?:?]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[?:?]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[?:?]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222) ~[?:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:670) ~[tomcat-servlet-api_9.0.71.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[?:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) ~[org.wso2.carbon.identity.context.rewrite.valve_1.4.52.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) ~[org.wso2.carbon.identity.authz.valve_1.4.52.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:109) ~[org.wso2.carbon.identity.auth.valve_1.4.52.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:58) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat_9.0.71.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
[2023-03-03 17:56:32,434] ERROR - InMemoryAPIDeployer Error retrieving artifacts for API 540a6ed9-a184-4ab6-afdd-3f1a49a3fdf1. Storage returned null
[2023-03-03 17:56:32,434] ERROR - InMemoryAPIDeployer Error deploying 540a6ed9-a184-4ab6-afdd-3f1a49a3fdf1 in Gateway
org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.exception.ArtifactSynchronizerException: Error retrieving artifacts for API 540a6ed9-a184-4ab6-afdd-3f1a49a3fdf1. Storage returned null
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact_aroundBody4(InMemoryAPIDeployer.java:170) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact(InMemoryAPIDeployer.java:155) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:91) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:86) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.lambda$0_aroundBody12(GatewayJMSMessageListener.java:170) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.lambda$0(GatewayJMSMessageListener.java:147) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
[2023-03-03 17:56:32,435] ERROR - InMemoryAPIDeployer Error deploying 540a6ed9-a184-4ab6-afdd-3f1a49a3fdf1 in Gateway
org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.exception.ArtifactSynchronizerException: Error deploying 540a6ed9-a184-4ab6-afdd-3f1a49a3fdf1 in Gateway
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact_aroundBody4(InMemoryAPIDeployer.java:175) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact(InMemoryAPIDeployer.java:155) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:91) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:86) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.lambda$0_aroundBody12(GatewayJMSMessageListener.java:170) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.lambda$0(GatewayJMSMessageListener.java:147) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
Caused by: org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.exception.ArtifactSynchronizerException: Error retrieving artifacts for API 540a6ed9-a184-4ab6-afdd-3f1a49a3fdf1. Storage returned null
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact_aroundBody4(InMemoryAPIDeployer.java:170) ~[org.wso2.carbon.apimgt.gateway_9.20.74.98.jar:?]
	... 6 more
```

**Comment by GihanAyesh** [comment]
Closing the issue as the public fix is merged.
