### ISSUE TITLE
Error configuring SAML SSO in APIM

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#1631]
### Description

After following the steps below, getting the provided error.

1. Create a Service Provider from the Management Console
2. Click on Configure under **"Inbound Authentication Configuration" -> "SAML2 Web SSO Configuration"**
3. A blank screen will be seen inside the main screen and the following error is seen in the terminal.

```
[2023-03-20 09:43:25,947] ERROR - [bridgeservlet] Servlet.service() for servlet [bridgeservlet] threw exception
javax.servlet.ServletException: JSP file [&#47;sso-saml&#47;add_service_provider.jsp] not found
	at org.apache.jasper.servlet.JspServlet.handleMissingResource(JspServlet.java:400) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:368) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327) ~[tomcat_9.0.70.wso2v1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.70.wso2v1.jar:?]
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207) ~[org.wso2.carbon.ui_4.8.1.jar:?]
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80) ~[org.wso2.carbon.ui_4.8.1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.70.wso2v1.jar:?]
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) ~[org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) ~[?:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.70.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) ~[org.wso2.carbon.tomcat.ext_4.8.1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:578) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:517) ~[tomcat_9.0.70.wso2v1.jar:?]
        …
[2023-03-20 09:43:25,948] ERROR - [bridgeservlet] Servlet.service() for servlet [bridgeservlet] threw exception
javax.servlet.ServletException: JSP file [&#47;sso-saml&#47;add_service_provider.jsp] not found
	at org.apache.jasper.servlet.JspServlet.handleMissingResource(JspServlet.java:400) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:368) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327) ~[tomcat_9.0.70.wso2v1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.70.wso2v1.jar:?]
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207) ~[org.wso2.carbon.ui_4.8.1.jar:?]
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80) ~[org.wso2.carbon.ui_4.8.1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.70.wso2v1.jar:?]
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) ~[org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) ~[?:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.70.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) ~[org.wso2.carbon.tomcat.ext_4.8.1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:578) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:517) ~[tomcat_9.0.70.wso2v1.jar:?]
	…
[2023-03-20 09:43:25,948] ERROR - JspTilesRequestContext JSPException while including path '/sso-saml/add_service_provider.jsp'.
javax.servlet.jsp.JspException: ServletException while including page.
	at org.apache.tiles.jsp.context.JspUtil.doInclude(JspUtil.java:102) ~[tiles-jsp_2.0.5.wso2v2.jar:?]
	at org.apache.tiles.jsp.context.JspTilesRequestContext.include(JspTilesRequestContext.java:88) ~[tiles-jsp_2.0.5.wso2v2.jar:?]
	at org.apache.tiles.jsp.context.JspTilesRequestContext.dispatch(JspTilesRequestContext.java:82) ~[tiles-jsp_2.0.5.wso2v2.jar:?]
	at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:465) ~[tiles-jsp_2.0.5.wso2v2.jar:?]
	at org.apache.tiles.jsp.taglib.InsertAttributeTag.render(InsertAttributeTag.java:140) ~[tiles-jsp_2.0.5.wso2v2.jar:?]
	at org.apache.tiles.jsp.taglib.InsertAttributeTag.render(InsertAttributeTag.java:117) ~[tiles-jsp_2.0.5.wso2v2.jar:?]
	at org.apache.tiles.jsp.taglib.RenderTagSupport.execute(RenderTagSupport.java:171) ~[tiles-jsp_2.0.5.wso2v2.jar:?]
	at org.apache.tiles.jsp.taglib.RoleSecurityTagSupport.doEndTag(RoleSecurityTagSupport.java:75) ~[tiles-jsp_2.0.5.wso2v2.jar:?]
	at org.apache.tiles.jsp.taglib.ContainerTagSupport.doEndTag(ContainerTagSupport.java:80) ~[tiles-jsp_2.0.5.wso2v2.jar:?]
	at org.apache.jsp.admin.layout.template_jsp._jspx_meth_tiles_005finsertAttribute_005f7(template_jsp.java:781) ~[?:?]
	at org.apache.jsp.admin.layout.template_jsp._jspService(template_jsp.java:444) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[tomcat_9.0.70.wso2v1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.70.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379) ~[tomcat_9.0.70.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327) ~[tomcat_9.0.70.wso2v1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.70.wso2v1.jar:?]
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207) ~[org.wso2.carbon.ui_4.8.1.jar:?]
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80) ~[org.wso2.carbon.ui_4.8.1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.70.wso2v1.jar:?]
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) ~[org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) ~[?:?]
```

### Steps to Reproduce

Please check the description.

### Affected Component

APIM

### Version

4.2.0

**Comment by tharikaGitHub** [comment]
The issue is because we are not packing the relevant identity feature in APIM. Refer [1] for information. 

Closing based on the above explanation.

[1] https://github.com/wso2/product-apim/issues/7124
