### ISSUE TITLE
Request with Content-Type : "application/json" and empty body fails after moved to U2 from wum

### ISSUE THREAD

**Issue by JanithaSampathBandara** [wso2/api-manager#1636]
### Description

This customer has recently moved from WUM to U2. They have a use case to build messages for all the APIs. After moving U2, they get errors in the following scenario.

If incoming request has “Content-Type” : Application/json and message body is empty
We did some analysis. Found that previously, they were using FORCE_POST_PUT_NOBODY property to prevent this type of error. After moving to U2 (17), they see these errors.

Since customers used with no request body previously, after U2, all the requests with no-request body and have Content Type application/json fail. It seems that in the U2 level, support for FORCE_POST_PUT_NOBODY was removed. 

### Steps to Reproduce

1. Create an API with POST/PATCH/DELETE resources
2. Send a request with “Content-Type : application/json” and empty message body
3. You’ll be below errors in logs

### Affected Component

APIM

### Version

2.0.0

### Relevant Log Output

```shell
ERROR {org.apache.synapse.commons.json.JsonUtil} -  #writeAsJson. Payload could not be written as JSON. MessageID: urn:uuid:2fe94c00-cde3-45e9-abba-c3e984115151 {org.apache.synapse.commons.json.JsonUtil}
ERROR {org.apache.synapse.core.axis2.Axis2Sender} -  Unexpected error during sending message out {org.apache.synapse.core.axis2.Axis2Sender}
org.apache.axis2.AxisFault: Payload could not be written as JSON.
   at org.apache.synapse.commons.json.JsonUtil.writeAsJson(JsonUtil.java:266)
   at org.apache.synapse.commons.json.JsonFormatter.writeTo(JsonFormatter.java:62)
   at org.apache.synapse.transport.passthru.PassThroughHttpSender.sendRequestContent(PassThroughHttpSender.java:428)
   at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:276)
   at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
   at org.apache.synapse.core.axis2.DynamicAxisOperation$DynamicOperationClient.send(DynamicAxisOperation.java:185)
   at org.apache.synapse.core.axis2.DynamicAxisOperation$DynamicOperationClient.executeImpl(DynamicAxisOperation.java:167)
   at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
   at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:580)
   at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:78)
   at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:544)
   at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:382)
   at org.apache.synapse.endpoints.HTTPEndpoint.send(HTTPEndpoint.java:85)
   at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:118)
   at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:95)
   at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:57)
   at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:169)
   at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:95)
   at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:57)
   at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
   at org.apache.synapse.rest.Resource.process(Resource.java:325)
   at org.apache.synapse.rest.API.process(API.java:417)
   at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:90)
   at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
   at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:300)
   at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:86)
   at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
   at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:358)
   at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:404)
   at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181)
   at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   at java.lang.Thread.run(Thread.java:750)
```

**Comment by dulithsenanayake** [comment]
Closing this since this is already fixed with this PR[1].
[1]: https://github.com/wso2/wso2-synapse/pull/1699
