### ISSUE TITLE
API fail if the endpoint session timeout value is set as an integer.

### ISSUE THREAD

**Issue by SupunRandunu** [wso2/api-manager#1637]
### Description

API fails with the error [1] if the endpoint session timeout value is set as an integer. 
```

[1]ERROR {org.apache.synapse.config.xml.endpoints.IndirectEndpointFactory} - Invalid session timeout value : 300.0
 WARN {org.apache.synapse.config.xml.SynapseXMLConfigurationFactory} - Endpoint configuration: DocumentAPI--vv1_APIproductionEndpoint cannot be built - Continue in fail-safe mode org.apache.synapse.SynapseException: Invalid session timeout value : 300.0
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.handleException(EndpointFactory.java:330)
	at org.apache.synapse.config.xml.endpoints.SALoadbalanceEndpointFactory.createEndpoint(SALoadbalanceEndpointFactory.java:79)
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.createEndpointWithName(EndpointFactory.java:143)
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.getEndpointFromElement(EndpointFactory.java:80)
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineEndpoint(SynapseXMLConfigurationFactory.java:285)
	at org.wso2.carbon.endpoint.service.EndpointAdmin.addEndpoint(EndpointAdmin.java:183)
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint_aroundBody0(EndpointAdminServiceProxy.java:59)
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint(EndpointAdminServiceProxy.java:55)
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:696)
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653)
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody6(InMemoryAPIDeployer.java:219)
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:193)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:145)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:131)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody20(GatewayStartupListener.java:316)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:305)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody32(GatewayStartupListener.java:305)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:305)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:422)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:419)
	at java.lang.Thread.run(Thread.java:748)

ERROR {org.wso2.carbon.endpoint.service.EndpointAdmin} - Unable to create endpoint
ERROR {org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy} - Error adding endpoint file to the gateway org.wso2.carbon.endpoint.EndpointAdminException: Unable to create endpoint
	at org.wso2.carbon.endpoint.service.EndpointAdmin.handleFault(EndpointAdmin.java:599)
	at org.wso2.carbon.endpoint.service.EndpointAdmin.addEndpoint(EndpointAdmin.java:188)
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint_aroundBody0(EndpointAdminServiceProxy.java:59)
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint(EndpointAdminServiceProxy.java:55)
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:696)
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653)
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody6(InMemoryAPIDeployer.java:219)
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:193)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:145)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:131)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody20(GatewayStartupListener.java:316)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:305)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody32(GatewayStartupListener.java:305)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:305)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:422)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:419)
	at java.lang.Thread.run(Thread.java:748)

ERROR {org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer} - Error in deploying DocumentAPI to the Gateway org.apache.axis2.AxisFault: Error while adding the endpoint fileUnable to create endpoint
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint_aroundBody0(EndpointAdminServiceProxy.java:65)
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint(EndpointAdminServiceProxy.java:55)
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:696)
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653)
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody6(InMemoryAPIDeployer.java:219)
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:193)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:145)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:131)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody20(GatewayStartupListener.java:316)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:305)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody32(GatewayStartupListener.java:305)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:305)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:422)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:419)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.endpoint.EndpointAdminException: Unable to create endpoint
	at org.wso2.carbon.endpoint.service.EndpointAdmin.handleFault(EndpointAdmin.java:599)
	at org.wso2.carbon.endpoint.service.EndpointAdmin.addEndpoint(EndpointAdmin.java:188)
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.addEndpoint_aroundBody0(EndpointAdminServiceProxy.java:59)
	... 14 more
```

### Steps to Reproduce

- Create an API and navigate to the API Configurations->Endpoints.
- Expand the Load balance and Failover Configurations and set the endpoint type as Load Balanced.
- Click the Load Balance Configurations and save the default Session Timeout Value.
- Re-deploy the API and Restart the server.
- Then You may get the below error continuously in the log.

### Affected Component

APIM

### Version

4.1.0

**Comment by Tharsanan1** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/11944
