### ISSUE TITLE
Micro gateway restarting in PROD

### ISSUE THREAD

**Issue by vikumkbv** [wso2/api-manager#1643]
### Problem

Hi Team,

Could you please provide the fix for the following NPE which is logged to the ballerina-internal.log in MGW 3.2.0. This should fix at the ballerina level.

```
[2023-03-15 13:07:44,673] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException

        at org.ballerinalang.jvm.BallerinaErrors.filterStackTraceElement(BallerinaErrors.java:255)

        at org.ballerinalang.jvm.values.ErrorValue.getStackTrace(ErrorValue.java:192)

        at org.ballerinalang.jvm.values.ErrorValue.getPrintableStackTrace(ErrorValue.java:208)

        at org.ballerinalang.net.http.HttpUtil.handleFailure(HttpUtil.java:415)

        at org.ballerinalang.net.http.HttpCallableUnitCallback.notifyFailure(HttpCallableUnitCallback.java:42)

        at org.ballerinalang.jvm.scheduling.Scheduler.postProcess(Scheduler.java:324)

        at org.ballerinalang.jvm.scheduling.Scheduler.run(Unknown Source)

        at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Unknown Source)

        at java.base/java.lang.Thread.run(Unknown Source)

```

### Solution

N/A

### Affected Component

APIM

### Version

3.2.0

### Suggested Labels

product/mgw

**Comment by YasasRangika** [comment]
This issue has been fixed in the master branch via the PR: https://github.com/wso2/product-microgateway/pull/3323.
