### ISSUE TITLE
[APIM 3.2] Startup errors 

### ISSUE THREAD

**Issue by pdkgamage** [wso2/api-manager#166]
### Description

Following error is observed and the server is not getting started.

[2022-06-08 11:53:56,089] ERROR - Digester Begin event threw exception
java.lang.ClassNotFoundException: org.wso2.carbon.identity.auth.valve.AuthenticationValve
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.core.runtime.internal.adaptor.ContextFinder.loadClass(ContextFinder.java:131)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:144)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1263)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1542)
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.configure(CarbonTomcat.java:88)
	at org.wso2.carbon.tomcat.internal.ServerManager.init(ServerManager.java:122)
	at org.wso2.carbon.tomcat.internal.TomcatBundleActivator.start(TomcatBundleActivator.java:45)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
[2022-06-08 11:53:56,091] ERROR - CarbonTomcat error while parsing xml stream
java.lang.ClassNotFoundException: org.wso2.carbon.identity.auth.valve.AuthenticationValve
	at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:2651)
	at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:2683)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1266)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1542)
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.configure(CarbonTomcat.java:88)
	at org.wso2.carbon.tomcat.internal.ServerManager.init(ServerManager.java:122)
	at org.wso2.carbon.tomcat.internal.TomcatBundleActivator.start(TomcatBundleActivator.java:45)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
[2022-06-08 11:53:56,647]  INFO - BinaryDataReceiverServiceComponent Binary Data Receiver server activated

I removed few jars which removed from wum update and applied wum diff. These are the jar files removed. then start the server but server didn't get started. Also, if i restore these jars again server start without any issue.

Remove "jackson-databind-2.9.9.jar" file from <APIM_HOME>/lib/runtimes/cxf3 directory
Remove "net.minidev.json-smart_1.3.0.jar" from <APIM_HOME>/repository/components/plugins
Remove "slf4j.api_1.6.1.jar" from <APIM_HOME>/repository/components/plugins
Remove "slf4j.api_1.7.13.jar" from <APIM_HOME>/repository/components/plugins
Remove "slf4j.api_1.7.21.jar" from <APIM_HOME>/repository/components/plugins
Remove "slf4j.log4j12_1.6.1.jar" from <APIM_HOME>/repository/components/plugins
Remove "slf4j.log4j12_1.7.13.jar" from <APIM_HOME>/repository/components/plugins
Remove "slf4j.log4j12_1.7.21.jar" from <APIM_HOME>/repository/components/plugins
Remove "commons-codec-1.4.jar" from <APIM_HOME>/repository/components/tools/forget-me/lib
Remove "log4j-1.2.17.jar" from <APIM_HOME>/repository/components/tools/forget-me/lib
Remove "slf4j-api-1.7.25.jar" from <APIM_HOME>/repository/components/tools/forget-me/lib
Remove "slf4j-log4j12-1.7.25.jar" from <APIM_HOME>/repository/components/tools/forget-me/lib

Any reason?

### Steps to Reproduce

applied wum diff manually. wum level 1621359805584 to 1651515169359.

### Affected Component

APIM

### Version

3.2

### Environment Details (with versions)

Ubuntu

### Related Issues

https://github.com/wso2/product-is/issues/3238

**Comment by pubudu538** [comment]
Answer for this available in StackOverflow. You can read the original answer from https://stackoverflow.com/a/76916398/3176125. Copying the same answer here for more visibility.

----
This WSO2 IS/APIM startup failure encounters when using the latest JDK versions 11 (JDK 11.0.20) and 17 (JDK 17.0.8+9). This is due to a fix that has been implemented by JDK [1].

According to the JDK release notes [2] [3], we can disable these newly introduced validations to preserve backward compatibility. These validations can be disabled by adding the following.

- Linux / MacOS Users:

Include the provided lines below after the line: "-Djava.net.preferIPv4Stack=true " in either:

wso2server.sh for WSO2 Identity Server and API Manager versions prior to 4.0.0, or api-manager.sh for WSO2 API Manager versions 4.0.0 and later.

```
-Djdk.util.zip.disableZip64ExtraFieldValidation=true \
-Djdk.nio.zipfs.allowDotZipEntry=true \
```
- Windows Users:

Append the provided parameters below to the CMD_LINE_ARGS parameter (at the end of the line starting with "set CMD_LINE_ARGS") in either:

wso2server.bat for WSO2 Identity Server and API Manager versions prior to 4.0.0, or api-manager.bat for WSO2 API Manager versions 4.0.0 and later.

```
-Djdk.util.zip.disableZip64ExtraFieldValidation=true 
-Djdk.nio.zipfs.allowDotZipEntry=true
```

[1] - https://bugs.openjdk.org/browse/JDK-8251329

[2] - https://www.oracle.com/java/technologies/javase/11-0-20-relnotes.html

[3] - https://www.oracle.com/java/technologies/javase/17all-relnotes.html

Thank you!
Pubudu.
