### ISSUE TITLE
API Gateway Error while creating an API with a malformed context with the APICTL tool 

### ISSUE THREAD

**Issue by DaniduWijendra** [wso2/api-manager#1702]
### Description

When create an API with a malformed context eg: /testapi{version} using the APICTL tool. In that case, it was deployed and published in the gateway without any error. We expecting that there should be a proper validation to check at all parameter levels while creating an API from the APICTL tool and it should not save in case of an error.

### Steps to Reproduce

Start the APIM server and create an API from the APICTL tool which has the following context.

_/testapi{version}_

While creating the API you can see the following error trace.
```
INFO - API {api:TestAPI:v20} Initializing API: TestAPI:v20
Exception in thread "Thread-187" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 10
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at org.wso2.carbon.apimgt.gateway.internal.DataHolder.addAPIMetaData_aroundBody32(DataHolder.java:138)
	at org.wso2.carbon.apimgt.gateway.internal.DataHolder.addAPIMetaData(DataHolder.java:130)
	at org.wso2.carbon.apimgt.gateway.internal.DataHolder.addAPIMetaData_aroundBody40(DataHolder.java:200)
	at org.wso2.carbon.apimgt.gateway.internal.DataHolder.addAPIMetaData(DataHolder.java:195)
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:101)
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:86)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.lambda$0_aroundBody12(GatewayJMSMessageListener.java:170)
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.lambda$0(GatewayJMSMessageListener.java:147)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Therefore we believe that when there is a malformed context in the API, the API should not be created from the APICTL tool and it should give a proper error message while creating the API.

### Affected Component

APICTL

### Version

3.2.0 4.1.0

**Comment by YasasRangika** [comment]
As stated in the linked internal issue this issue does not apply to the master branch.
