### ISSUE TITLE
NPEs when using throttling with Redis.

### ISSUE THREAD

**Issue by janithcmw** [wso2/api-manager#1735]
### Description

Hi All,

When trying out throttling with Redis based on the documentation[1] the following errors were observed.

```
ERROR {org.apache.synapse.commons.throttle.core.ThrottleWindowReplicator} - Could not replicate throttle data java.lang.NullPointerException
	at org.wso2.carbon.apimgt.gateway.RedisBaseDistributedCountManager.getTimestamp_aroundBody12(RedisBaseDistributedCountManager.java:202)
	at org.wso2.carbon.apimgt.gateway.RedisBaseDistributedCountManager.getTimestamp(RedisBaseDistributedCountManager.java:1)
	at org.apache.synapse.commons.throttle.core.SharedParamManager.getSharedTimestamp(SharedParamManager.java:172)
	at org.apache.synapse.commons.throttle.core.ThrottleWindowReplicator$ReplicatorTask.run(ThrottleWindowReplicator.java:111)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
ERROR {org.apache.synapse.commons.throttle.core.ThrottleWindowReplicator} - Could not replicate throttle data java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:655)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at org.wso2.carbon.apimgt.gateway.RedisBaseDistributedCountManager.asyncGetAndAlterCounter_aroundBody10(RedisBaseDistributedCountManager.java:181)
	at org.wso2.carbon.apimgt.gateway.RedisBaseDistributedCountManager.asyncGetAndAlterCounter(RedisBaseDistributedCountManager.java:1)
	at org.wso2.carbon.apimgt.gateway.RedisBaseDistributedCountManager.setCounter_aroundBody2(RedisBaseDistributedCountManager.java:75)
	at org.wso2.carbon.apimgt.gateway.RedisBaseDistributedCountManager.setCounter(RedisBaseDistributedCountManager.java:1)
	at org.apache.synapse.commons.throttle.core.SharedParamManager.setDistributedCounter(SharedParamManager.java:58)
	at org.apache.synapse.commons.throttle.core.ThrottleWindowReplicator$ReplicatorTask.run(ThrottleWindowReplicator.java:142)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

[1] https://apim.docs.wso2.com/en/latest/design/rate-limiting/advanced-topics/configuring-rate-limiting-api-gateway-cluster/#configuring-a-redis-cluster-with-api-manager

Thanks!
Janith.

### Steps to Reproduce

This can be reproduced by following the documentation[1].

[1] https://apim.docs.wso2.com/en/latest/design/rate-limiting/advanced-topics/configuring-rate-limiting-api-gateway-cluster/#configuring-a-redis-cluster-with-api-manager

### Affected Component

APIM

### Version

4.2.0

**Comment by YasasRangika** [comment]
public fix PR: https://github.com/wso2/carbon-apimgt/pull/11968

**Comment by thisaltennakoon** [comment]
This fix has been covered from https://github.com/wso2/carbon-apimgt/pull/12059
