### ISSUE TITLE
MI does not retry to connect to RabbitMQ broker after connectivity fails with AlreadyClosedException.

### ISSUE THREAD

**Issue by imedyaosandi** [wso2/api-manager#1760]
### Description

When MI lost the connectivity to RabbitMQ broker, initially MI tries to recover the connection. During the recovery process, if MI used an already closed connection or channel to reconnect, we could observe the AlreadyClosedException as below.

```
[2023-04-20 20:29:59,785] ERROR {ForgivingExceptionHandler} - Caught an exception when recovering topology Caught an exception while recovering queue SalesOrderQueue: connection is already closed due to connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0) com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering queue SalesOrderQueue: connection is already closed due to connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverQueue(AutorecoveringConnection.java:753)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverTopology(AutorecoveringConnection.java:665)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:579)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$addAutomaticRecoveryListener$3(AutorecoveringConnection.java:509)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:797)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:774)
	at com.rabbitmq.client.impl.AMQConnection.handleIoError(AMQConnection.java:748)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$null$1(AutorecoveringConnection.java:134)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:258)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:341)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:282)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141)
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:968)
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:52)
	at com.rabbitmq.client.impl.recovery.RecordedQueue.recover(RecordedQueue.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$recoverQueue$5(AutorecoveringConnection.java:722)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.wrapRetryIfNecessary(AutorecoveringConnection.java:818)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverQueue(AutorecoveringConnection.java:721)
	... 8 more
```
After this exception the MI listener does not retry to connect to the broker and needs a redeployment of the listener service.

### Steps to Reproduce

1. Enable the rabbitmq listener with below configs
```
[transport.rabbitmq]
listener_enable = true

[[transport.rabbitmq.listener]]
name = "AMQPConnectionFactory"
parameter.hostname = "localhost"
parameter.port = 5672
parameter.username = "guest"
parameter.password = "guest"
parameter.retry_interval = "1000"
parameter.retry_count = 5
```
2. Set up rabbitmq server. (RabbitMQ 3.10.19 / Erlang 25.3)
3. Deploy the below listener proxy.
```
<proxy xmlns="http://ws.apache.org/ns/synapse" name="AMQPProxy" transports="rabbitmq" statistics="disable" trace="enable" startOnLoad="true">
<target>
 <inSequence>
   <log level="full"/>
   <property name="OUT_ONLY" value="true"/>
   <property name="FORCE_SC_ACCEPTED" value="true" scope="axis2"/>
   <drop/>
    <!-- <send>
     <endpoint>
       <address uri="http://localhost:9000/services/SimpleStockQuoteService"/>
     </endpoint>
    </send> -->
 </inSequence>
</target>
 <outSequence>
   <drop/>
 </outSequence>
    <parameter name="rabbitmq.queue.name">SalesOrderQueue</parameter>
    <parameter name="rabbitmq.connection.factory">AMQPConnectionFactory</parameter>
   <description/>
</proxy>
```
3. Start the MI server in debug mode (-debug 5005)
4. Add a debug point[1] and enable remote debugging.
5. Stop the rabbitmq server and this will hit the debug point[1]. Using the evaluator call the channel.close() method and resume the debugging. You will observe the below logs;
```
[2023-04-20 13:19:08,612]  WARN {ForgivingExceptionHandler} - An unexpected connection driver error occured (Exception message: Connection reset)
[2023-04-20 13:19:35,488]  WARN {ChannelManager} - Consumer dispatcher for channel didn't shutdown after waiting for 10000 ms
[2023-04-20 13:19:35,490]  INFO {ServiceTaskManager} - The consumer with consumer tag: amq.ctag-Q_JQCyAuvcanKj0dmJdWhA was shut down.
```
6. Then restart the broker and you will observe the below error.
```
[2023-04-20 13:24:41,018]  WARN {ForgivingExceptionHandler} - An unexpected connection driver error occured (Exception message: Connection reset)
[2023-04-20 13:24:41,026] ERROR {ForgivingExceptionHandler} - Caught an exception when recovering topology Caught an exception while recovering queue SalesOrderQueue: connection is already closed due to connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0) com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering queue SalesOrderQueue: connection is already closed due to connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverQueue(AutorecoveringConnection.java:753)
	at com.rabbitmq.client.impl.recovery.Listening for transport dt_socket at address: 5005
AutorecoveringConnection.recoverTopology(AutorecoveringConnection.java:665)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:579)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$addAutomaticRecoveryListener$3(AutorecoveringConnection.java:509)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:797)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:774)
	at com.rabbitmq.client.impl.AMQConnection.handleIoError(AMQConnection.java:748)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$null$1(AutorecoveringConnection.java:134)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:258)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:341)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:282)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141)
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:968)
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:52)
	at com.rabbitmq.client.impl.recovery.RecordedQueue.recover(RecordedQueue.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$recoverQueue$5(AutorecoveringConnection.java:722)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.wrapRetryIfNecessary(AutorecoveringConnection.java:818)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverQueue(AutorecoveringConnection.java:721)
	... 8 more
```
After the above exception MI listener does not retry to connect to the broker even though the broker is available.

[1] https://github.com/wso2/wso2-axis2-transports/blob/v2.0.0-wso2v65/modules/rabbitmq/src/main/java/org/apache/axis2/transport/rabbitmq/ServiceTaskManager.java#L190

### Affected Component

MI

### Version

4.1.0

**Comment by YasasRangika** [comment]
This issue has been resolved after changing the load balancer configurations of the RabbitMQ cluster.
