### ISSUE TITLE
Container not starting within k3s

### ISSUE THREAD

**Issue by wopl** [wso2/api-manager#1781]
### Description

Downloaded the latest WSO2AM from docker.wso2.com/wso2am:4.1.0.16
mounted a volume to /home/wso2carbon/wso2am-4.1.0/repository
changed owner of this dir to user 802:802
added /home/wso2carbon/data/deployment/server/executionplans directory as it was not found (again user 802:802)

And still the container is not starting up (see logfile)
Did I oversee anything?

### Steps to Reproduce

see in description

### Affected Component

APIM

### Version

4.1.0.16

### Environment Details (with versions)

k3s Kubernetes Cluster

### Relevant Log Output

Start WSO2 Carbon server
JAVA_HOME environment variable is set to /opt/java/openjdk
CARBON_HOME environment variable is set to /home/wso2carbon/wso2am-4.1.0
Using Java memory options: -Xms256m -Xmx1024m
Configuration error
java.io.FileNotFoundException: /home/wso2carbon/wso2am-4.1.0/repository/conf/etc/logging-bridge.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:490)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:328)
	at java.logging/java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:445)
	at java.logging/java.util.logging.LogManager$2.run(LogManager.java:394)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.logging/java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:382)
	at java.logging/java.util.logging.LogManager.getLogManager(LogManager.java:430)
	at java.logging/sun.util.logging.internal.LoggingProviderImpl.demandJULLoggerFor(LoggingProviderImpl.java:408)
	at java.logging/sun.util.logging.internal.LoggingProviderImpl.demandLoggerFor(LoggingProviderImpl.java:436)
	at java.base/jdk.internal.logger.DefaultLoggerFinder.getLogger(DefaultLoggerFinder.java:157)
	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:389)
	at java.base/jdk.internal.logger.LazyLoggers.getLazyLogger(LazyLoggers.java:444)
	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:414)
	at java.base/java.lang.System.getLogger(System.java:1662)
	at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.<clinit>(ConnectorBootstrap.java:866)
	at jdk.management.agent/jdk.internal.agent.Agent.startLocalManagementAgent(Agent.java:318)
	at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:450)
	at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:599)
[2023-04-28 11:31:10,666]  WARN {org.wso2.config.mapper.ConfigParser} - deployment.toml not found at /home/wso2carbon/wso2am-4.1.0/repository/conf/deployment.toml
Apr 28, 2023 11:31:10 AM org.wso2.carbon.server.Main addSystemProperties
WARNING: The file '/home/wso2carbon/wso2am-4.1.0/repository/conf/carbon.properties' does not exist.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:69)
	at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: java.lang.RuntimeException: Could not find framework
	at org.wso2.carbon.server.CarbonLauncher.buildInitialPropertyMap(CarbonLauncher.java:199)
	at org.wso2.carbon.server.CarbonLauncher.launch(CarbonLauncher.java:74)
	at org.wso2.carbon.server.Main.launchCarbon(Main.java:176)
	at org.wso2.carbon.server.Main.main(Main.java:109)
	... 6 more

### Suggested Labels

bug

**Comment by wopl** [comment]
resolved: mounting the volume did destroy the structure.
