### ISSUE TITLE
The USER_ROLE_CACHE  already existing issue due to the concurrent executions of the cache initializing method

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/api-manager#1848]
### Description

The below error can be observed during the server startup when the APIM server has been deployed in an active-active manner.  As per the debugging observations, this happened due to the concurrent execution of the **USER_ROLES_CACHE** creation method and it has been identified that this is a highly unlikely scenario that can be happened due to the slow execution of the threads. Furthermore, the server hasn't functioned as expected due to the below error, and had to restart the server to recover.

```
TID: [-1234] [] [2023-05-16 11:34:04,644] ERROR {org.wso2.carbon.andes.authorization.service.andes.AndesAuthorizationPlugin} - Error while invoking AndesAuthorizationHandler org.wso2.carbon.andes.authorization.andes.AndesAuthorizationHandlerException: Error handling publish queue.
    at org.wso2.carbon.andes.authorization.andes.AndesAuthorizationHandler.handlePublishToExchange(AndesAuthorizationHandler.java:587)
    at org.wso2.carbon.andes.authorization.service.andes.AndesAuthorizationPlugin.authorise(AndesAuthorizationPlugin.java:156)
    at org.wso2.andes.server.security.SecurityManager$12.allowed(SecurityManager.java:394)
    at org.wso2.andes.server.security.SecurityManager.checkAllPlugins(SecurityManager.java:238)
    at org.wso2.andes.server.security.SecurityManager.authorisePublish(SecurityManager.java:390)
    at org.wso2.andes.server.AMQChannel.setPublishFrame(AMQChannel.java:392)
    at org.wso2.andes.server.handler.BasicPublishMethodHandler.methodReceived(BasicPublishMethodHandler.java:95)
    at org.wso2.andes.server.handler.ServerMethodDispatcherImpl.dispatchBasicPublish(ServerMethodDispatcherImpl.java:245)
    at org.wso2.andes.framing.amqp_0_91.BasicPublishBodyImpl.execute(BasicPublishBodyImpl.java:156)
    at org.wso2.andes.server.state.AMQStateManager.methodReceived(AMQStateManager.java:169)
    at org.wso2.andes.server.protocol.AMQProtocolEngine.methodFrameReceived(AMQProtocolEngine.java:388)
    at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92)
    at org.wso2.andes.server.protocol.AMQProtocolEngine.frameReceived(AMQProtocolEngine.java:333)
    at org.wso2.andes.server.protocol.AMQProtocolEngine.dataBlockReceived(AMQProtocolEngine.java:282)
    at org.wso2.andes.server.protocol.AMQProtocolEngine$1.run(AMQProtocolEngine.java:251)
    at org.wso2.andes.pool.Job.processAll(Job.java:111)
    at org.wso2.andes.pool.Job.run(Job.java:158)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while accessing Java Security Manager Privilege Block when called by method getRoleListOfUser with 1 length of Objects and argTypes [class java.lang.String]
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
    at java.security.AccessController.doPrivileged(Native Method)
    at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:195)
    ... 22 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:198)
    ... 24 more
Caused by: javax.cache.CacheException: Cache $__local__$.USER_ROLES_CACHE already exists
    at org.wso2.carbon.caching.impl.CarbonCacheManager.createCacheBuilder(CarbonCacheManager.java:100)
    at org.wso2.carbon.user.core.common.UserRolesCache.getUserRolesCache(UserRolesCache.java:79)
    at org.wso2.carbon.user.core.common.UserRolesCache.getRolesListOfUser(UserRolesCache.java:138)
    at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUserFromCache(AbstractUserStoreManager.java:7876)
    at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUser(AbstractUserStoreManager.java:6349)
    ... 29 more
```

### Steps to Reproduce

- Deploy two APIM nodes in an active-active manner.
- Start both servers.

PS: We couldn't able to reproduce this issue locally since this is a highly unlikely scenario.

### Affected Component

APIM

### Version

3.2.0

**Comment by HeshanSudarshana** [comment]
Closing the issue since this is already fixed [1] in carbon 4.8.x branch.

[1] https://github.com/wso2/carbon-kernel/pull/2900
