### ISSUE TITLE
[APIM - 4.0.0] Errors when trying to delete a tenant through the TenantMgtAdminService

### ISSUE THREAD

**Issue by YasasRangika** [wso2/api-manager#1863]
### Description

The server encounters the below errors when trying to invoke any soap API endpoint in the `TenantMgtAdminService` .

### Steps to Reproduce

Follow the steps in [1] doc and invoke the Soap API via Soap UI.

### Affected Component

APIM

### Version

4.0.0

### Environment Details (with versions)

SOAP UI version: 5.7.0

### Relevant Log Output

```shell
[2023-05-23 13:06:03,492]  WARN - AuthenticationHandler Illegal access attempt at [2023-05-23 13:06:03,0492] from IP address 127.0.0.1 while trying to authenticate access to service TenantMgtAdminService
[2023-05-23 13:06:03,695]  INFO - CarbonAuthenticationUtil 'admin@carbon.super [-1234]' logged in at [2023-05-23 13:06:03,695+0530]
[2023-05-23 13:06:03,696] ERROR - Class System failure.null
java.lang.NullPointerException: null
	at org.wso2.carbon.server.admin.module.handler.AuthorizationHandler.doAuthorization(AuthorizationHandler.java:104) ~[org.wso2.carbon.server.admin_4.6.2.jar:?]
	at org.wso2.carbon.server.admin.module.handler.AuthorizationHandler.invoke(AuthorizationHandler.java:87) [org.wso2.carbon.server.admin_4.6.2.jar:?]
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340) [axis2_1.6.1.wso2v63_6.jar:?]
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313) [axis2_1.6.1.wso2v63_6.jar:?]
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261) [axis2_1.6.1.wso2v63_6.jar:?]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167) [axis2_1.6.1.wso2v63_6.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:484) [synapse-nhttp-transport_2.1.7.wso2v227_56.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:200) [synapse-nhttp-transport_2.1.7.wso2v227_56.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v63_6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
[2023-05-23 13:06:03,698] ERROR - AxisEngine System failure.
org.apache.axis2.AxisFault: System failure.
	at org.wso2.carbon.server.admin.module.handler.AuthorizationHandler.invoke(AuthorizationHandler.java:93) ~[org.wso2.carbon.server.admin_4.6.2.jar:?]
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340) ~[axis2_1.6.1.wso2v63_6.jar:?]
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313) ~[axis2_1.6.1.wso2v63_6.jar:?]
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261) ~[axis2_1.6.1.wso2v63_6.jar:?]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167) [axis2_1.6.1.wso2v63_6.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:484) [synapse-nhttp-transport_2.1.7.wso2v227_56.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:200) [synapse-nhttp-transport_2.1.7.wso2v227_56.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v63_6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
[2023-05-23 13:06:03,699] ERROR - ServerWorker Error processing POST request for : /services/TenantMgtAdminService.TenantMgtAdminServiceHttpsSoap11Endpoint
org.apache.axis2.AxisFault: System failure.
	at org.wso2.carbon.server.admin.module.handler.AuthorizationHandler.invoke(AuthorizationHandler.java:93) ~[org.wso2.carbon.server.admin_4.6.2.jar:?]
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340) ~[axis2_1.6.1.wso2v63_6.jar:?]
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313) ~[axis2_1.6.1.wso2v63_6.jar:?]
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261) ~[axis2_1.6.1.wso2v63_6.jar:?]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167) ~[axis2_1.6.1.wso2v63_6.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:484) [synapse-nhttp-transport_2.1.7.wso2v227_56.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:200) [synapse-nhttp-transport_2.1.7.wso2v227_56.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v63_6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]```
```

[1] https://apim.docs.wso2.com/en/latest/administer/multitenancy/managing-tenants/

**Comment by YasasRangika** [comment]
This is due to a value assignment issue for Endpoint URL. Endpoints are working correctly.
