### ISSUE TITLE
Using a encrypted password for the transport.rabbitmq.sender doesn't work in MI 4.1.0

### ISSUE THREAD

**Issue by isurul28** [wso2/api-manager#1882]
### Description

In Mi 4.1.0 pack when we set an encrypted password using parameter.password = "$secret{rabbitpass}"[1] for rabbitmq password in the depoyment.toml file we are getting the below error. When we change it to a plain text the error is not coming and the connection is working.

> [2023-05-29 15:31:43,996] ERROR {RabbitMQConnectionFactory} - [AMQPConnectionFactory] Error creating connection to RabbitMQ Broker. Reattempting to connect. com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
> at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:384)
> at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
> at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
> at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1110)
> at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1067)
> at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:889)
> at org.apache.axis2.transport.rabbitmq.RabbitMQUtils.createConnection(RabbitMQUtils.java:80)
> at org.apache.axis2.transport.rabbitmq.RabbitMQConnectionFactory.create(RabbitMQConnectionFactory.java:70)
> at org.apache.axis2.transport.rabbitmq.RabbitMQConnectionFactory.create(RabbitMQConnectionFactory.java:46)
> at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62)
> at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1051)
> at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:347)
> at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:270)
> at org.apache.axis2.transport.rabbitmq.RabbitMQConnectionPool.borrowObject(RabbitMQConnectionPool.java:51)
> at org.apache.axis2.transport.rabbitmq.ServiceTaskManager.start(ServiceTaskManager.java:60)
> at org.apache.axis2.transport.rabbitmq.RabbitMQListener.startEndpoint(RabbitMQListener.java:80)
> at org.apache.axis2.transport.rabbitmq.RabbitMQListener.startEndpoint(RabbitMQListener.java:33)
> at org.apache.axis2.transport.base.AbstractTransportListenerEx.startListeningForService(AbstractTransportListenerEx.java:154)
> at org.apache.axis2.transport.base.AbstractTransportListener.internalStartListeningForService(AbstractTransportListener.java:213)
> at org.apache.axis2.transport.base.AbstractTransportListener$2.serviceAdded(AbstractTransportListener.java:126)
> at org.apache.axis2.transport.base.tracker.AxisServiceTracker.serviceAdded(AxisServiceTracker.java:212)
> at org.apache.axis2.transport.base.tracker.AxisServiceTracker.start(AxisServiceTracker.java:188)
> at org.apache.axis2.transport.base.AbstractTransportListener.start(AbstractTransportListener.java:178)
> at org.apache.axis2.transport.base.AbstractTransportListenerEx.start(AbstractTransportListenerEx.java:83)
> at org.apache.axis2.engine.ListenerManager.start(ListenerManager.java:168)
> at org.apache.axis2.engine.ListenerManager.startSystem(ListenerManager.java:186)
> at org.wso2.micro.integrator.initializer.StartupFinalizer.completeInitialization(StartupFinalizer.java:79)
> at org.wso2.micro.integrator.initializer.StartupFinalizer.finalizeStartup(StartupFinalizer.java:61)
> at org.wso2.micro.integrator.initializer.deployment.AppDeployerServiceComponent.activate(AppDeployerServiceComponent.java:83)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
> at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
> at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
> at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
> at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
> at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
> at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
> at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
> at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
> at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
> at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
> at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
> at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
> at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
> at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
> at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
> at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
> at org.wso2.micro.integrator.initializer.ServiceBusInitializer.activate(ServiceBusInitializer.java:192)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
> at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
> at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
> at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
> at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
> at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
> at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
> at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
> at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
> at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
> at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
> at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
> at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
> at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
> at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
> at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
> at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
> at org.wso2.micro.integrator.ntask.core.internal.TasksDSComponent.activate(TasksDSComponent.java:147)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
> at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
> at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
> at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
> at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
> at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
> at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
> at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
> at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
> at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
> at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70

The same issue has been fixed in MI 4.0.0 version [1]. Need to front-port the fix to MI 4.1.0 version

[1].https://github.com/wso2/api-manager/issues/1114

### Steps to Reproduce

1. Create a consumer Rabbitmq proxy
2. Enable RabbitMQ listener and put the RabbitMQ config to deployment.toml . We need to add the password as parameter.password = "$secret{rabbitpass}" and we need to give the password value under the secret section
3. Enable secure-vault 
4. Now start the MI server you will get the above-mentioned error

### Affected Component

MI

### Version

4.1.0

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
