### ISSUE TITLE
Subscription workflow fails for tenants when Solace is enabled

### ISSUE THREAD

**Issue by tgtshanika** [wso2/api-manager#1888]
### Description

When the solace provider is enabled, the subscription workflow approvals fail with the following NPE. 

 

### Steps to Reproduce

1. Navigate to repository/conf/deployment.toml
2. Enable solace provider
```
[[apim.gateway.environment]]
name = "devportalEnv"
display_name = "Developer portal Test Environment"
type = "hybrid"
display_in_api_console = false
description = "development api gateway broker"
provider = "solace"
service_url = "http://localhost:9960"
username = "testUser"
ws_endpoint = "ws://localhost:9960/"
wss_endpoint = "wss://localhost:9960/"
http_endpoint = "http://localhost:9960"
https_endpoint = "https://localhost:9960/"
password = "testPassword"
show_as_token_endpoint_url = false
```
3. Start the server
4. Enable subscription creation workflow for tenants
5. Subscribe to an API 
6. Navigate to admin portal and approve the pending subscription creation task

### Affected Component

APIM

### Version

4.1.0

### Relevant Log Output

```shell
ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.impl.APIManagerFactory.getAPIProvider_aroundBody8(APIManagerFactory.java:71) ~[org.wso2.carbon.apimgt.impl_9.20.74.146.jar:?]
	at org.wso2.carbon.apimgt.impl.APIManagerFactory.getAPIProvider(APIManagerFactory.java:68) ~[org.wso2.carbon.apimgt.impl_9.20.74.146.jar:?]
	at org.wso2.carbon.apimgt.solace.notifiers.SolaceSubscriptionsNotifier.createSubscription(SolaceSubscriptionsNotifier.java:93) ~[org.wso2.carbon.apimgt.solace_9.20.74.2.jar:?]
	at org.wso2.carbon.apimgt.solace.notifiers.SolaceSubscriptionsNotifier.process(SolaceSubscriptionsNotifier.java:73) ~[org.wso2.carbon.apimgt.solace_9.20.74.2.jar:?]
	at org.wso2.carbon.apimgt.solace.notifiers.SolaceSubscriptionsNotifier.publishEvent(SolaceSubscriptionsNotifier.java:56) ~[org.wso2.carbon.apimgt.solace_9.20.74.2.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.lambda$0_aroundBody914(APIUtil.java:695) ~[org.wso2.carbon.apimgt.impl_9.20.74.146.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.lambda$0(APIUtil.java:695) ~[org.wso2.carbon.apimgt.impl_9.20.74.146.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.sendNotification_aroundBody8(APIUtil.java:693) ~[org.wso2.carbon.apimgt.impl_9.20.74.146.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.sendNotification(APIUtil.java:689) ~[org.wso2.carbon.apimgt.impl_9.20.74.146.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.WorkflowUtils.sendNotificationAfterWFComplete_aroundBody0(WorkflowUtils.java:105) ~[org.wso2.carbon.apimgt.impl_9.20.74.146.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.WorkflowUtils.sendNotificationAfterWFComplete(WorkflowUtils.java:57) ~[org.wso2.carbon.apimgt.impl_9.20.74.146.jar:?]
	at org.wso2.carbon.apimgt.rest.api.admin.v1.impl.WorkflowsApiServiceImpl.workflowsUpdateWorkflowStatusPost(WorkflowsApiServiceImpl.java:198) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.admin.v1.WorkflowsApi.workflowsUpdateWorkflowStatusPost(WorkflowsApi.java:94) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[?:?]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[?:?]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[?:?]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[?:?]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) ~[?:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:696) ~[tomcat-servlet-api_9.0.71.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[?:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) ~[org.wso2.carbon.identity.context.rewrite.valve_1.4.52.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) ~[org.wso2.carbon.identity.authz.valve_1.4.52.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:109) ~[org.wso2.carbon.identity.auth.valve_1.4.52.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:58) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat_9.0.71.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by YasasRangika** [comment]
As per the comment from the linked internal issue, this issue does not apply to the master.
