### ISSUE TITLE
Error when invoking mutual SSL protected Api with certificate in the request header ("client_certificate_encode = false" scenario)

### ISSUE THREAD

**Issue by AshenShalitha** [wso2/api-manager#1930]
### Description

Hi team,

When invoking an MLTS-enabled API with the "client_certificate_encode" enabled as follows and passing the URL-encoded certificate we can get a successful response.

```
 [apimgt.mutual_ssl]
 certificate_header = "X-WSO2-CLIENT-CERTIFICATE"
 # This property needs to be true if the MutualSSL connection is established between the load balancer and the Gateway.
 enable_client_validation = false
 #This property needs to be true if the certificate should be decoded when it is passed from the load balancer to the Gateway.
 client_certificate_encode = true
```

However, if we set the client_certificate_encode to false and invoke the API with certificate (Without encoding) we'll get an error response and error in the log.

### Steps to Reproduce

- Add the following configurations to the deployment.toml (Note that client_certificate_encode = false )
```
 [apimgt.mutual_ssl]
 certificate_header = "X-WSO2-CLIENT-CERTIFICATE"
 enable_client_validation = false
 client_certificate_encode = false
```
- Start the server and publish a new API with mutual ssl authentication enabled.
- Add a public certificate to the API and call that API by passing the certificate in the request header.

### Affected Component

APIM

### Version

4.1.0

### Relevant Log Output

```shell
[2023-06-09 17:05:32,194] ERROR - Utils Error while validating into Certificate Existence
org.wso2.carbon.apimgt.api.APIManagementException: Error while converting into X509Certificate
	at org.wso2.carbon.apimgt.gateway.handlers.Utils.getClientCertificateFromHeader_aroundBody34(Utils.java:488) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.Utils.getClientCertificateFromHeader(Utils.java:461) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.Utils.getClientCertificate_aroundBody32(Utils.java:446) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.Utils.getClientCertificate(Utils.java:426) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.authenticator.MutualSSLAuthenticator.authenticate_aroundBody4(MutualSSLAuthenticator.java:103) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.authenticator.MutualSSLAuthenticator.authenticate(MutualSSLAuthenticator.java:96) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate_aroundBody56(APIAuthenticationHandler.java:523) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate(APIAuthenticationHandler.java:517) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody46(APIAuthenticationHandler.java:403) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:353) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.apache.synapse.api.API.process(API.java:403) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:76) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v80_2.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:394) ~[synapse-nhttp-transport_2.1.7.wso2v271_25.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:208) ~[synapse-nhttp-transport_2.1.7.wso2v271_25.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v80_2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_372]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_372]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
Caused by: javax.security.cert.CertificateException: InvocationTargetException: javax.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at javax.security.cert.X509Certificate.getInst(X509Certificate.java:241) ~[?:1.8.0_372]
	at javax.security.cert.X509Certificate.getInstance(X509Certificate.java:175) ~[?:1.8.0_372]
	at org.wso2.carbon.apimgt.gateway.handlers.Utils.getClientCertificateFromHeader_aroundBody34(Utils.java:485) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	... 25 more
[2023-06-09 17:05:32,196] ERROR - APIAuthenticationHandler API authentication failure due to Unclassified Authentication Failure
org.wso2.carbon.apimgt.gateway.handlers.security.APISecurityException: Error while validating into Certificate Existence
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate_aroundBody56(APIAuthenticationHandler.java:537) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate(APIAuthenticationHandler.java:517) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody46(APIAuthenticationHandler.java:403) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:353) ~[org.wso2.carbon.apimgt.gateway_9.20.74.163.jar:?]
	at org.apache.synapse.api.API.process(API.java:403) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:76) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) ~[synapse-core_2.1.7.wso2v271_25.jar:2.1.7-wso2v271.25]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v80_2.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:394) ~[synapse-nhttp-transport_2.1.7.wso2v271_25.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:208) ~[synapse-nhttp-transport_2.1.7.wso2v271_25.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v80_2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_372]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_372]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
[2023-06-09 17:05:42,414]  INFO - CarbonEventManagementService Starting polling event receivers
```

### Suggested Labels

apim

**Comment by YasasRangika** [comment]
Merge-pending master fix PR: https://github.com/wso2/carbon-apimgt/pull/12087
