### ISSUE TITLE
Cannot self signup a user in a normal tenant

### ISSUE THREAD

**Issue by binodmx** [wso2/api-manager#1942]
### Description

Getting an error while self signing up a user for a normal tenant.

```
Caused by: org.wso2.carbon.identity.event.IdentityEventException: Error while adding custom roles to the user
        at org.wso2.carbon.apimgt.impl.workflow.UserSignUpSimpleWorkflowExecutor.complete_aroundBody4(UserSignUpSimpleWorkflowExecutor.java:90) ~[org.wso2.carbon.apimgt.impl_9.0.174.336.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.UserSignUpSimpleWorkflowExecutor.complete(UserSignUpSimpleWorkflowExecutor.java:56) ~[org.wso2.carbon.apimgt.impl_9.0.174.336.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.UserSignUpSimpleWorkflowExecutor.execute_aroundBody2(UserSignUpSimpleWorkflowExecutor.java:51) ~[org.wso2.carbon.apimgt.impl_9.0.174.336.jar:?]
	at org.wso2.carbon.apimgt.impl.workflow.UserSignUpSimpleWorkflowExecutor.execute(UserSignUpSimpleWorkflowExecutor.java:46) ~[org.wso2.carbon.apimgt.impl_9.0.174.336.jar:?]
	at org.wso2.carbon.apimgt.impl.handlers.UserPostSelfRegistrationHandler.executeUserRegistrationWorkflow_aroundBody4(UserPostSelfRegistrationHandler.java:124) ~[org.wso2.carbon.apimgt.impl_9.0.174.336.jar:?]
	at org.wso2.carbon.apimgt.impl.handlers.UserPostSelfRegistrationHandler.executeUserRegistrationWorkflow(UserPostSelfRegistrationHandler.java:87) ~[org.wso2.carbon.apimgt.impl_9.0.174.336.jar:?]
	at org.wso2.carbon.apimgt.impl.handlers.UserPostSelfRegistrationHandler.handleEvent_aroundBody2(UserPostSelfRegistrationHandler.java:73) ~[org.wso2.carbon.apimgt.impl_9.0.174.336.jar:?]
	at org.wso2.carbon.apimgt.impl.handlers.UserPostSelfRegistrationHandler.handleEvent(UserPostSelfRegistrationHandler.java:64) ~[org.wso2.carbon.apimgt.impl_9.0.174.336.jar:?]
	at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56) ~[org.wso2.carbon.identity.event_5.18.187.82.jar:?]
	at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1695) ~[org.wso2.carbon.identity.governance_1.4.72.57.jar:?]
	at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1671) ~[org.wso2.carbon.identity.governance_1.4.72.57.jar:?]
	at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1659) ~[org.wso2.carbon.identity.governance_1.4.72.57.jar:?]
	at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.doPostAddUser(IdentityMgtEventListener.java:229) ~[org.wso2.carbon.identity.governance_1.4.72.57.jar:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4998) ~[org.wso2.carbon.user.core_4.6.2.311.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:206) ~[org.wso2.carbon.user.core_4.6.2.311.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:203) ~[org.wso2.carbon.user.core_4.6.2.311.jar:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4691) ~[org.wso2.carbon.user.core_4.6.2.311.jar:?]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4677) ~[org.wso2.carbon.user.core_4.6.2.311.jar:?]
	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.registerUser(UserSelfRegistrationManager.java:218) ~[org.wso2.carbon.identity.recovery_1.4.72.14.jar:?]
	... 62 more

```

### Steps to Reproduce

1. Create a normal tenant (wso2.com)
2. Go to Devportal.
3. Go to sign-in page and click on `Create Account`
4. Enter username `testuser@wso2.com` and click on `Proceed to Self Register`
5. Fill the form and click on `Register`

### Affected Component

APIM

### Version

4.0.0

**Comment by Avishka-Shamendra** [comment]
Hi all,

The issue seems to be resolved when self-signup configurations are enabled specifically for tenants. While self-signup configuration is typically enabled by default for the super tenant, it needs to be explicitly enabled for individual tenants. [Enabling self-signup documentation](https://apim.docs.wso2.com/en/4.0.0/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup)

Thank you
Avishka
