### ISSUE TITLE
Deleting an application with a name containing spaces using APICTL

### ISSUE THREAD

**Issue by cbabey** [wso2/api-manager#1978]
### Description

Hi Team,

When attempting to delete an application with a name containing spaces (e.g., "test app") using the apictl tool, the APIM server throws a below NullPointerException. 

`./apictl delete app -n 'test app' -e dev -k --verbose`

```
[2023-07-05 08:28:23,554] ERROR - CompositeValve Could not handle the request, could be due to the maxHttpHeaderSize limitation.
java.lang.NullPointerException: null
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:46) [org.wso2.carbon.tomcat.ext_4.6.0.114.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.0.114.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [tomcat_9.0.71.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:59) [org.wso2.carbon.tomcat.ext_4.6.0.114.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:124) [org.wso2.carbon.tomcat.ext_4.6.0.114.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) [tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) [tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat_9.0.71.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.71.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372-internal]
```

**Apitcl verbose output**

```
./apictl delete app -n 'test app' -e dev -k --verbose
Executed ImportExportCLI (apictl) on Wed, 05 Jul 2023 08:46:17 +0530
[INFO]: Insecure: true
[INFO]: app called
[INFO]: connecting to https://localhost:9443/oauth2/token
Error: %!s(<nil>)
Body:
apictl: Error while getting App Id for deletion  Reason: Request didn't respond 200 OK for searching existing applications. Status: 400
Exit status 1
```

Upon further analysis, it is identified that an NP (NullPointerException) exception was encountered while attempting to invoke the REST API endpoint `(/api/am/admin/v1/applications?user=admin&name=<APP_NAME>)` to search for the application in order retrieve the corresponding application ID for the given the API Name.
 In the servlet access logs

As per the HTTP access logs in the servlet transport, it is identified that the endpoint receives the request with a corrupted query parameter and it is not URL encoded even if it contains the special characters. 

he HTTP access logs in the servlet transport, it has been observed that the endpoint is receiving a request with a corrupted query parameter. The query parameter appears to be not URL encoded, even though it contains special characters.

`127.0.0.1 - - [05/Jul/2023:08:46:22 +0530] GET /api/am/admin/v1/applications?user=admin&name=test null 400 - - - 0.009
`
we retested the flow by providing a URL-encoded value for the application name using the apictl command. Unfortunately, the test resulted in an error message: "Cannot find the application: test%20app."

```
./apictl delete app -n 'test%20app' -e dev -k --verbose
Executed ImportExportCLI (apictl) on Wed, 05 Jul 2023 08:53:36 +0530
[INFO]: Insecure: true
[INFO]: app called
[INFO]: connecting to https://localhost:9443/oauth2/token
apictl: Error while getting App Id for deletion  Reason: Cannot find the application: test%20app for owner: admin
Exit status 1
```

As per the APICTL implementation for the delete application[1][2], it appears that the application name is directly appended to the URL without URL encoding. 

So, we update the implementation by encoding the application name before appending it to the URL, with this change, we were able to delete the application without getting any issues. 

```
applicationEndpoint := utils.GetAdminApplicationListEndpointOfEnv(environment, utils.MainConfigFilePath) +
		"?user=" + appOwner + "&name=" + url.QueryEscape(appName)
```

```
 
➜  apictl ./apictl delete app -n 'test test' -e dev -k --verbose
Executed ImportExportCLI (apictl) on Wed, 05 Jul 2023 09:04:04 +0530
[INFO]: Insecure: true
[INFO]: app called
[INFO]: connecting to https://localhost:9443/oauth2/token
[INFO]: DeleteApplication: URL: https://localhost:9443/api/am/admin/v1/applications/98217c81-eb8c-40ce-9012-8f7c6e1619b0
Application deleted successfully!. Status: 200
```

[1]https://github.com/wso2/product-apim-tooling/blob/3.2.x/import-export-cli/impl/deleteApp.go#L39
[2]https://github.com/wso2/product-apim-tooling/blob/3.2.x/import-export-cli/impl/deleteApp.go#L75

### Steps to Reproduce

1. Create an application with a name containing spaces (e.g., "test app") in the APIM-3.2.0
2. Try to delete the created application using the latest APICTL tool (3.2.6) 

`./apictl delete app -n 'test app' -e dev -k `

### Affected Component

APICTL

### Version

3.2.6

**Comment by npamudika** [comment]
Added changes to the master branch via https://github.com/wso2/product-apim-tooling/pull/988

**Comment by npamudika** [comment]
The fixes are there in the APICTL 3.2.7 and 4.2.1 patch releases.
