### ISSUE TITLE
[Migration][APIM260 - APIM410] NullPointerException when Storing revision artifacts into gateway artifacts and external server

### ISSUE THREAD

**Issue by jithma95** [wso2/api-manager#1979]
### Description

During the apim component migration,  the below error when the migration client try to store the revision artifacts APIM migration from 2.6.0 to the 4.1.0 version.

```
TID: [-1234] [] [2023-06-29 09:54:47,530] ERROR {Events.Framework} - FrameworkEvent ERROR java.lang.NullPointerException
	at org.wso2.carbon.apimgt.impl.definitions.OAS3Parser.getOASDefinitionForPublisher_aroundBody46(OAS3Parser.java:996)
	at org.wso2.carbon.apimgt.impl.definitions.OAS3Parser.getOASDefinitionForPublisher(OAS3Parser.java:866)
	at org.wso2.carbon.apimgt.rest.api.common.RestApiCommonUtil.retrieveSwaggerDefinition(RestApiCommonUtil.java:444)
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.addAPIMetaInformationToArchive(ExportUtils.java:915)
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.exportApi(ExportUtils.java:234)
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.ImportExportAPIServiceImpl.exportAPI(ImportExportAPIServiceImpl.java:124)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.addAPIRevision(V400RegistryResourceMigrator.java:649)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.apiRevisionRelatedMigration(V400RegistryResourceMigrator.java:473)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.migrate(V400RegistryResourceMigrator.java:140)
	at org.wso2.carbon.apimgt.migration.migrator.client.V400Migration.migrate(V400Migration.java:64)
	at org.wso2.carbon.apimgt.migration.APIMMigrationClient.executeMigration(APIMMigrationClient.java:87)
	at org.wso2.carbon.apimgt.migration.APIMMigrationClient.completedServerStartup(APIMMigrationClient.java:64)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyAfter(CarbonCoreServiceComponent.java:264)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:218)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:323)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
```

### Steps to Reproduce

**Steps to Reproduce**

- create a mssql-2019 docker container
- Restore the DB backup.
- replace the key store after changing the db details.
- Run the APIM component migration with org.wso2.carbon.apimgt.migrate.client-4.1.0.51.jar

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
N/A in master: As mentioned in the linked internal ticket master branch does not need fixes on this issue.
