### ISSUE TITLE
PolicyUtil Error in retrieving throttle policies

### ISSUE THREAD

**Issue by Rashmika998** [wso2/api-manager#198]
### Description

[2022-06-16 13:26:35,690] ERROR - PolicyUtil Error in retrieving throttle policies
org.wso2.carbon.apimgt.throttle.policy.deployer.exception.ThrottlePolicyDeployerException: {"code":901300,"message":"Bad Request","description":"Provided tenant domain '*' is invalid","moreInfo":"","error":[]}Event-Hub status code is : 400
	at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.getPolicies(PolicyRetriever.java:203) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.22.4.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.getAllSubscriptionPolicies(PolicyRetriever.java:87) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.22.4.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.PolicyUtil.deployAllPolicies(PolicyUtil.java:159) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.22.4.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.ThrottlePolicyStartupListener.run(ThrottlePolicyStartupListener.java:76) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.22.4.SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.1.0

**Comment by chamilaadhi** [comment]
There are two more error logs as well. 
<img width="1006" alt="Screenshot 2022-10-28 at 10 24 40 AM" src="https://user-images.githubusercontent.com/4861150/198506469-8bc97eae-3e5b-44e7-a84f-748d27eba10b.png">
<img width="804" alt="Screenshot 2022-10-28 at 10 24 45 AM" src="https://user-images.githubusercontent.com/4861150/198506472-56034391-422a-4ef5-83f0-c92036074119.png">

**Comment by tharikaGitHub** [comment]
This issue will be fixed as a consolidation of a different fix [1].

[1] https://github.com/wso2/carbon-apimgt/pull/11293

**Comment by rmsamitha** [comment]
Closing as this as this is fixed via https://github.com/wso2/carbon-apimgt/pull/11651 as per discussion with @tharikaGitHub
