### ISSUE TITLE
Mapping parameter exceptions in latest U2 updates of Streaming Integrator

### ISSUE THREAD

**Issue by ug205** [wso2/api-manager#1991]
### Description

Mapping parameter exceptions observed HTTP sinks when defining the payload

### Steps to Reproduce

Deploy a siddhi application with a payload mapping similar to below at HTTP sink at level 47 of SI 1.1.0

@payload( """{"ABC" : {"sampleID" : "{{sampleID}}" , "name" : "{{name}}"} , "Invocation" : {"XYZ" : {"receiver" : "{{receiver}}", "sender" : "{{sender}}", "title" : "{{title}}", "values" : "{{values}}", "sample" : "{{sample}}" ,"link" : "", "details" : {"field1" : "{{field1}}" , "field2": "{{field2}}" , "field3" : "{{field3}}" ,"field4" : "{{field4}}", "field5" : "{{field5}}", "field6" : "{{field6}}", "field7" : "", "field8" : "", "field9" : "", "field10" : "", "field11" : "", "field12" : "", "field13" : "", "field14" : "", "field15" : "", "field16" : "", "field17" : "", "field18" : "", "field19" : "", "field20" : ""} } } }""")))

Observe Mapping parameter exceptions when trying to deploy.
```

 Mapping parameter should be surrounded only with '{{' and '}}'.
	at io.siddhi.core.util.transport.TemplateBuilder.assignTemplateArrayAttributePositions(TemplateBuilder.java:150)
	at io.siddhi.core.util.transport.TemplateBuilder.parse(TemplateBuilder.java:102)
	at io.siddhi.core.util.transport.TemplateBuilder.<init>(TemplateBuilder.java:50)
	at io.siddhi.core.stream.output.sink.SinkMapper.buildMapperTemplate(SinkMapper.java:83)
	at io.siddhi.core.stream.output.sink.SinkMapper.init(SinkMapper.java:69)
	at io.siddhi.core.stream.output.sink.Sink.init(Sink.java:116)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSink(DefinitionParserHelper.java:549)
	at io.siddhi.core.util.SiddhiAppRuntimeBuilder.defineStream(SiddhiAppRuntimeBuilder.java:119)
	at io.siddhi.core.util.parser.SiddhiAppParser.defineStreamDefinitions(SiddhiAppParser.java:375)
	at io.siddhi.core.util.parser.SiddhiAppParser.parse(SiddhiAppParser.java:231)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:87)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:97)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:80)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:97)
```

### Affected Component

SI

### Version

1.1.0

**Comment by YasasRangika** [comment]
Public fix: https://github.com/siddhi-io/siddhi/pull/1820 has already been merged into the master branch.
