### ISSUE TITLE
High CPU in HTTPS-Listener I/O dispatcher threads

### ISSUE THREAD

**Issue by shefandarren** [wso2/api-manager#200]
### Description

HTTPS-Listener I/O dispatcher threads are consuming CPU. When the 'org.apache.http.impl.nio.reactor.IOSessionImpl' objects related to those threads were analyzed, a GET request with a large json payload was observed. The GW has received an invalid http response for this request. In a correct http response, the initial response line should be like HTTP/1.1 200 OK. But in this particular response, the initial line is 0 .. 1.1 200.

### Steps to Reproduce

Request:
[errorres13.txt](https://github.com/wso2/api-manager/files/8917117/errorres13.txt)

Response:
[errorres13.txt](https://github.com/wso2/api-manager/files/8917121/errorres13.txt)

Invoke an API with the request shared above and make a backend respond with the response shared above.

### Affected Component

APIM

### Version

4.0.0

### Environment Details (with versions)

JDK version: oracle jdk 1.8_251

### Relevant Log Output

```shell
[2022-06-13 20:32:24,520]  WARN - TargetHandler ERROR_CODE = 101506, STATE_DESCRIPTION = Exception occurred after Server written the request headers and the request body to the backend, INTERNAL_STATE = REQUEST_DONE, DIRECTION = REQUEST, CAUSE_OF_ERROR = HTTP Protocol violation : Not a valid protocol version: [0x1e][0x1f][0x20][0x21][0x22][0x23], TARGET_HOST = 127.0.0.1, TARGET_PORT = 7000, TARGET_CONTEXT = http://localhost:7000, HTTP_METHOD = GET, TRIGGER_TYPE = api, TRIGGER_NAME = test:v1.0.1, REMOTE_ADDRESS = localhost/127.0.0.1:7000, CONNECTION = http-outgoing-2
[2022-06-13 20:32:24,520] ERROR - TargetHandler HTTP protocol violation : Not a valid protocol version: [0x1e][0x1f][0x20][0x21][0x22][0x23] For : 127.0.0.1:7000
org.apache.http.ProtocolException: Not a valid protocol version: [0x1e][0x1f][0x20][0x21][0x22][0x23]
    at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:209) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
    at org.apache.synapse.transport.http.conn.LoggingNHttpClientConnection$LoggingNHttpMessageParser.parse(LoggingNHttpClientConnection.java:408) ~[synapse-nhttp-transport_2.1.7.wso2v227_18.jar:?]
    at org.apache.synapse.transport.http.conn.LoggingNHttpClientConnection$LoggingNHttpMessageParser.parse(LoggingNHttpClientConnection.java:382) ~[synapse-nhttp-transport_2.1.7.wso2v227_18.jar:?]
    at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:245) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
    at org.apache.synapse.transport.http.conn.LoggingNHttpClientConnection.consumeInput(LoggingNHttpClientConnection.java:115) ~[synapse-nhttp-transport_2.1.7.wso2v227_18.jar:?]
    at org.apache.synapse.transport.passthru.ClientIODispatch.onInputReady(ClientIODispatch.java:83) ~[synapse-nhttp-transport_2.1.7.wso2v227_18.jar:?]
    at org.apache.synapse.transport.passthru.ClientIODispatch.onInputReady(ClientIODispatch.java:41) ~[synapse-nhttp-transport_2.1.7.wso2v227_18.jar:?]
    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: org.apache.http.ParseException: Not a valid protocol version:
    at org.apache.http.message.BasicLineParser.parseProtocolVersion(BasicLineParser.java:134) ~[httpcore_4.4.14.wso2v1.jar:?]
    at org.apache.http.message.BasicLineParser.parseStatusLine(BasicLineParser.java:366) ~[httpcore_4.4.14.wso2v1.jar:?]
    at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:112) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
    at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:50) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
    at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
    at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:207) ~[httpcore-nio_4.4.14.wso2v1.jar:?]
```

**Comment by shefandarren** [comment]
This is duplicated in: https://github.com/wso2/api-manager/issues/199

**Comment by madushadhanushka** [comment]
Duplicate https://github.com/wso2/api-manager/issues/199
