### ISSUE TITLE
Can't redeploy the particular API after failing the revision deployment with the endpoint exists by the key/name error.

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/api-manager#2010]
### Description

The API revision deployment fails with the "`No endpoint exists by the key/name`" error message when trying to deploy the revision when there is high traffic for the particular API. However, it Can't redeploy the particular API even in the no traffic due to `No endpoint exists by the key/name` issue. It requires restarting the server to recover.

### Steps to Reproduce

- Deployed a sample API.
- Conducted a load test on the deployed API with Jmeter (No of threads: 600, Loop Count: infinite)
- Tried to update the sample API (by deploying a new revision) during the load test and was able to observe that API invocations failed with 404 HTTP status after that.
- The API revision deployment failed with the `No endpoint exists by the key/name` error message.
- Stopped the load test and tried to redeploy the API.
- The API revision deployment failed with the same error message.

### Affected Component

APIM

### Version

4.0.0

### Relevant Log Output

```shell
TID: [] [] [2023-06-07 16:50:46,511] ERROR {org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy} - Error deleting endpoint from gateway org.apache.synapse.SynapseException: No endpoint exists by the key/name : sample1--vv1_APIproductionEndpoint
    at org.apache.synapse.config.SynapseConfiguration.handleException(SynapseConfiguration.java:1800)
    at org.apache.synapse.config.SynapseConfiguration.removeEndpoint(SynapseConfiguration.java:1218)
    at org.wso2.carbon.endpoint.service.EndpointAdmin.deleteEndpoint(EndpointAdmin.java:292)
    at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint_aroundBody2(EndpointAdminServiceProxy.java:82)
    at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint(EndpointAdminServiceProxy.java:1)
    at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI_aroundBody98(APIGatewayAdmin.java:827)
    at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI(APIGatewayAdmin.java:1)
    at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI_aroundBody100(APIGatewayAdmin.java:895)
    at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI(APIGatewayAdmin.java:1)
    at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.unDeployAPI_aroundBody8(InMemoryAPIDeployer.java:302)
    at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.unDeployAPI(InMemoryAPIDeployer.java:1)
    at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:96)
    at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:1)
    at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run_aroundBody0(GatewayJMSMessageListener.java:177)
    at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run(GatewayJMSMessageListener.java:1)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)

TID: [] [] [2023-06-07 16:50:46,511] ERROR {org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer} - Error deploying 2fce91db-21d5-4ba8-a8c5-f31c9c543340 in Gateway org.apache.axis2.AxisFault: Error while deleting the endpoint fileNo endpoint exists by the key/name : sample1--vv1_APIproductionEndpoint
    at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint_aroundBody2(EndpointAdminServiceProxy.java:88)
    at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint(EndpointAdminServiceProxy.java:1)
    at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI_aroundBody98(APIGatewayAdmin.java:827)
    at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI(APIGatewayAdmin.java:1)
    at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI_aroundBody100(APIGatewayAdmin.java:895)
    at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.unDeployAPI(APIGatewayAdmin.java:1)
    at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.unDeployAPI_aroundBody8(InMemoryAPIDeployer.java:302)
    at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.unDeployAPI(InMemoryAPIDeployer.java:1)
    at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:96)
    at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:1)
    at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run_aroundBody0(GatewayJMSMessageListener.java:177)
    at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run(GatewayJMSMessageListener.java:1)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.synapse.SynapseException: No endpoint exists by the key/name : sample1--vv1_APIproductionEndpoint
    at org.apache.synapse.config.SynapseConfiguration.handleException(SynapseConfiguration.java:1800)
    at org.apache.synapse.config.SynapseConfiguration.removeEndpoint(SynapseConfiguration.java:1218)
    at org.wso2.carbon.endpoint.service.EndpointAdmin.deleteEndpoint(EndpointAdmin.java:292)
    at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint_aroundBody2(EndpointAdminServiceProxy.java:82)
    ... 16 more
```

**Comment by YasasRangika** [comment]
Need to merge master fix PR: https://github.com/wso2/carbon-apimgt/pull/12137
