### ISSUE TITLE
 SFTP connection failure in EI 6.5.0 after upgrading to pack update level 87+

### ISSUE THREAD

**Issue by veneerac** [wso2/api-manager#2013]
### Description

After updating EI 6.5.0 to update level 88 or a later version, an error occurs.

### Steps to Reproduce

To reproduce the issue, please follow these steps:

1. Deploy the proxy service using the file connector to the SFTP.

```xml
<proxy name="TEST_Proxy" startOnLoad="true" transports="http https" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <inSequence>
            <fileconnector.isFileExist>
                <source>sftp://[username]:[password]@[FTPserver]/home/test.csv?transport.vfs.AvoidPermissionCheck=true</source>
                <setTimeout>180000</setTimeout>
                <setPassiveMode>true</setPassiveMode>
                <setSoTimeout>180000</setSoTimeout>
                <setStrictHostKeyChecking>no</setStrictHostKeyChecking>
                <setUserDirIsRoot>false</setUserDirIsRoot>
            </fileconnector.isFileExist>
    
            <log>
                <property expression="get-property('testValue')" name="testValue == "/>
            </log>
    
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </target>
</proxy>
```

2. Invoke the proxy service.

### Affected Component

EI

### Version

EI 6.5.0

### Environment Details (with versions)

Level 88

### Relevant Log Output

```shell
PassThroughMessageProcessor-1] ERROR {org.wso2.carbon.connector.FileExist} -  Error while processing a file. org.apache.commons.vfs2.FileSystemException: Could not connect to SFTP server at "{org.apache.commons.vfs2.provider.ftp.FtpFileSystem.org.apache.commons.vfs2.provider.ftp.FtpFileSystemConfigBuilder.PASSIVE=true, org.apache.commons.vfs2.provider.ftp.FtpFileSystem.org.apache.commons.vfs2.provider.ftp.FtpFileSystemConfigBuilder.SO_TIMEOUT=180000, org.apache.commons.vfs2.provider.sftp.SftpFileSystem.avoidpermissioncheck=true, org.apache.commons.vfs2.provider.sftp.SftpFileSystem.org.apache.commons.vfs2.provider.sftp.SftpFileSystemConfigBuilder.STRICT_HOST_KEY_CHECKING=no, org.apache.commons.vfs2.provider.sftp.SftpFileSystem.org.apache.commons.vfs2.provider.sftp.SftpFileSystemConfigBuilder.TIMEOUT=180000, org.apache.commons.vfs2.provider.sftp.SftpFileSystem.org.apache.commons.vfs2.provider.sftp.SftpFileSystemConfigBuilder.USER_DIR_IS_ROOT=false}". at org.apache.commons.vfs2.provider.sftp.SftpClient.ensureSession(SftpClient.java:106) at org.apache.commons.vfs2.provider.sftp.SftpClient.<init>(SftpClient.java:42) at org.apache.commons.vfs2.provider.sftp.SftpFileSystem.<init>(SftpFileSystem.java:60) at org.apache.commons.vfs2.provider.sftp.SftpFileProvider.doCreateFileSystem(SftpFileProvider.java:71) at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.getFileSystem(AbstractOriginatingFileProvider.java:158) at
```

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
