### ISSUE TITLE
Unclear error message when jwks is not available

### ISSUE THREAD

**Issue by ramiroll** [wso2/api-manager#2016]
### Problem

If you have a third part keymanager configure with use "Self validate JWT" and that's jwks endpoint is not accessible and the jwks is not already cached. The logged error in the logging are not explaining what is happening.

Sample of the error:
[2023-07-14 15:51:37,510] ERROR [97c9ca7e-df78-4184-840e-d67c76cac1e2] {org.wso2.carbon.apimgt.impl.jwt.JWTValidatorImpl} - Error while parsing JWT java.text.ParseException: Unexpected exception: null| at com.nimbusds.jose.util.JSONObjectUtils.parse(JSONObjectUtils.java:77)| at com.nimbusds.jose.jwk.JWKSet.parse(JWKSet.java:309)| at org.wso2.carbon.apimgt.impl.jwt.JWTValidatorImpl.retrieveJWKSet_aroundBody18(JWTValidatorImpl.java:184)| at org.wso2.carbon.apimgt.impl.jwt.JWTValidatorImpl.retrieveJWKSet(JWTValidatorImpl.java:181)| at org.wso2.carbon.apimgt.impl.jwt.JWTValidatorImpl.validateSignature_aroundBody4(JWTValidatorImpl.java:108)| at org.wso2.carbon.apimgt.impl.jwt.JWTValidatorImpl.validateSignature(JWTValidatorImpl.java:98)| at org.wso2.carbon.apimgt.impl.jwt.JWTValidatorImpl.validateToken_aroundBody0(JWTValidatorImpl.java:58)| at org.wso2.carbon.apimgt.impl.jwt.JWTValidatorImpl.validateToken(JWTValidatorImpl.java:53)| at org.wso2.carbon.apimgt.impl.jwt.JWTValidationServiceImpl.validateJWTToken_aroundBody0(JWTValidationServiceImpl.java:44)| at org.wso2.carbon.apimgt.impl.jwt.JWTValidationServiceImpl.validateJWTToken(JWTValidationServiceImpl.java:36)| at org.wso2.carbon.apimgt.gateway.handlers.security.jwt.JWTValidator.getJwtValidationInfo_aroundBody16(JWTValidator.java:444)| at org.wso2.carbon.apimgt.gateway.handlers.security.jwt.JWTValidator.getJwtValidationInfo(JWTValidator.java:413)| at org.wso2.carbon.apimgt.gateway.handlers.security.jwt.JWTValidator.authenticate_aroundBody0(JWTValidator.java:135)| at org.wso2.carbon.apimgt.gateway.handlers.security.jwt.JWTValidator.authenticate(JWTValidator.java:111)| at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.authenticate_aroundBody4(OAuthAuthenticator.java:273)| at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.authenticate(OAuthAuthenticator.java:116)| at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate_aroundBody58(APIAuthenticationHandler.java:530)| at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate(APIAuthenticationHandler.java:524)| at org.wso2.nn.handlers.ExtendedAuthenticationHandler.isSuperAuthenticate(ExtendedAuthenticationHandler.java:77)| at org.wso2.nn.handlers.ExtendedAuthenticationHandler.isAuthenticate(ExtendedAuthenticationHandler.java:68)| at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody50(APIAuthenticationHandler.java:419)| at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:378)| at org.wso2.nn.handlers.ExtendedAuthenticationHandler.handleRequest(ExtendedAuthenticationHandler.java:33)| at org.apache.synapse.rest.API.process(API.java:391)| at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:146)| at org.apache.synapse.rest.RESTRequestHandler.identifyAPI(RESTRequestHandler.java:166)| at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:97)| at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:73)| at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:336)| at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99)| at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)| at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRESTRequest(MultitenantMessageReceiver.java:701)| at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doNhttpREST(MultitenantMessageReceiver.java:608)| at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doREST(MultitenantMessageReceiver.java:412)| at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:260)| at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:88)| at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)| at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:387)| at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:446)| at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:201)| at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)| at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)| at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)| at java.base/java.lang.Thread.run(Thread.java:829)

### Solution

Improving the error messagge/Error handling

### Affected Component

APIM

### Version

3.2.0

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this since the update has been released. 

Thanks!
Dulith
