### ISSUE TITLE
To remove unnecessary stack trace that is printing due to an error that occurs when closing the inactive web socket channels

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/api-manager#2022]
### Problem

The following error trace is getting printed when removing resources allocated for the inactive web socket channel. However, it doesn't have any functional impact since this is related to the inactive channels. But it introduces an unnecessary noise that decreases the readability of the logs due to containing the full stack trace and getting printed frequently when the load is high.

```
[2023-07-03 03:04:30,127] ERROR - InboundWebsocketSourceHandler Error encountered while processing inbound websocket connection

org.apache.synapse.SynapseException: Endpoint not found for port : 8099 tenant domain : null

	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.handleException(InboundWebsocketSourceHandler.java:645) ~[org.wso2.carbon.inbound.endpoint_4.7.61.33.jar:?]

	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.channelInactive(InboundWebsocketSourceHandler.java:183) ~[org.wso2.carbon.inbound.endpoint_4.7.61.33.jar:?]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) [io.netty.handler_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.handler.codec.MessageAggregator.channelInactive(MessageAggregator.java:438) [io.netty.codec_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.handler.codec.MessageAggregator.channelInactive(MessageAggregator.java:438) [io.netty.codec_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) [io.netty.codec_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:357) [io.netty.codec_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) [io.netty.codec_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:357) [io.netty.codec_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1073) [io.netty.handler_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.common_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [io.netty.common_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [io.netty.common_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.common_4.1.73.Final.jar:4.1.73.Final]

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.common_4.1.73.Final.jar:4.1.73.Final]

	at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Solution

Since this error occurs due to breaking the connection in an unintended manner, we can introduce a single-line error for this instead of printing the full stack trace.

### Affected Component

APIM

### Version

3.2.0

**Comment by YasasRangika** [comment]
This issue is marked as an invalid in the linked internal issue.
