### ISSUE TITLE
Apim Component Migration Fails Due to Missing “Organization” Column at an Early Stage

### ISSUE THREAD

**Issue by Abshan** [wso2/api-manager#2042]
### Description

When migrating the product from APIM-3.1.0 to APIM-4.2.0, we observed an error during the APIM component migration step. Please find the complete error stack trace below,

```
ERROR {org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO} - Failed to retrieve API categories for organization carbon.super org.postgresql.util.PSQLException: ERROR: column "organization" does not exist
  Position: 61
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at jdk.internal.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy53.executeQuery(Unknown Source)
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getAllCategories_aroundBody724(ApiMgtDAO.java:15410)
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getAllCategories(ApiMgtDAO.java:1)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAllAPICategoriesOfOrganization_aroundBody708(APIUtil.java:8329)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAllAPICategoriesOfOrganization(APIUtil.java:1)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.populateAPIProductInformation_aroundBody134(AbstractAPIManager.java:1482)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.populateAPIProductInformation(AbstractAPIManager.java:1)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIProductbyUUID_aroundBody390(APIProviderImpl.java:4867)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIProductbyUUID(APIProviderImpl.java:1)
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getAPIProductbyUUID(UserAwareAPIProvider.java:1)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.exportAPIProduct(V400RegistryResourceMigrator.java:950)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.addAPIProductRevision(V400RegistryResourceMigrator.java:740)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.apiRevisionRelatedMigration(V400RegistryResourceMigrator.java:476)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.migrate(V400RegistryResourceMigrator.java:140)
	at org.wso2.carbon.apimgt.migration.migrator.client.V400Migration.migrate(V400Migration.java:64)
	at org.wso2.carbon.apimgt.migration.APIMMigrationClient.executeMigration(APIMMigrationClient.java:90)
	at org.wso2.carbon.apimgt.migration.APIMMigrationClient.completedServerStartup(APIMMigrationClient.java:63)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyAfter(CarbonCoreServiceComponent.java:264)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:214)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:309)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:118)
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

ERROR {org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator} - WSO2 API-M Migration Task : Error while adding API revisions, API uuid: b7064b0e-843c-4836-866a-ff76a2306a38 org.wso2.carbon.apimgt.migration.APIMigrationException: WSO2 API-M Migration Task : Error while Store the Revision Artifact for API product: b7064b0e-843c-4836-866a-ff76a2306a38 for tenant -1234(carbon.super)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.addAPIProductRevision(V400RegistryResourceMigrator.java:757)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.apiRevisionRelatedMigration(V400RegistryResourceMigrator.java:476)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.migrate(V400RegistryResourceMigrator.java:140)
	at org.wso2.carbon.apimgt.migration.migrator.client.V400Migration.migrate(V400Migration.java:64)
	at org.wso2.carbon.apimgt.migration.APIMMigrationClient.executeMigration(APIMMigrationClient.java:90)
	at org.wso2.carbon.apimgt.migration.APIMMigrationClient.completedServerStartup(APIMMigrationClient.java:63)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyAfter(CarbonCoreServiceComponent.java:264)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:214)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:309)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:118)
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: org.wso2.carbon.apimgt.api.APIManagementException: Failed to retrieve API categories for organization carbon.super
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.handleException_aroundBody310(ApiMgtDAO.java:7112)
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.handleException(ApiMgtDAO.java:1)
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getAllCategories_aroundBody724(ApiMgtDAO.java:15426)
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getAllCategories(ApiMgtDAO.java:1)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAllAPICategoriesOfOrganization_aroundBody708(APIUtil.java:8329)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAllAPICategoriesOfOrganization(APIUtil.java:1)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.populateAPIProductInformation_aroundBody134(AbstractAPIManager.java:1482)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.populateAPIProductInformation(AbstractAPIManager.java:1)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIProductbyUUID_aroundBody390(APIProviderImpl.java:4867)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIProductbyUUID(APIProviderImpl.java:1)
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getAPIProductbyUUID(UserAwareAPIProvider.java:1)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.exportAPIProduct(V400RegistryResourceMigrator.java:950)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.addAPIProductRevision(V400RegistryResourceMigrator.java:740)
	... 47 more
Caused by: org.postgresql.util.PSQLException: ERROR: column "organization" does not exist
  Position: 61
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at jdk.internal.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy53.executeQuery(Unknown Source)
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getAllCategories_aroundBody724(ApiMgtDAO.java:15410)
	... 57 more
```

The above error stack trace can be observed during the **3.2.0** to **4.0.0** APIM component migration step. As the error states, when trying to retrieve API category information, the above error is getting thrown because the "ORGANIZATION" column is missing in the table schema.

We observed that the migration client attempts to query the "AM_API_CATEGORIES" table during the Registry resource migration step. However, it appears to be looking for a value in the "ORGANIZATION" column at an early stage of the migration process (from version 3.2.0 to 4.0.0).

The issue lies in the fact that the "ORGANIZATION" column was introduced in APIM version 4.1.0, and the migration scripts that are supposed to create this column should be executed in the next step (from 4.0.0 to 4.1.0) of the APIM component migration. 

Due to the above issue, migration from APIM-3.1.0 to APIM-4.2.0 is blocked.

### Steps to Reproduce

The mentioned issue can be replicated when migrating an APIM-3.1.0 setup to the APIM-4.2.0 version, which consists of a few REST APIs and API Products.

### Affected Component

APIM

### Version

4.2.0

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
