### ISSUE TITLE
Exception occurred while performing web socket load test with custom configurations

### ISSUE THREAD

**Issue by DaniduWijendra** [wso2/api-manager#2059]
### Description

While performing a websocket load test with the following websocket related configurations, observed the following error trace when performing a load test for around 3 minutes.

```
[apim.ws]
subprotocol_handler = "org.wso2.bny.test.subprotocol.SubprotocolHandlerv10stomp;org.wso2.bny.test.subprotocol.SubprotocolHandlerv11stomp;org.wso2.bny.test.subprotocol.SubprotocolHandlerv12stomp"

[apim.wss]
subprotocol_handler = "org.wso2.bny.test.subprotocol.SubprotocolHandlerv10stomp;org.wso2.bny.test.subprotocol.SubprotocolHandlerv11stomp;org.wso2.bny.test.subprotocol.SubprotocolHandlerv12stomp"
```

Error trace

```
2023-07-24 20:15:50,059] ERROR - InboundWebsocketSourceHandler dc215cfffec5925c-000018ce-00000175-9b7518c9a65d1968-47e1a168 -- Error encountered while processing inbound websocket connection
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.SubprotocolBuilderUtil.buildSubprotocolString(SubprotocolBuilderUtil.java:48) ~[org.wso2.carbon.inbound.endpoint_4.7.61.37.jar:?]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.handleHandshake(InboundWebsocketSourceHandler.java:235) ~[org.wso2.carbon.inbound.endpoint_4.7.61.37.jar:?]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.channelRead(InboundWebsocketSourceHandler.java:161) ~[org.wso2.carbon.inbound.endpoint_4.7.61.37.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at org.wso2.carbon.apimgt.gateway.handlers.WebsocketInboundHandler.channelRead_aroundBody4(WebsocketInboundHandler.java:292) [org.wso2.carbon.apimgt.gateway_6.7.206.428.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.WebsocketInboundHandler.channelRead(WebsocketInboundHandler.java:168) [org.wso2.carbon.apimgt.gateway_6.7.206.428.jar:?]
	at com.bnymellon.ess.wso2.apimgt.gateway.handlers.BNYMWebSocketInboundHandler.channelRead(BNYMWebSocketInboundHandler.java:96) [com.bnymellon.ess.wso2.apimgt.gateway-2.10.8.8.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [io.netty.handler_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [io.netty.common_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.common_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.common_4.1.86.Final.jar:4.1.86.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]


```

### Steps to Reproduce

- Created mock WebSocket backed-end using tornado 1 ( python ) which echoes back

```
import tornado.httpserver
import tornado.websocket
import tornado.ioloop
import tornado.web
import socket
'''
This is a simple Websocket Echo server that uses the Tornado websocket handler.
Please run `pip install tornado` with python of version 2.7.9 or greater to install tornado.
This program will echo back the reverse of whatever it recieves.
Messages are output to the terminal for debuggin purposes. 
''' 
 
class WSHandler(tornado.websocket.WebSocketHandler):
    def open(self):
        print ('new connection')
      
    def on_message(self, message):
        print ('message received:  ',message)
        #print ('sending back message: ' % message[::-1])
        self.write_message(message)
 
 
application = tornado.web.Application([
    (r'/ws', WSHandler),
])
 
 
if __name__ == '__main__':
    http_server = tornado.httpserver.HTTPServer(application)
    http_server.listen(8888)
    myIP = socket.gethostbyname(socket.gethostname())
    print ('** Websocket Server Started at **' ,myIP)
    tornado.ioloop.IOLoop.instance().start()
```

- Deployed a WebSocket API with the aforementioned BE endpoint ( ws://localhost:8888/ws )
- Conducted a load test by invoking the WebSocket endpoint by executing the below script in parallel and we could notice the below error trace a few times in the wso2carbon log after executing the script for a few minutes

```
#!/bin/bash
for i in `seq 1 3000`
do  
 echo "Looping ... number $i";  
    wscat --no-check --connect ws://localhost:9099/new/1.0.0?access_token=eyJ4NXQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l3WW1NNFpUQTNNV0kyTkRBelpHUXpOR00wWkdSbE5qSmtPREZrWkRSaU9URmtNV0ZoTXpVMlpHVmxOZyIsImtpZCI6Ik16WXhNbUZrT0dZd01XSTBaV05tTkRjeE5HWXdZbU00WlRBM01XSTJOREF6WkdRek5HTTBaR1JsTmpKa09ERmtaRFJpT1RGa01XRmhNelUyWkdWbE5nX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJhZG1pbiIsImF1dCI6IkFQUExJQ0FUSU9OIiwiYXVkIjoiUF92Y0VFQWk2S2V2eFNMWkJFYVZYWVQ4UUlRYSIsIm5iZiI6MTY4OTk0MjgxOCwiYXpwIjoiUF92Y0VFQWk2S2V2eFNMWkJFYVZYWVQ4UUlRYSIsInNjb3BlIjoiZGVmYXVsdCIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTQ0M1wvb2F1dGgyXC90b2tlbiIsImV4cCI6OTIyMzM3MjAzNjg1NDc3NSwiaWF0IjoxNjg5OTQyODE4LCJqdGkiOiIyNzMyNDM5My0yZWNhLTQ4ZmQtODVkNS1kZDVkY2JjODliMGEifQ.qTjLBAt4cXaaJ2Z0Mz6EN674LkYzvuWziX7tCj_P8IlbQJlKVyHFInTV__CT9fERYS90-2L6X_aI93IcOmCZ2lPnLUJyB8T2wuqrcNh4zWh-BkCY1ftDPopCf-1ixOmzQGUQdvRtyW4rMs5-mQm-XfI3xBcJxsRNNEaxtziJNDE2hfJnKw8XANzbGvmUllbMcC0MFhwixL6kXSrKjcjb55IcBzfrmqdgrsj2X8kuqZurJt-qHSYnd0JLeNANoeHueT9Rsx4sdzQGdZ_gnu_nwFm1o5P0AF1ppULAMc8QXggBrOJZ5b96XvZwkdcF21rg4mTd1kD1Xm6DIaEwqtpc4A -w 1 -x '{ "hello" : "world"}'
    sleep $delay
done | tee test_wscat_out.txt
```

### Affected Component

APIM

### Version

3.2.0

**Comment by Lakith-Rambukkanage** [comment]
Fixed by :https://github.com/wso2/carbon-mediation/pull/1685
