### ISSUE TITLE
Cannot change SP names in wso2 APIM 4.1.0

### ISSUE THREAD

**Issue by AshenShalitha** [wso2/api-manager#2060]
### Description

HI team,

When trying to modify the service provider names of the oAuth2 applications with the respective name of the application like in the previous APIM versions (To have the name of the application in the SP rather than the application UUID). In older versions, we can do this using the following system property [1] which we introduced in APIM-2.6 to prevent the updated SP names from getting overwritten when updating the application.

`-Doverride.sp.name=false`

After adding this property in APIM-4.1, the SP name can modify and it will not get overwritten when updating the application. However, if we click the application update button more than one time, we'll get the following error in the carbon log. Also, the changes made to the application will not be saved as well.

As per the source code the request sent to the DCR endpoint when updating the application, is returning 500. Furthermore, we noticed that the only SP_APP table is getting updated with the new SP name. The IDN_OAUTH_CONSUMER_APPS table still contains the older SP name (name with the application uuid).

[1] https://github.com/wso2/product-apim/issues/9455

### Steps to Reproduce

- Update the <APIM_HOME>/bin/api-manager.sh file with the following system property
`-Doverride.sp.name=false `
- Restart the APIM server
- Create an application through the devportal
- Generate application keys
- Go to the https://:9443/carbon portal
- Select the relevant SP-> Click on Edit -> Update the name -> Click on Update
- Go back to the devportal
- Open the same application and click "Update" button
- Then click the "Update" button again

### Affected Component

APIM

### Version

4.1.0

### Relevant Log Output

```shell
ERROR - AbstractKeyManager Error occurred while updating OAuth Client :
org.wso2.carbon.apimgt.impl.kmclient.KeyManagerClientException: Received status code: 500 Reason:
	at org.wso2.carbon.apimgt.impl.kmclient.KMClientErrorDecoder.decode_aroundBody0(KMClientErrorDecoder.java:49) ~[org.wso2.carbon.apimgt.impl_9.20.74.186.jar:?]
	at org.wso2.carbon.apimgt.impl.kmclient.KMClientErrorDecoder.decode(KMClientErrorDecoder.java:39) ~[org.wso2.carbon.apimgt.impl_9.20.74.186.jar:?]
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at com.sun.proxy.$Proxy461.updateApplication(Unknown Source) ~[?:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.updateApplication_aroundBody4(AMDefaultKeyManagerImpl.java:395) ~[org.wso2.carbon.apimgt.impl_9.20.74.186.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.updateApplication(AMDefaultKeyManagerImpl.java:352) ~[org.wso2.carbon.apimgt.impl_9.20.74.186.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.updateAuthClient_aroundBody176(APIConsumerImpl.java:4751) ~[org.wso2.carbon.apimgt.impl_9.20.74.186.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.updateAuthClient(APIConsumerImpl.java:4666) ~[org.wso2.carbon.apimgt.impl_9.20.74.186.jar:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl.applicationsApplicationIdOauthKeysKeyMappingIdPut(ApplicationsApiServiceImpl.java:1288) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.ApplicationsApi.applicationsApplicationIdOauthKeysKeyMappingIdPut(ApplicationsApi.java:376) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[?:?]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[?:?]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[?:?]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[?:?]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPut(AbstractHTTPServlet.java:234) ~[?:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:558) ~[tomcat-servlet-api_9.0.76.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[?:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) ~[tomcat_9.0.76.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat_9.0.76.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat_9.0.76.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat_9.0.76.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat_9.0.76.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat_9.0.76.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat_9.0.76.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[tomcat_9.0.76.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[tomcat_9.0.76.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat_9.0.76.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) ~[org.wso2.carbon.identity.context.rewrite.valve_1.4.52.jar:
```

### Suggested Labels

apim

**Comment by Kirishikesan** [comment]
Hi team,

Closing this since its completed.
PR : https://github.com/wso2-extensions/apim-km-wso2is/pull/110

Thanks & Regards,
Kirishikesan
