### ISSUE TITLE
Operation policy "Set To Header" only supports values, not expressions

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/api-manager#21]
### Describe your problem(s)
With the new operations policies feature, we introduced a policy named **Set To Header** which has the ability to do the functionality that we did in [1] in APIM 4.0.0, in an easy manner. 

But it has the ability only to add the Values to the Header Values, not expressions. 

### Steps to reproduce
1. Create a REST API with few resources.
2. Change its endpoint type to Dynamic Endpoints.
    ![image](https://user-images.githubusercontent.com/25246848/164643384-7f4fe862-dc46-48a1-8362-e02f02e8027f.png)
3. Go to the Policies section and add the **Set To Header** policy to all the resources as a request policy. It will prompt to enter the header value. Enter it as ```get-property('system','calculator.api.endpoint.url')```.
    ![image](https://user-images.githubusercontent.com/25246848/164644141-612478a1-4b90-4709-9761-72f9ed402f2d.png)
    (Make sure that you have already set the system property before. You can easily do it by starting the server like this -> ```sh api-manager.sh -Dcalculator.api.endpoint.url=https://localhost:9443/am/sample/calculator/v1/api/ ```)
4. Deploy and Publish the API.
5. Go to the Developer portal and invoke it. You'll get an Internal Server Error as below.
    ![image](https://user-images.githubusercontent.com/25246848/164644448-9047c998-da5c-45e8-bfad-e46b6ab5073c.png)
6. If you check the logs, it'll have the below error.
```
[2022-04-22 13:29:14,556] ERROR - ClientUtils The system cannot infer the transport information from the get-property('system','calculator.api.endpoint.url')/add?x=1&y=2 URL.
[2022-04-22 13:29:14,566] ERROR - Axis2Sender {api:CalculatorAPI:v1.0.0} Unexpected error during sending message out. The system cannot infer the transport information from the get-property('system','calculator.api.endpoint.url')/add?x=1&y=2 URL.
org.apache.axis2.AxisFault: The system cannot infer the transport information from the get-property('system','calculator.api.endpoint.url')/add?x=1&y=2 URL.
	at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:86) ~[axis2_1.6.1.wso2v80.jar:?]
	at org.apache.synapse.core.axis2.DynamicAxisOperation$DynamicOperationClient.executeImpl(DynamicAxisOperation.java:124) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) ~[axis2_1.6.1.wso2v80.jar:?]
	at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:668) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:86) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:586) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:410) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.endpoints.DefaultEndpoint.send(DefaultEndpoint.java:106) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.endpoints.IndirectEndpoint.send(IndirectEndpoint.java:56) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:126) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:171) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.api.Resource.process(Resource.java:342) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.api.API.process(API.java:477) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:76) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v80.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:376) ~[synapse-nhttp-transport_2.1.7.wso2v271.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:190) ~[synapse-nhttp-transport_2.1.7.wso2v271.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v80.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
[2022-04-22 13:29:14,938]  WARN - EndpointContext Endpoint : CalculatorAPI--v1.0.0_APIproductionEndpoint  will be marked SUSPENDED as it failed
[2022-04-22 13:29:14,941]  WARN - EndpointContext Suspending endpoint : CalculatorAPI--v1.0.0_APIproductionEndpoint  - current suspend duration is : 30000ms - Next retry after : Fri Apr 22 13:29:44 IST 2022
[2022-04-22 13:29:14,946]  INFO - LogMediator {api:CalculatorAPI:v1.0.0} STATUS = Executing default 'fault' sequence, ERROR_CODE = 0, ERROR_MESSAGE = Unexpected error during sending message out. The system cannot infer the transport information from the get-property('system','calculator.api.endpoint.url')/add?x=1&y=2 URL.
```
7. Moreover, if you call the Gateway REST API (```https://127.0.0.1:9443/api/am/gateway/v2/sequence?apiName=CalculatorAPI&version=1.0.0```) and check the enforced policies the response will look like below.
```
{
    "sequences": [
        "<sequence xmlns=\"http://ws.apache.org/ns/synapse\" name=\"CalculatorAPI:v1.0.0--In\"><property name=\"switchExpression\" expression=\"fn:concat($ctx:REST_METHOD,'_',$ctx:API_ELECTED_RESOURCE)\"/><switch source=\"$ctx:switchExpression\"><case regex=\"GET_\/add\"><header name=\"To\" value=\"get-property('system','calculator.api.endpoint.url')\"/></case><case regex=\"GET_\/subtract\"><header name=\"To\" value=\"get-property('system','calculator.api.endpoint.url')\"/></case></switch></sequence>"
    ]
}
```
  **Note that, it has the ```get-property('system','calculator.api.endpoint.url')``` as a value. It should be an expression.**

### Workaround
The workaround is to create a custom policy like below and add it and enforce it.
```
<sequence xmlns="http://ws.apache.org/ns/synapse" name="default-endpoint-seq">
    <header name="To" expression="get-property('system','calculator.api.endpoint.url')"/>
</sequence>
```
However, this workaround is similar to what we do in old APIM versions such as APIM 4.0.0, 3.2.0 etc. Having **Set To Header** inbuilt sequence is of no use if we are to move with this workaround in this type of situation.

### Describe your solution
Give the support to add a header expression as well (not only a header value) when enforcing the sequence to the resource.

[1] https://apim.docs.wso2.com/en/4.0.0/deploy-and-publish/deploy-on-gateway/api-gateway/message-mediation/adding-dynamic-endpoints/

**Comment by 1akshitha** [comment]
We have two options. Create a new policy to handle expressions. But this is not nice as there are two different policies for the same functionality and it will be confusing. 

The second option is to patch the same To Header policy to accept two attributes (Value or expression). We need to change the j2 mapping and the policy spec to accept this new attribute.
