### ISSUE TITLE
[4.2.0] Password Recovery is not Working

### ISSUE THREAD

**Issue by hisanhunais** [wso2/api-manager#2142]
### Description

Password recover is not working for APIM 4.2.0 pack.

### Steps to Reproduce

1. Add below configurations to deployment.toml.
```
[output_adapter.email]
from_address= "<real-mail>@gmail.com"
username= "<real-mail>"
password= "<app-password>"
hostname= "smtp.gmail.com"
port= 587
enable_start_tls= true
enable_authentication= true

[identity_mgt.notification_channel_recovery]
recovery_code_validity=2

[identity_mgt.resend_notification]
resend_code_validity=5

[identity_mgt.password_reset_sms]
sms_otp_validity=2
```

2. Start the server.
3. Then create a user from devportal self signup option.
4. Try the forget password option and proceed by entering the username.
5. Go to user's mail and from the received mail, try to change the password.

### Affected Component

APIM

### Version

4.2.0

### Relevant Log Output

```shell
ERROR - IdentityManagementEndpointUtil Exception while retrieving error details from original exception. Original exception:
java.lang.IllegalArgumentException: missing provider
	at sun.security.jca.GetInstance.getService(GetInstance.java:79) ~[?:?]
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:206) ~[?:?]
	at java.security.Signature.getInstance(Signature.java:404) ~[?:?]
	at org.wso2.carbon.core.util.SignatureUtil.doSignature(SignatureUtil.java:103) ~[org.wso2.carbon.core_4.8.1.4.jar:?]
	at org.apache.jsp.self_002dregistration_002dprocess_jsp._jspService(self_002dregistration_002dprocess_jsp.java:472)
```

**Comment by hisanhunais** [comment]
The master fix has been done via https://github.com/wso2/identity-apps/pull/4059
