### ISSUE TITLE
Null Pointer exception when using dev portal REST API to generate token for Out of Band provisioned app

### ISSUE THREAD

**Issue by Arshardh** [wso2/api-manager#2154]
### Description

https://apis.wso2.com/api/am/devportal/v3/applications/<applicationId>/oauth-keys/<keyMappingId>/generate-token

Using the above endpoint , we are getting the below NPE . Reproduced in 4.2.0 latest

```
TID: [-1234] [api/am/devportal] [2023-08-22 18:02:45,333] ERROR {org.wso2.carbon.apimgt.rest.api.util.exception.GlobalThrowableMapper} - An unknown exception has been captured by the global exception mapper. java.lang.NullPointerException
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl.applicationsApplicationIdKeysKeyTypeGenerateTokenPost(ApplicationsApiServiceImpl.java:906)
	at org.wso2.carbon.apimgt.rest.api.store.v1.ApplicationsApi.applicationsApplicationIdKeysKeyTypeGenerateTokenPost(ApplicationsApi.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	...
```

### Steps to Reproduce

Create an app with out-of-bad provisioned keys.
Use the dev portal rest API to generate a token

### Affected Component

APIM

### Version

4.2.0

**Comment by Irash-Perera** [comment]
This issue has already been resolved in the latest APIM releases.

**Tested environment:**
- APIM 4.7
- IS 7.3
