### ISSUE TITLE
SynapseException when using an invalid OAuth token to invoke a WebSocket API

### ISSUE THREAD

**Issue by thisaltennakoon** [wso2/api-manager#2156]
### Description

There's a SynapseException when using an invalid OAuth token to invoke a WebSocket API.

### Steps to Reproduce

- Follow [this](https://apim.docs.wso2.com/en/latest/tutorials/streaming-api/create-and-publish-websocket-api/) doc, create & publish a WebSocket API.
- Subscribe to an application and invoke the created WebSocket API using an **invalid OAuth token**

### Affected Component

APIM

### Version

4.2.0

### Relevant Log Output

```shell
ERROR - HandshakeProcessor Authentication failed for /chats/1.0.0
ERROR - InboundWebsocketSourceHandler Endpoint not found for port : 9099 tenant domain : null
ERROR - InboundWebsocketSourceHandler Error encountered while processing inbound websocket connection
org.apache.synapse.SynapseException: Endpoint not found for port : 9099 tenant domain : null
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.handleException(InboundWebsocketSourceHandler.java:648) ~[org.wso2.carbon.inbound.endpoint_4.7.175.jar:?]
	at org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler.channelInactive(InboundWebsocketSourceHandler.java:184) ~[org.wso2.carbon.inbound.endpoint_4.7.175.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at org.wso2.carbon.apimgt.gateway.handlers.WebsocketInboundHandler.channelInactive_aroundBody6(WebsocketInboundHandler.java:109) ~[org.wso2.carbon.apimgt.gateway_9.28.163.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.WebsocketInboundHandler.channelInactive(WebsocketInboundHandler.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.163.SNAPSHOT.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[io.netty.handler_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.MessageAggregator.channelInactive(MessageAggregator.java:436) ~[io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.MessageAggregator.channelInactive(MessageAggregator.java:436) ~[io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411) ~[io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) ~[io.netty.codec_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.common_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.common_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.common_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) ~[io.netty.transport_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.common_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.common_4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.common_4.1.86.Final.jar:4.1.86.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by ashanhr** [comment]
I attempted to reproduce the issue mentioned. Initially, the error reported was a `SynapseException`. However, in my recent tests, the system now throws an `APISecurityException` instead of a `SynapseException`. This indicates that the original issue has been resolved.
