### ISSUE TITLE
 React version bumping from 16.x to 17.x

### ISSUE THREAD

**Issue by Tharanidk** [wso2/api-manager#2160]
### Problem

We need to bump the React version from 16.x to 17.x to allow developers the flexibility to use new libraries when they develop new features.

### Solution

The PR https://github.com/wso2/apim-apps/pull/495 has addressed the following

1. Swagger-ui-react version is bumped from 4.x to 5.x 
2. Material-ui-chip-input dependency is removed and the library ( single file ) is copied to the webapp as a fix.
3. Webpack version is bumped from 4.x to 5.x 
4. Monaco editor is updated which doesn't have any notable changes at the code level.
5. React-html-parser is removed due to peer dependency mismatch with react 17.0.0 and added html-react-paser.
6. Graphiql-explorer is replaced with a fork from a React version updated fork. 

After the above update following fixes are need to be done,

- [x]  Postman collection is not downloading.

### Affected Component

APIM

### Version

4.3.0

**Comment by Tharanidk** [comment]
### **Work Log**

- Added the pr : https://github.com/wso2/apim-apps/pull/495 as a remote and started working from that point onward.
- Upgraded openapi-to-postmanv2 from2.14.1 version to [4.16.0](https://www.npmjs.com/package/openapi-to-postmanv2/v/4.16.0)
- Postman collection is not downloading because 'conversionResult' is giving an 'Undefined' result in the [convertToPostman](https://github.com/wso2/apim-apps/blob/main/portals/devportal/src/main/webapp/source/src/app/components/Apis/Details/ApiConsole/ApiConsole.jsx#L365-L385) function.
- The following error message is shown in the browser console 

> TypeError: Cannot read properties of undefined (reading 'result')
    at ApiConsole.jsx:370:39
    at schemapack.js:419:18
    at convertToOAS30IfSwagger (swaggerToOpenapi.js:32:14)
    at SchemaPack.convert (schemapack.js:317:7)
    at Object.convert (index.js:14:21)
    at ApiConsole.convertToPostman (ApiConsole.jsx:366:9)
    at onClick (ApiConsole.jsx:608:74)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
ApiConsole.jsx:369
 Conversion Result: undefined

- Clone the repository [openapi-too-postman ](https://github.com/postmanlabs/openapi-to-postman/tree/release/v4.16.0) and pointed the local repository as a import to debug the code.

**Comment by Tharanidk** [comment]
### **Findings**

- The error is coming from the crypto.createHash function in schemaUtils.js. This happens because of the change in the webpack.config.js  https://github.com/wso2/apim-apps/pull/495/files#diff-7c3a5206eebf0b12c878ad3471b038fffac7dd5cb021af715676ededaf20acb8R82

**Comment by Tharanidk** [comment]
### **Work Log**

- Resolved the issue with the Postman collection not downloading.
- Starting Automated UI tests and manual testing related to React version bumping to 17.0.0

**Comment by Tharanidk** [comment]
### **Work Log**

- Work on checking the compatibility of different dependencies with React 18.0.0 before start bumping the React version to 18.0.0
https://docs.google.com/spreadsheets/d/1tK_u5qh90uvqLoLESwJHGxxwqqgOP2wNleaoMpBX9Lc/edit#gid=0
