### ISSUE TITLE
500 error occurs when refreshing Business Info and API definition pages

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/api-manager#2161]
### Description

500 error occurs when refreshing Business Info and API definition pages.

### Steps to Reproduce

Login to APIM publisher portal
Deploy an API
Navigate to Business Info/ API definition pages
Refresh the page.

### Affected Component

APIM

### Version

4.2.0

### Relevant Log Output

```shell
[2023-09-11 14:05:05,973] ERROR - AuthenticationValve Error while normalizing the request URI to process the authentication: 
java.net.URISyntaxException: Illegal character in path at index 61: /publisher/apis/52dd7d90-1b70-44cd-bc62-197071453c83/business info
	at java.net.URI$Parser.fail(URI.java:2913) ~[?:?]
	at java.net.URI$Parser.checkChars(URI.java:3084) ~[?:?]
	at java.net.URI$Parser.parseHierarchical(URI.java:3166) ~[?:?]
	at java.net.URI$Parser.parse(URI.java:3125) ~[?:?]
	at java.net.URI.<init>(URI.java:600) ~[?:?]
	at org.wso2.carbon.identity.auth.service.util.AuthConfigurationUtil.getNormalizedRequestURI(AuthConfigurationUtil.java:346) ~[org.wso2.carbon.identity.auth.service_1.7.1.2.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:105) ~[org.wso2.carbon.identity.auth.valve_1.7.1.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106) ~[org.wso2.carbon.tomcat.ext_4.8.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) ~[org.wso2
```

**Comment by HeshanSudarshana** [comment]
This issue is not reproduced in APIM 4.2.0 or 4.3.0.
