### ISSUE TITLE
Unable to import OpenAPI 3.0.3 spec (LiveLock)

### ISSUE THREAD

**Issue by LuisMalhadas** [wso2/api-manager#2168]
### Description

I built a docker image containing wso2am-4.2.0, following from the github actions scripts.
I deploy it and all seems fine.
The issue arises once you want to import a larger OpenAPI spec: 
(too big to leave here, if required I can provide it separately somehow)

### Steps to Reproduce

The dockerfile:
```dockerfile
# Use the official OpenJDK 11 image as the base image
FROM openjdk:11.0.16-jdk-slim-bullseye as carbon-apimgt

# Set environment variables
ENV WSO2_API_MANAGER_VERSION="4.2.0"
ENV WSO2_API_MANAGER_HOME="/opt/wso2am-${WSO2_API_MANAGER_VERSION}"
ENV JAVA_HOME="/usr/local/openjdk-11"
ENV ANT_HOME="/opt/apache-ant-1.7.0"
ENV MAVEN_HOME="/opt/apache-maven-3.6.3"
ENV MAVEN_OPTS="-Xmx2048M -XX:MaxPermSize=1024m"

# Install necessary packages
RUN apt-get update && \
    apt-get install -y -q --no-install-recommends \
        apt-transport-https build-essential \
        ca-certificates curl git libssl-dev wget unzip git && \
    rm -rf /var/lib/apt/lists/* && \
    wget -P /tmp https://archive.apache.org/dist/ant/binaries/apache-ant-1.7.0-bin.zip && \
    unzip /tmp/apache-ant-1.7.0-bin.zip -d /opt && \
    rm /tmp/apache-ant-1.7.0-bin.zip && \
    wget -P /tmp https://archive.apache.org/dist/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.zip && \
    unzip /tmp/apache-maven-3.9.4-bin.zip -d /opt && \
    rm /tmp/apache-maven-3.9.4-bin.zip

# Install NodeJS 14
RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

WORKDIR ${WSO2_API_MANAGER_HOME}

# Clone and Install carbon-apimgt component
RUN git clone -b v9.28.175 https://github.com/wso2/carbon-apimgt.git && \
    cd carbon-apimgt && \
    sh /opt/apache-maven-3.9.4/bin/mvn --file pom.xml -Dmaven.test.skip=true -Dskip.aspectj=true -Dnpm.build.skip=true -DskipBenchMarkTest=true install 


FROM  ubuntu:20.04 as wso2am

# Set environment variables
ENV WSO2_API_MANAGER_VERSION="4.2.0"
ENV WSO2_API_MANAGER_HOME="/opt/wso2am-${WSO2_API_MANAGER_VERSION}"
ENV ANT_HOME="/opt/apache-ant-1.7.0"
ENV MAVEN_HOME="/opt/apache-maven-3.6.3"
ENV MAVEN_OPTS="-Xmx2048M -XX:MaxPermSize=1024m"
ENV JAVA_HOME="/usr/lib/jvm/java-8-openjdk-arm64"
ENV TZ="Europe/Madrid"

RUN ln -snf /usr/share/zoneinfo/Europe/Madrid /etc/localtime && \
    echo "Europe/Madrid" > /etc/timezone

# Copy the carbon-apimgt maven repository to the new image
COPY --from=carbon-apimgt /root/.m2 /root/.m2

# Install necessary packages
RUN apt-get update --allow-unauthenticated && \
    apt-get install -y -q --no-install-recommends \
        apt-transport-https build-essential software-properties-common rpm \
        ca-certificates curl git libssl-dev wget unzip git openjdk-8-jdk && \
    rm -rf /var/lib/apt/lists/* && \
    wget -P /tmp https://archive.apache.org/dist/ant/binaries/apache-ant-1.7.0-bin.zip && \
    unzip /tmp/apache-ant-1.7.0-bin.zip -d /opt && \
    rm /tmp/apache-ant-1.7.0-bin.zip && \
    wget -P /tmp https://archive.apache.org/dist/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.zip && \
    unzip /tmp/apache-maven-3.9.4-bin.zip -d /opt && \
    rm /tmp/apache-maven-3.9.4-bin.zip

WORKDIR ${WSO2_API_MANAGER_HOME}

# Install NodeJS 10
RUN apt-get update && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/* 

# Clone and Install product-apim component
RUN git clone --branch release-4.2.0-m1-o248 https://github.com/wso2/product-apim.git && \
    cd product-apim && \
    sh /opt/apache-maven-3.9.4/bin/mvn -Dcheckstyle.skip -Dmaven.test.skip=true -DskipTests -Dfindbugs.skip=true -Dpmd.skip=true -Dmaven.javadoc.skip=true -Dskip.aspectj=true -Dnpm.build.skip=true -DskipBenchMarkTest=true -DskipIntegrationTests=true install 

# Finaly extract the wso2am zip file
RUN unzip /opt/wso2am-4.2.0/product-apim//modules/distribution/product/target/wso2am-4.2.0-SNAPSHOT.zip -d ${WSO2_API_MANAGER_HOME}

# Install Oracle Java 11
# Copy the Oracle JDK 11 RPM package into the image
COPY jdk-11.0.19_linux-aarch64_bin.tar.gz jdk-11.0.19_linux-aarch64_bin.tar.gz

# Extract the JDK tar.gz
RUN mkdir -p /opt/java && \
    tar -xzvf jdk-11.0.19_linux-aarch64_bin.tar.gz -C /opt/java --strip-components=1 && \
    rm jdk-11.0.19_linux-aarch64_bin.tar.gz

ENV JAVA_HOME="/opt/java"
ENV PATH=$PATH:$JAVA_HOME/bin

# Expose ports
EXPOSE 11111 5672 8243 8280 9099 9443 9611 9711 9763 9999

RUN cat /opt/wso2am-4.2.0/wso2am-4.2.0-SNAPSHOT/bin/api-manager.sh

# Start WSO2 API Manager
CMD ["/bin/sh", "-c","/opt/wso2am-4.2.0/wso2am-4.2.0-SNAPSHOT/bin/api-manager.sh"]
```

Build deploy and import RESTful API from the publisher portal, and select URL. 
The backend replies to http://.../api with the json specified previously.

### Affected Component

Analytics

### Version

4.2.0

### Environment Details (with versions)

Shouldn't matter much, but I am using an M2 Apple silicon, fully updated. Everything else can be observed on the dockerfile.

### Relevant Log Output

```shell
platform-backend-apimanager-1  | JAVA_HOME environment variable is set to /opt/java
platform-backend-apimanager-1  | CARBON_HOME environment variable is set to /opt/wso2am-4.2.0/wso2am-4.2.0-SNAPSHOT
platform-backend-apimanager-1  | Using Java memory options: -Xms512m -Xmx2048m
platform-backend-apimanager-1  | [2023-09-14 09:25:31,619]  INFO {org.wso2.config.mapper.ConfigParser} - Configurations Changed in :repository/resources/security/sslprofiles.xml
platform-backend-apimanager-1  | [2023-09-14 09:25:31,619]  INFO {org.wso2.config.mapper.ConfigParser} - Configurations Changed in :repository/resources/security/listenerprofiles.xml
platform-backend-apimanager-1  | [2023-09-14 09:25:31,619]  INFO {org.wso2.config.mapper.ConfigParser} - Overriding files in configuration directory /opt/wso2am-4.2.0/wso2am-4.2.0-SNAPSHOT
platform-backend-apimanager-1  | [2023-09-14 09:25:35,267]  INFO - CarbonCoreActivator Starting WSO2 Carbon...
platform-backend-apimanager-1  | [2023-09-14 09:25:35,267]  INFO - CarbonCoreActivator Operating System : Linux 5.15.49-linuxkit-pr, aarch64
platform-backend-apimanager-1  | [2023-09-14 09:25:35,267]  INFO - CarbonCoreActivator Java Home        : /opt/java
platform-backend-apimanager-1  | [2023-09-14 09:25:35,267]  INFO - CarbonCoreActivator Java Version     : 11.0.19
platform-backend-apimanager-1  | [2023-09-14 09:25:35,267]  INFO - CarbonCoreActivator Java VM          : Java HotSpot(TM) 64-Bit Server VM 11.0.19+9-LTS-224,Oracle Corporation
platform-backend-apimanager-1  | [2023-09-14 09:25:35,267]  INFO - CarbonCoreActivator Carbon Home      : /opt/wso2am-4.2.0/wso2am-4.2.0-SNAPSHOT
platform-backend-apimanager-1  | [2023-09-14 09:25:35,267]  INFO - CarbonCoreActivator Java Temp Dir    : /opt/wso2am-4.2.0/wso2am-4.2.0-SNAPSHOT/tmp
platform-backend-apimanager-1  | [2023-09-14 09:25:35,267]  INFO - CarbonCoreActivator User             : root, en-US, Europe/Madrid
platform-backend-apimanager-1  | [2023-09-14 09:25:35,336]  INFO - DefaultCryptoProviderComponent 'CryptoService.Secret' property has not been set. 'org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider' won't be registered as an internal crypto provider. Please set the secret if the provider needs to be registered.
platform-backend-apimanager-1  | [2023-09-14 09:25:35,479]  INFO - KafkaEventAdapterServiceDS Successfully deployed the Kafka output event adaptor service
platform-backend-apimanager-1  | [2023-09-14 09:25:35,538]  INFO - TemplateDeployerServiceTrackerDS Successfully deployed the execution manager tracker service
platform-backend-apimanager-1  | [2023-09-14 09:25:36,130]  INFO - ServiceComponent Eventing Hub ServiceComponent is activated
platform-backend-apimanager-1  | [2023-09-14 09:25:36,433]  WARN - Digester Match [Server/Service/Engine/Host/Valve] failed to set property [maxDays] to []

...

platform-backend-apimanager-1  | [Broker] BRK-1001 : Startup : Version: 0.11 Build: 90784:90849
platform-backend-apimanager-1  | [Broker] MNG-1001 : Startup
platform-backend-apimanager-1  | [Broker] MNG-1004 : Ready : Using the platform JMX Agent
platform-backend-apimanager-1  | [Broker] BRK-1002 : Starting : Listening on TCP port 5672
platform-backend-apimanager-1  | [2023-09-14 09:25:57,869]  INFO - listening [Broker] BRK-1002 : Starting : Listening on TCP port 5672
platform-backend-apimanager-1  | [Broker] BRK-1002 : Starting : Listening on TCP/SSL port 8672
platform-backend-apimanager-1  | [2023-09-14 09:25:57,873]  INFO - listening [Broker] BRK-1002 : Starting : Listening on TCP/SSL port 8672
platform-backend-apimanager-1  | [Broker] BRK-1004 : Qpid Broker Ready
platform-backend-apimanager-1  | [2023-09-14 09:25:57,877]  INFO - QpidServiceComponent AMQP Host Address : 0.0.0.0 Port : 5672
platform-backend-apimanager-1  | [2023-09-14 09:25:57,878]  INFO - QpidServiceComponent Successfully connected to AMQP server on port 5672
platform-backend-apimanager-1  | [2023-09-14 09:25:57,878]  INFO - QpidServiceComponent WSO2 Message Broker is started.
platform-backend-apimanager-1  | [2023-09-14 09:25:57,989]  INFO - BinaryDataReceiver Started Binary SSL Transport on port : 9711
platform-backend-apimanager-1  | [2023-09-14 09:25:57,990]  INFO - BinaryDataReceiver Started Binary TCP Transport on port : 9611
platform-backend-apimanager-1  | [2023-09-14 09:25:58,062]  INFO - ThriftServerStartupObserver  Thrift Data Receiver is disabled.
platform-backend-apimanager-1  | [2023-09-14 09:25:58,083]  INFO - PassThroughHttpListener Starting Pass-through HTTP Listener...
platform-backend-apimanager-1  | [2023-09-14 09:25:58,088]  INFO - PassThroughListeningIOReactorManager Pass-through HTTP Listener started on 0.0.0.0:8280
platform-backend-apimanager-1  | [2023-09-14 09:25:58,088]  INFO - PassThroughHttpMultiSSLListener Starting Pass-through HTTPS Listener...
platform-backend-apimanager-1  | [2023-09-14 09:25:58,095]  INFO - PassThroughListeningIOReactorManager Pass-through HTTPS Listener started on 0.0.0.0:8243
platform-backend-apimanager-1  | [2023-09-14 09:25:58,138]  WARN - SSLUtilBase The trusted certificate with alias [geotrustglobalca] and DN [CN=GeoTrust Global CA, O=GeoTrust Inc., C=US] is not valid due to [NotAfter: Sat May 21 06:00:00 CEST 2022]. Certificates signed by this trusted certificate WILL be accepted

...

platform-backend-apimanager-1  | [2023-09-14 09:25:59,700] ERROR - PolicyUtil Error in retrieving throttle policies
platform-backend-apimanager-1  | org.wso2.carbon.apimgt.throttle.policy.deployer.exception.ThrottlePolicyDeployerException: {"code":901300,"message":"Bad Request","description":"Provided tenant domain '*' is invalid","moreInfo":"","error":[]}Event-Hub status code is : 400
platform-backend-apimanager-1  |        at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.getPolicies(PolicyRetriever.java:203) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.27.0.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.getAllSubscriptionPolicies(PolicyRetriever.java:87) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.27.0.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.PolicyUtil.deployAllPolicies(PolicyUtil.java:159) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.27.0.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.ThrottlePolicyStartupListener.run(ThrottlePolicyStartupListener.java:76) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.27.0.jar:?]
platform-backend-apimanager-1  |        at java.lang.Thread.run(Thread.java:834) [?:?]

...

platform-backend-apimanager-1  | [2023-09-14 09:40:09,338]  WARN - CarbonStuckThreadDetectionValve Thread [https-jsse-nio-9443-exec-42] (id=[{6}]) has been active for [600,368] milliseconds (since [9/14/23, 9:30 AM]) to serve the same request for [https://localhost:9443/api/am/publisher/v3/apis/validate-openapi?returnContent=true] and may be stuck (configured threshold for this StuckThreadDetectionValve is [600] seconds). There is/are [1] thread(s) in total that are monitored by this Valve and may be stuck., tenantDomain=carbon.super, correlation-id=afc2f549-7499-423b-994e-c9579b21b898
platform-backend-apimanager-1  | java.lang.Throwable: null
platform-backend-apimanager-1  |        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
platform-backend-apimanager-1  |        at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
platform-backend-apimanager-1  |        at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
platform-backend-apimanager-1  |        at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore_4.4.15.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[httpcore_4.4.15.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[httpcore_4.4.15.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[httpclient_4.5.13.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient_4.5.13.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore_4.4.15.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore_4.4.15.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[httpclient_4.5.13.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore_4.4.15.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore_4.4.15.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient_4.5.13.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient_4.5.13.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient_4.5.13.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient_4.5.13.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient_4.5.13.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient_4.5.13.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient_4.5.13.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient_4.5.13.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.validateAPIDefinitionByURL_aroundBody64(OASParserUtil.java:1022) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.apimgt.impl.definitions.OASParserUtil.validateAPIDefinitionByURL(OASParserUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.apimgt.impl.restapi.publisher.ApisApiServiceImplUtils.validateOpenAPIDefinition_aroundBody20(ApisApiServiceImplUtils.java:610) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.apimgt.impl.restapi.publisher.ApisApiServiceImplUtils.validateOpenAPIDefinition(ApisApiServiceImplUtils.java:1) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.validateOpenAPIDefinition(ApisApiServiceImpl.java:3491) ~[?:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.validateOpenAPIDefinition(ApisApiServiceImpl.java:2736) ~[?:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.validateOpenAPIDefinition(ApisApi.java:1814) ~[?:?]
platform-backend-apimanager-1  |        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
platform-backend-apimanager-1  |        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
platform-backend-apimanager-1  |        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
platform-backend-apimanager-1  |        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) ~[?:?]
platform-backend-apimanager-1  |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-servlet-api_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[?:?]
platform-backend-apimanager-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119) ~[org.wso2.carbon.identity.context.rewrite.valve_1.7.1.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:116) ~[org.wso2.carbon.identity.context.rewrite.valve_1.7.1.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:165) ~[org.wso2.carbon.identity.authz.valve_1.7.1.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:111) ~[org.wso2.carbon.identity.auth.valve_1.7.1.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
platform-backend-apimanager-1  |        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
platform-backend-apimanager-1  |        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
platform-backend-apimanager-1  |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat_9.0.58.wso2v1.jar:?]
platform-backend-apimanager-1  |        at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Related Issues

The log also shows:
```
The latest update level is 'wso2am-4.2.0.31'. 
platform-backend-apimanager-1  | This consists of 124 updates
platform-backend-apimanager-1  | applied on top of 'wso2am-4.2.0.0'
platform-backend-apimanager-1  | [WARNING] 
platform-backend-apimanager-1  |  The update level
platform-backend-apimanager-1  | 'wso2am-4.2.0.31' consists of 15 critical security updates applied on top of
platform-backend-apimanager-1  | 'wso2am-4.2.0.0'. 
platform-backend-apimanager-1  | WSO2 strongly recommends to use 'wso2am-4.2.0.31'
platform-backend-apimanager-1  | distribution in production as soon as possible.
```
But haven't found anything in github for that version...

**Comment by LuisMalhadas** [comment]
Issue was on my backend. 
Sorry
