### ISSUE TITLE
NativeWorkerPool Uncaught Exception in Workflow Subscription

### ISSUE THREAD

**Issue by veneerac** [wso2/api-manager#2188]
### Description

Issue when create the work flow approval. When we try to approve a workflow, we're getting an error about a 'null point'. Here’s the error:

### Steps to Reproduce

1. We add an API Subscription Workflow (you can see how in document [1]).
2. When we approve the workflow we've made, we get the error I've shown above.

### Affected Component

Analytics

### Version

4.2.0 (level 27)

### Relevant Log Output

```shell
ERROR - NativeWorkerPool Uncaught exception
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
	at org.wso2.carbon.apimgt.keymgt.SubscriptionDataHolder.getTenantSubscriptionStore_aroundBody8(SubscriptionDataHolder.java:68) ~[org.wso2.carbon.apimgt.keymgt_9.28.116.55.jar:?]
	at org.wso2.carbon.apimgt.keymgt.SubscriptionDataHolder.getTenantSubscriptionStore(SubscriptionDataHolder.java:1) ~[org.wso2.carbon.apimgt.keymgt_9.28.116.55.jar:?]
	at org.wso2.carbon.apimgt.keymgt.service.KeyManagerDataServiceImpl.addOrUpdateSubscription_aroundBody4(KeyManagerDataServiceImpl.java:95) ~[org.wso2.carbon.apimgt.keymgt_9.28.116.55.jar:?]
	at org.wso2.carbon.apimgt.keymgt.service.KeyManagerDataServiceImpl.addOrUpdateSubscription(KeyManagerDataServiceImpl.java:1) ~[org.wso2.carbon.apimgt.keymgt_9.28.116.55.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:220) ~[org.wso2.carbon.apimgt.gateway_9.28.116.55.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.116.55.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:115) ~[org.wso2.carbon.apimgt.gateway_9.28.116.55.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.116.55.jar:?]
	at org.wso2.carbon.apimgt.common.jms.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:656) ~[org.wso2.carbon.apimgt.common.jms_9.28.116.jar:?]
	at org.wso2.carbon.apimgt.common.jms.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:555) ~[org.wso2.carbon.apimgt.common.jms_9.28.116.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v83_2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by YasasRangika** [comment]
This issue does not affect the master branch.
