### ISSUE TITLE
[APIM][420] Issue configuring ELK based Analytics for Public API 

### ISSUE THREAD

**Issue by kaushi2142** [wso2/api-manager#2200]
### Description

When ELK based Analytics is configured in APIM and a public API (security disabled) is invoked, the following error occurs:

`TID: [] [] [2023-09-22 08:57:52,898] ERROR {org.wso2.carbon.apimgt.common.analytics.publishers.impl.AbstractRequestDataPublisher} - Error occurred when publishing event. org.wso2.am.analytics.publisher.exception.MetricReportingException: userName is missing in metric data. This metric event will not be processed further.`

### Steps to Reproduce

Steps to recreate:

1. Configure ELK Analytics in APIM 4.2.0:
 ```
 [apim.analytics]
 enable = true
 type = "elk" 
 ```
2. Publish the Pizzashack API and turn off Security in the GET /menu resource
3. Deploy a new revision
4. . Invoke GET `https://localhost:8243/pizzashack/1.0.0/menu`
5. We get the below error:

```
[2023-09-26 14:48:27,460] ERROR - AbstractRequestDataPublisher Error occurred when publishing event.
org.wso2.am.analytics.publisher.exception.MetricReportingException: userName is missing in metric data. This metric event will not be processed further.
	at org.wso2.am.analytics.publisher.reporter.elk.ELKMetricEventBuilder.validate(ELKMetricEventBuilder.java:79) ~[org.wso2.am.analytics.publisher.client_1.2.3.jar:?]
	at org.wso2.am.analytics.publisher.reporter.AbstractMetricEventBuilder.build(AbstractMetricEventBuilder.java:32) ~[org.wso2.am.analytics.publisher.client_1.2.3.jar:?]
	at org.wso2.am.analytics.publisher.reporter.elk.ELKCounterMetric.incrementCount(ELKCounterMetric.java:49) ~[org.wso2.am.analytics.publisher.client_1.2.3.jar:?]
	at org.wso2.carbon.apimgt.common.analytics.publishers.impl.AbstractRequestDataPublisher.publish(AbstractRequestDataPublisher.java:73) ~[org.wso2.carbon.apimgt.common.analytics_9.28.116.jar:?]
	at org.wso2.carbon.apimgt.common.analytics.collectors.impl.SuccessRequestDataCollector.collectData(SuccessRequestDataCollector.java:95) ~[org.wso2.carbon.apimgt.common.analytics_9.28.116.jar:?]
	at org.wso2.carbon.apimgt.common.analytics.collectors.impl.GenericRequestDataCollector.collectData(GenericRequestDataCollector.java:46) ~[org.wso2.carbon.apimgt.common.analytics_9.28.116.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.AnalyticsMetricsHandler.handleResponseOutFlow_aroundBody8(AnalyticsMetricsHandler.java:95) ~[org.wso2.carbon.apimgt.gateway_9.28.116.55.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.AnalyticsMetricsHandler.handleResponseOutFlow(AnalyticsMetricsHandler.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.116.55.jar:?]
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:188) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:574) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:123) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.api.Resource.process(Resource.java:342) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.api.API.process(API.java:416) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:108) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:128) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:55) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:63) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:346) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:642) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:218) ~[synapse-core_4.0.0.wso2v20_15.jar:4.0.0-wso2v20.15]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v83_2.jar:?]
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:338) ~[synapse-nhttp-transport_4.0.0.wso2v20_12.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v83_2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

Update level : 4.2.0.35

**Comment by BilawalDildar-ETEC** [comment]
@RusJaI & @kaushikobbekaduwa  Can you please share the steps how to fix this.
org.wso2.am.analytics.publisher.exception.MetricReportingException: userName is missing in metric data. This metric event will not be processed further.
If you share all steps it would be better.
