### ISSUE TITLE
java 17 build failure

### ISSUE THREAD

**Issue by Et7f3** [wso2/api-manager#2232]
### Description

[The section https://github.com/wso2/product-apim#system-requirements
describe "Java 11 or higher"](https://github.com/wso2/product-apim/blob/fa4423ede7ffc3e0964fe1a667f790bede2fce58/README.md?plain=1#L194)

So I expect to build it with jdk17

### Steps to Reproduce

git clone https://gist.github.com/Et7f3/b663ec7788e09415fa4cfaf0c6c3e83f build_failure
cd build_failure
vagrant up --provider=libvirt

# this is to copy to gist stdout.log
vagrant ssh -c 'cd product-apim; ../demo.sh' | xclip -selection clipboard

You can also do:
vagrant ssh
# inside shell
cd product-apim
# debug
../demo.sh

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

centos9s vagrant box (for full reproduction)

### Relevant Log Output

```shell
[[1;34mINFO[m] Command line:
	[/usr/lib/jvm/java-17-openjdk-17.0.6.0.10-3.el9.x86_64/bin/java, -jar, /home/vagrant/.m2/repository/org/eclipse/tycho/tycho-bundles-external/0.25.0/eclipse/plugins/org.eclipse.equinox.launcher_1.3.200.v20151021-1308.jar, -configuration, /tmp/tycho-p2-runtime6436111613025920233.tmp/configuration, -nosplash, -application, org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher, -source, /home/vagrant/product-apim/modules/p2-profile/product/target/tmp.1697732341842/featureExtract, -metadataRepository, file:/home/vagrant/product-apim/modules/p2-profile/product/target/p2-repo, -metadataRepositoryName, am-p2-profile, -artifactRepository, file:/home/vagrant/product-apim/modules/p2-profile/product/target/p2-repo, -artifactRepositoryName, am-p2-profile, -publishArtifacts, -publishArtifactRepository, -compress, -append]
java.lang.ExceptionInInitializerError
	at org.eclipse.osgi.storage.Storage.<init>(Storage.java:100)
	at org.eclipse.osgi.storage.Storage.createStorage(Storage.java:87)
	at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:66)
	at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:31)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:303)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:239)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:670)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:609)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1516)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1489)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @396a51ab
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.findMethod(FrameworkExtensionInstaller.java:51)
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.findMethod(FrameworkExtensionInstaller.java:58)
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.findAddURLMethod(FrameworkExtensionInstaller.java:42)
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.<clinit>(FrameworkExtensionInstaller.java:36)
	... 14 more
An error has occurred. See the log file
null.
[[1;31mERROR[m] P2 publisher return code was 13
[1;31morg.apache.maven.plugin.MojoFailureException[m: [1;31mP2 publisher return code was 13[m
    [1mat[m org.wso2.maven.p2.RepositoryGenMojo.generateRepository ([1mRepositoryGenMojo.java:255[m)
    [1mat[m org.wso2.maven.p2.RepositoryGenMojo.createRepo ([1mRepositoryGenMojo.java:204[m)
    [1mat[m org.wso2.maven.p2.RepositoryGenMojo.execute ([1mRepositoryGenMojo.java:191[m)
    [1mat[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo ([1mDefaultBuildPluginManager.java:137[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:210[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:156[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:148[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:117[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:81[m)
    [1mat[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build ([1mSingleThreadedBuilder.java:56[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute ([1mLifecycleStarter.java:128[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:305[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:192[m)
    [1mat[m org.apache.maven.DefaultMaven.execute ([1mDefaultMaven.java:105[m)
    [1mat[m org.apache.maven.cli.MavenCli.execute ([1mMavenCli.java:957[m)
    [1mat[m org.apache.maven.cli.MavenCli.doMain ([1mMavenCli.java:289[m)
    [1mat[m org.apache.maven.cli.MavenCli.main ([1mMavenCli.java:193[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([1mNative Method[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([1mNativeMethodAccessorImpl.java:77[m)
    [1mat[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([1mDelegatingMethodAccessorImpl.java:43[m)
    [1mat[m java.lang.reflect.Method.invoke ([1mMethod.java:568[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([1mLauncher.java:282[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launch ([1mLauncher.java:225[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([1mLauncher.java:406[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.main ([1mLauncher.java:347[m)
```

**Comment by gspadotto** [comment]
Try setting the environment variable as described in https://github.com/wso2/micro-integrator/issues/3154
