### ISSUE TITLE
Throws a Nullpointerexception (Npe) Exception When a User Credential or SSL Error Is Thrown.

### ISSUE THREAD

**Issue by Abshan** [wso2/api-manager#2323]
### Description

When APIM-3.2.0 is configured with the APIM-Analytics 3.2.0 version, during the connection establishment process with the Analytics auth URL (ssl://localhost:7711) if an "DataEndpointLoginException" is thrown, the following NPE exception would get printed in the carbon.logs without a proper cause for the error message.

```
ERROR - APIMgtUsageDataBridgeDataPublisher Error initializing APIMgtUsageDataBridgeDataPublisher
java.lang.NullPointerException: null
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.runConnection(DataEndpointConnectionWorker.java:124) ~[org.wso2.carbon.databridge.agent_5.2.26.10.jar:?]
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpoint.connect(DataEndpoint.java:163) ~[org.wso2.carbon.databridge.agent_5.2.26.10.jar:?]
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpoint.initialize(DataEndpoint.java:193) ~[org.wso2.carbon.databridge.agent_5.2.26.10.jar:?]
	at org.wso2.carbon.databridge.agent.DataPublisher.processEndpoints(DataPublisher.java:204) ~[org.wso2.carbon.databridge.agent_5.2.26.10.jar:?]
	at org.wso2.carbon.databridge.agent.DataPublisher.<init>(DataPublisher.java:128) ~[org.wso2.carbon.databridge.agent_5.2.26.10.jar:?]
	at org.wso2.carbon.apimgt.usage.publisher.APIMgtUsageDataBridgeDataPublisher.getDataPublisher(APIMgtUsageDataBridgeDataPublisher.java:117) ~[org.wso2.carbon.apimgt.usage.publisher_6.7.206.19.jar:?]
	at org.wso2.carbon.apimgt.usage.publisher.APIMgtUsageDataBridgeDataPublisher.init(APIMgtUsageDataBridgeDataPublisher.java:48) [org.wso2.carbon.apimgt.usage.publisher_6.7.206.19.jar:?]
```
The "DataEndpointLoginException" can get thrown for scenarios like invalid credentials defined on either side (APIM or Analytics) or a certificate issue (missing certificate). For all these scenarios the same NPE exception gets thrown.

This needs to be fixed with proper exception handling.

### Steps to Reproduce

1. Configure APIM analytics 3.2 with APIM 3.2.0 version.
2. Configure invalid credentials on either side.
3. Start the Analytics worker server first, and then the APIM server.
4. The above mentioned error log would get printed during the startup logs.

### Affected Component

APIM

### Version

3.2.0

**Comment by npamudika** [comment]
@sgayangi Please mention the public PR

**Comment by npamudika** [comment]
Fixed via https://github.com/wso2/carbon-analytics-common/pull/817

**Comment by ShavinAnjithaAlpha** [comment]
The reported NPE originates from `APIMgtUsageDataBridgeDataPublisher.java`, which handled the legacy Stream Processor (SP)-based analytics publishing path. That class was removed from `carbon-apimgt` entirely in commit [`91d4b08438a2`](https://github.com/wso2/carbon-apimgt/commit/91d4b08438a2) ("Remove SP based analytics", 2021-02-21), as part of decommissioning SP-based analytics in favor of the newer analytics architecture. 

The deletion commit is a confirmed git ancestor of all three, and of current master. So the exact code path described in this issue does not exist in 4.5.0, 4.6.0, 4.7.0, or later.
                                                                              
No other component reintroduces this pattern for analytics publishing, so this is resolved as a side effect of the SP-analytics removal rather than a targeted fix. Closing as not applicable to 4.5.0+.
