### ISSUE TITLE
Secured connection between GW and the TM when publishing throttle data.

### ISSUE THREAD

**Issue by JanithaSampathBandara** [wso2/api-manager#2366]
### Description

Hi All,

It's unable to make the GW to TM binary connection with full SSL encryption. Modified configurations as follows.

```
[[apim.analytics.url_group]]
analytics_url =["ssl://localhost:9711"]
analytics_auth_url =["ssl://localhost:9711"]
```

```
[[apim.throttling.url_group]]
traffic_manager_urls = ["ssl://localhost:9711"]
traffic_manager_auth_urls = ["ssl://localhost:9711"]
```

Our default recommendations are similar to the following and we are using the port 9611 to push data via TCP protocol.

```
[[apim.analytics.url_group]]
analytics_url =["tcp://localhost:9611"]
analytics_auth_url =["ssl://localhost:9711"]
```

```
[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9611"]
traffic_manager_auth_urls = ["ssl://localhost:9711"]
```

When it comes to the above modified configurations with fully TCP-SSL protocol the following error can be seen in the TM node.

```
ERROR - BinaryDataReceiver Error while reading from the socket.
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1575) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1405) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1305) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:818) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.access$200(SSLSocketImpl.java:73) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:909) ~[?:1.8.0_362]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_362]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[?:1.8.0_362]
	at org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver$BinaryTransportReceiver.run(BinaryDataReceiver.java:255) [org.wso2.carbon.databridge.receiver.binary_5.2.34.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_362]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167) ~[?:1.8.0_362]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1397) ~[?:1.8.0_362]
	... 13 more
```

This was tested with the thrift protocol as well and observed similar behaviour when both the URLs were configured under the TCP-SSL protocol.

```
ERROR - TThreadPoolServer Thrift Error occurred during processing of message.
org.apache.thrift.transport.TTransportException: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:178) ~[libthrift_0.14.0.wso2v1.jar:?]
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:109) ~[libthrift_0.14.0.wso2v1.jar:?]
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:463) ~[libthrift_0.14.0.wso2v1.jar:?]
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:361) ~[libthrift_0.14.0.wso2v1.jar:?]
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:244) ~[libthrift_0.14.0.wso2v1.jar:?]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27) ~[libthrift_0.14.0.wso2v1.jar:?]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248) [libthrift_0.14.0.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1575) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1405) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1305) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:818) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.access$200(SSLSocketImpl.java:73) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:909) ~[?:1.8.0_362]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_362]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_362]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_362]
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:176) ~[libthrift_0.14.0.wso2v1.jar:?]
	... 9 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167) ~[?:1.8.0_362]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1397) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1305) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:818) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.access$200(SSLSocketImpl.java:73) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:909) ~[?:1.8.0_362]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_362]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_362]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_362]
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:176) ~[libthrift_0.14.0.wso2v1.jar:?]
	... 9 more
```

### Steps to Reproduce

In a TM separated distributed setup, add below configurations in the GW's deployment.toml file and restart the GW.

```
[[apim.analytics.url_group]]
analytics_url =["ssl://localhost:9711"]
analytics_auth_url =["ssl://localhost:9711"]
```

```
[[apim.throttling.url_group]]
traffic_manager_urls = ["ssl://localhost:9711"]
traffic_manager_auth_urls = ["ssl://localhost:9711"]
```

### Affected Component

APIM

### Version

4.0.0

**Comment by Avishka-Shamendra** [comment]
Hi all,

Closing this as public fix has been added through https://github.com/wso2/carbon-analytics-common/commit/fa1755eb66b352b479ce4cdf9012289d9084351e

Thank you
Avishka
