### ISSUE TITLE
[APIM Analytics 3.2.0] OSGI issue when starting the APIM Analytics 3.2.0 worker

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/api-manager#2368]
### Description

The following OSGI issue occurs when trying to start the APIM Analytics 3.2.0 worker profile.

```
[2024-01-09 14:49:59,290]  INFO {org.ops4j.pax.logging.spi.support.EventAdminConfigurationNotifier} - Logging configuration changed. (Event Admin service unavailable - no notification sent).
org.osgi.framework.BundleException: Could not resolve module: msf4j-analytics [48]
  Unresolved requirement: Import-Package: org.wso2.carbon.config; version="[2.1.5,3.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.startBundles(ConfigApplier.java:453)
	at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.install(ConfigApplier.java:111)
	at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:191)
	at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:205)
	at org.eclipse.equinox.internal.simpleconfigurator.Activator.start(Activator.java:60)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:724)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:932)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.wso2.carbon.launcher.CarbonServer.loadInitialBundles(CarbonServer.java:242)
	at org.wso2.carbon.launcher.CarbonServer.start(CarbonServer.java:83)
	at org.wso2.carbon.launcher.Main.main(Main.java:84)
org.osgi.framework.BundleException: Could not resolve module: msf4j-core [49]
  Unresolved requirement: Import-Package: org.wso2.carbon.kernel.startupresolver; version="[5.0.0,6.0.0)"
    -> Export-Package: org.wso2.carbon.kernel.startupresolver; bundle-symbolic-name="org.wso2.carbon.core"; bundle-version="5.2.12"; version="5.2.12"
       org.wso2.carbon.core [89]
         Unresolved requirement: Import-Package: org.wso2.carbon.config.annotation; version="[2.0.0,3.0.0)"
  Unresolved requirement: Import-Package: org.wso2.carbon.kernel.config.model; version="[5.0.0,6.0.0)"
    -> Export-Package: org.wso2.carbon.kernel.config.model; bundle-symbolic-name="org.wso2.carbon.core"; bundle-version="5.2.12"; version="5.2.12"; uses:="javax.xml.bind.annotation,org.wso2.carbon.config.annotation"
```

### Steps to Reproduce

Start the APIM Analytics 3.2.0 worker profile.

### Affected Component

Analytics

### Version

3.2.0

**Comment by HeshanSudarshana** [comment]
Hi all,

Closing the issue since the update is released with the fix.

Thanks,
Heshan
