### ISSUE TITLE
Error in a Custom UniqueId Secondary Store

### ISSUE THREAD

**Issue by PrabodDunuwila** [wso2/api-manager#2422]
### Description

Hi all,

Observing the below error when developing a custom uniqueId secondary user store in APIM 4.2.0.
```
ERROR {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Error occurred while accessing Java Security Manager Privilege Block when called by method getUserClaimValuesWithID with 3 length of Objects and argTypes [class java.lang.String, class [Ljava.lang.String;, class java.lang.String] java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
        at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:237)
        at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValuesWithID(AbstractUserStoreManager.java:12119)
        at org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler.retrieveAllNunNullUserClaimValues(DefaultClaimHandler.java:645)
        at org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler.handleLocalClaims(DefaultClaimHandler.java:482)

Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:240)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        ... 65 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.wso2.carbon.user.core.common.UserUniqueIDDomainResolver.getDomainForUserId(String, int)
```
As observed, a null check to check the userUniqueIDDomainResolver is not available in the APIM 4.2.0 version.

Thanks,
Prabod.

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.2.0

**Comment by HeshanSudarshana** [comment]
Closing the issue since the update is released and the public fix is merged.
