### ISSUE TITLE
WSO2 APIM 3.2 is error: org.wso2.carbon.registry.RegistryException

### ISSUE THREAD

**Issue by bocamap** [wso2/api-manager#2440]
### Description

ERROR {org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO} - Failed to remove properties from resource version 392374. ORA-00060: deadlock detected while waiting for resource
java.sql.BatchUpdateException: ORA-00060: deadlock detected while waiting for resource

        at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:12296)
        at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:246)
        at sun.reflect.GeneratedMethodAccessor194.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy49.executeBatch(Unknown Source)
        at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.removeProperties(JDBCResourceDAO.java:1798)
        at org.wso2.carbon.registry.core.jdbc.Repository.removeResource(Repository.java:624)
        at org.wso2.carbon.registry.core.jdbc.Repository.deleteNode(Repository.java:580)
        at org.wso2.carbon.registry.core.jdbc.Repository.deleteSubTree(Repository.java:542)
        at org.wso2.carbon.registry.core.jdbc.Repository.delete(Repository.java:455)
        at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.delete(EmbeddedRegistry.java:855)
        at org.wso2.carbon.registry.core.session.UserRegistry.deleteInternal(UserRegistry.java:879)
        at org.wso2.carbon.registry.core.session.UserRegistry.access$1100(UserRegistry.java:73)
        at org.wso2.carbon.registry.core.session.UserRegistry$12.run(UserRegistry.java:854)
        at org.wso2.carbon.registry.core.session.UserRegistry$12.run(UserRegistry.java:851)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.wso2.carbon.registry.core.session.UserRegistry.delete(UserRegistry.java:851)
        at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.delete(MountHandler.java:508)
        at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.delete(HandlerManager.java:2629)
        at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.delete(UserDefinedHandlerManager.java:214)
        at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.delete(HandlerLifecycleManager.java:443)
        at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.delete(EmbeddedRegistry.java:851)
        at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.delete(CacheBackedRegistry.java:595)
        at org.wso2.carbon.registry.core.session.UserRegistry.deleteInternal(UserRegistry.java:879)
        at org.wso2.carbon.registry.core.session.UserRegistry.access$1100(UserRegistry.java:73)
        at org.wso2.carbon.registry.core.session.UserRegistry$12.run(UserRegistry.java:854)
        at org.wso2.carbon.registry.core.session.UserRegistry$12.run(UserRegistry.java:851)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.wso2.carbon.registry.core.session.UserRegistry.delete(UserRegistry.java:851)
        at org.wso2.carbon.andes.commons.registry.RegistryClient.deleteQueue(RegistryClient.java:140)

### Affected Component

APIM

### Version

3.2

### Environment Details (with versions)

linux

### Suggested Labels

WSO2 APIM RegistryException deadlock

**Comment by chamilaadhi** [comment]
Do you have any reproducing steps for this?
