### ISSUE TITLE
Revision Deployment failed with the ERROR : No endpoint exists by the key/name : PizzaShackAPI--v1.0.0_APIsandboxEndpoint

### ISSUE THREAD

**Issue by cbabey** [wso2/api-manager#2484]
### Description

Intermittent failures in deploying API revisions by throwing the following error trace. This issue is causing 404 error responses for their API calls, and a server restart is necessary to recover from this state.

```
[2024-02-09 13:51:31,262] ERROR - EndpointAdminServiceProxy Error deleting endpoint from gateway
org.apache.synapse.SynapseException: No endpoint exists by the key/name : PizzaShackAPI--v1.0.0_APIsandboxEndpoint
	at org.apache.synapse.config.SynapseConfiguration.handleException(SynapseConfiguration.java:1823) ~[synapse-core_2.1.7.wso2v227_66.jar:2.1.7-wso2v227.66]
	at org.apache.synapse.config.SynapseConfiguration.removeEndpoint(SynapseConfiguration.java:1241) ~[synapse-core_2.1.7.wso2v227_66.jar:2.1.7-wso2v227.66]
	at org.wso2.carbon.endpoint.service.EndpointAdmin.deleteEndpoint(EndpointAdmin.java:292) ~[org.wso2.carbon.endpoint_4.7.99.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint_aroundBody2(EndpointAdminServiceProxy.java:82) [org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint(EndpointAdminServiceProxy.java:76) [org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:710) [org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:654) [org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:91) [org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:81) [org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run_aroundBody0(GatewayJMSMessageListener.java:178) [org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run(GatewayJMSMessageListener.java:152) [org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_392-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_392-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_392-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_392-internal]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392-internal]
[2024-02-09 13:51:31,315] ERROR - InMemoryAPIDeployer Error deploying b422d4e9-fc66-4bfe-b083-2d5797c1cd0d in Gateway
org.apache.axis2.AxisFault: Error while deleting the endpoint fileNo endpoint exists by the key/name : PizzaShackAPI--v1.0.0_APIsandboxEndpoint
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint_aroundBody2(EndpointAdminServiceProxy.java:88) ~[org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint(EndpointAdminServiceProxy.java:76) ~[org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:710) ~[org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:654) ~[org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:91) [org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:81) [org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run_aroundBody0(GatewayJMSMessageListener.java:178) [org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run(GatewayJMSMessageListener.java:152) [org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_392-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_392-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_392-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_392-internal]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392-internal]
Caused by: org.apache.synapse.SynapseException: No endpoint exists by the key/name : PizzaShackAPI--v1.0.0_APIsandboxEndpoint
	at org.apache.synapse.config.SynapseConfiguration.handleException(SynapseConfiguration.java:1823) ~[synapse-core_2.1.7.wso2v227_66.jar:2.1.7-wso2v227.66]
	at org.apache.synapse.config.SynapseConfiguration.removeEndpoint(SynapseConfiguration.java:1241) ~[synapse-core_2.1.7.wso2v227_66.jar:2.1.7-wso2v227.66]
	at org.wso2.carbon.endpoint.service.EndpointAdmin.deleteEndpoint(EndpointAdmin.java:292) ~[org.wso2.carbon.endpoint_4.7.99.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.EndpointAdminServiceProxy.deleteEndpoint_aroundBody2(EndpointAdminServiceProxy.java:82) ~[org.wso2.carbon.apimgt.gateway_9.0.174.375.jar:?]
	... 12 more
```

### Steps to Reproduce

1. Create an API and add a 1s delay to the API using a custom in-sequence mediation as mentioned above. 
2. Download the attached Jmeter script. 
3.  Details that are required to execute the Jmeter script
  3.1 Generate access token to invoke the Publisher portal Rest API with the apim:api_create apim:api_publish apim:api_import_export scops.
  3.2 Generate the access token to invoke the Published API. 
  3.3  Get the UUID of the published API 

4. First start the Jmeter script by only enabling `Deploy_New_API_Revision` thread group and disable the `Invoke_API` thread group then run it around 2 to 3 minutes. 
		(it will create multiple revisions and the event will be queued in the MB and the GW component will pick the events one by one and redeploy the revisions)
5. Then rerun the Jmeter script again by enabling the `Invoke_API` thread group and disabling the `Deploy_New_API_Revision`.

### Affected Component

APIM

### Version

4.0.0

**Comment by tharikaGitHub** [comment]
The public fixes are :

1. https://github.com/wso2/wso2-synapse/pull/2158
2. https://github.com/wso2/carbon-mediation/pull/1707
3. https://github.com/wso2/carbon-apimgt/pull/12308
