### ISSUE TITLE
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MB_EXCHANGE" not found when running the pack for a long time

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/api-manager#2503]
### Description

The following error can be seen when the pack has been running for a long time. This can be seen in both the all-in-one and distributed setups.

```
TID: [] Tenant: [] [2024-02-22 00:25:21,366] [] : apim-gw : ERROR {org.wso2.andes.kernel.disruptor.LogExceptionHandler} - [ Sequence: 54972 ] Exception occurred while processing inbound events. 
org.wso2.andes.kernel.AndesException: Error occurred while retrieving all exchange information. 
    at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertSQLException(RDBMSStoreUtils.java:132) ~[andes_3.3.28.jar:?]
    at org.wso2.andes.store.rdbms.RDBMSAndesContextStoreImpl.getAllMessageRoutersStored(RDBMSAndesContextStoreImpl.java:811) ~[andes_3.3.28.jar:?]
    at org.wso2.andes.store.FailureObservingAndesContextStore.getAllMessageRoutersStored(FailureObservingAndesContextStore.java:326) ~[andes_3.3.28.jar:?]
    at org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent.reloadMessageRoutersFromDB(InboundDBSyncRequestEvent.java:111) ~[andes_3.3.28.jar:?]
    at org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent.updateState(InboundDBSyncRequestEvent.java:73) ~[andes_3.3.28.jar:?]
    at org.wso2.andes.kernel.disruptor.inbound.InboundEventContainer.updateState(InboundEventContainer.java:268) ~[andes_3.3.28.jar:?]
    at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:70) ~[andes_3.3.28.jar:?]
    at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:40) ~[andes_3.3.28.jar:?]
    at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [disruptor_3.4.2.wso2v1.jar:?]
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [disruptor_3.4.2.wso2v1.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MB_EXCHANGE" not found; SQL statement:
SELECT EXCHANGE_DATA FROM MB_EXCHANGE [42102-224]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:514) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:489) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.message.DbException.get(DbException.java:223) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.message.DbException.get(DbException.java:199) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8064) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8035) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.readTableOrView(Parser.java:8024) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.readTablePrimary(Parser.java:1788) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.readTableReference(Parser.java:2268) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.parseSelectFromPart(Parser.java:2718) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.parseSelect(Parser.java:2824) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.parseQueryPrimary(Parser.java:2708) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.parseQueryTerm(Parser.java:2564) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2543) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2536) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.parseQueryExpression(Parser.java:2529) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.parseQuery(Parser.java:2498) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.parsePrepared(Parser.java:627) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.parse(Parser.java:592) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.parse(Parser.java:564) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.command.Parser.prepareCommand(Parser.java:483) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:559) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:93) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:316) ~[h2-engine_2.2.224.wso2v2.jar:?]
    at jdk.internal.reflect.GeneratedMethodAccessor64.invoke(Unknown Source) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
    at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:131) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:75) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:75) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:158) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:39) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:75) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
    at jdk.proxy6.$Proxy52.prepareStatement(Unknown Source)
```

### Steps to Reproduce

Run the 4.3.0 pack for some time

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
Closing the issue as the PR is merged.
