### ISSUE TITLE
Cannot access the Advanced search UI of the Management Console

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#2580]
### Description

When trying to access the Advanced search UI from the Management console, the UI goes blank as follows. 
<img width="270" alt="Screen Shot 2024-03-05 at 3 23 59 PM" src="https://github.com/wso2/api-manager/assets/8557410/bc8aeeab-4b13-4297-968c-c5d9f8b66655">
<img width="1512" alt="Screen Shot 2024-03-05 at 3 24 10 PM" src="https://github.com/wso2/api-manager/assets/8557410/ceb9a719-6d10-4faf-94e9-5607ed4a3d69">

And the following error get's logged in the terminal.

```
[2024-03-05 15:24:05,654] ERROR - [bridgeservlet] Servlet.service() for servlet [bridgeservlet] threw exception
org.apache.jasper.JasperException: Unable to compile class for JSP:

An error occurred at line: [636] in the generated java file: [/Users/tharikamadurapperuma/Documents/RnD/AfterVersionUpgrades/quicktest/wso2am-4.3.0-SNAPSHOT/lib/tomcat/work/Catalina/localhost/ROOT/proxytemp/hc_2126442517/org/apache/jsp/search/advancedSearch_jsp.java]
Syntax error, insert "while ( Expression ) ;" to complete DoStatement

An error occurred at line: [642] in the generated java file: [/Users/tharikamadurapperuma/Documents/RnD/AfterVersionUpgrades/quicktest/wso2am-4.3.0-SNAPSHOT/lib/tomcat/work/Catalina/localhost/ROOT/proxytemp/hc_2126442517/org/apache/jsp/search/advancedSearch_jsp.java]
Syntax error, insert "else Statement" to complete IfStatement

An error occurred at line: [642] in the generated java file: [/Users/tharikamadurapperuma/Documents/RnD/AfterVersionUpgrades/quicktest/wso2am-4.3.0-SNAPSHOT/lib/tomcat/work/Catalina/localhost/ROOT/proxytemp/hc_2126442517/org/apache/jsp/search/advancedSearch_jsp.java]
Syntax error, insert "}" to complete Block

Stacktrace:
	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102) ~[tomcat_9.0.85.wso2v1.jar:?]
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:214) ~[tomcat_9.0.85.wso2v1.jar:?]
	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:531) ~[tomcat_9.0.85.wso2v1.jar:?]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:398) ~[tomcat_9.0.85.wso2v1.jar:?]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:368) ~[tomcat_9.0.85.wso2v1.jar:?]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:352) ~[tomcat_9.0.85.wso2v1.jar:?]
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:603) ~[tomcat_9.0.85.wso2v1.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399) ~[tomcat_9.0.85.wso2v1.jar:?]
.
.
.
.
[2024-03-05 15:24:05,662] ERROR - [bridgeservlet] Servlet.service() for servlet [bridgeservlet] threw exception
java.lang.ClassNotFoundException: org.apache.jsp.search.advancedSearch_jsp
	at java.net.URLClassLoader.findClass(URLClassLoader.java:476) ~[?:?]
```

### Steps to Reproduce

1. Login to the Management Console
2. Click `Search` under the `Browse` button in the Resources tab

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
Closing as the issue is fixed with https://github.com/wso2/product-apim/pull/13426
