### ISSUE TITLE
Page crashes when user trying to generate access token with scopes using global key manager 

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2583]
### Description

Page crashes when user trying to generate access token with scopes using global key manager 

<img width="1499" alt="Screenshot 2024-03-06 at 12 36 12" src="https://github.com/wso2/api-manager/assets/54719880/d7267659-6ddc-40ef-8f28-c00803973c8e">

### Steps to Reproduce

Prerequisites
------------
1. Configure ISKM as global key manager
2. Create a tenant 
3. Deploy an API in super tenant and tenant publisher portals
4. Enable Cross tenant subcription

Steps
------
1. Login to publisher portal
2. create a local scope and assign to a resource of the particular API
3. Click Save and deploy 
4. Login to devportal
5. Create an Application 
6. Subscribe to the API
7. Navigate to OAuth2 tokens and select ISKM global key manager
8. Generate keys
9. Generate Access token

### Affected Component

APIM

### Version

4.3.0

### Relevant Log Output

```shell
[2024-03-06 12:18:59,446] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: Cannot invoke "feign.Response$Body.asInputStream()" because "httpResponse" is null
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.readHttpResponseAsString_aroundBody44(AMDefaultKeyManagerImpl.java:925) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.readHttpResponseAsString(AMDefaultKeyManagerImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.isScopeExists_aroundBody64(AMDefaultKeyManagerImpl.java:1140) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.isScopeExists(AMDefaultKeyManagerImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.updateResourceScopes_aroundBody56(AMDefaultKeyManagerImpl.java:1043) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.updateResourceScopes(AMDefaultKeyManagerImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.updateAPIResources_aroundBody62(APIProviderImpl.java:1014) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.updateAPIResources(APIProviderImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.updateAPI_aroundBody60(APIProviderImpl.java:962) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.updateAPI(APIProviderImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.updateAPI_aroundBody54(APIProviderImpl.java:847) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.updateAPI(APIProviderImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.updateAPI(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.29.45.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.PublisherCommonUtils.updateSwagger(PublisherCommonUtils.java:1415) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.29.45.SNAPSHOT.jar:?]
```

**Comment by chamilaadhi** [comment]
Tried this on the latest build but couldn't reproduce it

**Comment by chamilaadhi** [comment]
I have done a fix for scope related issue in global KM in https://github.com/wso2/api-manager/issues/2697 . This pr https://github.com/wso2/carbon-apimgt/pull/12361 fixes an issue related to the application keys loading page when scope is enabled. Please try this in the latest pack
