### ISSUE TITLE
Application with cross tenant subscription import fail through CURL command

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#2596]
### Description

Cross tenant subscription enabled application fail and throwing NPE during the import through the curl command.

```
ERROR - [2024-03-07 14:21:01,767] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[?:1.8.0_292]
at java.util.regex.Matcher.reset(Matcher.java:309) ~[?:1.8.0_292]
at java.util.regex.Matcher.(Matcher.java:229) ~[?:1.8.0_292]
at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[?:1.8.0_292]
at org.wso2.carbon.apimgt.impl.utils.APIUtil.removeXMediationScriptsFromSwagger_aroundBody616(APIUtil.java:8995) ~[org.wso2.carbon.apimgt.impl_9.0.174.393.jar:?]
at org.wso2.carbon.apimgt.impl.utils.APIUtil.removeXMediationScriptsFromSwagger(APIUtil.java:8991) ~[org.wso2.carbon.apimgt.impl_9.0.174.393.jar:?]
at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getOpenAPIDefinition_aroundBody226(APIConsumerImpl.java:5541) ~[org.wso2.carbon.apimgt.impl_9.0.174.393.jar:?]
at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getOpenAPIDefinition(APIConsumerImpl.java:5539) ~[org.wso2.carbon.apimgt.impl_9.0.174.393.jar:?]
at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getAPI_aroundBody10(AbstractAPIManager.java:458) ~[org.wso2.carbon.apimgt.impl_9.0.174.393.jar:?]
at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getAPI(AbstractAPIManager.java:426) ~[org.wso2.carbon.apimgt.impl_9.0.174.393.jar:?]
at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.getAPI_aroundBody22(UserAwareAPIConsumer.java:120) ~[org.wso2.carbon.apimgt.impl_9.0.174.393.jar:?]
at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.getAPI(UserAwareAPIConsumer.java:118) ~[org.wso2.carbon.apimgt.impl_9.0.174.393.jar:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.utils.ImportUtils.importSubscriptions(ImportUtils.java:190) ~[classes/:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl.applicationsImportPost(ApplicationsApiServiceImpl.java:258) ~[classes/:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.ApplicationsApi.applicationsImportPost(ApplicationsApi.java:470) ~[classes/:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.5.5.jar:3.5.5]
at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.5.5.jar:3.5.5]
at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.5.5.jar:3.5.5]
at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.5.5.jar:3.5.5]
at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.5.5.jar:3.5.5]
at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.5.5.jar:3.5.5]
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) [cxf-core-3.5.5.jar:3.5.5]
at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.5.5.jar:3.5.5]
at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) [cxf-rt-transports-http-3.5.5.jar:3.5.5]
at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.5.5.jar:3.5.5]
at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.5.5.jar:3.5.5]
at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.5.5.jar:3.5.5]
at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [cxf-rt-transports-http-3.5.5.jar:3.5.5]
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) [cxf-rt-transports-http-3.5.5.jar:3.5.5]
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) [cxf-rt-transports-http-3.5.5.jar:3.5.5]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) [tomcat-servlet-api_9.0.82.wso2v1.jar:?]
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) [cxf-rt-transports-http-3.5.5.jar:3.5.5]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) [tomcat_9.0.82.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [tomcat_9.0.82.wso2v1.jar:?]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat_9.0.82.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [tomcat_9.0.82.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [tomcat_9.0.82.wso2v1.jar:?]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168) [tomcat_9.0.82.wso2v1.jar:?]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [tomcat_9.0.82.wso2v1.jar:?]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) [tomcat_9.0.82.wso2v1.jar:?]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [tomcat_9.0.82.wso2v1.jar:?]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [tomcat_9.0.82.wso2v1.jar:?]
at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) [org.wso2.carbon.identity.context.rewrite.valve_1.4.25.jar:?]
```

### Steps to Reproduce

- Create environment with two tenants
- Create API in tenant one and enable visibility to all tenants
- Create application in tenant two and generate keys
- switch to tenant 1 and subscribe to the API using same app
- Export the application through curl command - 
 `curl -k -H "Authorization: Bearer 159d01a9-dea6-377a-bf67-1d5442568688" "https://localhost:9443/api/am/devportal/v2/applications/export?appName=Tenent2App&appOwner=user2@tenent2.com&withKeys=true" > Tenent2App.zip`
- Delete the application from the tenant 2
- Import the application using CURL command - 
 `curl -k -X POST -H "Authorization: Bearer 159d01a9-dea6-377a-bf67-1d5442568688" -F file=@[user2@tenent2.com-Tenent2App.zip](mailto:user2@tenent2.com-Tenent2App.zip) "https://localhost:9443/api/am/devportal/v2/applications/import?preserveOwner=true&skipSubscriptions=false&appOwner=USER2@TENENT2.COM&skipApplicationKeys=false&update=true"`

### Affected Component

APIM

### Version

4.0

**Comment by RusJaI** [comment]
Closing as issue is not reproducible in master branch
