### ISSUE TITLE
Update Dependency Package Version (Javax.Mail)

### ISSUE THREAD

**Issue by Abshan** [wso2/api-manager#2597]
### Description

Hi Team, 

With the recent fix [1] that has been released to update the javax.mail version in the axiom component, it has been changed to jakarta.mail as mentioned in the referenced link. However, this dependency version change has not been reflected in the` json-schema-validator-all_2.2.6.wso2v4` component, and when the JSON schema validator class is called, the following stack trace gets thrown,
```
Uncaught exception {org.apache.axis2.transport.base.threads.NativeWorkerPool}
java.lang.NoClassDefFoundError: javax/mail/internet/AddressException
	at com.github.fge.jsonschema.library.format.CommonFormatAttributesDictionary.<clinit>(CommonFormatAttributesDictionary.java:56)
	at com.github.fge.jsonschema.library.format.DraftV3FormatAttributesDictionary.<clinit>(DraftV3FormatAttributesDictionary.java:47)
	at com.github.fge.jsonschema.library.DraftV3Library.<clinit>(DraftV3Library.java:32)
	at com.github.fge.jsonschema.cfg.ValidationConfigurationBuilder.<clinit>(ValidationConfigurationBuilder.java:63)
	at com.github.fge.jsonschema.cfg.ValidationConfiguration.newBuilder(ValidationConfiguration.java:92)
	at com.github.fge.jsonschema.cfg.ValidationConfiguration.byDefault(ValidationConfiguration.java:102)
	at com.github.fge.jsonschema.main.JsonSchemaFactoryBuilder.<init>(JsonSchemaFactoryBuilder.java:68)
	at com.github.fge.jsonschema.main.JsonSchemaFactory.newBuilder(JsonSchemaFactory.java:123)
	at com.github.fge.jsonschema.main.JsonSchemaFactory.byDefault(JsonSchemaFactory.java:113)
	...
Caused by: java.lang.ClassNotFoundException: javax.mail.internet.AddressException cannot be found by json-schema-validator-all_2.2.6.wso2v4
```
The `javax.mail.*` dependency package and the version needs to be updated with the jakarta.mail package version.

[1] https://github.com/wso2/api-manager/issues/2171

### Steps to Reproduce

Calling the JSON Schema Validator

### Affected Component

APIM

### Version

2.6.0

**Comment by YasasRangika** [comment]
The fix for the master branch is already been added.
