### ISSUE TITLE
fn:replace command in the API mediation file is not working After U2 294

### ISSUE THREAD

**Issue by dilshanfardil** [wso2/api-manager#2690]
### Description

Hi Team,

When we use the replace function

```
<sequence name="sample-sequence" xmlns="http://ws.apache.org/ns/synapse">
      <property name="OriginalProperty" value="Test!value"/>
      <property name="modifiedProperty" expression="replace($ctx:OriginalProperty,'!','*')" xmlns:fn="http://www.w3.org/2005/xpath-functions" />
      <log level="custom">
            <property name="OriginalProperty__" expression="get-property('OriginalProperty')"/>
            <property name="modifiedProperty__" expression="get-property('modifiedProperty')"/>
      </log>
</sequence>
```

 we are getting this ERROR

```
ERROR {org.apache.synapse.util.xpath.SynapseXPath} - Evaluation of the XPath expression fn:replace($ctx:OriginalProperty,'!','*') resulted in an error
javax.xml.transform.TransformerException: DOM Synapse XPATH variable resolution failed
at com.sun.org.apache.xpath.internal.XPath.execute(XPath.java:370)
at com.sun.org.apache.xpath.internal.XPath.execute(XPath.java:307)
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:126)
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:100)
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:182)
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:227)
at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:656)
at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:489)
at org.apache.synapse.mediators.builtin.PropertyMediator.getResultValue(PropertyMediator.java:387)
at org.apache.synapse.mediators.builtin.PropertyMediator.mediate(PropertyMediator.java:125)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate_aroundBody0(APIManagerExtensionHandler.java:73)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate(APIManagerExtensionHandler.java:58)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest_aroundBody2(APIManagerExtensionHandler.java:90)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest(APIManagerExtensionHandler.java:79)
at org.apache.synapse.rest.API.process(API.java:391)
at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:146)
at org.apache.synapse.rest.RESTRequestHandler.identifyAPI(RESTRequestHandler.java:166)
at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:97)
at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:73)
at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:336)
at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99)
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:390)
at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:211)
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.synapse.SynapseException: DOM Synapse XPATH variable resolution failed
at org.apache.synapse.util.xpath.DOMSynapseXPathVariableResolver.resolveVariable(DOMSynapseXPathVariableResolver.java:31)
at com.sun.org.apache.xpath.internal.jaxp.JAXPVariableStack.getVariableOrParam(JAXPVariableStack.java:64)
at com.sun.org.apache.xpath.internal.operations.Variable.execute(Variable.java:221)
at com.sun.org.apache.xpath.internal.operations.Variable.execute(Variable.java:190)
at com.sun.org.apache.xpath.internal.functions.FuncExtFunction.execute(FuncExtFunction.java:201)
at com.sun.org.apache.xpath.internal.XPath.execute(XPath.java:341)
... 30 more
Caused by: org.jaxen.UnresolvableException: Variable OriginalProperty
at org.jaxen.SimpleVariableContext.getVariableValue(SimpleVariableContext.java:141)
at org.apache.synapse.util.xpath.SynapseXPathVariableContext.getVariableValue(SynapseXPathVariableContext.java:264)
at org.apache.synapse.util.xpath.DOMSynapseXPathVariableResolver.resolveVariable(DOMSynapseXPathVariableResolver.java:27)
... 35 more
---------
org.apache.synapse.SynapseException: DOM Synapse XPATH variable resolution failed
at org.apache.synapse.util.xpath.DOMSynapseXPathVariableResolver.resolveVariable(DOMSynapseXPathVariableResolver.java:31)
at com.sun.org.apache.xpath.internal.jaxp.JAXPVariableStack.getVariableOrParam(JAXPVariableStack.java:64)
at com.sun.org.apache.xpath.internal.operations.Variable.execute(Variable.java:221)
at com.sun.org.apache.xpath.internal.operations.Variable.execute(Variable.java:190)
at com.sun.org.apache.xpath.internal.functions.FuncExtFunction.execute(FuncExtFunction.java:201)
at com.sun.org.apache.xpath.internal.XPath.execute(XPath.java:341)
at com.sun.org.apache.xpath.internal.XPath.execute(XPath.java:307)
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:126)
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:100)
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:182)
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:227)
at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:656)
at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:489)
at org.apache.synapse.mediators.builtin.PropertyMediator.getResultValue(PropertyMediator.java:387)
at org.apache.synapse.mediators.builtin.PropertyMediator.mediate(PropertyMediator.java:125)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate_aroundBody0(APIManagerExtensionHandler.java:73)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate(APIManagerExtensionHandler.java:58)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest_aroundBody2(APIManagerExtensionHandler.java:90)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest(APIManagerExtensionHandler.java:79)
at org.apache.synapse.rest.API.process(API.java:391)
at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:146)
at org.apache.synapse.rest.RESTRequestHandler.identifyAPI(RESTRequestHandler.java:166)
at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:97)
at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:73)
at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:336)
at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99)
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:390)
at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:211)
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.jaxen.UnresolvableException: Variable OriginalProperty
at org.jaxen.SimpleVariableContext.getVariableValue(SimpleVariableContext.java:141)
at org.apache.synapse.util.xpath.SynapseXPathVariableContext.getVariableValue(SynapseXPathVariableContext.java:264)
at org.apache.synapse.util.xpath.DOMSynapseXPathVariableResolver.resolveVariable(DOMSynapseXPathVariableResolver.java:27)
... 35 more
--------------- linked to ------------------
javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: DOM Synapse XPATH variable resolution failed
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:195)
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:227)
at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:656)
at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:489)
at org.apache.synapse.mediators.builtin.PropertyMediator.getResultValue(PropertyMediator.java:387)
at org.apache.synapse.mediators.builtin.PropertyMediator.mediate(PropertyMediator.java:125)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate_aroundBody0(APIManagerExtensionHandler.java:73)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate(APIManagerExtensionHandler.java:58)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest_aroundBody2(APIManagerExtensionHandler.java:90)
at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest(APIManagerExtensionHandler.java:79)
at org.apache.synapse.rest.API.process(API.java:391)
at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:146)
at org.apache.synapse.rest.RESTRequestHandler.identifyAPI(RESTRequestHandler.java:166)
at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:97)
at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:73)
at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:336)
at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99)
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:390)
at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:211)
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.transform.TransformerException: DOM Synapse XPATH variable resolution failed
at com.sun.org.apache.xpath.internal.XPath.execute(XPath.java:370)
at com.sun.org.apache.xpath.internal.XPath.execute(XPath.java:307)
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:126)
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:100)
at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:182)
... 26 more
Caused by: org.apache.synapse.SynapseException: DOM Synapse XPATH variable resolution failed
at org.apache.synapse.util.xpath.DOMSynapseXPathVariableResolver.resolveVariable(DOMSynapseXPathVariableResolver.java:31)
at com.sun.org.apache.xpath.internal.jaxp.JAXPVariableStack.getVariableOrParam(JAXPVariableStack.java:64)
at com.sun.org.apache.xpath.internal.operations.Variable.execute(Variable.java:221)
at com.sun.org.apache.xpath.internal.operations.Variable.execute(Variable.java:190)
at com.sun.org.apache.xpath.internal.functions.FuncExtFunction.execute(FuncExtFunction.java:201)
at com.sun.org.apache.xpath.internal.XPath.execute(XPath.java:341)
... 30 more
Caused by: org.jaxen.UnresolvableException: Variable OriginalProperty
at org.jaxen.SimpleVariableContext.getVariableValue(SimpleVariableContext.java:141)
at org.apache.synapse.util.xpath.SynapseXPathVariableContext.getVariableValue(SynapseXPathVariableContext.java:264)
at org.apache.synapse.util.xpath.DOMSynapseXPathVariableResolver.resolveVariable(DOMSynapseXPathVariableResolver.java:27)
... 35 more
```

Thank You
Dilshan

### Steps to Reproduce

Create a sample API

Add this to the mediation sequence

```
<sequence name="sample-sequence" xmlns="http://ws.apache.org/ns/synapse">
      <property name="OriginalProperty" value="Test!value"/>
      <property name="modifiedProperty" expression="replace($ctx:OriginalProperty,'!','*')" xmlns:fn="http://www.w3.org/2005/xpath-functions" />
      <log level="custom">
            <property name="OriginalProperty__" expression="get-property('OriginalProperty')"/>
            <property name="modifiedProperty__" expression="get-property('modifiedProperty')"/>
      </log>
</sequence>
```

### Affected Component

APIM

### Version

3.2.0

**Comment by Lakith-Rambukkanage** [comment]
Fixed for issue https://github.com/wso2/product-apim/issues/8197 by PR : https://github.com/wso2/product-apim/pull/9129
