### ISSUE TITLE
NPE occur when using respond mediator in request flow sequence and choreo analytics enabled

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#2694]
### Description

NPE has occurred when using the respond mediator within the request mediation flow.

```
[2024-03-20 06:04:52,813] ERROR - AnalyticsMetricsHandler Error Occurred when collecting data
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.SynapseAnalyticsDataProvider.getBackendLatency_aroundBody54(SynapseAnalyticsDataProvider.java:390) ~[org.wso2.carbon.apimgt.gateway_9.0.174.295.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.SynapseAnalyticsDataProvider.getBackendLatency(SynapseAnalyticsDataProvider.java:385) ~[org.wso2.carbon.apimgt.gateway_9.0.174.295.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.SynapseAnalyticsDataProvider.getLatencies_aroundBody18(SynapseAnalyticsDataProvider.java:205) ~[org.wso2.carbon.apimgt.gateway_9.0.174.295.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.SynapseAnalyticsDataProvider.getLatencies(SynapseAnalyticsDataProvider.java:203) ~[org.wso2.carbon.apimgt.gateway_9.0.174.295.jar:?]
	at org.wso2.carbon.apimgt.common.analytics.collectors.impl.SuccessRequestDataCollector.collectData(SuccessRequestDataCollector.java:73) ~[org.wso2.carbon.apimgt.common.analytics_9.0.174.197.jar:?]
	at org.wso2.carbon.apimgt.common.analytics.collectors.impl.GenericRequestDataCollector.collectData(GenericRequestDataCollector.java:46) ~[org.wso2.carbon.apimgt.common.analytics_9.0.174.197.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.AnalyticsMetricsHandler.handleResponseOutFlow_aroundBody8(AnalyticsMetricsHandler.java:101) [org.wso2.carbon.apimgt.gateway_9.0.174.295.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.AnalyticsMetricsHandler.handleResponseOutFlow(AnalyticsMetricsHandler.java:81) [org.wso2.carbon.apimgt.gateway_9.0.174.295.jar:?]
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:184) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.synapse.mediators.builtin.RespondMediator.mediate(RespondMediator.java:46) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate_aroundBody0(APIManagerExtensionHandler.java:74) [org.wso2.carbon.apimgt.gateway_9.0.174.295.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate(APIManagerExtensionHandler.java:59) [org.wso2.carbon.apimgt.gateway_9.0.174.295.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest_aroundBody2(APIManagerExtensionHandler.java:100) [org.wso2.carbon.apimgt.gateway_9.0.174.295.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest(APIManagerExtensionHandler.java:80) [org.wso2.carbon.apimgt.gateway_9.0.174.295.jar:?]
	at org.apache.synapse.api.API.process(API.java:389) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:108) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:128) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:60) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:84) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:70) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) [synapse-core_2.1.7.wso2v227_40.jar:2.1.7-wso2v227.40]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v63_3.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375) [synapse-nhttp-transport_2.1.7.wso2v227_43.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:189) [synapse-nhttp-transport_2.1.7.wso2v227_43.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v63_3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_401]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_401]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_401]
```

### Steps to Reproduce

1. Enable the choreo analytics.

```
[apim.analytics]
enable = true
config_endpoint = "https://analytics-event-auth.choreo.dev/auth/v1"
auth_token = "<auth_token>"
```

2. Adding the following sequence (which has a respond mediator) into the request mediation flow.

```
<sequence xmlns="http://ws.apache.org/ns/synapse" name="sequence_new">
    <log level="full">
        <property name="IN_MESSAGE" value="IN_MESSAGE"/>
    </log>
    <respond/>
</sequence>
```
3. Invoke the API.
4. Observe the following error logs.

```
[2024-03-21 16:08:41,505] ERROR - AnalyticsMetricsHandler Error Occurred when collecting data
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.SynapseAnalyticsDataProvider.getBackendLatency_aroundBody48(SynapseAnalyticsDataProvider.java:349) ~[org.wso2.carbon.apimgt.gateway_9.0.174.128.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.SynapseAnalyticsDataProvider.getBackendLatency(SynapseAnalyticsDataProvider.java:344) ~[org.wso2.carbon.apimgt.gateway_9.0.174.128.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.SynapseAnalyticsDataProvider.getLatencies_aroundBody18(SynapseAnalyticsDataProvider.java:194) ~[org.wso2.carbon.apimgt.gateway_9.0.174.128.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.SynapseAnalyticsDataProvider.getLatencies(SynapseAnalyticsDataProvider.java:192) ~[org.wso2.carbon.apimgt.gateway_9.0.174.128.jar:?]
	at org.wso2.carbon.apimgt.common.analytics.collectors.impl.SuccessRequestDataCollector.collectData(SuccessRequestDataCollector.java:70) ~[org.wso2.carbon.apimgt.common.analytics_9.0.174.130.jar:?]
	at org.wso2.carbon.apimgt.common.analytics.collectors.impl.GenericRequestDataCollector.collectData(GenericRequestDataCollector.java:46) ~[org.wso2.carbon.apimgt.common.analytics_9.0.174.130.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.AnalyticsMetricsHandler.handleResponseOutFlow_aroundBody8(AnalyticsMetricsHandler.java:99) [org.wso2.carbon.apimgt.gateway_9.0.174.128.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.analytics.AnalyticsMetricsHandler.handleResponseOutFlow(AnalyticsMetricsHandler.java:80) [org.wso2.carbon.apimgt.gateway_9.0.174.128.jar:?]
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:184) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.synapse.mediators.builtin.RespondMediator.mediate(RespondMediator.java:46) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate_aroundBody0(APIManagerExtensionHandler.java:74) [org.wso2.carbon.apimgt.gateway_9.0.174.128.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.mediate(APIManagerExtensionHandler.java:59) [org.wso2.carbon.apimgt.gateway_9.0.174.128.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest_aroundBody2(APIManagerExtensionHandler.java:100) [org.wso2.carbon.apimgt.gateway_9.0.174.128.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.ext.APIManagerExtensionHandler.handleRequest(APIManagerExtensionHandler.java:80) [org.wso2.carbon.apimgt.gateway_9.0.174.128.jar:?]
	at org.apache.synapse.api.API.process(API.java:389) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:84) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:70) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) [synapse-core_2.1.7.wso2v227_23.jar:2.1.7-wso2v227.23]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v63_3.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375) [synapse-nhttp-transport_2.1.7.wso2v227_18.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:434) [synapse-nhttp-transport_2.1.7.wso2v227_18.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182) [synapse-nhttp-transport_2.1.7.wso2v227_18.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v63_3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

### Affected Component

APIM

### Version

4.0.0

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this as this was fixed.

Thanks!
Dulith
