### ISSUE TITLE
Error logged when publishing an API when a Token is not configured for Marketplace feature

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#2708]
### Description

When trying to publish an API in the latest pack, even though publishing happens correctly, the publishing process takes some time to complete and there is an error log in the backend as follows.

```
[2024-03-24 19:11:39,750]  WARN - APIUtil Failed retrieving from remote endpoint: Connect to localhost:9090 [localhost/127.0.0.1] failed: Connection refused (Connection refused). Retrying after 15 seconds.
[2024-03-24 19:11:54,769] ERROR - MarketplaceAssistantApiServiceImpl Error encountered while executing the execute statement of Marketplace Assistant service
org.wso2.carbon.apimgt.api.APIManagementException: Error encountered while connecting to service
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getMarketplaceChatApiCount_aroundBody904(APIUtil.java:10494) ~[org.wso2.carbon.apimgt.impl_9.29.81.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getMarketplaceChatApiCount(APIUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.29.81.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.MarketplaceAssistantApiServiceImpl.getMarketplaceAssistantApiCount(MarketplaceAssistantApiServiceImpl.java:115) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.MarketplaceAssistantApi.getMarketplaceAssistantApiCount(MarketplaceAssistantApi.java:52) ~[?:?]

...

Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:9090 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient_4.5.13.wso2v1.jar:?]
```

Good to handle the behaviour for the default case where a token is not configured for the API Marketplace feature.

### Steps to Reproduce

1. Login and try to create and publish an API.
2. You will notice the above error in the backend terminal.

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
This issue is fixed with https://github.com/wso2/carbon-apimgt/pull/12363. Hence closing.
