### ISSUE TITLE
Cannot Enable API KEY for API Products

### ISSUE THREAD

**Issue by Kirishikesan** [wso2/api-manager#2710]
### Description

Error thrown when enabling API key for API Products through publisher portal

<img width="1512" alt="image" src="https://github.com/wso2-enterprise/wso2-apim-internal/assets/62060834/5e6b2a33-ffe0-4c26-86c4-3b49857d9d5a">

### Steps to Reproduce

1. Create and API Product form publisher
2. Go to Runtime Configurations > Application Level Security > Check "API Key" > Save

### Relevant Log Output

```shell
[2024-03-21 16:21:28,367] ERROR - GlobalThrowableMapper Unrecognized property 'audiences'
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "audiences" (class org.wso2.carbon.apimgt.rest.api.publisher.v1.dto.APIProductDTO), not marked as ignorable (40 known properties: "additionalPropertiesMap", "securityScheme", "monetization", "revisionedApiProductId", "name", "businessInformation", "policies", "state", "visibility", "createdTime", "revisionId", "subscriptionAvailability", "accessControl", "id", "categories", "enableSchemaValidation", "scopes", "responseCachingEnabled", "accessControlRoles", "isRevision", "authorizationHeader", "transport", "visibleRoles", "gatewayVendor", "context", "provider", "hasThumbnail", "apiThrottlingPolicy", "apiType", "visibleTenants", "additionalProperties", "description", "subscriptionAvailableTenants", "cacheTimeout", "corsConfiguration", "lastUpdatedTimestamp", "tags", "lastUpdatedTime", "apis", "workflowStatus"])
 at [Source: (org.apache.cxf.transport.http.AbstractHTTPDestination$1); line: 1, column: 3088] (through reference chain: org.wso2.carbon.apimgt.rest.api.publisher.v1.dto.APIProductDTO["audiences"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1138) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2224) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1709) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1687) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2079) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1229) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:801) ~[?:?]
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1608) ~[?:?]
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBody(JAXRSUtils.java:1560) ~[?:?]
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processRequestBodyParameter(JAXRSUtils.java:1058) ~[?:?]
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameters(JAXRSUtils.java:989) ~[?:?]
```

### Affected Component

APIM

**Comment by RakhithaRR** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/12404
