### ISSUE TITLE
Migration Failure: Missing 'Organization' Column in APIM Component

### ISSUE THREAD

**Issue by Abshan** [wso2/api-manager#2740]
### Description

When migrating the product from APIM-3.2.0 to APIM-4.2.0, we observed an error during the APIM component migration step. Please find the complete error stack trace below,
```
ERROR - V400RegistryResourceMigrator WSO2 API-M Migration Task : Error while adding API revisions, API uuid: d29f469f-ee35-4862-8e67-6fcde0a34c50
org.wso2.carbon.apimgt.migration.APIMigrationException: WSO2 API-M Migration Task : Error while Store the Revision Artifact for API product: d29f469f-ee35-4862-8e67-6fcde0a34c50 for tenant -1234(carbon.super)
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.addAPIProductRevision(V400RegistryResourceMigrator.java:757) ~[org.wso2.carbon.apimgt.migrate.client-4.2.0.57.jar:?]
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.apiRevisionRelatedMigration(V400RegistryResourceMigrator.java:476) ~[org.wso2.carbon.apimgt.migrate.client-4.2.0.57.jar:?]
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.migrate(V400RegistryResourceMigrator.java:140) ~[org.wso2.carbon.apimgt.migrate.client-4.2.0.57.jar:?]
	at org.wso2.carbon.apimgt.migration.migrator.client.V400Migration.migrate(V400Migration.java:65) ~[org.wso2.carbon.apimgt.migrate.client-4.2.0.57.jar:?]
	at org.wso2.carbon.apimgt.migration.APIMMigrationClient.executeMigration(APIMMigrationClient.java:90) ~[org.wso2.carbon.apimgt.migrate.client-4.2.0.57.jar:?]
	at org.wso2.carbon.apimgt.migration.APIMMigrationClient.completedServerStartup(APIMMigrationClient.java:63) ~[org.wso2.carbon.apimgt.migrate.client-4.2.0.57.jar:?]
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyAfter(CarbonCoreServiceComponent.java:264) ~[?:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:214) ~[?:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:309) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:118) ~[org.wso2.carbon.tenant.throttling.agent_4.9.20.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:96) ~[org.wso2.carbon.tenant.throttling.agent_4.9.20.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) ~[org.wso2.carbon.core_4.8.1.8.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) ~[org.wso2.carbon.core_4.8.1.8.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) ~[org.wso2.carbon.core_4.8.1.8.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: org.wso2.carbon.apimgt.api.APIManagementException: Error while retrieving apimgt connection
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.setDefaultVersion_aroundBody482(ApiMgtDAO.java:9952) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.setDefaultVersion(ApiMgtDAO.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.populateDefaultVersion_aroundBody10(AbstractAPIManager.java:181) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.populateDefaultVersion(AbstractAPIManager.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIProductbyUUID_aroundBody406(APIProviderImpl.java:5164) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIProductbyUUID(APIProviderImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getAPIProductbyUUID(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.exportAPIProduct(V400RegistryResourceMigrator.java:950) ~[org.wso2.carbon.apimgt.migrate.client-4.2.0.57.jar:?]
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.addAPIProductRevision(V400RegistryResourceMigrator.java:740) ~[org.wso2.carbon.apimgt.migrate.client-4.2.0.57.jar:?]
	... 47 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "AM_API"."ORGANIZATION": invalid identifier
at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:710) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:608) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1330) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1102) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:456) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:498) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:272) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:1198) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.OracleStatement.prepareDefineBufferAndExecute(OracleStatement.java:1390) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1269) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1794) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1592) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3754) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3940) ~[ojdbc11.jar:23.3.0.23.09]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1103) ~[ojdbc11.jar:23.3.0.23.09]
	at jdk.internal.reflect.GeneratedMethodAccessor58.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118) ~[jdbc-pool_9.0.56.wso2v1.jar:?]
	at com.sun.proxy.$Proxy49.executeQuery(Unknown Source) ~[?:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.setDefaultVersion_aroundBody482(ApiMgtDAO.java:9934) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.setDefaultVersion(ApiMgtDAO.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.populateDefaultVersion_aroundBody10(AbstractAPIManager.java:181) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.populateDefaultVersion(AbstractAPIManager.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIProductbyUUID_aroundBody406(APIProviderImpl.java:5164) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.getAPIProductbyUUID(APIProviderImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getAPIProductbyUUID(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.28.116.136.jar:?]
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.exportAPIProduct(V400RegistryResourceMigrator.java:950) ~[org.wso2.carbon.apimgt.migrate.client-4.2.0.57.jar:?]
	at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.addAPIProductRevision(V400RegistryResourceMigrator.java:740) ~[org.wso2.carbon.apimgt.migrate.client-4.2.0.57.jar:?]
	... 47 more
```
The error stack trace mentioned above occurs during the APIM component migration from version 3.2.0 to 4.0.0. Specifically, the error occurs when creating a revision for an API product. The error message indicates that a query is attempting to access a column named `ORGANIZATION` in the `API_AM` table. However, this column was introduced in APIM version 4.1.0. Referencing this column during an earlier stage of the migration process (from 3.2.0 to 4.0.0) disrupts the overall APIM component migration.

The issue lies in the fact that the "ORGANIZATION" column was introduced in APIM version 4.1.0, and the migration scripts that are supposed to create this column supposed to be executed in the next step (from 4.0.0 to 4.1.0) of the APIM component migration. So, any queries being executed with reference to the missing columns needs to be fixed.

Due to the above issue, migration from APIM-3.2.0 to APIM-4.2.0 is blocked.

### Steps to Reproduce

Migrating an APIM-3.2.0 server with API products to APIM-4.0.0 or a later version

### Affected Component

APIM

### Version

4.2.0

**Comment by dulithsenanayake** [comment]
Hi all,

We are closing this as the U2 update was released and added the public fix as well. 

Thanks!
Dulith
