### ISSUE TITLE
Cannot invoke API Products when AI features are enabled

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/api-manager#2780]
### Description

API Products cannot be invoked when AI features are enabled. The browser returns a CORS error and when invoking locally, a resource not found error is thrown by the gateway.

Some other weird behaviours can also been seen with this. When Create and Publish option is selected from the API Product form, even though the product creation is successful, the UI will not be redirected to the overview page. Sometimes, the resources of the API Product are not shown on the publisher side after creation. The following error can also been seen in the gateway logs in such scenarios.

```
ERROR {org.apache.synapse.config.xml.rest.APIFactory} - An API must contain at least one resource definition
ERROR {org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer} - Error deploying 008b2c1c-86c0-47ed-862f-3e78e57e92d0 in Gateway org.apache.axis2.AxisFault: Error while publishing API to the Gateway. An API must contain at least one resource definition|
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi_aroundBody0(RESTAPIAdminServiceProxy.java:55) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]|
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi(RESTAPIAdminServiceProxy.java:1) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]|
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:768) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]|
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:1) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]|
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:103) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]|
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:1) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]|
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run_aroundBody0(GatewayJMSMessageListener.java:190) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]|
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run(GatewayJMSMessageListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]|
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]|
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]|
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]|
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]|
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]|
Caused by: org.apache.synapse.SynapseException: An API must contain at least one resource definition|
	at org.apache.synapse.config.xml.rest.APIFactory.handleException(APIFactory.java:207) ~[synapse-core_4.0.0.wso2v103.jar:4.0.0-wso2v103]|
	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:103) ~[synapse-core_4.0.0.wso2v103.jar:4.0.0-wso2v103]|
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApi(RestApiAdmin.java:854) ~[org.wso2.carbon.rest.api_4.7.202.jar:?]|
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiFromString(RestApiAdmin.java:112) ~[org.wso2.carbon.rest.api_4.7.202.jar:?]|
	at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiForTenant(RestApiAdmin.java:138) ~[org.wso2.carbon.rest.api_4.7.202.jar:?]|
	at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi_aroundBody0(RESTAPIAdminServiceProxy.java:52) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]|
	... 12 more|
```

### Steps to Reproduce

Create, deploy, and invoke an API Product when AI features have been enabled

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
Closing the issue as the PR is merged.
