### ISSUE TITLE
Publisher tryout console not working and got blank page

### ISSUE THREAD

**Issue by tharindu1st** [wso2/api-manager#2782]
### Description

Publisher tryout console not working and got blank page
![image](https://github.com/wso2/api-manager/assets/6345931/38fcc21e-95ae-491e-bec0-5cc342ed2f66)

### Steps to Reproduce

Create api and deploy to two environments like default and test.
remove test environment
load publisher test console.

### Affected Component

APIM

### Version

4.3.0-beta

### Environment Details (with versions)

Distributed

### Relevant Log Output

```shell
index.bb83891bcb5646950bba.bundle.js:sourcemap:2 TypeError: Cannot read properties of undefined (reading 'vhosts')
    at TryOutConsole.jsx:181:68
    at Object.Qa [as useMemo] (index.bb83891bcb5646950bba.bundle.js:sourcemap:2:294099)
    at t.useMemo (index.bb83891bcb5646950bba.bundle.js:sourcemap:2:388297)
    at Xj (TryOutConsole.jsx:177:34)
    at _a (index.bb83891bcb5646950bba.bundle.js:sourcemap:2:289718)
    at ks (index.bb83891bcb5646950bba.bundle.js:sourcemap:2:301339)
    at _u (index.bb83891bcb5646950bba.bundle.js:sourcemap:2:347417)
    at wc (index.bb83891bcb5646950bba.bundle.js:sourcemap:2:335702)
    at mc (index.bb83891bcb5646950bba.bundle.js:sourcemap:2:335630)
    at gc (index.bb83891bcb5646950bba.bundle.js:sourcemap:2:335493)
```

### Suggested Labels

apim

**Comment by AnuGayan** [comment]
Fixed by https://github.com/wso2/apim-apps/pull/669
