### ISSUE TITLE
Cannot Create API Product using API with OAS 3.1.0 definition

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/api-manager#2789]
### Description

When API product is created with an API having a OAS 3.1.0 definition, Following error is thrown in the gateway when deploying 

        org.apache.axis2.AxisFault: Error while publishing API to the Gateway. An API must contain at least one resource definition
	        at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi_aroundBody0(RESTAPIAdminServiceProxy.java:55) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]
	        at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi(RESTAPIAdminServiceProxy.java:1) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]
	        at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:768) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]
	        at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:1) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]
	        at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:103) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]
	        at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:1) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]
	        at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run_aroundBody0(GatewayJMSMessageListener.java:190) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]
	        at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run(GatewayJMSMessageListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]
	        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	        at java.lang.Thread.run(Thread.java:829) ~[?:?]
        Caused by: org.apache.synapse.SynapseException: An API must contain at least one resource definition
	        at org.apache.synapse.config.xml.rest.APIFactory.handleException(APIFactory.java:207) ~[synapse-core_4.0.0.wso2v103.jar:4.0.0-wso2v103]
	        at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:103) ~[synapse-core_4.0.0.wso2v103.jar:4.0.0-wso2v103]
	        at org.wso2.carbon.rest.api.service.RestApiAdmin.addApi(RestApiAdmin.java:854) ~[org.wso2.carbon.rest.api_4.7.202.jar:?]
	        at org.wso2.carbon.rest.api.service.RestApiAdmin.addApiFromString(RestApiAdmin.java:112) ~[org.wso2.carbon.rest.api_4.7.202.jar:?]
	        at org.wso2.carbon.apimgt.gateway.utils.RESTAPIAdminServiceProxy.addApi_aroundBody0(RESTAPIAdminServiceProxy.java:50) ~[org.wso2.carbon.apimgt.gateway_9.29.95.jar:?]
	        ... 12 more

### Steps to Reproduce

1. Create a API from OAS3.1.0 spec. Use [passenger-api.json](https://github.com/wso2/api-manager/files/14832701/passenger-api.json)
2. Create API product from one of this resource.
3. Deploy product

### Affected Component

APIM

### Version

4.3.0

**Comment by chamilaadhi** [comment]
Seems this issue is coming for oas def 3.0 as well. When I try this definition https://gist.githubusercontent.com/chamilaadhi/2870e96911e17de1a0b15d146dfa0498/raw/e02a60bab078e3c5c510e6ab36d182729138faa6/user-flat.yml

**Comment by chamilaadhi** [comment]
Another definition https://gist.githubusercontent.com/chamilaadhi/4d1e1f4493cae483943a581ca135c1de/raw/b2ce67ee82ebd98dcd14e0e4ae56d1ead1c2ef5d/passenger-api.json . This is working in APIM 4.2.0 but not working in 4.3.0. Above error is printed. So seems this issue is not related to openapi definition

**Comment by tharikaGitHub** [comment]
This error is not reproducible for APIs created from scratch, but reproducible for imported APIs. When an API is imported, the `x-auth-type` property is not set for the resources causing the issue. If you edit the swagger definition with something like the following, the deployment issue does not happen for API products.

```
x-auth-type: Application & Application User
```
