### ISSUE TITLE
[APIM 4.1.0]JSON Schema Validator fails when 'example' is used with date-time format.

### ISSUE THREAD

**Issue by SameeraSI** [wso2/api-manager#2799]
### Description

When using ‘example’ in property-level with ‘format: date-time’ in schema validation as below,
```
date:
    type: string
    description: Test Description.
    format: date-time
    example: '2017-07-21T17:32:28Z'

```
APIM shows the following error:
```
[2024-04-02 23:07:58,112] ERROR - ServerWorker Error processing GET request for : /test/1.0/test.
java.lang.IllegalArgumentException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.LinkedHashMap["Test"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["date"]->io.swagger.v3.oas.models.media.DateTimeSchema["example"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4544) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4475) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.atlassian.oai.validator.schema.SchemaValidator.lambda$new$0(SchemaValidator.java:92) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at com.atlassian.oai.validator.schema.SchemaValidator.<init>(SchemaValidator.java:92) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at com.atlassian.oai.validator.OpenApiInteractionValidator.<init>(OpenApiInteractionValidator.java:149) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at com.atlassian.oai.validator.OpenApiInteractionValidator.<init>(OpenApiInteractionValidator.java:46) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at com.atlassian.oai.validator.OpenApiInteractionValidator$Builder.build(OpenApiInteractionValidator.java:543) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.getOpenAPIValidator_aroundBody0(SchemaValidator.java:57) ~[org.wso2.carbon.apimgt.gateway_9.28.116.142.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.getOpenAPIValidator(SchemaValidator.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.116.142.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest_aroundBody2(SchemaValidator.java:66) ~[org.wso2.carbon.apimgt.gateway_9.28.116.142.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest(SchemaValidator.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.116.142.jar:?]
	at org.apache.synapse.api.API.process(API.java:403) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:108) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:128) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:60) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:76) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:350) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v83_3.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:399) ~[synapse-nhttp-transport_4.0.0.wso2v20_34.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:213) ~[synapse-nhttp-transport_4.0.0.wso2v20_34.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v83_3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.LinkedHashMap["Test"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["date"]->io.swagger.v3.oas.models.media.DateTimeSchema["example"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1312) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4522) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	... 27 more
```

But validation can be done without example as below,
```
date:
    type: string
    description: Test Description.
    format: date-time
```

### Steps to Reproduce

Create a mock backend to give a response with a date as follows:
`[{ "status": "Good!", "date":"2017-07-21T17:32:28Z", "value":"1"}]`

Create an API with the above backend and enable 'Schema Validation' from the publisher portal.

Then modify the API Definition to validate the 'date' field with the 'format' as 'date-time' and provide an 'example' as follows:
```
date:
    type: string
    description: Test Description.
    format: date-time
    example: '2017-07-21T17:32:28Z'
```

Then after invoking the API following response can be received:
```
<soapenv:Reason xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
    <soapenv:Text xml:lang="en-US">Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.LinkedHashMap["Test"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["date"]->io.swagger.v3.oas.models.media.DateTimeSchema["example"])</soapenv:Text>
</soapenv:Reason>
```

With following error in the logs:
```
[2024-04-02 23:07:58,112] ERROR - ServerWorker Error processing GET request for : /test/1.0/test.
java.lang.IllegalArgumentException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.LinkedHashMap["Test"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["date"]->io.swagger.v3.oas.models.media.DateTimeSchema["example"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4544) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4475) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.atlassian.oai.validator.schema.SchemaValidator.lambda$new$0(SchemaValidator.java:92) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at com.atlassian.oai.validator.schema.SchemaValidator.<init>(SchemaValidator.java:92) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at com.atlassian.oai.validator.OpenApiInteractionValidator.<init>(OpenApiInteractionValidator.java:149) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at com.atlassian.oai.validator.OpenApiInteractionValidator.<init>(OpenApiInteractionValidator.java:46) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at com.atlassian.oai.validator.OpenApiInteractionValidator$Builder.build(OpenApiInteractionValidator.java:543) ~[swagger-request-validator-core_2.12.1.wso2v2.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.getOpenAPIValidator_aroundBody0(SchemaValidator.java:57) ~[org.wso2.carbon.apimgt.gateway_9.28.116.142.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.getOpenAPIValidator(SchemaValidator.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.116.142.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest_aroundBody2(SchemaValidator.java:66) ~[org.wso2.carbon.apimgt.gateway_9.28.116.142.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.SchemaValidator.handleRequest(SchemaValidator.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.116.142.jar:?]
	at org.apache.synapse.api.API.process(API.java:403) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:108) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:128) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:60) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:76) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:350) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) ~[synapse-core_4.0.0.wso2v20_31.jar:4.0.0-wso2v20.31]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v83_3.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:399) ~[synapse-nhttp-transport_4.0.0.wso2v20_34.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:213) ~[synapse-nhttp-transport_4.0.0.wso2v20_34.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v83_3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.LinkedHashMap["Test"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["date"]->io.swagger.v3.oas.models.media.DateTimeSchema["example"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1312) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4522) ~[com.fasterxml.jackson.core.jackson-databind_2.15.0.jar:?]
	... 27 more
```

### Affected Component

APIM

### Version

4.1.0.143

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this since the update was released.

Thanks!
Dulith
