### ISSUE TITLE
[APIM 4.3.0-RC] OCSP and CRL certificate verification fails with noSuchMethod exception

### ISSUE THREAD

**Issue by Akila94** [wso2/api-manager#2813]
### Description

When testing the certificate revocation validation feature with APIM 4.3.0 RC release, the following exceptions were printed when using OCSP and CRL verifiers.

```
Exception in thread "HTTPS-Listener I/O dispatcher-19" java.lang.NoSuchMethodError: 'org.bouncycastle.asn1.DERIA5String org.bouncycastle.asn1.DERIA5String.getInstance(java.lang.Object)'
	at org.apache.synapse.transport.certificatevalidation.ocsp.OCSPVerifier.getAIALocations(OCSPVerifier.java:279)
	at org.apache.synapse.transport.certificatevalidation.ocsp.OCSPVerifier.checkRevocationStatus(OCSPVerifier.java:109)
	at org.apache.synapse.transport.certificatevalidation.CertificateVerificationManager.verifyCertificateValidity(CertificateVerificationManager.java:144)
	at org.apache.synapse.transport.http.conn.ServerSSLSetupHandler.verify(ServerSSLSetupHandler.java:80)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:373)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.outboundTransport(SSLIOSession.java:603)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:154)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:187)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:341)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-04-05 16:42:43,793] FATAL - PassThroughListeningIOReactorManager Exception encountered in the HTTPS-Listener I/O dispatcher Listener. No more connections will be accepted by this transport
org.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:359) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager$1.run(PassThroughListeningIOReactorManager.java:561) ~[synapse-nhttp-transport_4.0.0.wso2v104.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bouncycastle.asn1.DERIA5String org.bouncycastle.asn1.DERIA5String.getInstance(java.lang.Object)'
	at org.apache.synapse.transport.certificatevalidation.ocsp.OCSPVerifier.getAIALocations(OCSPVerifier.java:279) ~[synapse-nhttp-transport_4.0.0.wso2v104.jar:?]
	at org.apache.synapse.transport.certificatevalidation.ocsp.OCSPVerifier.checkRevocationStatus(OCSPVerifier.java:109) ~[synapse-nhttp-transport_4.0.0.wso2v104.jar:?]
	at org.apache.synapse.transport.certificatevalidation.CertificateVerificationManager.verifyCertificateValidity(CertificateVerificationManager.java:144) ~[synapse-nhttp-transport_4.0.0.wso2v104.jar:?]
	at org.apache.synapse.transport.http.conn.ServerSSLSetupHandler.verify(ServerSSLSetupHandler.java:80) ~[synapse-nhttp-transport_4.0.0.wso2v104.jar:?]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:373) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.outboundTransport(SSLIOSession.java:603) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:154) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:187) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:341) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	... 1 more
```

and 

```
Exception in thread "HTTPS-Listener I/O dispatcher-11" java.lang.NoSuchMethodError: 'org.bouncycastle.asn1.DERIA5String org.bouncycastle.asn1.DERIA5String.getInstance(java.lang.Object)'
	at org.apache.synapse.transport.certificatevalidation.crl.CRLVerifier.getCrlDistributionPoints(CRLVerifier.java:167)
	at org.apache.synapse.transport.certificatevalidation.crl.CRLVerifier.checkRevocationStatus(CRLVerifier.java:62)
	at org.apache.synapse.transport.certificatevalidation.CertificateVerificationManager.verifyCertificateValidity(CertificateVerificationManager.java:144)
	at org.apache.synapse.transport.http.conn.ServerSSLSetupHandler.verify(ServerSSLSetupHandler.java:80)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:373)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.outboundTransport(SSLIOSession.java:603)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:154)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:187)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:341)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-04-05 16:57:38,404] FATAL - PassThroughListeningIOReactorManager Exception encountered in the HTTPS-Listener I/O dispatcher Listener. No more connections will be accepted by this transport
org.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:359) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager$1.run(PassThroughListeningIOReactorManager.java:561) ~[synapse-nhttp-transport_4.0.0.wso2v104.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bouncycastle.asn1.DERIA5String org.bouncycastle.asn1.DERIA5String.getInstance(java.lang.Object)'
	at org.apache.synapse.transport.certificatevalidation.crl.CRLVerifier.getCrlDistributionPoints(CRLVerifier.java:167) ~[synapse-nhttp-transport_4.0.0.wso2v104.jar:?]
	at org.apache.synapse.transport.certificatevalidation.crl.CRLVerifier.checkRevocationStatus(CRLVerifier.java:62) ~[synapse-nhttp-transport_4.0.0.wso2v104.jar:?]
	at org.apache.synapse.transport.certificatevalidation.CertificateVerificationManager.verifyCertificateValidity(CertificateVerificationManager.java:144) ~[synapse-nhttp-transport_4.0.0.wso2v104.jar:?]
	at org.apache.synapse.transport.http.conn.ServerSSLSetupHandler.verify(ServerSSLSetupHandler.java:80) ~[synapse-nhttp-transport_4.0.0.wso2v104.jar:?]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:373) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.nio.reactor.ssl.SSLIOSession.outboundTransport(SSLIOSession.java:603) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:154) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:187) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:341) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio_4.4.16.wso2v4.jar:?]
	... 1 more
```

The same issue occurs when trying to verify with both OCSP and CRL verifiers.

### Steps to Reproduce

Got this issue when testing the following feature: 
https://apim.docs.wso2.com/en/4.3.0/install-and-setup/setup/advance-configurations/configure-certificate-revocation/

Steps to reproduce,

1. Import the immediate issuer of the client cert to the client-truststore.jks.
2. Do the above configurations with ```enable = true``` and ```allow_full_cert_chain_validation = false``` so the verification will happen when a single certificate is sent in the request.
3. Send a request with the child certificate of the issuer which was imported to the client-truststore.jks.

### Affected Component

APIM

### Version

4.3.0

### Relevant Log Output

```shell
Provided above
```

### Suggested Labels

APIM 4.3.0

**Comment by HeshanSudarshana** [comment]
Closing since the fix is merged.
