### ISSUE TITLE
Delete few users created using self signup option

### ISSUE THREAD

**Issue by DaniduWijendra** [wso2/api-manager#2825]
### Description

When trying to create users via the Self Sign-Up REST API. we were able to create users like /etc/pass by passing usernames like etc/pass which is not allowed to be created via dev portal UI or management console. 
the 

### Steps to Reproduce

Start the APIM server and invoke the following CURL command to create new user via REST API.

```
curl --location 'https://localhost:9443/api/identity/user/v1.0/me' \
--header 'accept: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--data '{
"user": {
  "username": "/etc/passwod",
  "password": "password",
  "claims": [
    {
      "uri": "http://wso2.org/claims/givenname",
      "value": "RestUser"
    },
     {
      "uri": "http://wso2.org/claims/lastname",
      "value": "RestUserLast"
    },
     {
      "uri": "http://wso2.org/claims/emailaddress",
      "value": "RestUser"
    }
  ]
},
"properties": [
  {
    "key": "string",
    "value": "string"
  }
]
}'
```

Next, when tried to delete this user, and observed the the below stack trace. 

```
ERROR - JDBCAuthorizationManager Error occurred while accessing Java Security Manager Privilege Block
[2024-04-10 13:52:53,924] ERROR - UserRealmProxy Error occurred while accessing Java Security Manager Privilege Block
org.wso2.carbon.user.core.UserStoreException: Error occurred while accessing Java Security Manager Privilege Block
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.callSecure(JDBCAuthorizationManager.java:1523) ~[org.wso2.carbon.user.core_4.6.3.10.jar:?]
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.isUserAuthorized(JDBCAuthorizationManager.java:215) ~[org.wso2.carbon.user.core_4.6.3.10.jar:?]
	at org.wso2.carbon.user.mgt.UserRealmProxy.deleteUser(UserRealmProxy.java:885) ~[org.wso2.carbon.user.mgt_5.18.248.10.jar:?]
	at org.wso2.carbon.user.mgt.UserAdmin.deleteUser(UserAdmin.java:246) ~[org.wso2.carbon.user.mgt_5.18.248.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212) ~[axis2_1.6.1.wso2v80_5.jar:?]
	at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117) ~[axis2_1.6.1.wso2v80_5.jar:?]
	at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40) ~[axis2_1.6.1.wso2v80_5.jar:?]
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110) ~[axis2_1.6.1.wso2v80_5.jar:?]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v80_5.jar:?]
	at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:170) ~[axis2_1.6.1.wso2v80_5.jar:?]
	at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:82) ~[axis2_1.6.1.wso2v80_5.jar:?]
	at org.wso2.carbon.core.transports.local.CarbonLocalTransportSender.finalizeSendWithToAddress(CarbonLocalTransportSender.java:45) ~[org.wso2.carbon.core_4.6.3.14.jar:?]
	at org.apache.axis2.transport.local.LocalTransportSender.invoke(LocalTransportSender.java:77) ~[axis2_1.6.1.wso2v80_5.jar:?]
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442) ~[axis2_1.6.1.wso2v80_5.jar:?]




Caused by: java.security.PrivilegedActionException
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_382]
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.callSecure(JDBCAuthorizationManager.java:1508) ~[org.wso2.carbon.user.core_4.6.3.10.jar:?]
	... 84 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager$2.run(JDBCAuthorizationManager.java:1511) ~[org.wso2.carbon.user.core_4.6.3.10.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_382]
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.callSecure(JDBCAuthorizationManager.java:1508) ~[org.wso2.carbon.user.core_4.6.3.10.jar:?]
	... 84 more
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.user.core.authorization.AuthorizationCache.isCaseSensitiveUsername(AuthorizationCache.java:329) ~[org.wso2.carbon.user.core_4.6.3.10.jar:?]
	at org.wso2.carbon.user.core.authorization.AuthorizationCache.isUserAuthorized(AuthorizationCache.java:150) ~[org.wso2.carbon.user.core_4.6.3.10.jar:?]
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.isUserAuthorized(JDBCAuthorizationManager.java:246) ~[org.wso2.carbon.user.core_4.6.3.10.jar:?]
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager$2.run(JDBCAuthorizationManager.java:1511) ~[org.wso2.carbon.user.core_4.6.3.10.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_382]
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.callSecure(JDBCAuthorizationManager.java:1508) ~[org.wso2.carbon.user.core_4.6.3.10.jar:?]
	... 84 more
[2024-04-10 13:52:53,927] ERROR - UserAdminClient Error occurred while accessing Java Security Manager Privilege Block
org.wso2.carbon.user.mgt.stub.UserAdminUserAdminException: UserAdminUserAdminException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_382]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_382]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_382]
	at org.wso2.carbon.user.mgt.stub.UserAdminStub.deleteUser(UserAdminStub.java:5675) ~[org.wso2.carbon.user.mgt.stub_5.18.248.jar:?]
	at org.wso2.carbon.user.mgt.ui.UserAdminClient.deleteUser(UserAdminClient.java:128) ~[org.wso2.carbon.user.mgt.ui_5.18.248.jar:?]
	at org.apache.jsp.user.delete_002dfinish_002dajaxprocessor_jsp._jspService(delete_002dfinish_002dajaxprocessor_jsp.java:163) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[tomcat_9.0.82.wso2v1.jar:?]
...
```

### Affected Component

APIM

### Version

4.1.0

**Comment by AnuGayan** [comment]
This does not seem to be a bug in the REST API , rather the correct configs have not been set under userstore configs to enforce the correct validations. The username passed in the above API is validated against the username regex of the relevant userstore when using the self-signup REST API to register users.

The following property can be used to set the correct regex validation for the userstore if they need to prevent special chars in the username.

[user_store]
username_java_regex="/^[A-Za-z]+$/"

The username passed in the self-signup API is validated as expected when the above property is set.

{
"code": "20045",
"message": "Bad Request",
"description": "Provided username /ra/do violates the policy."
}
