### ISSUE TITLE
Daylight saving time change causes APIM to use a date that does not exist in mysql.

### ISSUE THREAD

**Issue by TomasWso2** [wso2/api-manager#2845]
### Description

When daylight time saving time skip happens and time zones between APIM server and JDBC connection are different. Each time APIM tries to query or insert a the current date, it will throw an error because the date does not exist.
March 10 between 2AM and 3AM UTC

`[2024-03-09 21:11:37,243] ERROR - JDBCResourceDAO Failed to add resource to path /_system/config/repository/connection/props. Data truncation: Incorrect datetime value: '2024-03-10 02:11:37.174' for column 'REG_LAST_UPDATED_TIME' at row 1
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Incorrect datetime value: '2024-03-10 02:11:37.174' for column 'REG_LAST_UPDATED_TIME' at row 1
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-java-8.0.30.jar:8.0.30]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-java-8.0.30.jar:8.0.30]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[mysql-connector-java-8.0.30.jar:8.0.30]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009) ~[mysql-connector-java-8.0.30.jar:8.0.30]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320) ~[mysql-connector-java-8.0.30.jar:8.0.30]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994) ~[mysql-connector-java-8.0.30.jar:8.0.30]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
    at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118) ~[jdbc-pool_9.0.56.wso2v1.jar:?]
    at com.sun.proxy.$Proxy52.executeUpdate(Unknown Source) ~[?:?]
    at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.addResourceWithoutContentId(JDBCResourceDAO.java:1424) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.update(JDBCResourceDAO.java:620) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.Repository.update(Repository.java:1113) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.Repository.put(Repository.java:288) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:717) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
    at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:292) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:597) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
    at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.core.init.CarbonServerManager.populateConnectionProperties(CarbonServerManager.java:678) ~[org.wso2.carbon.core_4.8.1.4.jar:?]
    at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:450) ~[org.wso2.carbon.core_4.8.1.4.jar:?]
    at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) ~[org.wso2.carbon.core_4.8.1.4.jar:?]
    at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) ~[org.wso2.carbon.core_4.8.1.4.jar:?]
    at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
[2024-03-09 21:11:37,256] FATAL - CarbonServerManager WSO2 Carbon initialization Failed
org.wso2.carbon.registry.core.exceptions.RegistryException: Unable to put resource Failed to add resource to path /_system/config/repository/connection/props. Data truncation: Incorrect datetime value: '2024-03-10 02:11:37.174' for column 'REG_LAST_UPDATED_TIME' at row 1
    at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:299) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:597) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
    at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813) ~[org.wso2.carbon.registry.core_4.8.1.5.jar:?]
    at org.wso2.carbon.core.init.CarbonServerManager.populateConnectionProperties(CarbonServerManager.java:678) ~[org.wso2.carbon.core_4.8.1.4.jar:?]
    at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:450) ~[org.wso2.carbon.core_4.8.1.4.jar:?]
    at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) ~[org.wso2.carbon.core_4.8.1.4.jar:?]
    at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) ~[org.wso2.carbon.core_4.8.1.4.jar:?]
    at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to add resource to path /_system/config/repository/connection/props. Data truncation: Incorrect datetime value: '2024-03-10 02:11:37.174' for column 'REG_LAST_UPDATED_TIME' at row 1`

### Steps to Reproduce

Reproducing steps

Setup Mysql and create apim_db and shared_db. 

Configure the jdbc connection url in the deployment.toml for both apim_db and shared_db to include "serverTimezone=UTC":
[database.shared_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/shared_db?useSSL=false&amp;useJDBCCompliantTimezoneShift=true&amp;serverTimezone=UTC"
username = "sharedadmin"
password = "sharedadmin"
driver="com.mysql.cj.jdbc.Driver"

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/apim_db?useSSL=false&amp;useJDBCCompliantTimezoneShift=true&amp;serverTimezone=UTC"
username = "apimadmin"
password = "apimadmin"
driver="com.mysql.cj.jdbc.Driver"

Change your local system time to March 9, 9:11PM in EST time zone.

Start mysql server.

Start APIM server.

You’ll observe the above-mentioned error.

If the error does not occur, create an application, generate keys and access_token for it first.

This should occur in any update level of APIM 4.x.x 

### Affected Component

APIM

### Version

4.0.0

### Related Issues

https://github.com/wso2/micro-integrator/issues/3273

**Comment by AnuGayan** [comment]
Updated the documentation to reflect the required changes https://github.com/wso2/docs-apim/pull/8017
