### ISSUE TITLE
API blocking does not work intermittently 

### ISSUE THREAD

**Issue by akila95fernando** [wso2/api-manager#2946]
### Description

At gateway startup blocking conditions are notloaded intermittently with following error .

```
INFO - JMSTransportHandler Starting jms topic consumer thread for the perAPILog topic...
Exception in thread "Timer-15" java.lang.NullPointerException
at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService_aroundBody6(KeyTemplateRetriever.java:117)
at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService(KeyTemplateRetriever.java:115)
at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run_aroundBody0(KeyTemplateRetriever.java:55)
at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run(KeyTemplateRetriever.java:51)
at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
at java.base/java.util.TimerThread.run(Timer.java:506)
Exception in thread "Timer-14" java.lang.NullPointerException
at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.loadBlockingConditionsFromWebService_aroundBody6(BlockingConditionRetriever.java:112)
at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.loadBlockingConditionsFromWebService(BlockingConditionRetriever.java:109)
at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.run_aroundBody0(BlockingConditionRetriever.java:52)
at org.wso2.carbon.apimgt.gateway.throttling.util.BlockingConditionRetriever.run(BlockingConditionRetriever.java:48)
at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
at java.base/java.util.TimerThread.run(Timer.java:506)
```

### Steps to Reproduce

1. Add blocking conditions via admin portal
2. Restart GW ( profiled mode ) 

### Affected Component

APIM

### Version

3.2.0 &  3.2.1

**Comment by Tharanidk** [comment]
Fix : https://github.com/wso2/carbon-apimgt/pull/12474
