### ISSUE TITLE
Carbon Console UI Experiencing Significant Delays and Unresponsiveness During Role Permission Updates

### ISSUE THREAD

**Issue by cbabey** [wso2/api-manager#2949]
### Description

Significant delays when updating role permissions through the Carbon console UI. The process takes approximately 5 to 6 minutes for permission updates, and also, the browser session expires during this time since it takes significant time to complete the update process. Additionally, the console becomes unresponsive, prompting the following stack traces which were logged by the CarbonStuckThreadDetectionValve thread since CarbonStuckThreadDetectionValve identified that the particular thread was stuck for more than 10 minutes.

```
[2024-01-31 17:16:43,146]  WARN - CarbonStuckThreadDetectionValve Thread [https-jsse-nio-9443-exec-3] (id=[{6}]) has been active for [602,839] milliseconds (since [1/31/24, 5:06 PM]) to serve the same request for [https://wso2apim-nt.cariprpccoll.it/carbon/role/edit-permissions-finish-ajaxprocessor.jsp] and may be stuck (configured threshold for this StuckThreadDetectionValve is [600] seconds). There is/are [2] thread(s) in total that are monitored by this Valve and may be stuck., tenantDomain=carbon.super
java.lang.Throwable: null
   at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
   at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
   at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
   at sun.nio.ch.IOUtil.read(IOUtil.java:245) ~[?:?]
   at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
   at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:353) ~[?:?]
   at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:187) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:676) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:263) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:195) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:137) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:110) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:91) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.net.ano.CryptoNIONSDataChannel.readDataFromSocketChannel(Unknown Source) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:791) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:449) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:410) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:270) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.jdbc.driver.T4CPreparedStatement.fetch(T4CPreparedStatement.java:1079) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.jdbc.driver.OracleStatement.fetchMoreRows(OracleStatement.java:3469) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.jdbc.driver.InsensitiveScrollableResultSet.fetchMoreRows(InsensitiveScrollableResultSet.java:742) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.jdbc.driver.InsensitiveScrollableResultSet.absoluteInternal(InsensitiveScrollableResultSet.java:698) ~[ojdbc10.jar:19.19.0.0.0]
   at oracle.jdbc.driver.InsensitiveScrollableResultSet.next(InsensitiveScrollableResultSet.java:412) ~[ojdbc10.jar:19.19.0.0.0]
   at org.wso2.carbon.user.core.authorization.PermissionTree.updatePermissionTreeFromDB(PermissionTree.java:1132) ~[org.wso2.carbon.user.core_4.6.0.114.jar:?]
   at org.wso2.carbon.user.core.authorization.PermissionTree.updatePermissionTree(PermissionTree.java:1006) ~[org.wso2.carbon.user.core_4.6.0.114.jar:?]
   at org.wso2.carbon.user.core.authorization.PermissionTree.updatePermissionTree(PermissionTree.java:961) ~[org.wso2.carbon.user.core_4.6.0.114.jar:?]
   at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.getDeniedRolesForResource(JDBCAuthorizationManager.java:450) ~[org.wso2.carbon.user.core_4.6.0.114.jar:?]
   at org.wso2.carbon.registry.core.secure.AuthorizeRoleListener.authorizeRole(AuthorizeRoleListener.java:163) ~[org.wso2.carbon.registry.core_4.6.0.101.jar:?]
   at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.authorizeRole(JDBCAuthorizationManager.java:590) ~[org.wso2.carbon.user.core_4.6.0.114.jar:?]
   at org.wso2.carbon.registry.core.secure.AuthorizeRoleListener.authorizeRole(AuthorizeRoleListener.java:156) ~[org.wso2.carbon.registry.core_4.6.0.101.jar:?]
   at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.authorizeRole(JDBCAuthorizationManager.java:590) ~[org.wso2.carbon.user.core_4.6.0.114.jar:?]
   at org.wso2.carbon.registry.core.secure.AuthorizeRoleListener.authorizeRole(AuthorizeRoleListener.java:156) ~[org.wso2.carbon.registry.core_4.6.0.101.jar:?]
   at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.authorizeRole(JDBCAuthorizationManager.java:590) ~[org.wso2.carbon.user.core_4.6.0.114.jar:?]
   at org.wso2.carbon.registry.core.secure.AuthorizeRoleListener.authorizeRole(AuthorizeRoleListener.java:156) ~[org.wso2.carbon.registry.core_4.6.0.101.jar:?]
   at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.authorizeRole(JDBCAuthorizationManager.java:590) ~[org.wso2.carbon.user.core_4.6.0.114.jar:?]
   at org.wso2.carbon.registry.core.secure.AuthorizeRoleListener.authorizeRole(AuthorizeRoleListener.java:156) ~[org.wso2.carbon.registry.core_4.6.0.101.jar:?]
   at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.authorizeRole(JDBCAuthorizationManager.java:590) ~[org.wso2.carbon.user.core_4.6.0.114.jar:?]
   at jdk.internal.reflect.GeneratedMethodAccessor483.invoke(Unknown Source) ~[?:?]
   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
   at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
   at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager$2.run(JDBCAuthorizationManager.java:1507) ~[org.wso2.carbon.user.core_4.6.0.114.jar:?]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
   at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.callSecure(JDBCAuthorizationManager.java:1504) ~[org.wso2.carbon.user.core_4.6.0.114.jar:?]
   at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.authorizeRole(JDBCAuthorizationManager.java:583) ~[org.wso2.carbon.user.core_4.6.0.114.jar:?]
   at org.wso2.carbon.user.mgt.UserRealmProxy.setRoleUIPermission(UserRealmProxy.java:2149) ~[org.wso2.carbon.user.mgt_5.17.5.162.jar:?]
   at org.wso2.carbon.user.mgt.UserAdmin.setRoleUIPermission(UserAdmin.java:476) ~[org.wso2.carbon.user.mgt_5.17.5.162.jar:?]
   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
   at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
   at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212) ~[axis2_1.6.1.wso2v41_14.jar:?]
   at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117) ~[axis2_1.6.1.wso2v41_14.jar:?]
   at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40) ~[axis2_1.6.1.wso2v41_14.jar:?]
   at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110) ~[axis2_1.6.1.wso2v41_14.jar:?]
   at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v41_14.jar:?]
   at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:170) ~[axis2_1.6.1.wso2v41_14.jar:?]
   at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:82) ~[axis2_1.6.1.wso2v41_14.jar:?]
   at org.wso2.carbon.core.transports.local.CarbonLocalTransportSender.finalizeSendWithToAddress(CarbonLocalTransportSender.java:45) ~[org.wso2.carbon.core_4.6.0.110.jar:?]
   at org.apache.axis2.transport.local.LocalTransportSender.invoke(LocalTransportSender.java:77) ~[axis2_1.6.1.wso2v41_14.jar:?]
   at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442) ~[axis2_1.6.1.wso2v41_14.jar:?]
   at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442) ~[axis2_1.6.1.wso2v41_14.jar:?]
   at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228) ~[axis2_1.6.1.wso2v41_14.jar:?]
   at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) ~[axis2_1.6.1.wso2v41_14.jar:?]
   at org.wso2.carbon.user.mgt.stub.UserAdminStub.setRoleUIPermission(UserAdminStub.java:5268) ~[org.wso2.carbon.user.mgt.stub_5.17.5.jar:?]
   at org.wso2.carbon.user.mgt.ui.UserAdminClient.setRoleUIPermission(UserAdminClient.java:227) ~[org.wso2.carbon.user.mgt.ui_5.17.5.183.jar:?]
   at org.apache.jsp.role.edit_002dpermissions_002dfinish_002dajaxprocessor_jsp._jspService(edit_002dpermissions_002dfinish_002dajaxprocessor_jsp.java:199) ~[?:?]
   at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[tomcat_9.0.71.wso2v1.jar:?]
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.71.wso2v1.jar:?]
   at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327) ~[tomcat_9.0.71.wso2v1.jar:?]
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.71.wso2v1.jar:?]
   at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207) ~[org.wso2.carbon.ui_4.6.0.111.jar:?]
   at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80) ~[org.wso2.carbon.ui_4.6.0.111.jar:?]
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.71.wso2v1.jar:?]
   at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) ~[org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
   at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[?:?]
   at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) ~[?:?]
   at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) ~[?:?]
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-servlet-api_9.0.71.wso2v1.jar:?]
   at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) ~[org.wso2.carbon.tomcat.ext_4.6.0.107.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88) ~[csrfguard_3.1.0.wso2v3.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65) ~[org.wso2.carbon.tomcat.ext_4.6.0.107.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.wso2.carbon.ui.filters.cache.URLBasedCachePreventionFilter.doFilter(URLBasedCachePreventionFilter.java:57) ~[org.wso2.carbon.ui_4.6.0.111.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86) ~[org.wso2.carbon.identity.context.rewrite.valve_1.4.0.jar:?]
   at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) ~[org.wso2.carbon.identity.authz.valve_1.4.0.jar:?]
   at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:111) ~[org.wso2.carbon.identity.auth.valve_1.4.0.13.jar:?]
   at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101) ~[org.wso2.carbon.tomcat.ext_4.6.0.107.jar:?]
   at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) ~[org.wso2.carbon.tomcat.ext_4.6.0.107.jar:?]
   at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) ~[org.wso2.carbon.tomcat.ext_4.6.0.107.jar:?]
   at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) ~[org.wso2.carbon.tomcat.ext_4.6.0.107.jar:?]
   at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:59) ~[org.wso2.carbon.tomcat.ext_4.6.0.107.jar:?]
   at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:124) ~[org.wso2.carbon.tomcat.ext_4.6.0.107.jar:?]
   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat_9.0.71.wso2v1.jar:?]
   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.71.wso2v1.jar:?]
   at java.lang.Thread.run(Thread.java:829) [?:?]

```
This problem occurred solely when utilizing the Oracle database alongside the JDBC userstore, particularly with a significant number of roles included.

### Steps to Reproduce

1. Configure the APIM-3.2.0 server with the Oracle database.
2. Create multiple roles by assigning permissions. 
3. Execute following query and check whether the query returns around 11k. 

```SELECT UM_ROLE_NAME, UM_RESOURCE_ID, UM_IS_ALLOWED, UM_ACTION, UM_DOMAIN_NAME FROM UM_PERMISSION, UM_ROLE_PERMISSION, UM_DOMAIN WHERE UM_ROLE_PERMISSION.UM_PERMISSION_ID=UM_PERMISSION.UM_ID AND UM_ROLE_PERMISSION.UM_DOMAIN_ID=UM_DOMAIN.UM_DOMAIN_ID AND UM_PERMISSION.UM_TENANT_ID=-1234 AND UM_ROLE_PERMISSION.UM_TENANT_ID=-1234 ```

5. Try to update a created role permission using carbon UI. 

### Affected Component

APIM

### Version

3.2.0

**Comment by Tharanidk** [comment]
Hi @BLasan ,

Please close this issue, once you have merged this fix (https://github.com/wso2/carbon-apimgt/pull/12473).

Regards,
Tharani
