### ISSUE TITLE
TargetHandler “Connection reset” errors for forceful backend connection terminations - APIM 3.2.1

### ISSUE THREAD

**Issue by akila95fernando** [wso2/api-manager#2965]
### Description

Following error is logged in wso2carbon.log when running APIM 3.2.1 in JDK 17 , when backend abruptly closes the connection

```
ERROR - TargetHandler I/O error: Connection reset, CORRELATION_ID = 7exxxxxcd3
java.net.SocketException: Connection reset
at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
at org.apache.http.nio.reactor.ssl.SSLIOSession.receiveEncryptedData(SSLIOSession.java:482) ~[httpcore-nio_4.4.16.wso2v1.jar:?]
at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:544) ~[httpcore-nio_4.4.16.wso2v1.jar:?]
at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120) [httpcore-nio_4.4.16.wso2v1.jar:?]
at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) [httpcore-nio_4.4.16.wso2v1.jar:?]
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) [httpcore-nio_4.4.16.wso2v1.jar:?]
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) [httpcore-nio_4.4.16.wso2v1.jar:?]
at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) [httpcore-nio_4.4.16.wso2v1.jar:?]
at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [httpcore-nio_4.4.16.wso2v1.jar:?]
at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) [httpcore-nio_4.4.16.wso2v1.jar:?]
at java.lang.Thread.run(Unknown Source) [?:?] 
```

### Steps to Reproduce

While invoking an API ,forcefully RESET the connection from backend

### Affected Component

APIM

### Version

3.2.0 &  3.2.1

**Comment by RakhithaRR** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/2194
