### ISSUE TITLE
java.lang.NoSuchMethodException: org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTPictureBaseImpl.<init>(org.apache.xmlbeans.SchemaType, boolean) error observed when the registry index is happening

### ISSUE THREAD

**Issue by virajxx** [wso2/api-manager#2974]
### Description

Hi Team,

In the API Manager 4.1.0 version,  during registry indexing we observed the following error:

java.lang.NoSuchMethodException: org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTPictureBaseImpl.(org.apache.xmlbeans.SchemaType, boolean)
at java.base/java.lang.Class.getConstructor0(Class.java:3349)
at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
at org.apache.xmlbeans.impl.schema.SchemaTypeImpl.getJavaImplConstructor2(SchemaTypeImpl.java:1817)
at org.apache.xmlbeans.impl.schema.SchemaTypeImpl.createUnattachedSubclass(SchemaTypeImpl.java:1961)
at org.apache.xmlbeans.impl.schema.SchemaTypeImpl.createUnattachedNode(SchemaTypeImpl.java:1950)
at org.apache.xmlbeans.impl.schema.SchemaTypeImpl.createElementType(SchemaTypeImpl.java:1051)
at org.apache.xmlbeans.impl.values.XmlObjectBase.create_element_user(XmlObjectBase.java:938)
at org.apache.xmlbeans.impl.store.Xobj.getUser(Xobj.java:1675)
at org.apache.xmlbeans.impl.store.Cur.getUser(Cur.java:2659)
at org.apache.xmlbeans.impl.store.Cur.getObject(Cur.java:2652)
at org.apache.xmlbeans.impl.store.Cursor._getObject(Cursor.java:995)
at org.apache.xmlbeans.impl.store.Cursor.getObject(Cursor.java:2904)
at org.apache.poi.xwpf.usermodel.XWPFDocument.onDocumentRead(XWPFDocument.java:162)
at org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:169)
at org.apache.poi.xwpf.usermodel.XWPFDocument.(XWPFDocument.java:119)
at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.fetchDocumentContent_aroundBody4(DocumentIndexer.java:198)
at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.fetchDocumentContent(DocumentIndexer.java:163)
at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.getIndexedDocument_aroundBody0(DocumentIndexer.java:101)
at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.getIndexedDocument(DocumentIndexer.java:74)
at org.wso2.carbon.registry.indexing.indexer.IndexDocumentCreator.getIndexDocument(IndexDocumentCreator.java:333)
at org.wso2.carbon.registry.indexing.indexer.IndexDocumentCreator.createIndexDocument(IndexDocumentCreator.java:96)
at org.wso2.carbon.registry.indexing.AsyncIndexer$IndexingTask.createIndexDocument(AsyncIndexer.java:245)
at org.wso2.carbon.registry.indexing.AsyncIndexer$IndexingTask.run(AsyncIndexer.java:210)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)

Additionally, we found that this error is reported as a bug [1].

[1]. [Apache Jira Issue TIKA-2549](https://issues.apache.org/jira/browse/TIKA-2549)

Thank,
Viraj.

### Steps to Reproduce

Steps to reproduce the issue:

1. Update the WSO2 API Manager to the 146 U2 update level.
2. Create an API and add the following document [1] using the publisher.

[1]. [blog post.docx](https://github.com/user-attachments/files/16025022/blog.post.docx)

### Affected Component

APIM

### Version

4.1.0

**Comment by npamudika** [comment]
This is fixed in the public branch as the poi version is 5.2.5. Hence closing.
