### ISSUE TITLE
Sequence cannot be imported to the Integration Studio 8.1.0

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/api-manager#307]
### Description

We are unable to import the attached sequence to the updated Integration studio 8.1.0. It failed with the following error.
However, the tags are correct in the sequence configs.
![Screenshot from 2022-06-30 09-02-40](https://user-images.githubusercontent.com/28178905/176615268-5c0af2e6-7c8f-423c-a6c7-b8482eb4ac2c.png)

This same sequence can be created from the EI-6.6.0 management console and the same sequence can deploy to the MI-4.1.0 without any issue.

This issue is occurring only at the Integration Studio.
[MRMInteractionProxyOutSequence.zip](https://github.com/wso2/api-manager/files/9017279/MRMInteractionProxyOutSequence.zip)

### Steps to Reproduce

1. Create a sequence from Integration studio 8.1.0 by importing the attached sequence. You will encounter the reported issue.

### Affected Component

IntegrationStudio

### Version

8.1.0

### Relevant Log Output

```shell
Error while saving the diagram

org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxParsingException: Unexpected close tag </sequence>; expected </case>.
 at [row,col {unknown-source}]: [1,295]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
	at org.apache.axiom.om.impl.llom.OMElementImpl.buildNext(OMElementImpl.java:653)
	at org.apache.axiom.om.impl.llom.OMElementImpl.getFirstOMChild(OMElementImpl.java:670)
	at org.apache.axiom.om.impl.llom.OMElementImpl.getChildren(OMElementImpl.java:352)
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:40)
	at org.apache.synapse.config.xml.AnonymousListMediatorFactory.createAnonymousListMediator(AnonymousListMediatorFactory.java:48)
	at org.apache.synapse.config.xml.SwitchMediatorFactory.createSpecificMediator(SwitchMediatorFactory.java:99)
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98)
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:225)
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:46)
	at org.apache.synapse.config.xml.FilterMediatorFactory.createSpecificMediator(FilterMediatorFactory.java:136)
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98)
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:225)
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:46)
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createSpecificMediator(SequenceMediatorFactory.java:87)
	at org.wso2.integrationstudio.gmf.esb.diagram.validator.ProcessSourceView.validateArtifacts(ProcessSourceView.java:1074)
	at org.wso2.integrationstudio.gmf.esb.diagram.validator.ProcessSourceView.validate(ProcessSourceView.java:1016)
	at org.wso2.integrationstudio.gmf.esb.diagram.validator.ProcessSourceView.mediatorValidation(ProcessSourceView.java:960)
	at org.wso2.integrationstudio.gmf.esb.diagram.validator.ProcessSourceView.synapseValidation(ProcessSourceView.java:793)
	at org.wso2.integrationstudio.gmf.esb.diagram.validator.ProcessSourceView.validateSynapseContent(ProcessSourceView.java:149)
	at org.wso2.integrationstudio.gmf.esb.diagram.part.EsbMultiPageEditor$10.run(EsbMultiPageEditor.java:1314)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5101)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4584)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: com.ctc.wstx.exc.WstxParsingException: Unexpected close tag </sequence>; expected </case>.
 at [row,col {unknown-source}]: [1,295]
	at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:606)
	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:479)
	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:464)
	at com.ctc.wstx.sr.BasicStreamReader.reportWrongEndElem(BasicStreamReader.java:3283)
	at com.ctc.wstx.sr.BasicStreamReader.readEndElem(BasicStreamReader.java:3210)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2829)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1072)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
	... 46 more
```

**Comment by sachithKay** [comment]
This seems to a be a very specific scenario, which occurs when there are two fault mediators in a scenario where there is a filter mediator, inside a switch mediator wrapper by another filter mediator.
If you remove one of the fault mediators, it works.

Following scenario also works.

![Screenshot 2022-07-01 at 12 34 05](https://user-images.githubusercontent.com/22365810/176843312-9bdf6ab2-ecbe-4efd-b6c8-e03f5bcb80fe.png)
