### ISSUE TITLE
APIM Runtime Page Broken 

### ISSUE THREAD

**Issue by Chilliwiddit** [wso2/api-manager#3137]
### Description

Their is a failure to load the UI when clicking the Runtime link, regardless of the API. 

The console error stack is given below:

`react-dom.production.min.js:188 TypeError: Cannot read properties of undefined (reading 'production')
    at ai (MaxBackendTps.jsx:184:77)
    at va (react-dom.production.min.js:160:137)
    at Au (react-dom.production.min.js:289:337)
    at bc (react-dom.production.min.js:279:389)
    at mc (react-dom.production.min.js:279:320)
    at vc (react-dom.production.min.js:279:180)
    at ic (react-dom.production.min.js:270:88)
    at uc (react-dom.production.min.js:272:300)
    at Wo (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273`

### Steps to Reproduce

1. Select any API
2. Click on the Runtime Page

### Affected Component

APIM

### Version

4.4.0

### Environment Details (with versions)

OS: Ubuntu

### Related Issues

Unable to utilize Runtime Issues

### Suggested Labels

UI, 4.4.0

**Comment by Chilliwiddit** [comment]
This bug has been fixed

**Comment by Chilliwiddit** [comment]
This bug has been fixed
