### ISSUE TITLE
TM cannot publish events to the broker after the following error of more than 100

### ISSUE THREAD

**Issue by JanithaSampathBandara** [wso2/api-manager#3183]
### Description

Hi All,

Once the following error is observed more than 100(by default there are 100 connections in the connection pool[1]), it is impossible to connect to the broker via JMS publisher.

```
ERROR - pool-55-thread-1 - JMSConnectionFactory Object AMQConnection:
Host: x.x.x.x
Port: 5672
Virtual Host: carbon
Client ID: clientid
Active session count: 0 has been closed
javax.jms.IllegalStateException: Object AMQConnection:
Host: x.x.x.x
Port: 5672
Virtual Host: carbon
Client ID: clientid
Active session count: 0 has been closed
	at org.wso2.andes.client.Closeable.checkNotClosed(Closeable.java:75) ~[andes_3.3.29.2.jar:?]
	at org.wso2.andes.client.AMQConnection.createSession(AMQConnection.java:715) ~[andes_3.3.29.2.jar:?]
	at org.wso2.andes.client.AMQConnection.createSession(AMQConnection.java:707) ~[andes_3.3.29.2.jar:?]
	at org.wso2.andes.client.AMQConnection.createSession(AMQConnection.java:701) ~[andes_3.3.29.2.jar:?]
	at org.wso2.andes.client.AMQConnection.createSession(AMQConnection.java:86) ~[andes_3.3.29.2.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSUtils.createSession(JMSUtils.java:438) ~[org.wso2.carbon.event.output.adapter.jms_5.2.57.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory$PoolableJMSConnectionFactory.makeObject(JMSConnectionFactory.java:358) [org.wso2.carbon.event.output.adapter.jms_5.2.57.jar:?]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181) [commons-pool_1.5.6.wso2v1.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.getConnectionFromPool(JMSConnectionFactory.java:286) [org.wso2.carbon.event.output.adapter.jms_5.2.57.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSMessageSender.send(JMSMessageSender.java:88) [org.wso2.carbon.event.output.adapter.jms_5.2.57.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.JMSEventAdapter$JMSSender.run(JMSEventAdapter.java:284) [org.wso2.carbon.event.output.adapter.jms_5.2.57.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

Regards,
Janitha
[1]https://github.com/wso2/carbon-analytics-common/blob/639d15457f4024b7abc0511a0ba8e1eed646ca79/components/event-publisher/event-output-adapters/org.wso2.carbon.event.output.adapter.jms/src/main/java/org/wso2/carbon/event/output/adapter/jms/internal/util/JMSConnectionFactory.java#L110

### Steps to Reproduce

Thrown the same error as above by patching the Andes code

### Affected Component

APIM

### Version

3.2.1.11

**Comment by dakshina99** [comment]
This is fixed through https://github.com/wso2/carbon-analytics-common/pull/846
