### ISSUE TITLE
Error while invoking an API when super admin details are changed from default values

### ISSUE THREAD

**Issue by Ashi1993** [wso2/api-manager#3192]
### Description

Getting an error while invoking an API when the super admin details are changed from default values. Used the APIM 4.4.0 Alpha release on h2 database. We are using an email as username for the admin. 

So we changed the super admin details as follows in the deployment toml file.
```
[super_admin]
username = "admin@wso2.com"
password = "wso2123"
create_admin_account = true
```

Added below config as well to enable emails domains
```
[tenant_mgt]
enable_email_domain = true
```

Curl Request
```
curl --location 'https://localhost:8243/pizzashack/1.0.0/order' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Internal-Key: eyJraWQiOiJnYXRld2F5X2NlcnRpZmljYXRlX2FsaWFzIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJhZG1pbkB3c28yLmNvbUBjYXJib24uc3VwZXIiLCJhdWQiOiI1NDEyMTE1My1lZTM5LTRmMTItYmE4My1jZDE2ZDM3ZWM5ODEiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo5NDQzL29hdXRoMi90b2tlbiIsImtleXR5cGUiOiJQUk9EVUNUSU9OIiwic3Vic2NyaWJlZEFQSXMiOlt7Im5hbWUiOiJQaXp6YVNoYWNrQVBJIiwiY29udGV4dCI6Ii9waXp6YXNoYWNrLzEuMC4wIiwidmVyc2lvbiI6IjEuMC4wIiwicHVibGlzaGVyIjoiYWRtaW5Ad3NvMi5jb20iLCJzdWJzY3JpcHRpb25UaWVyIjpudWxsLCJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjpudWxsfV0sImV4cCI6MTcyODMzNzA3MiwidG9rZW5fdHlwZSI6IkludGVybmFsS2V5IiwiaWF0IjoxNzI4Mjc3MDcyLCJqdGkiOiI1NjY0YjgyMi0yNjQxLTRkYjItOGNmMC0yYTMxMjI2ZDEwMDIifQ.OWSftXGJMUzhr0kAQYjHoS1bS01f8hHmSt6Otu9gwLh_26VlSDZk3uz2bfD-zDHu88p1s9bu6eOWs1E4IZN4C9HrZsaP0vMc-WKAiMinN7l3txovAKolAsE5dqIQI4plfda_cC31kYaWRCbo5JTIh4dPSNYgOASb-EH-BBkqIodOeWKklqGo_gOur3261ZkuLxBb7GzxTJCkj--74lx5pHNnxPiZmqagf6lFGye6GrZ01v0TvRsPRDTMmnGUb9NsUHG66RwGa6_mghJE1fDwvNY9xbuZQn05KLATAAMpa9Wz7MZ4OCSN8HByQk9ieP2mcB_f45WasAwKdfjhQBQURg' \
--data '{
  "customerName": "string",
  "delivered": true,
  "address": "string",
  "pizzaType": "string",
  "creditCardNumber": "string",
  "quantity": 0,
  "orderId": "string"
}'
```

Error got after invoking the Pizza Shack API
```
{
    "Fault": {
        "faultcode": "soapenv:Server",
        "faultstring": "Cannot invoke \"org.wso2.carbon.apimgt.impl.APIManagerConfigurationService.getAPIManagerConfiguration()\" because \"ajc$this.amConfigService\" is null",
        "detail": null
    }
}
```

### Steps to Reproduce

1. Change the super admin details as follows. 
```
[super_admin]
username = "admin@wso2.com"
password = "wso2123"
create_admin_account = true
```
2.Added below config as well to enable emails domains
```
[tenant_mgt]
enable_email_domain = true
```
3. Log into publisher using super admin credential and publish the PizzaShack API.
4. Invoke the API using following curl command.
```
curl --location 'https://localhost:8243/pizzashack/1.0.0/order' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Internal-Key: eyJraWQiOiJnYXRld2F5X2NlcnRpZmljYXRlX2FsaWFzIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJhZG1pbkB3c28yLmNvbUBjYXJib24uc3VwZXIiLCJhdWQiOiI1NDEyMTE1My1lZTM5LTRmMTItYmE4My1jZDE2ZDM3ZWM5ODEiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo5NDQzL29hdXRoMi90b2tlbiIsImtleXR5cGUiOiJQUk9EVUNUSU9OIiwic3Vic2NyaWJlZEFQSXMiOlt7Im5hbWUiOiJQaXp6YVNoYWNrQVBJIiwiY29udGV4dCI6Ii9waXp6YXNoYWNrLzEuMC4wIiwidmVyc2lvbiI6IjEuMC4wIiwicHVibGlzaGVyIjoiYWRtaW5Ad3NvMi5jb20iLCJzdWJzY3JpcHRpb25UaWVyIjpudWxsLCJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjpudWxsfV0sImV4cCI6MTcyODMzNzA3MiwidG9rZW5fdHlwZSI6IkludGVybmFsS2V5IiwiaWF0IjoxNzI4Mjc3MDcyLCJqdGkiOiI1NjY0YjgyMi0yNjQxLTRkYjItOGNmMC0yYTMxMjI2ZDEwMDIifQ.OWSftXGJMUzhr0kAQYjHoS1bS01f8hHmSt6Otu9gwLh_26VlSDZk3uz2bfD-zDHu88p1s9bu6eOWs1E4IZN4C9HrZsaP0vMc-WKAiMinN7l3txovAKolAsE5dqIQI4plfda_cC31kYaWRCbo5JTIh4dPSNYgOASb-EH-BBkqIodOeWKklqGo_gOur3261ZkuLxBb7GzxTJCkj--74lx5pHNnxPiZmqagf6lFGye6GrZ01v0TvRsPRDTMmnGUb9NsUHG66RwGa6_mghJE1fDwvNY9xbuZQn05KLATAAMpa9Wz7MZ4OCSN8HByQk9ieP2mcB_f45WasAwKdfjhQBQURg' \
--data '{
  "customerName": "string",
  "delivered": true,
  "address": "string",
  "pizzaType": "string",
  "creditCardNumber": "string",
  "quantity": 0,
  "orderId": "string"
}'
```

### Affected Component

APIM

### Version

4.4.0-Alpha

### Environment Details (with versions)

OS - MacOS 14.6.1
DB - H2

### Relevant Log Output

```shell
[2024-10-07 10:30:41,429] ERROR - ServerWorker Error processing POST request for : /pizzashack/1.0.0/order.
java.lang.NullPointerException: Cannot invoke "org.wso2.carbon.apimgt.impl.APIManagerConfigurationService.getAPIManagerConfiguration()" because "ajc$this.amConfigService" is null
	at org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder.getAPIManagerConfiguration_aroundBody10(ServiceReferenceHolder.java:133) ~[org.wso2.carbon.apimgt.gateway_9.30.10.jar:?]
	at org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder.getAPIManagerConfiguration(ServiceReferenceHolder.java:1) ~[org.wso2.carbon.apimgt.gateway_9.30.10.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.GatewayUtils.isOnDemandLoading_aroundBody134(GatewayUtils.java:1621) ~[org.wso2.carbon.apimgt.gateway_9.30.10.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.GatewayUtils.isOnDemandLoading(GatewayUtils.java:1) ~[org.wso2.carbon.apimgt.gateway_9.30.10.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.Utils.getSelectedAPIList_aroundBody58(Utils.java:690) ~[org.wso2.carbon.apimgt.gateway_9.30.10.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.Utils.getSelectedAPIList(Utils.java:1) ~[org.wso2.carbon.apimgt.gateway_9.30.10.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.DefaultAPIHandler.handleRequestInFlow_aroundBody0(DefaultAPIHandler.java:77) ~[org.wso2.carbon.apimgt.gateway_9.30.10.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.DefaultAPIHandler.handleRequestInFlow(DefaultAPIHandler.java:1) ~[org.wso2.carbon.apimgt.gateway_9.30.10.jar:?]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.invokeHandlers(Axis2SynapseEnvironment.java:1202) ~[synapse-core_4.0.0.wso2v128.jar:4.0.0-wso2v128]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:288) ~[synapse-core_4.0.0.wso2v128.jar:4.0.0-wso2v128]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) ~[synapse-core_4.0.0.wso2v128.jar:4.0.0-wso2v128]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) ~[axis2_1.6.1.wso2v76.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:401) ~[synapse-nhttp-transport_4.0.0.wso2v128.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:460) ~[synapse-nhttp-transport_4.0.0.wso2v128.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:208) ~[synapse-nhttp-transport_4.0.0.wso2v128.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v76.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by nimsara66** [comment]
@Ashi1993 I was unable to replicate the above error on [wso2am-4.4.0-alpha](https://github.com/wso2/product-apim/releases/download/v4.4.0-alpha/wso2am-4.4.0-alpha.zip).

Could you please confirm that you have implemented the complete configuration in the `deployments.toml` file, as outlined in the [setup-an-e-mail-login](https://apim.docs.wso2.com/en/4.1.0/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords/#setup-an-e-mail-login) documentation?

Below is the complete configuration for your reference:

```
[super_admin]
username = "admin@wso2.com"
password = "wso2123"
create_admin_account = true

[tenant_mgt]
enable_email_domain= true

[apim.throttling]
username = "$ref{super_admin.username}@carbon.super"

[apim.throttling.policy_deploy]
username = "$ref{super_admin.username}@carbon.super"

[apim.throttling.jms]
username="admin!wso2.com!carbon.super"
password = "$ref{super_admin.password}"
```

**Comment by Ashi1993** [comment]
Hi @nimsara66,

I tested the API in APIM-4.4.0-beta with the above configurations and flow works as expected. Thanks for the response.

Regards,
Ashirwada
