### ISSUE TITLE
Okta keys fails to load in the applications page randomly

### ISSUE THREAD

**Issue by Piumal1999** [wso2/api-manager#3226]
### Description

Check the video:
(Initially, it shows that the production keys are generated with Okta. However, after switching between tabs multiple times, it shows that the keys are not generated.)

https://github.com/user-attachments/assets/92257684-1e91-4912-b187-c4f85036ecf7

### Steps to Reproduce

1. Follow the steps in [1].
2. Go to Applications → Production Keys → OAuth2 tokens, and select the Okta key created in the previous step.
3. It may or may not display the generated keys.

[1] https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-okta-connector/

### Affected Component

APIM

### Version

4.4.0

### Environment Details (with versions)

Distributed Setup
Chrome

**Comment by hisanhunais** [comment]
- The issue was reproducible. At the time when the issue occurs, the following log in printed on the server console.

```
ERROR - UserAwareAPIConsumer Error while retrieving Application Information
org.wso2.carbon.apimgt.api.APIManagementException: Error while retrieving Oauth Application
	at org.wso2.okta.client.OktaOAuthClient.handleException(OktaOAuthClient.java:774) ~[okta.key.manager_3.2.1.jar:?]
...
...
...
Caused by: org.wso2.carbon.apimgt.impl.kmclient.KeyManagerClientException: Received status code: 429 Reason:
	at org.wso2.okta.client.OktaErrorDecoder.decode(OktaErrorDecoder.java:46) ~[okta.key.manager_3.2.1.jar:?]
...
...
```
- This means the rate limit of Okta API has been reached. 
- When looking at the rate limit of `/oauth2/v1/clients` Okta API, the limit is 25 Per min.

<img width="1035" alt="Image" src="https://github.com/user-attachments/assets/8b39c941-19f8-475d-8a2b-ac8e321ea23f" />

- The token rate limit is set to 50% of each API rate limit. This means that the token can be used to invoke the `/oauth2/v1/clients` only 12 times per min

<img width="1035" alt="Image" src="https://github.com/user-attachments/assets/5326dc82-005a-48e6-9068-805735b59fcd" />

- When the minute passes, and the rate limit resets, the keys can be seen again.
