### ISSUE TITLE
[APIM-4.0.0] Getting "Unclassified Authentication Error" when using JWT tokens and invoking API for the second time. (using IS 5.11 as KM)

### ISSUE THREAD

**Issue by hasithakn** [wso2/api-manager#433]
### Description

APIM 4.0.0 setup-ed with IS as KM and was able to get bellow error when invoking API with JWT token. 

- The initial invoke of the API was success but when invoking 2nd time, getting below error,

```
{
    "code": "0",
    "message": "Unclassified Authentication Failure",
    "description": "Unclassified Authentication Failure"
}
```

- As a workaround disabled the **token cache**, Seems like issue it's when validating HOK (cnf) claim in jwt,

1) when we validate with token cache enabled it's executing below method,

https://github.com/wso2-support/carbon-apimgt/blob/support-9.0.174.x-full/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/jwt/JWTValidator.java#L497-L505

2) when we validate with token cache disabled it's executing below method,

https://github.com/wso2-support/carbon-apimgt/blob/support-9.0.174.x-full/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/jwt/JWTValidatorImpl.java#L96-L109

And also debugged and checked that in 2nd scenario, it's skipping the HOK validation in the flow. Therefore it seems that issue is when validating the `cnf` claim in JWT token.

### Steps to Reproduce

- Setup APIM 4.0.0 with IS as KM
- Get JWT token from APIM, 
- Invoke API two times.

### Affected Component

APIM

### Version

4.0.0

### Environment Details (with versions)

Ubuntu 20.04 , APIM 4.0.0 with IS 5.11

### Relevant Log Output

```
[2022-07-11 10:27:33,964] ERROR - APIAuthenticationHandler API authentication failure due to Unclassified Authentication Failure
org.wso2.carbon.apimgt.gateway.handlers.security.APISecurityException: Unclassified Authentication Failure
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate_aroundBody56(APIAuthenticationHandler.java:541) ~[org.wso2.carbon.apimgt.gateway_9.0.174.182.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate(APIAuthenticationHandler.java:521) ~[org.wso2.carbon.apimgt.gateway_9.0.174.182.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody46(APIAuthenticationHandler.java:408) [org.wso2.carbon.apimgt.gateway_9.0.174.182.jar:?]
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:361) [org.wso2.carbon.apimgt.gateway_9.0.174.182.jar:?]
	at org.apache.synapse.api.API.process(API.java:389) [synapse-core_2.1.7.wso2v227_33.jar:2.1.7-wso2v227.33]
	at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) [synapse-core_2.1.7.wso2v227_33.jar:2.1.7-wso2v227.33]
	at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) [synapse-core_2.1.7.wso2v227_33.jar:2.1.7-wso2v227.33]
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:59) [synapse-core_2.1.7.wso2v227_33.jar:2.1.7-wso2v227.33]
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:84) [synapse-core_2.1.7.wso2v227_33.jar:2.1.7-wso2v227.33]
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:70) [synapse-core_2.1.7.wso2v227_33.jar:2.1.7-wso2v227.33]
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) [synapse-core_2.1.7.wso2v227_33.jar:2.1.7-wso2v227.33]
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) [synapse-core_2.1.7.wso2v227_33.jar:2.1.7-wso2v227.33]
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101) [synapse-core_2.1.7.wso2v227_33.jar:2.1.7-wso2v227.33]
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v63_3.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375) [synapse-nhttp-transport_2.1.7.wso2v227_36.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:434) [synapse-nhttp-transport_2.1.7.wso2v227_36.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182) [synapse-nhttp-transport_2.1.7.wso2v227_36.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v63_3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]

```

### Suggested Labels

`Unclassified Authentication Failure`

**Comment by hasithakn** [comment]
Closing this issue : 
This Issue does not occur with correct MTLS certs and SP certs.
