### ISSUE TITLE
Updating Azure JMS from Qpid-jms-client 0.32 to 2.0

### ISSUE THREAD

**Issue by JanakaPushpakumara** [wso2/api-manager#448]
### Problem

We attempted to upgrade the qpid jms client to version 2.0.0 but we ran into a class cast exception [1]. Upon debugging the case further, we were able to conclude that this happens due to a JMS API incompatibility. As per our understanding and analysis, version 2.0.0 [2] is compiled using Jakarta JMS API 3.0 whereas our JMS transport is built on top of JMS API 2.0.

Moreover, we attempted to upgrade the qpid jms client to version 1.6.0 (the next best version) since it is compatible with the JMS API version used in our product. Here, I was able to initiate the JMS transport successfully (server started without any errors). But I ran into a class not found exception below when deploying the JMS consumer. 

```
[2022-07-08 10:43:46,564]  WARN {io.netty.channel.ChannelInitializer} - Failed to initialize a channel. Closing: [id: 0x6dbf46e1] java.lang.NoClassDefFoundError: io/netty/handler/ssl/OpenSslX509KeyManagerFactory
    at org.apache.qpid.jms.transports.netty.NettyTcpTransport.configureChannel(NettyTcpTransport.java:479)
    at org.apache.qpid.jms.transports.netty.NettyTcpTransport$1.initChannel(NettyTcpTransport.java:163)
    at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:139)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:132)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1267)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:139)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:805)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:456)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:375)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:425)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:402)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: io.netty.handler.ssl.OpenSslX509KeyManagerFactory cannot be found by qpid_jms_client_1.6.0_1.0.0
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:485)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    ... 17 more 
```
When further troubleshooting this issue, we found out that there is a set of netty libraries bundled into our product in the plugins directory. This was of version '4.0.39' and this was conflicting with the netty libraries required to upgrade to the qpid jms client version 1.6.0 leading to the class not found exception. The netty library version required for the upgrade is '4.1.75'. You can refer to the mvn repository in [2] for more information. Is this library upgrade something we can facilitate for EI 6.6.0? 

Furthermore, we noticed that the netty libraries are upgraded in MI 4.1.0. Therefore, we tried the qpid library upgrade in it. Here we were able to get the consumer deployed and we were able to successfully verify a publisher/consumer flow.

it is vital for upgrades to the latest qpid library. This was a recommendation from the Azure support team as the current client library used is 4 years old. They believe this would resolve some of the issues observed in the environment. Furthermore, we expect version 1.6.0 to be a short term solution whereas the product should look at facilitating version 2.0.0. 

[1] [https://github.com/wso2-support/wso2-axis2-transports/blob/support-2.0.0-wso2v42/modules/jms/src/main/java/org/apache/axis2/transport/jms/JMSUtils.java#L760](https://github.com/wso2-support/wso2-axis2-transports/blob/support-2.0.0-wso2v42/modules/jms/src/main/java/org/apache/axis2/transport/jms/JMSUtils.java#L760)
[2] [https://mvnrepository.com/artifact/org.apache.qpid/qpid-jms-client/2.0.0](https://mvnrepository.com/artifact/org.apache.qpid/qpid-jms-client/2.0.0)
[3] [https://mvnrepository.com/artifact/org.apache.qpid/qpid-jms-client/1.6.0](https://mvnrepository.com/artifact/org.apache.qpid/qpid-jms-client/1.6.0)

Thanks, 
Janaka.

### Solution

it is vital for upgrades to the latest qpid library. This was a recommendation from the Azure support team as the current client library used is 4 years old. They believe this would resolve some of the issues observed in the environment. Furthermore, we expect version 1.6.0 to be a short term solution whereas the product should look at facilitating version 2.0.0. 

### Affected Component

APIM

### Version

EI 6.6.0

### Implementation

N/a

### Suggested Labels

wso2ei-6.6.0

**Comment by dulithsenanayake** [comment]
Hi all,

All netty jars are already updated. Hence closing this issue.

Thanks,
Dulith
