### ISSUE TITLE
WSO2 Micro Integrator 4.1.0 on aarch64

### ISSUE THREAD

**Issue by isurul28** [wso2/api-manager#462]
### Description

When we deploy a MI 4.1.0 pack update level 04 pack on aarch64 architecture we are getting below error during MI start up

```
[2022-06-22 08:09:42,549] ERROR {Framework} - FrameworkEvent ERROR org.osgi.framework.BundleException: Could not resolve module: io.netty.tcnative-boringssl-static [70]
  Unresolved requirement: Require-Capability: osgi.native; native.paths.0:List<String>="META-INF/native/libnetty_tcnative_osx_x86_64.jnilib"; native.paths.2:List<String>="META-INF/native/libnetty_tcnative_linux_x86_64.so"; native.paths.1:List<String>="META-INF/native/libnetty_tcnative_osx_aarch_64.jnilib"; native.paths.4:List<String>="META-INF/native/netty_tcnative_windows_x86_64.dll"; native.paths.3:List<String>="META-INF/native/libnetty_tcnative_linux_aarch_64.so"; filter:="(|(&(|(osgi.native.osname~=macos)(osgi.native.osname~=macosx))(osgi.native.processor~=x86_64))(&(|(osgi.native.osname~=macos)(osgi.native.osname~=macosx))(osgi.native.processor~=aarch_64))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86_64))(&(osgi.native.osname~=linux)(osgi.native.processor~=aarch_64))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86_64)))
 at org.eclipse.osgi.container.Module.start(Module.java:457)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```
The netty have fix this on version 4.1.79. We need to update the product libraries in MI 4.1.0

### Steps to Reproduce

1. Run the MI 4.1.0 with latest update level in aarch64 system
2. During the start up you will see a netty error

### Affected Component

MI

### Version

4.1.0

**Comment by chameerar** [comment]
This issue is fixed in https://github.com/wso2/api-manager/issues/462
