### ISSUE TITLE
[4.0.0 Migration Testing] Error when super tenant API is attached with a fault sequence

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#598]
**Description:**
Getting below error when migrating from 3.0 - 4.0 when there is a super tenant API that has a fault sequence attached.

```
[2022-08-05 11:41:46,174] ERROR - ClassMediatorFactory Error loading class : org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler - Class not found
java.lang.ClassNotFoundException: org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler cannot be found by synapse-core_2.1.7.wso2v227
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_281]
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:100) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:251) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:53) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createSpecificMediator(SequenceMediatorFactory.java:87) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:251) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineSequence(SynapseXMLConfigurationFactory.java:232) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.wso2.carbon.sequences.services.SequenceAdmin.addSequence(SequenceAdmin.java:412) [org.wso2.carbon.sequences_4.7.99.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence_aroundBody0(SequenceAdminServiceProxy.java:58) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence(SequenceAdminServiceProxy.java:54) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:753) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody4(InMemoryAPIDeployer.java:170) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:148) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:121) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:113) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody18(GatewayStartupListener.java:255) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:244) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody28(GatewayStartupListener.java:244) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:244) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:338) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:335) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
[2022-08-05 11:41:46,246]  WARN - SynapseXMLConfigurationFactory Sequence configuration: Test:v1.0--Fault cannot be built - Continue in fail-safe mode
org.apache.synapse.SynapseException: Error loading class : org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler - Class not found
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:105) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:251) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:53) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createSpecificMediator(SequenceMediatorFactory.java:87) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:251) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineSequence(SynapseXMLConfigurationFactory.java:232) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.wso2.carbon.sequences.services.SequenceAdmin.addSequence(SequenceAdmin.java:412) [org.wso2.carbon.sequences_4.7.99.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence_aroundBody0(SequenceAdminServiceProxy.java:58) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence(SequenceAdminServiceProxy.java:54) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:753) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody4(InMemoryAPIDeployer.java:170) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:148) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:121) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:113) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody18(GatewayStartupListener.java:255) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:244) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody28(GatewayStartupListener.java:244) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:244) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:338) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:335) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler cannot be found by synapse-core_2.1.7.wso2v227
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_281]
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:100) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	... 23 more
```

This is because in the below code we remove tenants with isActive set as false.
```
List<Tenant> tenants = APIUtil.getAllTenantsWithSuperTenant();
tenants.removeIf(t -> (!t.isActive()));
```

As per the implementation of getAllTenantsWithSuperTenant in APIUtil we are not setting active status for super tenant when adding it. Therefore `carbon.super` gets removed from the tenant list and the fault sequence modification are not applied.
This is fixed in master branch by removing the logic to remove inactive tenants. Or else we can fix the APIUtil method to set super tenant status as well but that would require a product patch.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create an API in 3.0 and attach a fault sequence to it. (a common sequence would do)
2. Migrate to 4.0.0 and the above error will pop up during APIM migration.

**Related Issues:**

**Comment by dushaniw** [comment]
**Description:**
Getting below error when migrating from 3.0 - 4.0 when there is a super tenant API that has a fault sequence attached.

```
[2022-08-05 11:41:46,174] ERROR - ClassMediatorFactory Error loading class : org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler - Class not found
java.lang.ClassNotFoundException: org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler cannot be found by synapse-core_2.1.7.wso2v227
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_281]
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:100) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:251) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:53) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createSpecificMediator(SequenceMediatorFactory.java:87) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:251) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineSequence(SynapseXMLConfigurationFactory.java:232) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.wso2.carbon.sequences.services.SequenceAdmin.addSequence(SequenceAdmin.java:412) [org.wso2.carbon.sequences_4.7.99.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence_aroundBody0(SequenceAdminServiceProxy.java:58) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence(SequenceAdminServiceProxy.java:54) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:753) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody4(InMemoryAPIDeployer.java:170) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:148) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:121) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:113) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody18(GatewayStartupListener.java:255) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:244) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody28(GatewayStartupListener.java:244) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:244) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:338) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:335) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
[2022-08-05 11:41:46,246]  WARN - SynapseXMLConfigurationFactory Sequence configuration: Test:v1.0--Fault cannot be built - Continue in fail-safe mode
org.apache.synapse.SynapseException: Error loading class : org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler - Class not found
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:105) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:251) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:53) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createSpecificMediator(SequenceMediatorFactory.java:87) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:98) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:251) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineSequence(SynapseXMLConfigurationFactory.java:232) [synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	at org.wso2.carbon.sequences.services.SequenceAdmin.addSequence(SequenceAdmin.java:412) [org.wso2.carbon.sequences_4.7.99.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence_aroundBody0(SequenceAdminServiceProxy.java:58) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.utils.SequenceAdminServiceProxy.addSequence(SequenceAdminServiceProxy.java:54) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI_aroundBody96(APIGatewayAdmin.java:753) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.service.APIGatewayAdmin.deployAPI(APIGatewayAdmin.java:653) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody4(InMemoryAPIDeployer.java:170) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:148) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:121) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:113) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody18(GatewayStartupListener.java:255) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:244) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody28(GatewayStartupListener.java:244) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:244) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:338) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:335) [org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler cannot be found by synapse-core_2.1.7.wso2v227
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_281]
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:100) ~[synapse-core_2.1.7.wso2v227.jar:2.1.7-wso2v227]
	... 23 more
```

This is because in the below code we remove tenants with isActive set as false.
```
List<Tenant> tenants = APIUtil.getAllTenantsWithSuperTenant();
tenants.removeIf(t -> (!t.isActive()));
```

As per the implementation of getAllTenantsWithSuperTenant in APIUtil we are not setting active status for super tenant when adding it. Therefore `carbon.super` gets removed from the tenant list and the fault sequence modification are not applied.
This is fixed in master branch by removing the logic to remove inactive tenants. Or else we can fix the APIUtil method to set super tenant status as well but that would require a product patch.

**Suggested Labels:**


**Suggested Assignees:**


**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create an API in 3.0 and attach a fault sequence to it. (a common sequence would do)
2. Migrate to 4.0.0 and the above error will pop up during APIM migration.

**Related Issues:**

**Comment by dushaniw** [comment]
fixed with https://github.com/wso2-extensions/apim-migration-resources/pull/244
