### ISSUE TITLE
Error while running API Revision Related Migration in 4.0.0 client

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#605]
### Description

Getting below error when running the APIM migration client.
```
[2022-08-10 14:04:36,912] ERROR - APIMMigrationService WSO2 API-M Migration Task : Generic exception occurred while migrating
java.lang.NullPointerException: null
	at java.io.StringReader.<init>(StringReader.java:50) ~[?:1.8.0_342]
	at org.wso2.carbon.apimgt.impl.importexport.utils.CommonUtil.writeFile_aroundBody12(CommonUtil.java:204) ~[org.wso2.carbon.apimgt.impl-9.0.174.211-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.CommonUtil.writeFile(CommonUtil.java:201) ~[org.wso2.carbon.apimgt.impl-9.0.174.211-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.CommonUtil.writeToYamlOrJson_aroundBody32(CommonUtil.java:423) ~[org.wso2.carbon.apimgt.impl-9.0.174.211-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.importexport.utils.CommonUtil.writeToYamlOrJson(CommonUtil.java:414) ~[org.wso2.carbon.apimgt.impl-9.0.174.211-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.addAPIProductMetaInformationToArchive(ExportUtils.java:1000) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.185.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.exportApiProduct(ExportUtils.java:266) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.185.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.ImportExportAPIServiceImpl.exportAPIProduct(ImportExportAPIServiceImpl.java:129) ~[?:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPIProductRevision_aroundBody602(APIProviderImpl.java:9556) ~[org.wso2.carbon.apimgt.impl-9.0.174.211-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPIProductRevision(APIProviderImpl.java:9522) ~[org.wso2.carbon.apimgt.impl-9.0.174.211-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPIProductRevision(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl-9.0.174.211-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.migration.client.MigrateFrom320.apiRevisionRelatedMigration(MigrateFrom320.java:352) ~[org.wso2.carbon.apimgt.migrate.client-4.0.0-9.jar:4.0.0-${buildNumber}]
	at org.wso2.carbon.apimgt.migration.APIMMigrationService.completedServerStartup(APIMMigrationService.java:381) [org.wso2.carbon.apimgt.migrate.client-4.0.0-9.jar:4.0.0-${buildNumber}]
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyAfter(CarbonCoreServiceComponent.java:264) [org.wso2.carbon.core_4.6.2.275.jar:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:218) [org.wso2.carbon.core_4.6.2.275.jar:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:323) [org.wso2.carbon.core_4.6.2.275.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:118) [org.wso2.carbon.tenant.throttling.agent_4.9.10.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:96) [org.wso2.carbon.tenant.throttling.agent_4.9.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) [org.wso2.carbon.core_4.6.2.275.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) [org.wso2.carbon.core_4.6.2.275.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) [org.wso2.carbon.core_4.6.2.275.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

```

### Steps to Reproduce

1. Steup APIM 3.2.0
2. Create an API Product 
3. Migrate to 4.0.0

### Affected Component

APIM

### Version

4.0.0

### Environment Details (with versions)

Old APIM Version : 3.2.0
Migrate To Version : 4.0.0
DB : MySQL

**Comment by msm1992** [comment]
Created a patch ticket to get the NPE fixed in carbon-apimgt : https://github.com/wso2-enterprise/wso2-apim-internal/issues/492
