### ISSUE TITLE
Identity component migration failing from APIM 3.0.0 to 4.1.0 when AD is used as primary user store

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#628]
### Description

Identity component migration is failing when performing the "User ID migration" step when using Active Directory as the primary userstore. When updating the userId of user, it is throwing the below error.

```
ERROR {org.wso2.carbon.is.migration.service.v5100.migrator.UserIDMigrator} - Error occurred while updating user id for the user. user id updating process stopped at the offset 0 in domain PRIMARY in tenant carbon.super org.wso2.carbon.user.core.UserStoreException: One or more attributes you are trying to add/update are not supported by underlying LDAP for user : $DUPLICATE-170a5
	at org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager.handleException(ReadWriteLDAPUserStoreManager.java:2248)
	at org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager.doSetUserAttributes(ReadWriteLDAPUserStoreManager.java:903)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doSetUserClaimValues(AbstractUserStoreManager.java:738)
	at org.wso2.carbon.is.migration.service.v5100.migrator.UserIDMigrator.updateUserIDClaim(UserIDMigrator.java:339)
	at org.wso2.carbon.is.migration.service.v5100.migrator.UserIDMigrator.migrate(UserIDMigrator.java:240)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:76)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

### Steps to Reproduce

1. Perform APIM 3.0.0 to APIM 4.0.0 identity component migration having an AD as the primary user store. Can use IS LDAP here.
2. Observe the error during migration.

### Affected Component

APIM

### Version

4.1.0

### Related Issues

https://github.com/wso2-enterprise/wso2-apim-internal/issues/456

**Comment by tharikaGitHub** [comment]
This issue was reported to the IS Team and as per their feedback it is okay to remove the UserID migrator step if an Active Directory is used as the primary user store. We can add this to the documentation if required.

**Comment by tharikaGitHub** [comment]
Asked to add this information to IS user store migration document. Hence closing the issue.
