### ISSUE TITLE
APIM 2.6.0 to 4.0.0 migration fails when there are endpoint certificates attached

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#629]
### Description

When there is an API having endpoint certificates attached, APIM revision migration fails with the following error.

```
[2022-08-12 18:22:28,030]  INFO - MigrateFrom320 WSO2 API-M Migration Task : Starting API Revision related migration for tenant 1(adpexample.com)
[2022-08-12 18:22:30,938] ERROR - APIMMigrationService WSO2 API-M Migration Task : Generic exception occurred while migrating
java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_301]
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113) ~[?:1.8.0_301]
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1906) ~[commons-io_2.4.0.wso2v1.jar:?]
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:778) ~[commons-io_2.4.0.wso2v1.jar:?]
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:803) ~[commons-io_2.4.0.wso2v1.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIMgtDBUtil.getStringFromInputStream_aroundBody12(APIMgtDBUtil.java:168) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIMgtDBUtil.getStringFromInputStream(APIMgtDBUtil.java:165) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.CertificateMgtDAO.getCertificates_aroundBody16(CertificateMgtDAO.java:349) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.CertificateMgtDAO.getCertificates(CertificateMgtDAO.java:314) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.impl.certificatemgt.CertificateManagerImpl.getCertificates_aroundBody28(CertificateManagerImpl.java:374) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.impl.certificatemgt.CertificateManagerImpl.getCertificates(CertificateManagerImpl.java:364) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.getEndpointCertificateContentAndMetaData(ExportUtils.java:757) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.185.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.addEndpointCertificatesToArchive(ExportUtils.java:679) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.185.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ExportUtils.exportApi(ExportUtils.java:196) ~[org.wso2.carbon.apimgt.rest.api.publisher.v1.common_9.0.174.185.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.ImportExportAPIServiceImpl.exportAPI(ImportExportAPIServiceImpl.java:113) ~[?:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPIRevision_aroundBody574(APIProviderImpl.java:9214) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPIRevision(APIProviderImpl.java:9176) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPIRevision(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.migration.client.MigrateFrom320.apiRevisionRelatedMigration(MigrateFrom320.java:346) ~[org.wso2.carbon.apimgt.migrate.client-4.0.0.1-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.migration.APIMMigrationService.completedServerStartup(APIMMigrationService.java:275) [org.wso2.carbon.apimgt.migrate.client-4.0.0.1-SNAPSHOT.jar:?]
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyAfter(CarbonCoreServiceComponent.java:264) [org.wso2.carbon.core_4.6.2.275.jar:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:218) [org.wso2.carbon.core_4.6.2.275.jar:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:323) [org.wso2.carbon.core_4.6.2.275.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) [org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:118) [org.wso2.carbon.tenant.throttling.agent_4.9.10.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:96) [org.wso2.carbon.tenant.throttling.agent_4.9.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_301]
```

The AM_CERTIFICATE_METADATA table's CERTIFICATE column is null even after migration.

### Steps to Reproduce

1. Perform a migration from APIM 2.6.0 to 4.0.0 with an API having endpoint certificates attached.
2. Observe the error.

### Affected Component

APIM

### Version

4.0.0

**Comment by msm1992** [comment]
Fixed in 4.0.0 with https://github.com/wso2-extensions/apim-migration-resources/pull/259.
In 4.1.0 we run the DB Data migration(which includes certificate migration) prior to registry data migration(which includes revision related migration). Hence this is N/A for 4.1.0/master branches.
