### ISSUE TITLE
[APIM-3.2.0] - SQL Exception: Unable to load the applications in the Devportal

### ISSUE THREAD

**Issue by Hamool-Nizar** [wso2/api-manager#648]
### Description

Unable load the applications in the devportal after updating to the 3.2.0.188 update level. This issue is only occurring to one particular admin - user ("apim00m") and rest of the users can list the application in the devportal without any issues. When we try listing the applications using this particular admin - user ("apim00m") then we are getting the following errors in the APIM log.

`[2022-08-12 11:07:42,833] ERROR - ApiMgtDAO Error when reading the application information from the persistence store
[2022-08-12 11:07:42,895] ERROR - ApplicationsApiServiceImpl Error while retrieving Applications
at java.lang.Thread.run(Thread.java:834) [?:?]
...

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.ApplicationsApi.applicationsGet(ApplicationsApi.java:431) [classes/:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl.applicationsGet(ApplicationsApiServiceImpl.java:120) [classes/:?]
at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getApplicationsWithPagination(APIConsumerImpl.java:4732) [org.wso2.carbon.apimgt.impl_6.7.206.339.jar:?]
at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getApplicationsWithPagination_aroundBody182(APIConsumerImpl.java:4735) [org.wso2.carbon.apimgt.impl_6.7.206.339.jar:?]
at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getApplicationsWithPagination(ApiMgtDAO.java:4551) [org.wso2.carbon.apimgt.impl_6.7.206.339.jar:?]
at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getApplicationsWithPagination_aroundBody206(ApiMgtDAO.java:4654) [org.wso2.carbon.apimgt.impl_6.7.206.339.jar:?]
at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:596) ~[ojdbc10.jar:19.3.0.0.0]
at oracle.jdbc.driver.InsensitiveScrollableResultSet.findColumn(InsensitiveScrollableResultSet.java:270) ~[ojdbc10.jar:19.3.0.0.0]
at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3857) ~[ojdbc10.jar:19.3.0.0.0]
at oracle.jdbc.driver.OracleStatement.getColumnIndexPrimitive(OracleStatement.java:3899) ~[ojdbc10.jar:19.3.0.0.0]
java.sql.SQLException: Invalid column name
at java.lang.Thread.run(Thread.java:834) [?:?]
...
`

### Steps to Reproduce

1. Login into devportal.
2. List the Applications.

### Affected Component

APIM

### Version

3.2.0

### Relevant Log Output

```shell
[2022-08-12 11:07:42,833] ERROR - ApiMgtDAO Error when reading the application information from the persistence store
[2022-08-12 11:07:42,895] ERROR - ApplicationsApiServiceImpl Error while retrieving Applications
at java.lang.Thread.run(Thread.java:834) [?:?]
...

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.ApplicationsApi.applicationsGet(ApplicationsApi.java:431) [classes/:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl.applicationsGet(ApplicationsApiServiceImpl.java:120) [classes/:?]
at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getApplicationsWithPagination(APIConsumerImpl.java:4732) [org.wso2.carbon.apimgt.impl_6.7.206.339.jar:?]
at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getApplicationsWithPagination_aroundBody182(APIConsumerImpl.java:4735) [org.wso2.carbon.apimgt.impl_6.7.206.339.jar:?]
at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getApplicationsWithPagination(ApiMgtDAO.java:4551) [org.wso2.carbon.apimgt.impl_6.7.206.339.jar:?]
at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getApplicationsWithPagination_aroundBody206(ApiMgtDAO.java:4654) [org.wso2.carbon.apimgt.impl_6.7.206.339.jar:?]
at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:596) ~[ojdbc10.jar:19.3.0.0.0]
at oracle.jdbc.driver.InsensitiveScrollableResultSet.findColumn(InsensitiveScrollableResultSet.java:270) ~[ojdbc10.jar:19.3.0.0.0]
at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3857) ~[ojdbc10.jar:19.3.0.0.0]
at oracle.jdbc.driver.OracleStatement.getColumnIndexPrimitive(OracleStatement.java:3899) ~[ojdbc10.jar:19.3.0.0.0]
java.sql.SQLException: Invalid column name
at java.lang.Thread.run(Thread.java:834) [?:?]
...
```

**Comment by rmsamitha** [comment]
### Issue reproducible scenarios

Below is a note on where this issue can be reproduced based on the code on revision [[1]](https://github.com/wso2-support/carbon-apimgt/blob/a2d5d488877c6e6d43c8342ca002b06312d73df9/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java)

### - Group (org) defined user

1- h2/mysql/mssql/postgres/oracle
(line 4568 ApimgtDAO.java)

enable_application_sharing = true
login_username_case_insensitive = false  (default is true)

2 - h2/mysql/mssql/postgres/oracle/db2
(line 4572 ApimgtDAO.java)

enable_application_sharing = false
login_username_case_insensitive = false

3- h2/mysql/mssql/postgres/oracle/db2

enable_application_sharing = false
login_username_case_insensitive = false
(line 4576 ApimgtDAO.java)

### - Group (org) not defined user

1- mssql/postgres/oracle/db2
(line 4581 ApimgtDAO.java)
enable_application_sharing = true/false
login_username_case_insensitive = true

2 - h2/mysql/mssql/postgres/oracle/db2
(line 4583 ApimgtDAO.java)
enable_application_sharing = true/false
login_username_case_insensitive = false

So the fix is done on those queries on the specified lines.

[1] https://github.com/wso2-support/carbon-apimgt/blob/a2d5d488877c6e6d43c8342ca002b06312d73df9/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/dao/ApiMgtDAO.java

**Comment by rmsamitha** [comment]
This issue is not affected to public branch since the PR [1] caused this issue is not added into master branch.
The fix done through [1] is to resolve issue [2].
So if this same fix [1] is to be ported into master branch too, then it should contain fixes[3] done via this git issue [4]

[1] https://github.com/wso2-support/carbon-apimgt/pull/5256
[2] https://github.com/wso2/api-manager/issues/430
[3] https://github.com/wso2-support/carbon-apimgt/pull/5336
[4] https://github.com/wso2/api-manager/issues/648
