### ISSUE TITLE
Cache Mediator throws ConcurrentModificationException

### ISSUE THREAD

**Issue by DaniduWijendra** [wso2/api-manager#656]
### Description

The customer uses a proxy service in MI, which is used as a cache for JWT tokens. The token endpoint is exposed through a proxy on the MI server and gets tokens through the MI server. The customer explained that they store the response for 3 minutes and then get a new token. In that case, the customer has a lot of concurrent traffic and observed multiple errors like this.

`{proxy:token-proxy} token-proxy = faultSequence ERROR getting token, TraceId = null, HTTP_SC = 200, ERROR_MESSAGE = Runtime error occurred while mediating the message, ERROR_DETAIL = org.apache.synapse.SynapseException: Runtime error occurred while mediating the message at org.apache.synapse.mediators.AbstractMediator.handleException(AbstractMediator.java:376) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:139) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) at org.wso2.carbon.mediator.cache.CacheMediator.replaceEnvelopeWithCachedResponse(CacheMediator.java:387) at org.wso2.carbon.mediator.cache.CacheMediator.processRequestMessage(CacheMediator.java:323) at org.wso2.carbon.mediator.cache.CacheMediator.mediate(CacheMediator.java:250) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:228) at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375) at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:434) at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182) at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834)Caused by: java.util.ConcurrentModificationException at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1208) at java.base/java.util.TreeMap$KeyIterator.next(TreeMap.java:1262) at org.apache.synapse.transport.passthru.util.PassThroughTransportUtils.removeUnwantedHeadersFromHeaderMap(PassThroughTransportUtils.java:142) at org.apache.synapse.transport.passthru.util.PassThroughTransportUtils.removeUnwantedHeaders(PassThroughTransportUtils.java:122) at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:250) at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442) at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:213) at org.apache.synapse.mediators.builtin.RespondMediator.mediate(RespondMediator.java:46) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) ... 17 more}`

### Steps to Reproduce

1. Download the token-proxy.xml proxy service and configure the token endpoint from the API Manager 4.0.0 server.
`<property name="uri.var.uri" value="[https://localhost:9443/oauth2/token"/](https://localhost:9443/oauth2/token%22/)>`
2. Create an application from the dev portal and place the client id and client secret in the proxy service.
`<property name="Authorization" expression="concat('Basic ', base64Encode(concat('upR2uZJj_NTe9UTZmmFwwjV7fnYa',':','2yu5MOhi9Qjftte5wvvudwAEIzka')))" scope="transport"/>`
3. Download the TokenProxyCache.jmx script and run the load test for around 5 minutes.

4. You can observe an error trace in the carbon logs as below.
```
[2022-08-16 14:44:22,922] ERROR {SERVICE_LOGGER.token-proxy} - token-proxy = faultSequence ERROR getting token, TraceId = null, HTTP_SC = 200, ERROR_MESSAGE = Cache-Control:no-store,cacheKey:2422127-35-25-101-112808915-50-377-90-8472,Content-Type:application/json,messageType:application/json,Pragma:no-cache,Server:WSO2 Carbon Server,X-Content-Type-Options:nosniff,X-Frame-Options:DENY,X-XSS-Protection:1; mode=block, Unexpected error sending message back, ERROR_DETAIL = org.apache.synapse.SynapseException: Cache-Control:no-store,cacheKey:2422127-35-25-101-112808915-50-377-90-8472,Content-Type:application/json,messageType:application/json,Pragma:no-cache,Server:WSO2 Carbon Server,X-Content-Type-Options:nosniff,X-Frame-Options:DENY,X-XSS-Protection:1; mode=block, Unexpected error sending message back
	at org.apache.synapse.core.axis2.Axis2Sender.handleException(Axis2Sender.java:285)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:216)
	at org.apache.synapse.mediators.builtin.RespondMediator.mediate(RespondMediator.java:46)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.wso2.carbon.mediator.cache.CacheMediator.replaceEnvelopeWithCachedResponse(CacheMediator.java:387)
	at org.wso2.carbon.mediator.cache.CacheMediator.processRequestMessage(CacheMediator.java:323)
	at org.wso2.carbon.mediator.cache.CacheMediator.mediate(CacheMediator.java:250)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:228)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:434)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.axis2.AxisFault: Failed to submit the response
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.handleException(PassThroughHttpSender.java:656)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:292)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:213)
	... 19 more
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1208)
	at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1244)
	at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1239)
	at org.apache.synapse.transport.passthru.util.SourceResponseFactory.addResponseHeader(SourceResponseFactory.java:154)
	at org.apache.synapse.transport.passthru.util.SourceResponseFactory.create(SourceResponseFactory.java:99)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:527)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:290)
	... 21 more
```

### Affected Component

MI

### Version

4.0.0

### Relevant Log Output

```shell
[2022-08-16 14:44:22,922] ERROR {SERVICE_LOGGER.token-proxy} - token-proxy = faultSequence ERROR getting token, TraceId = null, HTTP_SC = 200, ERROR_MESSAGE = Cache-Control:no-store,cacheKey:2422127-35-25-101-112808915-50-377-90-8472,Content-Type:application/json,messageType:application/json,Pragma:no-cache,Server:WSO2 Carbon Server,X-Content-Type-Options:nosniff,X-Frame-Options:DENY,X-XSS-Protection:1; mode=block, Unexpected error sending message back, ERROR_DETAIL = org.apache.synapse.SynapseException: Cache-Control:no-store,cacheKey:2422127-35-25-101-112808915-50-377-90-8472,Content-Type:application/json,messageType:application/json,Pragma:no-cache,Server:WSO2 Carbon Server,X-Content-Type-Options:nosniff,X-Frame-Options:DENY,X-XSS-Protection:1; mode=block, Unexpected error sending message back
	at org.apache.synapse.core.axis2.Axis2Sender.handleException(Axis2Sender.java:285)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:216)
	at org.apache.synapse.mediators.builtin.RespondMediator.mediate(RespondMediator.java:46)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.wso2.carbon.mediator.cache.CacheMediator.replaceEnvelopeWithCachedResponse(CacheMediator.java:387)
	at org.wso2.carbon.mediator.cache.CacheMediator.processRequestMessage(CacheMediator.java:323)
	at org.wso2.carbon.mediator.cache.CacheMediator.mediate(CacheMediator.java:250)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:228)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:434)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.axis2.AxisFault: Failed to submit the response
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.handleException(PassThroughHttpSender.java:656)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:292)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:213)
	... 19 more
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1208)
	at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1244)
	at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1239)
	at org.apache.synapse.transport.passthru.util.SourceResponseFactory.addResponseHeader(SourceResponseFactory.java:154)
	at org.apache.synapse.transport.passthru.util.SourceResponseFactory.create(SourceResponseFactory.java:99)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:527)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:290)
	... 21 more
```

**Comment by DaniduWijendra** [comment]
Hi team,
Please find the attachment files.(resources.zip)
Thanks,
Danidu
[resources.zip](https://github.com/wso2-enterprise/wso2-apim-internal/files/9350315/resources.zip)
