### ISSUE TITLE
Cannot create or load Integration projects with APIs

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/api-manager#658]
### Description

In the latest(check the below image for versions) Integration studio the following issues can be observed, 
- There is no option to create an API in a project.
- Cannot load an Integration project with APIs.

![Screenshot from 2022-08-22 16-30-03](https://user-images.githubusercontent.com/18748929/185906048-031c327e-c18b-4bd2-a9e1-ec78797c8e86.png)

### Steps to Reproduce

Update the studio to the latest version and try to create a project using the Hello World Service sample in the Getting started window.

### Affected Component

IntegrationStudio

### Version

8.1.0

### Environment Details (with versions)

Ubuntu 20.04.2 LTS

### Relevant Log Output

```shell
org.eclipse.ui.WorkbenchException: Unable to create perspective 'org.wso2.integrationstudio.gmf.esb.diagram.custom.perspective'. There is no corresponding perspective extension.
	at org.eclipse.ui.internal.Workbench.busyShowPerspective(Workbench.java:2898)
	at org.eclipse.ui.internal.Workbench.lambda$18(Workbench.java:2879)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.Workbench.showPerspective(Workbench.java:2877)
	at org.eclipse.ui.internal.Workbench.showPerspective(Workbench.java:2852)
	at org.wso2.integrationstudio.distribution.project.util.MavenMultiModuleImportUtils$3.run(MavenMultiModuleImportUtils.java:488)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:6012)
	at org.wso2.integrationstudio.distribution.project.util.MavenMultiModuleImportUtils.setPerspective(MavenMultiModuleImportUtils.java:481)
	at org.wso2.integrationstudio.distribution.project.util.MavenMultiModuleImportUtils$2.run(MavenMultiModuleImportUtils.java:335)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5101)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4584)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:166)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:368)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1033)
	at org.wso2.integrationstudio.esb.dashboard.templates.maven.wizard.CommonTemplateProjectCreationWizard.performFinish(CommonTemplateProjectCreationWizard.java:103)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1515)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.wso2.integrationstudio.templates.dashboard.web.function.server.JSEmbeddedFunctions.openWizard(JSEmbeddedFunctions.java:87)
	at org.wso2.integrationstudio.templates.dashboard.web.function.server.OpenIDEFunctionServlet$1$1.run(OpenIDEFunctionServlet.java:47)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5101)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4584)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by SanojPunchihewa** [comment]
The issue seems to happen due to the update installation process. Taking a vanilla pack and adapting to the latest version solved this issue.
