### ISSUE TITLE
Oracle syntax issues in AM DB scripts while migrating from 3.2.0 to 4.0.0

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/api-manager#668]
### Description

Incorrect syntax for creating table AM_GW_API_ARTIFACTS in oracle scripts as wrong data type used for ARTIFACT column.

### Steps to Reproduce

Run the am db change scripts in the 3.2.0 to 4.0.0 Migration document.

### Affected Component

APIM

### Version

4.0.0

### Relevant Log Output

[2022-08-24 15:54:42,917] ERROR - InMemoryAPIDeployer Error deploying APIs to the Gateway 
org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.exception.ArtifactSynchronizerException: {"code":900967,"message":"General Error","description":"Server Error Occurred","moreInfo":"","error":[]}Event-Hub status code is : 500
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.DBRetriever.retrieveArtifact_aroundBody4(DBRetriever.java:115) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.DBRetriever.retrieveArtifact(DBRetriever.java:96) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.DBRetriever.retrieveAllArtifacts_aroundBody6(DBRetriever.java:129) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.DBRetriever.retrieveAllArtifacts(DBRetriever.java:121) ~[org.wso2.carbon.apimgt.impl_9.0.174.208.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup_aroundBody4(InMemoryAPIDeployer.java:165) [org.wso2.carbon.apimgt.gateway_9.0.174.204.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAllAPIsAtGatewayStartup(InMemoryAPIDeployer.java:148) [org.wso2.carbon.apimgt.gateway_9.0.174.204.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup_aroundBody2(GatewayStartupListener.java:128) [org.wso2.carbon.apimgt.gateway_9.0.174.204.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsAtStartup(GatewayStartupListener.java:114) [org.wso2.carbon.apimgt.gateway_9.0.174.204.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway_aroundBody18(GatewayStartupListener.java:274) [org.wso2.carbon.apimgt.gateway_9.0.174.204.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.deployArtifactsInGateway(GatewayStartupListener.java:263) [org.wso2.carbon.apimgt.gateway_9.0.174.204.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0_aroundBody28(GatewayStartupListener.java:263) [org.wso2.carbon.apimgt.gateway_9.0.174.204.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.access$0(GatewayStartupListener.java:263) [org.wso2.carbon.apimgt.gateway_9.0.174.204.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run_aroundBody0(GatewayStartupListener.java:358) [org.wso2.carbon.apimgt.gateway_9.0.174.204.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener$AsyncAPIDeployment.run(GatewayStartupListener.java:355) [org.wso2.carbon.apimgt.gateway_9.0.174.204.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[2022-08-24 15:54:42,917] ERROR - GatewayStartupListener Unable to deploy synapse artifacts at gateway. Next retry in 5 seconds
[2022-08-24 15:54:47,985] ERROR - GatewayArtifactsMgtDAO Failed to retrieve Gateway Artifact for labels : ,[Ljava.lang.String;@55377385
java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

**Comment by dushaniw** [comment]
In 3.2.0 -> 4.0.0 migration doc artifact column type is MEDIUMBLOB which is invalid

![image](https://user-images.githubusercontent.com/12208083/186418518-1c5b815c-1db7-4c6e-b11d-304b550493ba.png)

This should be corrected as other docs (3.1.0, 3.0.0, 2.6.0 -> 4.0.0).

![image](https://user-images.githubusercontent.com/12208083/186418824-48fcfb6c-93d7-4f0c-ae39-3c40e2263468.png)
