### ISSUE TITLE
[2.5.0] Load balanced endpoints retries infinite number of times

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#694]
### Description

Load balanced endpoints retries infinite number of times
```
waiting to lock <0x00000005c01505c8> (a org.apache.log4j.spi.RootLogger) at org.apache.log4j.Category.forcedLog(Category.java:391) at org.apache.log4j.Category.log(Category.java:856) at org.apache.commons.logging.impl.Log4JLogger.error(Log4JLogger.java:229) at org.apache.synapse.core.axis2.Axis2Sender.handleException(Axis2Sender.java:285) at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:91) at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:547) at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:384) at org.apache.synapse.endpoints.HTTPEndpoint.send(HTTPEndpoint.java:85) at org.apache.synapse.endpoints.LoadbalanceEndpoint.sendMessage(LoadbalanceEndpoint.java:223) at org.apache.synapse.endpoints.LoadbalanceEndpoint.send(LoadbalanceEndpoint.java:169) at org.apache.synapse.endpoints.LoadbalanceEndpoint.onChildEndpointFail(LoadbalanceEndpoint.java:343) at org.apache.synapse.endpoints.AbstractEndpoint.invokeNextFaultHandler(AbstractEndpoint.java:718) at org.apache.synapse.endpoints.AbstractEndpoint.onFault(AbstractEndpoint.java:536) at org.apache.synapse.endpoints.HTTPEndpoint.onFault(HTTPEndpoint.java:66) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:101) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:106) at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98) at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:338) at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158) at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
```

### Steps to Reproduce

Steps to reproduce:

1. Create a backend that takes around 200000 ms to send a reply.
2. Create a load-balanced endpoint in APIM and configured the above backend as a child endpoint.
3. Configure the endpoint suspension as initialDuration = 0, progressionFactor = 1.0 and maximumDuration =0
When we invoke the API even though the endpoint gets timeout it re-tries for an infinite no of times.

### Affected Component

APIM

### Version

2.5.0

**Comment by msm1992** [comment]
Public fix available with https://github.com/wso2/wso2-synapse/pull/1660/files
