### ISSUE TITLE
Fault sequence will not invoke when the connection reset is there - Web Socket API - APIM 3.2.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#716]
### Description

Fault sequence will not invoke when the connection reset is there for the web socket APIs.

### Steps to Reproduce

- Start the API manager and the configure backend through the websocket API.
- Generate a JWT and open the WS connection through the wscat command.
- After that, kill the backend port by using the below command.

```
sudo tcpkill -i  port 
sudo tcpkill -i lo port 7000
```

- Again try to send a message through the open socket and will get the **Connection Reset** error in the carbon logs as below. In there, cannot see any log mediator results in the **fault.xml** file.

```
[2022-07-25 21:57:56,414] ERROR - WebSocketClientHandler Error encountered while processing the response
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_312]
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_312]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_312]
at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_312]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[?:1.8.0_312]
at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258) ~[io.netty.buffer_4.1.73.Final.jar:4.1.73.Final]
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[io.netty.buffer_4.1.73.Final.jar:4.1.73.Final]
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[io.netty.transport_4.1.73.Final.jar:4.1.73.Final]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [io.netty.transport_4.1.73.Final.jar:4.1.73.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [io.netty.common_4.1.73.Final.jar:4.1.73.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.common_4.1.73.Final.jar:4.1.73.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.common_4.1.73.Final.jar:4.1.73.Final]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

### Affected Component

APIM

### Version

3.2.0

**Comment by vinok88** [comment]
HI team,
Kindly share the ETA.

Thanks

**Comment by vinok88** [comment]
Hi @tharikaGitHub,
We have already passed the most likely ETA. Are we on track to deliver this patch?

Thanks,
Vinod
