### ISSUE TITLE
Handle errors in API-M 4.2.0 component startup  during IS  and APIM migration before DB migration

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#748]
From 4.2 onwards, APIM migration client was revamped to run in stepwise migration mode for each version. As APIM and IS migration are two separate tasks, when running IS migration at first on an old data dump, APIM server throws errors in startup when activating some service components. Need to handle this in apim code base by checking the migration system property.
 
Related to https://github.com/wso2/carbon-apimgt/pull/11273

**Comment by Lakith-Rambukkanage** [comment]
Encountered login issues after 2.6.0 migration
tracked by issue : https://github.com/wso2/api-manager/issues/975

**Comment by Lakith-Rambukkanage** [comment]
## Note 
encountered the following error during both IS and APIM migrations, possibly due to migrate system parameter disabling certain flows in (https://github.com/wso2/carbon-apimgt/pull/11627)

```
[2022-11-21 20:15:18,246] ERROR - PolicyRetriever Error while executing the http client
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:353) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:296) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:291) ~[?:?]
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654) ~[?:?]
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473) ~[?:?]
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369) ~[?:?]
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:183) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427) ~[?:?]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient_4.5.13.wso2v1.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.executeHTTPRequest_aroundBody4(APIUtil.java:457) ~[org.wso2.carbon.apimgt.impl_9.27.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.executeHTTPRequest(APIUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.27.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.invokeService(PolicyRetriever.java:240) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.27.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.getPolicies(PolicyRetriever.java:198) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.27.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.getAllApplicationPolicies(PolicyRetriever.java:120) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.27.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.PolicyUtil.deployAllPolicies(PolicyUtil.java:173) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.27.10.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.ThrottlePolicyStartupListener.run(ThrottlePolicyStartupListener.java:76) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.27.10.SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439) ~[?:?]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129) ~[?:?]
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638) ~[?:?]
	... 32 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:?]
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:?]
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[?:?]
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434) ~[?:?]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129) ~[?:?]
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638) ~[?:?]
	... 32 more
```

**Comment by dushaniw** [comment]
@Lakith-Rambukkanage have we copied the keystores properly during migration?

**Comment by Lakith-Rambukkanage** [comment]
Resolved the errors, the errors have been caused by configuration issues in the older version.
Successfully smoke tested a 4.0.0 to 4.2.0 migration with a data populated 4.0.0.

**Comment by Lakith-Rambukkanage** [comment]
Smoke tests with data populated older APIMs:

- [ ] 2.6.0 to 4.2.0
- [ ] 3.0.0 to 4.2.0
- [ ] 3.1.0 to 4.2.0
- [ ] 3.2.0 to 4.2.0
- [x] 4.0.0 to 4.2.0
- [ ] 4.1.0 to 4.2.0

**Comment by Lakith-Rambukkanage** [comment]
Testing will be tracked by: https://github.com/wso2/api-manager/issues/995

**Comment by dushaniw** [comment]
closing the issue as fix https://github.com/wso2/carbon-apimgt/pull/11627 is merged.
