### ISSUE TITLE
[4.1.0] Database connections are getting busy when using Monetization feature

### ISSUE THREAD

**Issue by arunans23** [wso2/api-manager#80]
### Description:

$subject

Caused by: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [https-jsse-nio-9443-exec-45] Timeout: Pool empty. Unable to fetch a connection in 60 seconds, none available[size:50; busy:50; idle:0; lastwait:60000].
    at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:738)
    at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
    at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:136)
    at org.wso2.carbon.identity.core.persistence.JDBCPersistenceManager.getDBConnection(JDBCPersistenceManager.java:147)
    ... 57 more

### Steps to reproduce:

1. Configure monetization with Stripe
https://apim.docs.wso2.com/en/latest/design/api-monetization/monetizing-an-api/

2. When working with feature, you will observe the error.

### Affected product version:

4.1.0

**Comment by hisanhunais** [comment]
Fixed via https://github.com/wso2-extensions/wso2-am-stripe-plugin/pull/37 and is available from org.wso2.apim.monetization.impl-1.4.0.jar onwards
