### ISSUE TITLE
wso2 4.1 APM is getting Event-Hub status code Error during start

### ISSUE THREAD

**Issue by samxzq1983** [wso2/api-manager#818]
### Description

I am using the wso2 API manager 4.1 and deployed 2 instance as HA. In one of my instance, most of the time, starting the wso2 will get following error, which caused all the API request falls into this server return 404 resource not found error. The wired thing is sometimes restart this wso2 instance will not have such error. Does anyone have idea about this?

=====

2022-10-20T14:47:46,224 [-] [Thread-3] WARN SSLUtilBase The trusted certificate with alias [luxtrustglobalrootca] and DN [CN=LuxTrust Global Root, O=LuxTrust s.a., C=LU] is not valid due to [NotAfter: Wed Mar 17 17:51:37 SGT 2021]. Certificates signed by this trusted certificate WILL be accepted 2022-10-20T14:47:48,483 [-] [Thread-38] ERROR PolicyUtil Error in retrieving throttle policies org.wso2.carbon.apimgt.throttle.policy.deployer.exception.ThrottlePolicyDeployerException: Event-Hub status code is : 404 at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.getPolicies(PolicyRetriever.java:203) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.20.74.jar:?] at org.wso2.carbon.apimgt.throttle.policy.deployer.PolicyRetriever.getAllSubscriptionPolicies(PolicyRetriever.java:87) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.20.74.jar:?] at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.PolicyUtil.deployAllPolicies(PolicyUtil.java:159) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.20.74.jar:?] at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.ThrottlePolicyStartupListener.run(ThrottlePolicyStartupListener.java:76) ~[org.wso2.carbon.apimgt.throttle.policy.deployer_9.20.74.jar:?] at java.lang.Thread.run(Thread.java:834) [?:?] 2022-10-20T14:47:48,496 [-] [pool-155-thread-6] ERROR SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404 2022-10-20T14:47:48,496 [-] [Thread-3] ERROR APILoggerManager Could not retrieve subscriptions for tenantDomain : carbon.super 2022-10-20T14:47:48,500 [-] [pool-155-thread-7] ERROR SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404 2022-10-20T14:47:48,501 [-] [pool-155-thread-2] ERROR SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404 2022-10-20T14:47:48,501 [-] [pool-155-thread-1] ERROR SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404 2022-10-20T14:47:48,508 [-] [pool-155-thread-3] ERROR SubscriptionDataLoaderImpl Could not retrieve subscriptions for tenantDomain: carbon.super. Received response with status code 404 2022-10-20T14:47:48,508 [-] [pool-155-thread-6] WARN SubscriptionDataLoaderImpl Failed retrieving /subscription-policies from remote endpoint: Error while retrieving subscription. Retrying after 15 seconds. 2022-10-20T14:47:48,508 [-] [pool-155-thread-3] WARN SubscriptionDataLoaderImpl Failed retrieving /applications from remote endpoint: Error while retrieving subscription. Retrying after 15 seconds. 2022-10-20T14:47:48,508 [-] [Thread-3] ERROR APILoggerManager Error while calling internal service API org.wso2.carbon.apimgt.api.APIManagementException: Error while retrieving subscription from /api-logging-configs at org.wso2.carbon.apimgt.gateway.APILoggerManager.invokeService_aroundBody10(APILoggerManager.java:140) ~[org.wso2.carbon.apimgt.gateway_9.20.74.jar:?] at org.wso2.carbon.apimgt.gateway.APILoggerManager.invokeService(APILoggerManager.java:98) ~[org.wso2.carbon.apimgt.gateway_9.20.74.jar:?] at org.wso2.carbon.apimgt.gateway.APILoggerManager.initializeAPILoggerList_aroundBody0(APILoggerManager.java:58) ~[org.wso2.carbon.apimgt.gateway_9.20.74.jar:?] at org.wso2.carbon.apimgt.gateway.APILoggerManager.initializeAPILoggerList(APILoggerManager.java:56) ~[org.wso2.carbon.apimgt.gateway_9.20.74.jar:?]

### Affected Component

APIM

### Version

4.1

### Environment Details (with versions)

CentOS Linux 7 (Core) 
Kernel: Linux 3.10.0-1160.76.1.el7.x86_64

**Comment by samxzq1983** [comment]
BTW, the wso2 4.1 instance running is migrate from 3.2 by following [This steps](https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410/#step-3-migrate-the-identity-components).

Because my previous 3.2 version is running as HA mode (Active-Active deployment) by using NFS as an underline share folder. During the migration we still mount the share folder for 4.1 since migration step does not mentioned anything about the NFS. But I just noticed, for 4.1 version, there is one note - **You do not need to have a shared file system unless you use secondary user-stores since the matadata of Synapse and rate-limiting policies is persisted to the database.** highlight in [the this document](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/single-node/configuring-an-active-active-deployment/).

Does that mean I should unmount my NFS in 4.1 since I am not using secondary user-stores? And could this be the reason I am getting above error?
