### ISSUE TITLE
Need to improve Migration Client Pre validation step to validate documents

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/api-manager#826]
### Problem

There are errors thrown at indexing step in migration process if there are issues in documents in old setup.

Error 01
[2022-10-05 18:39:12,359] ERROR - DocumentIndexer Error while getting document content. java.io.IOException: Error: End-of-File, expected line at org.apache.pdfbox.pdfparser.BaseParser.readLine(BaseParser.java:1523) ~[org.apache.pdfbox_1.8.16.jar:1.8.16] at org.apache.pdfbox.pdfparser.PDFParser.parseHeader(PDFParser.java:364) ~[org.apache.pdfbox_1.8.16.jar:1.8.16] at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:186) ~[org.apache.pdfbox_1.8.16.jar:1.8.16] at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.fetchDocumentContent_aroundBody4(DocumentIndexer.java:185) ~[org.wso2.carbon.apimgt.impl_9.0.174.221.jar:?] at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.fetchDocumentContent(DocumentIndexer.java:162) ~[org.wso2.carbon.apimgt.impl_9.0.174.221.jar:?] at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.getIndexedDocument_aroundBody0(DocumentIndexer.java:100) [org.wso2.carbon.apimgt.impl_9.0.174.221.jar:?] at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.getIndexedDocument(DocumentIndexer.java:73) [org.wso2.carbon.apimgt.impl_9.0.174.221.jar:?] at org.wso2.carbon.registry.indexing.indexer.IndexDocumentCreator.getIndexDocument(IndexDocumentCreator.java:333) [org.wso2.carbon.registry.indexing_4.7.39.jar:?] at org.wso2.carbon.registry.indexing.indexer.IndexDocumentCreator.createIndexDocument(IndexDocumentCreator.java:96) [org.wso2.carbon.registry.indexing_4.7.39.jar:?] at org.wso2.carbon.registry.indexing.AsyncIndexer$IndexingTask.createIndexDocument(AsyncIndexer.java:245) [org.wso2.carbon.registry.indexing_4.7.39.jar:?] at org.wso2.carbon.registry.indexing.AsyncIndexer$IndexingTask.run(AsyncIndexer.java:210) [org.wso2.carbon.registry.indexing_4.7.39.jar:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_345] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_345] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_345] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_345] at java.lang.Thread.run(Thread.java:750) [?:1.8.0_345]

Error 02
[2022-10-05 18:48:57,867] ERROR - DocumentIndexer Error while getting document content. org.apache.poi.poifs.filesystem.NotOLE2FileException: Invalid header signature; read 0x342E312D46445025, expected 0xE11AB1A1E011CFD0 - Your file appears not to be a valid OLE2 document at org.apache.poi.poifs.storage.HeaderBlock.<init>(HeaderBlock.java:144) ~[poi_3.17.0.wso2v1.jar:?] at org.apache.poi.poifs.storage.HeaderBlock.<init>(HeaderBlock.java:113) ~[poi_3.17.0.wso2v1.jar:?] at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.<init>(NPOIFSFileSystem.java:301) ~[poi_3.17.0.wso2v1.jar:?] at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:81) ~[poi_3.17.0.wso2v1.jar:?] at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.fetchDocumentContent_aroundBody4(DocumentIndexer.java:191) ~[org.wso2.carbon.apimgt.impl_9.0.174.221.jar:?] at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.fetchDocumentContent(DocumentIndexer.java:162) ~[org.wso2.carbon.apimgt.impl_9.0.174.221.jar:?] at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.getIndexedDocument_aroundBody0(DocumentIndexer.java:100) [org.wso2.carbon.apimgt.impl_9.0.174.221.jar:?] at org.wso2.carbon.apimgt.impl.indexing.indexer.DocumentIndexer.getIndexedDocument(DocumentIndexer.java:73) [org.wso2.carbon.apimgt.impl_9.0.174.221.jar:?] at org.wso2.carbon.registry.indexing.indexer.IndexDocumentCreator.getIndexDocument(IndexDocumentCreator.java:333) [org.wso2.carbon.registry.indexing_4.7.39.jar:?] at org.wso2.carbon.registry.indexing.indexer.IndexDocumentCreator.createIndexDocument(IndexDocumentCreator.java:96) [org.wso2.carbon.registry.indexing_4.7.39.jar:?] at org.wso2.carbon.registry.indexing.AsyncIndexer$IndexingTask.createIndexDocument(AsyncIndexer.java:245) [org.wso2.carbon.registry.indexing_4.7.39.jar:?] at org.wso2.carbon.registry.indexing.AsyncIndexer$IndexingTask.run(AsyncIndexer.java:210) [org.wso2.carbon.registry.indexing_4.7.39.jar:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_345] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_345] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_345] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_345] at java.lang.Thread.run(Thread.java:750) [?:1.8.0_345]

### Solution

Need to improve Migration Client Pre validation step to validate documents.

### Affected Component

APIM

### Version

4.0.0

### Related Issues

https://github.com/wso2-enterprise/wso2-apim-internal/issues/781

**Comment by SupunTharakaSandaruwan** [comment]
Hi @CrowleyRajapakse ,

Kind reminder on this and highly appreciate if you can provide an update on this asap as the customer might face document invalid issues for production migration as well.

Regards,
Supun

**Comment by HiranyaKavishani** [comment]
The issue mentioned is not due to a migration effect, it is due to the upgrade of pdfbox/indexer library dependency. So, we don't need to include a pre-validation step here. That was the final conclusion decided as per comment [1] and hence closing the issue.

[1] https://github.com/wso2-enterprise/wso2-apim-internal/issues/781#issuecomment-1290256557
