### ISSUE TITLE
Adding a Subscription Throttling Policy with empty billing plan gives SQL error

### ISSUE THREAD

**Issue by IsuruMaduranga** [wso2/api-manager#854]
### Description

Calling Admin REST API to create a subscription throttling policy with no billing plan value gives SQL error

### Steps to Reproduce

1. Start an APIM server
2. Generate an access token
3. Call **_admin/v3/throttling/policies/subscription_** with following payload
`curl -k -X POST -H "Authorization: Bearer <your token>" -H "Content-Type: application/json" -d @data.json "https://127.0.0.1:9443/api/am/admin/v3/throttling/policies/subscription"`

Use following data.json
```
{
    "policyName": "30PerMin",
    "displayName": "30PerMin",
    "description": "Allows 30 request per minute",
    "isDeployed": false,
    "type": "AdvancedThrottlePolicyInfo",
    "rateLimitCount": 0,
    "subscriberCount": 0,
    "defaultLimit": {
        "type": "REQUESTCOUNTLIMIT",
        "requestCount": {
            "timeUnit": "min",
            "unitTime": 10,
            "requestCount": 30
        },
        "bandwidth": {
            "timeUnit": "min",
            "unitTime": 10,
            "dataAmount": 1000,
            "dataUnit": "KB"
        },
        "eventCount": {
            "timeUnit": "min",
            "unitTime": 10,
            "eventCount": 3000
        }
    }
}
```

### Affected Component

APIM

### Version

4.1.0

### Relevant Log Output

```shell
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "BILLING_PLAN"; SQL statement:
INSERT INTO AM_POLICY_SUBSCRIPTION (NAME, DISPLAY_NAME, TENANT_ID, DESCRIPTION, QUOTA_TYPE, QUOTA, 
 QUOTA_UNIT, UNIT_TIME, TIME_UNIT, IS_DEPLOYED, UUID,  RATE_LIMIT_COUNT, 
 RATE_LIMIT_TIME_UNIT, STOP_ON_QUOTA_REACH, MAX_DEPTH, MAX_COMPLEXITY, 
 BILLING_PLAN, CUSTOM_ATTRIBUTES, MONETIZATION_PLAN, 
 FIXED_RATE, BILLING_CYCLE, PRICE_PER_REQUEST, CURRENCY, CONNECTIONS_COUNT) 
 VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [23502-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:527) ~[h2_2.1.210.wso2v1.jar:?]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496) ~[h2_2.1.210.wso2v1.jar:?]
	at org.h2.message.DbException.get(DbException.java:227) ~[h2_2.1.210.wso2v1.jar:?]
	at org.h2.message.DbException.get(DbException.java:203) ~[h2_2.1.210.wso2v1.jar:?]
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:365) ~[h2_2.1.210.wso2v1.jar:?]
	at org.h2.table.Table.convertInsertRow(Table.java:931) ~[h2_2.1.210.wso2v1.jar:?]
	at org.h2.command.dml.Insert.insertRows(Insert.java:167) ~[h2_2.1.210.wso2v1.jar:?]
	at org.h2.command.dml.Insert.update(Insert.java:135) ~[h2_2.1.210.wso2v1.jar:?]
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:61) ~[h2_2.1.210.wso2v1.jar:?]
	at org.h2.command.CommandContainer.update(CommandContainer.java:174) ~[h2_2.1.210.wso2v1.jar:?]
	at org.h2.command.Command.executeUpdate(Command.java:252) ~[h2_2.1.210.wso2v1.jar:?]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209) ~[h2_2.1.210.wso2v1.jar:?]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169) ~[h2_2.1.210.wso2v1.jar:?]
	at sun.reflect.GeneratedMethodAccessor147.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118) ~[jdbc-pool_9.0.58.wso2v1.jar:?]
	at com.sun.proxy.$Proxy52.executeUpdate(Unknown Source) ~[?:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addSubscriptionPolicy_aroundBody518(ApiMgtDAO.java:10900) ~[org.wso2.carbon.apimgt.impl_9.20.74.47-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addSubscriptionPolicy(ApiMgtDAO.java:10852) ~[org.wso2.carbon.apimgt.impl_9.20.74.47-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addPolicy_aroundBody304(APIProviderImpl.java:6148) ~[org.wso2.carbon.apimgt.impl_9.20.74.47-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addPolicy(APIProviderImpl.java:6106) ~[org.wso2.carbon.apimgt.impl_9.20.74.47-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addPolicy(UserAwareAPIProvider.java:1) ~[org.wso2.carbon.apimgt.impl_9.20.74.47-SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.admin.v1.impl.ThrottlingApiServiceImpl.throttlingPoliciesSubscriptionPost(ThrottlingApiServiceImpl.java:512) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.admin.v1.ThrottlingApi.throttlingPoliciesSubscriptionPost(ThrottlingApi.java:486) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[?:?]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[?:?]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[?:?]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[?:?]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) ~[?:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-servlet-api_9.0.58.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[?:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) ~[org.wso2.carbon.identity.context.rewrite.valve_1.4.52.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) ~[org.wso2.carbon.identity.authz.valve_1.4.52.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) ~[org.wso2.carbon.identity.auth.valve_1.4.52.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:58) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) ~[org.wso2.carbon.tomcat.ext_4.6.3.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat_9.0.58.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_345]
```

**Comment by thisaltennakoon** [comment]
**Task Breakdown** 

- [ ] Reproduce the issue
- [ ]  Identify the fix
- [ ]  Implementation
