### ISSUE TITLE
Error while creating new version of an API using RESTful APIs. 

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/api-manager#876]
### Description

We cannot create a new version of an API using publisher RESTful API in the tenant environment. 

1. Create a new tenant. 
2. Create an API using RESTful API [1] (POST /apis) by using the tenant admin credentials. 
3. Create a new version of the same API using the same REST call. [1] (POST /apis)
- Change only the version in the payload.

The above steps are working fine on in update level 178 but after updating to level 204 you will get the below ERROR.

```
[2022-10-31 15:41:25,830] ERROR - ApisApiServiceImpl Error while adding new API : niran@wso2.com-PizzaShackAPI-2.0.0 - 900977:Block Condition Error::API Context does not exist
org.wso2.carbon.apimgt.api.APIManagementException: 900977:Block Condition Error::API Context does not exist
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.prepareToCreateAPIByDTO(ApisApiServiceImpl.java:448) ~[classes/:?]
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisPost(ApisApiServiceImpl.java:313) [classes/:?]
        at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisPost(ApisApi.java:962) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
```
If you try the same steps in the super tenant it works fine in update level 204 as well. This behavior only can be seen in the tenant environment. 

[1] - https://apim.docs.wso2.com/en/3.2.0/develop/product-apis/publisher-apis/publisher-v1/publisher-v1/#tag/APIs/paths/~1apis/post

Thanks & Regards,
Niran Peiris

### Steps to Reproduce

1. Create a new tenant.
2. Create an API using RESTful API [1] (POST /apis) by using the tenant admin credentials.
3. Create a new version of the same API using the same REST call. [1] (POST /apis)
- Change only the version in the payload.

### Affected Component

APIM

### Version

3.2.0

**Comment by lakshithagunasekara** [comment]
The correct way to handle the scenario you initially mentioned is to use the POST /apis/copy-api[1] to create a copy of the API. Then update the API using PUT /apis/{api-id}. If you follow this method APIM will work accordingly.
