### ISSUE TITLE
Support Kafka server version: kafka 3.1.0 and above

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/api-manager#879]
### Problem

We want to get the support for WSO2 Kafka connector and Kafka Inbound endpoint for Kafka version: kafka_2.12-3.1.0 and want to connect with MI-4.1.0.

We tested the latest Kafka connector:3.1.2 with kafka_2.12-3.1.0 and we were able to successfully publish the messages to Kafka without any issues.

But when using the latest WSO2 Kafka inbound endpoint org.apache.synapse.kafka.poll-1.0.11.jar, we observed the below error when consuming the messages.

[2022-10-26 19:32:54,888] ERROR {TaskQuartzJobAdapter} - Error in executing task: org.apache.kafka.clients.consumer.ConsumerRecord.checksum()J java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.ConsumerRecord.checksum()J
at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.populateMessageContext(KafkaMessageConsumer.java:179)
at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.commitRecords(KafkaMessageConsumer.java:127)
at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.consumeKafkaRecords(KafkaMessageConsumer.java:99)
at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.poll(KafkaMessageConsumer.java:358)
at org.wso2.carbon.inbound.endpoint.protocol.generic.GenericTask.taskExecute(GenericTask.java:40)
at org.wso2.carbon.inbound.endpoint.common.InboundTask.execute(InboundTask.java:49)
at org.wso2.micro.integrator.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:105)
at org.wso2.micro.integrator.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:63)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)

We observed the same issue for the previous org.apache.synapse.kafka.poll-1.0.10.jar Kafka inbound endpoint as well.

We were able to successfully consume the messages by using WSO2 inbound endpoints when using the previous Kafka server version: kafka_2.13-2.8.0.

When analyzing this issue, it seems like Wso2 Kafka inbound endpoint is using a deprecated checksum method in the latest Kafka server versions[2].

When checking the documents as well, we can see the WSO2 recommended Kafka server version is: Kafka_2.11-2.2.1.

Therefore, could you please check the possibility of upgrading the WSO2 Kafka Inbound endpoint to address this issue?

**Steps to reproduce:**

    Download Kafka server[3].
    Start the zookeeper and the Kafka server.
    Add the dependency jar files available in the attached zip file to the <MI_HOME>/lib folder.
    [share.zip](https://github.com/wso2-enterprise/wso2-apim-internal/files/9884985/share.zip)
    Use the attached inbound endpoint configs.
    Publish a message to Kafka and try to consume it.

[1] https://apim.docs.wso2.com/en/latest/reference/connectors/kafka-connector/setting-up-kafka/
[2] https://kafka.apache.org/32/javadoc/org/apache/kafka/clients/consumer/ConsumerRecord.html
[3] https://archive.apache.org/dist/kafka/3.1.0/kafka_2.12-3.1.0.tgzwants to get the support for WSO2 Kafka connector and Kafka Inbound endpoint for Kafka version: kafka_2.12-3.1.0 and wants to connect with MI-4.1.0.

### Solution

upgrading the WSO2 Kafka Inbound endpoint

### Affected Component

MI

### Version

4.1.0

**Comment by chanikag** [comment]
Fixed by https://github.com/wso2-extensions/esb-inbound-kafka/pull/56
