### ISSUE TITLE
Startup error with Traffic Manager profile

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#884]
### Description

The following errors could be seen in Traffic manager profile startup.

```
[2022-11-02 21:45:55,974] ERROR - OAuthServerConfiguration Cannot find class: org.wso2.carbon.identity.oauth2.grant.token.exchange.TokenExchangeGrantHandler
java.lang.ClassNotFoundException: org.wso2.carbon.identity.oauth2.grant.token.exchange.TokenExchangeGrantHandler cannot be found by org.wso2.carbon.identity.oauth_6.9.2
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.wso2.carbon.identity.oauth.config.OAuthServerConfiguration.getSupportedGrantTypes(OAuthServerConfiguration.java:837) ~[org.wso2.carbon.identity.oauth_6.9.2.jar:?]
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getSupportedGrantTypes(OAuth2Util.java:3493) ~[org.wso2.carbon.identity.oauth_6.9.2.jar:?]
	at org.wso2.carbon.identity.oauth2.internal.OAuth2ServiceComponent.activate(OAuth2ServiceComponent.java:195) ~[org.wso2.carbon.identity.oauth_6.9.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:1071) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.idp.mgt.internal.IdPManagementServiceComponent.activate(IdPManagementServiceComponent.java:240) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
.....

[2022-11-02 21:45:55,975]  WARN - OAuthServerConfiguration Grant type : urn:ietf:params:oauth:grant-type:token-exchange, is not added as a supported grant type. Relevant grant handler failed to initiate properly.
```

```
[2022-11-02 21:46:53,592]  WARN - StartupFinalizerServiceComponent Waiting for required OSGi services: org.wso2.carbon.identity.application.authentication.framework.ApplicationAuthenticationService,org.wso2.carbon.identity.oauth.OAuthAdminServiceImpl,
```

### Steps to Reproduce

Profile optimise and start the pack with traffic manager profile.

### Affected Component

APIM

### Version

APIM 4.2.0 M1 testing pack

**Comment by tharikaGitHub** [comment]
First part of the issue is fixed with https://github.com/wasuradananjith/product-apim/commit/8d2ec18b538887118aba3f629941659debbcc6d1

**Comment by tharikaGitHub** [comment]
The following Diff will fix the issue.
[finalDiff.txt](https://github.com/wso2/api-manager/files/9991534/finalDiff.txt)

**Comment by tharikaGitHub** [comment]
This issue is fixed with the commit https://github.com/wasuradananjith/product-apim/commit/a6a1dc532695791a820004462cf652e3adf076ab
