### ISSUE TITLE
Error adding an API State Change Workflow

### ISSUE THREAD

**Issue by thisaltennakoon** [wso2/api-manager#887]
### Description

The following error gets logged in the terminal when trying to approve the API state change pending request in the Admin portal.

### Steps to Reproduce

Follow the instructions in the document [Adding an API State Change Workflow](https://apim.docs.wso2.com/en/latest/design/advanced-topics/adding-an-api-state-change-workflow/#engaging-the-approval-workflow-executor-in-api-manager)

Error is there only when accepting the API state change

### Affected Component

APIM

### Version

4.x.x

### Environment Details (with versions)

OS - macOS Ventura(Version 13.0)
Java Version - 17

### Relevant Log Output

```shell
ERROR - NativeWorkerPool Uncaught exception
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
	at org.wso2.carbon.apimgt.keymgt.SubscriptionDataHolder.getTenantSubscriptionStore_aroundBody8(SubscriptionDataHolder.java:69) ~[org.wso2.carbon.apimgt.keymgt_9.26.62.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.keymgt.SubscriptionDataHolder.getTenantSubscriptionStore(SubscriptionDataHolder.java:1) ~[org.wso2.carbon.apimgt.keymgt_9.26.62.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.keymgt.service.KeyManagerDataServiceImpl.addOrUpdateSubscription_aroundBody4(KeyManagerDataServiceImpl.java:95) ~[org.wso2.carbon.apimgt.keymgt_9.26.62.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.keymgt.service.KeyManagerDataServiceImpl.addOrUpdateSubscription(KeyManagerDataServiceImpl.java:1) ~[org.wso2.carbon.apimgt.keymgt_9.26.62.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage_aroundBody2(GatewayJMSMessageListener.java:216) ~[org.wso2.carbon.apimgt.gateway_9.26.62.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.handleNotificationMessage(GatewayJMSMessageListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.26.62.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage_aroundBody0(GatewayJMSMessageListener.java:113) ~[org.wso2.carbon.apimgt.gateway_9.26.62.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener.onMessage(GatewayJMSMessageListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.26.62.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.common.jms.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:656) ~[org.wso2.carbon.apimgt.common.jms_9.26.62.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.common.jms.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:555) ~[org.wso2.carbon.apimgt.common.jms_9.26.62.SNAPSHOT.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) ~[axis2_1.6.1.wso2v83.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by tharikaGitHub** [comment]
The functionality works fine. But the above error is printed in the terminal.
