### ISSUE TITLE
Error when changing the password of the super_admin user

### ISSUE THREAD

**Issue by thisaltennakoon** [wso2/api-manager#888]
### Description

The following error gets logged in the terminal when trying to change the password of the Admin user in the [Management Console](https://localhost:9443/carbon)

### Steps to Reproduce

Follow the instructions in the document [Managing Users, Roles and Permissions --> Changing a Password](https://docs.wso2.com/display/ADMIN44x/Changing+a+Password)

### Affected Component

APIM

### Version

4.x.x

### Environment Details (with versions)

OS - macOS Ventura(Version 13.0)
Java Version - 17

### Relevant Log Output

```shell
[2022-11-03 15:20:58,093] ERROR - JMSConnectionFactory Error acquiring a Connection from the JMS CF : cacheInvalidationJMSPublisher using properties : {transport.jms.ConcurrentPublishers=allow, java.naming.provider.url=repository/conf/jndi-cp.properties, java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.DestinationType=topic, transport.jms.ConnectionFactoryJNDIName=TopicConnectionFactory, transport.jms.Destination=cacheInvalidation}
javax.jms.JMSException: Error creating connection: not allowed
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:346) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:53) ~[andes_3.3.24.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSUtils.createConnection(JMSUtils.java:387) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.createConnection(JMSConnectionFactory.java:268) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory$PoolableJMSConnectionFactory.makeObject(JMSConnectionFactory.java:356) ~[?:?]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181) ~[commons-pool_1.5.6.wso2v1.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.getConnectionFromPool(JMSConnectionFactory.java:286) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSMessageSender.send(JMSMessageSender.java:86) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.JMSEventAdapter$JMSSender.run(JMSEventAdapter.java:284) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.wso2.andes.AMQConnectionFailureException: not allowed
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:496) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:328) ~[andes_3.3.24.jar:?]
	... 13 more
Caused by: org.wso2.andes.client.AMQAuthenticationException: not allowed
	at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:79) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:554) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:487) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.pool.Job.processAll(Job.java:111) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.pool.Job.run(Job.java:158) ~[andes_3.3.24.jar:?]
	... 3 more
[2022-11-03 15:20:58,093] ERROR - AMQConnection Throwable Received but no listener set.
org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
	at org.wso2.andes.client.protocol.AMQProtocolHandler.closed(AMQProtocolHandler.java:274) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:755) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolSession.closeProtocolSession(AMQProtocolSession.java:379) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:104) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:554) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:487) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.pool.Job.processAll(Job.java:111) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.pool.Job.run(Job.java:158) ~[andes_3.3.24.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-11-03 15:20:58,093] ERROR - AMQConnection Throwable Received but no listener set.
org.wso2.andes.AMQDisconnectedException: Server closed connection and reconnection not permitted.
	at org.wso2.andes.client.protocol.AMQProtocolHandler.closed(AMQProtocolHandler.java:274) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.transport.network.mina.MinaNetworkHandler.sessionClosed(MinaNetworkHandler.java:150) ~[andes_3.3.24.jar:?]
	at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain$TailFilter.sessionClosed(AbstractIoFilterChain.java:548) ~[andes_3.3.24.jar:?]
	at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.callNextSessionClosed(AbstractIoFilterChain.java:267) ~[andes_3.3.24.jar:?]
	at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.access$800(AbstractIoFilterChain.java:51) ~[andes_3.3.24.jar:?]
	at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.sessionClosed(AbstractIoFilterChain.java:631) ~[andes_3.3.24.jar:?]
	at org.wso2.org.apache.mina.common.IoFilterAdapter.sessionClosed(IoFilterAdapter.java:65) ~[andes_3.3.24.jar:?]
	at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.callNextSessionClosed(AbstractIoFilterChain.java:267) ~[andes_3.3.24.jar:?]
	at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain.access$800(AbstractIoFilterChain.java:51) ~[andes_3.3.24.jar:?]
	at org.wso2.org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.sessionClosed(AbstractIoFilterChain.java:631) ~[andes_3.3.24.jar:?]
	at org.wso2.org.apache.mina.filter.executor.ExecutorFilter.processEvent(ExecutorFilter.java:230) ~[andes_3.3.24.jar:?]
	at org.wso2.org.apache.mina.filter.executor.ExecutorFilter$ProcessEventsRunnable.run(ExecutorFilter.java:264) ~[andes_3.3.24.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at org.wso2.org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:51) ~[andes_3.3.24.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-11-03 15:20:58,093] ERROR - JMSConnectionFactory Error acquiring a Connection from the JMS CF : cacheInvalidationJMSPublisher using properties : {transport.jms.ConcurrentPublishers=allow, java.naming.provider.url=repository/conf/jndi-cp.properties, java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.DestinationType=topic, transport.jms.ConnectionFactoryJNDIName=TopicConnectionFactory, transport.jms.Destination=cacheInvalidation}
org.wso2.carbon.event.output.adapter.core.exception.OutputEventAdapterRuntimeException: Error acquiring a Connection from the JMS CF : cacheInvalidationJMSPublisher using properties : {transport.jms.ConcurrentPublishers=allow, java.naming.provider.url=repository/conf/jndi-cp.properties, java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.DestinationType=topic, transport.jms.ConnectionFactoryJNDIName=TopicConnectionFactory, transport.jms.Destination=cacheInvalidation}
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.handleException(JMSConnectionFactory.java:197) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.createConnection(JMSConnectionFactory.java:278) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory$PoolableJMSConnectionFactory.makeObject(JMSConnectionFactory.java:356) ~[?:?]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181) ~[commons-pool_1.5.6.wso2v1.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.getConnectionFromPool(JMSConnectionFactory.java:286) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSMessageSender.send(JMSMessageSender.java:86) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.JMSEventAdapter$JMSSender.run(JMSEventAdapter.java:284) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: javax.jms.JMSException: Error creating connection: not allowed
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:346) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:53) ~[andes_3.3.24.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSUtils.createConnection(JMSUtils.java:387) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.createConnection(JMSConnectionFactory.java:268) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	... 10 more
Caused by: org.wso2.andes.AMQConnectionFailureException: not allowed
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:496) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:328) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:53) ~[andes_3.3.24.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSUtils.createConnection(JMSUtils.java:387) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory.createConnection(JMSConnectionFactory.java:268) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	... 10 more
Caused by: org.wso2.andes.client.AMQAuthenticationException: not allowed
	at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:79) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:554) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:487) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.pool.Job.processAll(Job.java:111) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.pool.Job.run(Job.java:158) ~[andes_3.3.24.jar:?]
	... 3 more
[2022-11-03 15:20:58,093] ERROR - AMQConnection Throwable Received but no listener set.
org.wso2.andes.AMQException: AMQP timed out when attempting to close the connection 
	at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:746) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolSession.closeProtocolSession(AMQProtocolSession.java:379) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:104) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchConnectionClose(ClientMethodDispatcherImpl.java:192) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:554) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:487) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.pool.Job.processAll(Job.java:111) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.pool.Job.run(Job.java:158) ~[andes_3.3.24.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.wso2.andes.AMQTimeoutException: Server did not respond in a timely fashion
	at org.wso2.andes.client.util.BlockingWaiter.block(BlockingWaiter.java:176) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.BlockingMethodFrameListener.blockForFrame(BlockingMethodFrameListener.java:122) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolHandler.writeCommandFrameAndWaitForReply(AMQProtocolHandler.java:689) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolHandler.syncWrite(AMQProtocolHandler.java:711) ~[andes_3.3.24.jar:?]
	at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:742) ~[andes_3.3.24.jar:?]
	... 14 more
[2022-11-03 15:20:58,093] ERROR - JMSMessageSender Cannot invoke "org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory$JMSPooledConnectionHolder.getProducer()" because "pooledConnection" is null
java.lang.NullPointerException: Cannot invoke "org.wso2.carbon.event.output.adapter.jms.internal.util.JMSConnectionFactory$JMSPooledConnectionHolder.getProducer()" because "pooledConnection" is null
	at org.wso2.carbon.event.output.adapter.jms.internal.util.JMSMessageSender.send(JMSMessageSender.java:88) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at org.wso2.carbon.event.output.adapter.jms.JMSEventAdapter$JMSSender.run(JMSEventAdapter.java:284) ~[org.wso2.carbon.event.output.adapter.jms_5.2.45.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by marmo94** [comment]
Hello, if you have special characters in the username/password, it will cause problems

**Comment by tharikaGitHub** [comment]
@marmo94 this error happens even without adding special characters. But the functionality works fine. Only the above logs get printed in the terminal.

**Comment by thisaltennakoon** [comment]
Closing this issue because before changing the password from the management console, first we need to change that in the deployment.toml and restart the server.

Also, this behaviour is there in the APIM 4.1.0
