### ISSUE TITLE
Error when configuring a JDBC User Store as a primary user store

### ISSUE THREAD

**Issue by thisaltennakoon** [wso2/api-manager#901]
### Description

The following error gets logged in the terminal when trying to configure a JDBC User Store as a primary user store

### Steps to Reproduce

Follow the instructions in the document [Configuring a JDBC User Store](https://apim.docs.wso2.com/en/latest/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store/)

### Affected Component

APIM

### Version

4.x.x

### Environment Details (with versions)

OS - macOS Ventura(Version 13.0)
Java Version - 17

### Relevant Log Output

```shell
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:69)
	at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: java.lang.StackOverflowError
	at net.consensys.cava.toml.MutableTomlTable.keyPathSet(MutableTomlTable.java:71)
	at net.consensys.cava.toml.MutableTomlTable.lambda$keyPathSet$1(MutableTomlTable.java:80)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.consensys.cava.toml.MutableTomlTable.keyPathSet(MutableTomlTable.java:92)
	at net.consensys.cava.toml.MutableTomlTable.lambda$keyPathSet$1(MutableTomlTable.java:80)

.........................
.........................
```

**Comment by tharikaGitHub** [comment]
@thisaltennakoon can you share the deployment.toml configurations that you added? Seems there is a parsing error in the configurations.

**Comment by thisaltennakoon** [comment]
Closing this issue as this has occurred due to misconfiguration done by me in the deployment.toml when doing testing.
