### ISSUE TITLE
Error when starting the deprecated key manager profile

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#915]
### Description

The following error log gets printed when starting the deprecated key manager profile. Web app deployment fails.

```
[2022-11-12 10:19:23,946]  INFO - TomcatGenericWebappsDeployer Deployed webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/authenticationendpoint].File[/Users/tharika/Documents/Release-APIM-4.2.0/11thNov/KM/repository/deployment/server/webapps/authenticationendpoint]
[2022-11-12 10:19:24,969] ERROR - ContextLoader Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cxf' defined in class path resource [META-INF/cxf/cxf.xml]: Cannot resolve reference to bean 'AuthenticationInterceptor' while setting bean property 'inInterceptors' with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'AuthenticationInterceptor' defined in ServletContext resource [/WEB-INF/beans.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.OAuthAuthenticationInterceptor]: Constructor threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "org.wso2.carbon.apimgt.impl.APIManagerConfiguration.getJwtConfigurationDto()" because "org.wso2.carbon.apimgt.rest.api.common.APIMConfigUtil.configuration" is null
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342) ~[?:?]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113) ~[?:?]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedList(BeanDefinitionValueResolver.java:428) ~[?:?]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:173) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1707) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[?:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[?:?]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[?:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[?:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[?:?]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[?:?]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[?:?]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[?:?]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401) ~[?:?]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292) ~[?:?]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) ~[?:?]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4768) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:303) ~[?:?]
	at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:209) ~[?:?]
	at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.handleWebappDeployment(TomcatGenericWebappsDeployer.java:255) ~[org.wso2.carbon.webapp.mgt_4.11.4.jar:?]
	at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.handleWarWebappDeployment(TomcatGenericWebappsDeployer.java:206) ~[org.wso2.carbon.webapp.mgt_4.11.4.jar:?]
	at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.handleHotDeployment(TomcatGenericWebappsDeployer.java:175) ~[org.wso2.carbon.webapp.mgt_4.11.4.jar:?]
	at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.deploy(TomcatGenericWebappsDeployer.java:140) ~[org.wso2.carbon.webapp.mgt_4.11.4.jar:?]
	at org.wso2.carbon.webapp.mgt.AbstractWebappDeployer.deployThisWebApp(AbstractWebappDeployer.java:224) ~[org.wso2.carbon.webapp.mgt_4.11.4.jar:?]
	at org.wso2.carbon.webapp.mgt.AbstractWebappDeployer.deploy(AbstractWebappDeployer.java:114) ~[org.wso2.carbon.webapp.mgt_4.11.4.jar:?]
	at org.wso2.carbon.webapp.deployer.WebappDeployer.deploy(WebappDeployer.java:42) ~[org.wso2.carbon.webapp.deployer_4.11.4.jar:?]
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:153) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.apache.axis2.deployment.DeploymentEngine.loadServices(DeploymentEngine.java:135) ~[axis2_1.6.1.wso2v83.jar:?]
	at org.wso2.carbon.core.CarbonAxisConfigurator.deployServices(CarbonAxisConfigurator.java:568) ~[org.wso2.carbon.core_4.8.0.m1.jar:?]
	at org.wso2.carbon.core.internal.DeploymentServerStartupObserver.completingServerStartup(DeploymentServerStartupObserver.java:51) ~[?:?]
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyBefore(CarbonCoreServiceComponent.java:258) ~[?:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:166) ~[?:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:323) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:118) ~[org.wso2.carbon.tenant.throttling.agent_4.9.10.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:96) ~[org.wso2.carbon.tenant.throttling.agent_4.9.10.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) ~[org.wso2.carbon.core_4.8.0.m1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) ~[org.wso2.carbon.core_4.8.0.m1.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) ~[org.wso2.carbon.core_4.8.0.m1.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'AuthenticationInterceptor' defined in ServletContext resource [/WEB-INF/beans.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.OAuthAuthenticationInterceptor]: Constructor threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "org.wso2.carbon.apimgt.impl.APIManagerConfiguration.getJwtConfigurationDto()" because "org.wso2.carbon.apimgt.rest.api.common.APIMConfigUtil.configuration" is null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[?:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[?:?]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[?:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[?:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[?:?]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330) ~[?:?]
	... 82 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.OAuthAuthenticationInterceptor]: Constructor threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "org.wso2.carbon.apimgt.impl.APIManagerConfiguration.getJwtConfigurationDto()" because "org.wso2.carbon.apimgt.rest.api.common.APIMConfigUtil.configuration" is null
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[?:?]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[?:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[?:?]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[?:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[?:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[?:?]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330) ~[?:?]
	... 82 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.wso2.carbon.apimgt.impl.APIManagerConfiguration.getJwtConfigurationDto()" because "org.wso2.carbon.apimgt.rest.api.common.APIMConfigUtil.configuration" is null
	at org.wso2.carbon.apimgt.rest.api.common.APIMConfigUtil.getTokenIssuerMap(APIMConfigUtil.java:45) ~[org.wso2.carbon.apimgt.rest.api.common_9.26.69.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.rest.api.util.impl.OAuthJwtAuthenticatorImpl.getTokenIssuers(OAuthJwtAuthenticatorImpl.java:316) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.util.impl.OAuthJwtAuthenticatorImpl.<init>(OAuthJwtAuthenticatorImpl.java:75) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.OAuthAuthenticationInterceptor.<init>(OAuthAuthenticationInterceptor.java:60) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[?:?]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[?:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[?:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[?:?]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[?:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[?:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[?:?]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330) ~[?:?]
	... 82 more
```

### Steps to Reproduce

Profile optimize and start the deprecated key manager profile. (api-key-manager-deprecated)

### Affected Component

APIM

### Version

APIM 4.2.0 M1 testing pack

**Comment by prasa7** [comment]
I was able to reproduce the issue. @tharikaGitHub Currently finding the route cause of the issue

**Comment by Tharanidk** [comment]
Update -2023-01-17

- I was able to reproduce the issue. 
- Working on finding the route cause of the error.

**Comment by Tharanidk** [comment]
Update -2023-01-19

-Analyzed the stack trace and went through the path where a null point exception is produced.
- Still couldn't find the reason for this error.

**Comment by Tharanidk** [comment]
I have analyzed the issue with @AnuGayan and @wasuradananjith.

- Although it gives an output saying NULL POint issue, it seems this happens not due to a code issue. Some jars are not loading to the OSGI runtime.
- Working on finding the missing jars.

**Comment by Tharanidk** [comment]
Update 2023-01-20

These are the findings
- Analyzed the pack using OSGi commands and found that some components are unsatisfied in the pack
      Unsatisfied		org.wso2.apimgt.broker.lifecycle			
      Unsatisfied		org.wso2.apimgt.cache.invalidation.listener
      Unsatisfied		org.wso2.apimgt.impl.services			
      Unsatisfied		org.wso2.carbon.apimgt.impl.internal.StartupServiceComponent			
      Unsatisfied		org.wso2.apimgt.jms.listener	
      Unsatisfied		api.tokenmgt.component			
      Unsatisfied		org.wso2.carbon.apimgt.tracing.internal.TracingServiceComponent	
      Unsatisfied		org.wso2.carbon.identity.provision.internal.IdentityProvisionServiceComponent

Laterly found that this behaviour is same for 4.1.0 pack as well. But 4.1.0 pack starting fine for the deprecated-keyamanager-profile.

While analysing the unsatisfied components, found that the org.wso2.carbon.apimgt.eventing jar is not found in the 4.2.0 pack. So, added the jar to dropings folder. Still the issue is there.

- Compared the bundles.js files related to deprecated-key-manager-profile in both 4.1.0 and 4.2.0 to find the difference. There after added the missing lined to 4.2.0 bundles.js (ex:azure.key.manager,1.0.1,../plugins/azure.key.manager_1.0.1.jar,4,true). Still the issue is there when starting.

- Tried debugging the 4.1.0 pack with https://github.com/wso2-support/carbon-apimgt repository, debug points are not hitting. Semms like there's no update has gone for 4.1.0 pack related to org.wso2.carbon.apimgt.rest.api.common component.

**Comment by Tharanidk** [comment]
Update 2023-01-23

- Took the  [wso2/carbon-apimgt](https://github.com/wso2/carbon-apimgt)  repository and [wso2/apim-apps](https://github.com/wso2/apim-apps) repository to the latest level and rebuild the pack. Issue is still reproducing.

- Checkedout to https://github.com/wso2/product-apim/commit/296a4e7874eaca37dea8d78c550da7ebce994cbb, and build the product pack taking a new .m2 repository. Issue is not reproducing in that pack. It took more than 6 hours to build the pack.

- There after checked out for the following commit and check whether the issue is reproducing after building the pack.
https://github.com/wso2/product-apim/commit/b4557ede1df3a6a0d5dc2d03299813f4447187df : Issue is reproducing here.

- Got a diff to compare the difference between these two commits

**Comment by Tharanidk** [comment]
Update 2023-01-24

- Tried checking out for middle commits of the same PR and building the product-apim repository to take the pack. It was difficult to build commits as some dependency issues and missing artifacts issues raised.
![Screenshot from 2023-01-25 07-20-22](https://user-images.githubusercontent.com/42825038/214462727-7068b895-b364-4dbe-af0f-5c03b9519471.png)
![Screenshot from 2023-01-25 07-20-35](https://user-images.githubusercontent.com/42825038/214462740-eba3729e-b9f9-42a7-8ffa-07f3d5704626.png)
Also it took more hours than expected to try out these

- Checked out to https://github.com/wso2/product-apim/commit/296a4e7874eaca37dea8d78c550da7ebce994cbb, and built the product pack. Tried applying a few changes using cherry-pick commits. build failures similar to the above happened.

- Starting from the commit https://github.com/wso2/product-apim/commit/296a4e7874eaca37dea8d78c550da7ebce994cbb,, tried applying changes manually.

**Comment by Tharanidk** [comment]
Seems the issue is happening because of the set of commits that were cherry-picked.(from https://github.com/wso2/product-apim/commit/2735893866893c542f6dbf7de86b521823c2c4af to https://github.com/wso2/product-apim/commit/fad96fa9c14245b3f6c5748d88f92862951fcb1c)

**Comment by AnuGayan** [comment]
Hi All,

I was able to fix the above error by adding the following packages to the Key-Manager profile.

``` XML
<feature>
     <id>org.wso2.carbon.apimgt.keymanager.feature.group</id>
     <version>${carbon.apimgt.version}</version>
 </feature>
 <feature>
     <id>org.wso2.carbon.apimgt.internal.service.feature.group</id>
     <version>${carbon.apimgt.version}</version>
 </feature>
 <feature>
     <id>org.wso2.carbon.andes.server.feature.group</id>
     <version>${carbon.messaging.version}</version>
 </feature>

 <feature>
     <id>org.wso2.carbon.apimgt.eventing.feature.group</id>
     <version>${carbon.apimgt.version}</version>
 </feature>
 <feature>
     <id>org.wso2.carbon.apimgt.eventing.hub.feature.group</id>
     <version>${carbon.apimgt.version}</version>
 </feature>
 <feature>
     <id>handy-uri-templates</id>
     <version>${damnhandy.version}</version>
 </feature>
```

By adding the eventing hub feature, it executes the CorrelationConfigManager and logs the following error,

`CorrelationConfigManager Failed retrieving correlation configs. Retrying after 4 seconds...`

It seems like even though the correlation_logs is disabled, the correlation config manager is getting initialized. Need to verify the behaviour and find a fix to mitigate this.

Thank You,
Anusha

**Comment by AnuGayan** [comment]
Hi All,

Had a chat with Tharindu today morning and he suggested removing the client-registration#v0.17 web app from the profile which is related to the above error since it is not needed in the traffic manager. 

Thank You,
Anusha
