### ISSUE TITLE
hot update was not successful

### ISSUE THREAD

**Issue by NahidAfzali** [wso2/api-manager#917]
### Description

I'm running my WSO2 source code with IntelliJ and vscode and this command: "npm start". But when I run devportal this error appears. I changed the node version, the maven version, and also changed IDE. But this error still appears.

What is a solution for this error or maybe a bug?

![Bjocf (1)](https://user-images.githubusercontent.com/83702827/201469979-0259ccd1-2338-4455-bb73-ed634ed8d1c6.png)

### Steps to Reproduce

eccording to the steps in this page: 

https://github.com/wso2/product-apim

after "npm start" this error appears.

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

IDE: VSCode, IntelliJ
windows : 10
npm v7.21.1
Maven v3.6.3
node v16.9.1

### Relevant Log Output

```shell
when I run "mvn clean install" this error appears: "File not found ('source//src//app//**//*.jsx') at module.exports (G:\WSO2\source-code-apim-apps-main\apim-apps-main\portals\devportal\src\main\webapp\node_modules\extract-react-intl-messages-compact\extractReactIntl.js:92:11) at async module.exports (G:\WSO2\source-code-apim-apps-main\apim-apps-main\portals\devportal\src\main\webapp\node_modules\extract-react-intl-messages-compact\index.js:95:25) [ERROR] Command execution failed.", 
and after command "npm start" this error appears:
```

**Comment by tharikaGitHub** [comment]
Hi @NahidAfzali can you try the approach given in article [1]? It should work.

[1] https://tharanidk.medium.com/applying-ui-changes-in-wso2-api-manager-a6f1c1d70167

**Comment by NahidAfzali** [comment]
Yes, I tried it before, but it didn't work. I think there is a problem with userTheme.js and its configuration. Can you help me more?
