### ISSUE TITLE
Error logging into tenant after configuring IS as Key manager with DB Sharing

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#918]
### Description

When trying to login with a tenant to Publisher portal when IS is configured as Key Manager in APIM according to [1],

The following error in logged in IS.
```
[2022-11-13 11:34:18,925] [6be70e93-7c04-4c1b-96d3-b8a9a52ca72b] ERROR {org.wso2.carbon.identity.oauth.endpoint.oidcdiscovery.OIDCDiscoveryEndpoint} - Server Configuration error occurred. org.wso2.carbon.base.ServerConfigurationException: Error while retrieving OIDC Id token issuer value for tenant domain: wso2.com
	at org.wso2.carbon.identity.discovery.builders.ProviderConfigBuilder.buildOIDProviderConfig(ProviderConfigBuilder.java:62)
	at org.wso2.carbon.identity.discovery.DefaultOIDCProcessor.getResponse(DefaultOIDCProcessor.java:62)
	at org.wso2.carbon.identity.oauth.endpoint.oidcdiscovery.OIDCDiscoveryEndpoint.getResponse(OIDCDiscoveryEndpoint.java:103)
	at org.wso2.carbon.identity.oauth.endpoint.oidcdiscovery.OIDCDiscoveryEndpoint.getOIDProviderConfiguration(OIDCDiscoveryEndpoint.java:68)
...
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:153)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:116)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:165)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:111)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
...
Caused by: org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Error while getting Resident Identity Provider of 'wso2.com' tenant.
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getResidentIdp(OAuth2Util.java:3762)
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getIssuerLocation(OAuth2Util.java:3744)
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getIdTokenIssuer(OAuth2Util.java:3714)
	at org.wso2.carbon.identity.discovery.builders.ProviderConfigBuilder.buildOIDProviderConfig(ProviderConfigBuilder.java:60)
	... 58 more
Caused by: org.wso2.carbon.idp.mgt.IdentityProviderManagementException: Error retrieving primary certificate for tenant : wso2.com
	at org.wso2.carbon.idp.mgt.IdentityProviderManager.getResidentIdP(IdentityProviderManager.java:284)
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getResidentIdp(OAuth2Util.java:3758)
	... 61 more
Caused by: org.wso2.carbon.core.util.CryptoException: An error occurred while decrypting data.
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:317)
	at org.wso2.carbon.core.util.CryptoUtil.base64DecodeAndDecrypt(CryptoUtil.java:431)
	at org.wso2.carbon.core.util.KeyStoreManager.getKeyStore(KeyStoreManager.java:145)
	at org.wso2.carbon.idp.mgt.IdentityProviderManager.getResidentIdP(IdentityProviderManager.java:277)
	... 62 more
Caused by: org.wso2.carbon.crypto.api.CryptoException: An error occurred while decrypting using the algorithm : 'RSA/ECB/OAEPwithSHA1andMGF1Padding'
	at org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider.decrypt(SymmetricKeyInternalCryptoProvider.java:152)
	at org.wso2.carbon.crypto.impl.DefaultCryptoService.decrypt(DefaultCryptoService.java:132)
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:311)
	... 65 more
Caused by: java.security.InvalidKeyException: unknown key type passed to RSA
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineInit(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineInit(Unknown Source)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1296)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1236)
	at org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider.decrypt(SymmetricKeyInternalCryptoProvider.java:139)
	... 67 more
```

The following error is logged in APIM.

```
[2022-11-13 11:28:42,804] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
feign.FeignException$InternalServerError: [500 ] during [GET] to [https://localhost:9444/t/wso2.com/oauth2/token/.well-known/openid-configuration] [OpenIDConnectDiscoveryClient#getOpenIdConnectConfiguration()]: [Error in reading configuration.]
	at feign.FeignException.serverErrorStatus(FeignException.java:231) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.FeignException.errorStatus(FeignException.java:180) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.FeignException.errorStatus(FeignException.java:169) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at jdk.proxy33.$Proxy460.getOpenIdConnectConfiguration(Unknown Source) ~[?:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getOpenIdConnectConfigurations_aroundBody772(APIUtil.java:9050) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getOpenIdConnectConfigurations(APIUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAndSetDefaultKeyManagerConfiguration_aroundBody744(APIUtil.java:8638) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAndSetDefaultKeyManagerConfiguration(APIUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
	at org.wso2.carbon.apimgt.impl.APIAdminImpl.getKeyManagerConfigurationsByOrganization_aroundBody28(APIAdminImpl.java:363) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
	at org.wso2.carbon.apimgt.impl.APIAdminImpl.getKeyManagerConfigurationsByOrganization(APIAdminImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
	at org.wso2.carbon.apimgt.internal.service.impl.KeymanagersApiServiceImpl.keymanagersGet(KeymanagersApiServiceImpl.java:47) ~[?:?]
	at org.wso2.carbon.apimgt.internal.service.KeymanagersApi.keymanagersGet(KeymanagersApi.java:48) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
```

This works for the super tenant.

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/

### Steps to Reproduce

1. Configure IS 6.0.0 with APIM according to [1].
2. Create a tenant in API Manager. 
3. Login to publisher portal using this tenant.
4. The following error could be observed in IS 6.0.0 logs
```
[2022-11-13 11:34:18,925] [6be70e93-7c04-4c1b-96d3-b8a9a52ca72b] ERROR {org.wso2.carbon.identity.oauth.endpoint.oidcdiscovery.OIDCDiscoveryEndpoint} - Server Configuration error occurred. org.wso2.carbon.base.ServerConfigurationException: Error while retrieving OIDC Id token issuer value for tenant domain: wso2.com
	at org.wso2.carbon.identity.discovery.builders.ProviderConfigBuilder.buildOIDProviderConfig(ProviderConfigBuilder.java:62)
	at org.wso2.carbon.identity.discovery.DefaultOIDCProcessor.getResponse(DefaultOIDCProcessor.java:62)
	at org.wso2.carbon.identity.oauth.endpoint.oidcdiscovery.OIDCDiscoveryEndpoint.getResponse(OIDCDiscoveryEndpoint.java:103)
	at org.wso2.carbon.identity.oauth.endpoint.oidcdiscovery.OIDCDiscoveryEndpoint.getOIDProviderConfiguration(OIDCDiscoveryEndpoint.java:68)
...
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:153)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:116)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:165)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:111)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
...
Caused by: org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Error while getting Resident Identity Provider of 'wso2.com' tenant.
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getResidentIdp(OAuth2Util.java:3762)
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getIssuerLocation(OAuth2Util.java:3744)
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getIdTokenIssuer(OAuth2Util.java:3714)
	at org.wso2.carbon.identity.discovery.builders.ProviderConfigBuilder.buildOIDProviderConfig(ProviderConfigBuilder.java:60)
	... 58 more
Caused by: org.wso2.carbon.idp.mgt.IdentityProviderManagementException: Error retrieving primary certificate for tenant : wso2.com
	at org.wso2.carbon.idp.mgt.IdentityProviderManager.getResidentIdP(IdentityProviderManager.java:284)
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getResidentIdp(OAuth2Util.java:3758)
	... 61 more
Caused by: org.wso2.carbon.core.util.CryptoException: An error occurred while decrypting data.
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:317)
	at org.wso2.carbon.core.util.CryptoUtil.base64DecodeAndDecrypt(CryptoUtil.java:431)
	at org.wso2.carbon.core.util.KeyStoreManager.getKeyStore(KeyStoreManager.java:145)
	at org.wso2.carbon.idp.mgt.IdentityProviderManager.getResidentIdP(IdentityProviderManager.java:277)
	... 62 more
Caused by: org.wso2.carbon.crypto.api.CryptoException: An error occurred while decrypting using the algorithm : 'RSA/ECB/OAEPwithSHA1andMGF1Padding'
	at org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider.decrypt(SymmetricKeyInternalCryptoProvider.java:152)
	at org.wso2.carbon.crypto.impl.DefaultCryptoService.decrypt(DefaultCryptoService.java:132)
	at org.wso2.carbon.core.util.CryptoUtil.decrypt(CryptoUtil.java:311)
	... 65 more
Caused by: java.security.InvalidKeyException: unknown key type passed to RSA
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineInit(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineInit(Unknown Source)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1296)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1236)
	at org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider.decrypt(SymmetricKeyInternalCryptoProvider.java:139)
	... 67 more
```
5. The following error could be observed in APIM logs.
 ```
[2022-11-13 11:28:42,804] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
feign.FeignException$InternalServerError: [500 ] during [GET] to [https://localhost:9444/t/wso2.com/oauth2/token/.well-known/openid-configuration] [OpenIDConnectDiscoveryClient#getOpenIdConnectConfiguration()]: [Error in reading configuration.]
	at feign.FeignException.serverErrorStatus(FeignException.java:231) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.FeignException.errorStatus(FeignException.java:180) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.FeignException.errorStatus(FeignException.java:169) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
	at jdk.proxy33.$Proxy460.getOpenIdConnectConfiguration(Unknown Source) ~[?:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getOpenIdConnectConfigurations_aroundBody772(APIUtil.java:9050) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getOpenIdConnectConfigurations(APIUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAndSetDefaultKeyManagerConfiguration_aroundBody744(APIUtil.java:8638) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getAndSetDefaultKeyManagerConfiguration(APIUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
	at org.wso2.carbon.apimgt.impl.APIAdminImpl.getKeyManagerConfigurationsByOrganization_aroundBody28(APIAdminImpl.java:363) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
	at org.wso2.carbon.apimgt.impl.APIAdminImpl.getKeyManagerConfigurationsByOrganization(APIAdminImpl.java:1) ~[org.wso2.carbon.apimgt.impl_9.27.0.jar:?]
	at org.wso2.carbon.apimgt.internal.service.impl.KeymanagersApiServiceImpl.keymanagersGet(KeymanagersApiServiceImpl.java:47) ~[?:?]
	at org.wso2.carbon.apimgt.internal.service.KeymanagersApi.keymanagersGet(KeymanagersApi.java:48) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
```

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/

### Affected Component

APIM

### Version

APIM 4.2.0 M1 testing pack

**Comment by thisaltennakoon** [comment]
This error has occurred because IS 6.0.0 uses Symmetric encryption as default and APIM uses Asymmetric algorithm as default.
Adding following configuration to <IS_HOME>/repository/conf/deployment.toml can solve this issue.

[keystore]
userstore_password_encryption = "InternalKeyStore"

[system.parameter]
"org.wso2.CipherTransformation"="RSA/ECB/OAEPwithSHA1andMGF1Padding"

[encryption]
internal_crypto_provider = "org.wso2.carbon.crypto.provider.KeyStoreBasedInternalCryptoProvider"
