### ISSUE TITLE
Different versions of the same common API Policy cannot be enforced to the same API

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/api-manager#951]
### Description

When we try to enforce different versions of the same common API Policy, to two resource in the same API an error occurs.resources

### Steps to Reproduce

1. Log in to the Publisher portal
2. Create a common API Policy (global operation policy) by uploading the policy here [AMyPolicy_v1.j2.txt](https://github.com/wso2/api-manager/files/10027327/AMyPolicy_v1.j2.txt) as shown below (Make sure to give the details as shown in the screenshot and before uploading, make sure the change the extension **.j2.txt** to **.j2**). 
![image](https://user-images.githubusercontent.com/25246848/202344836-14d3fc8d-970f-4d3c-92e6-ae9b1f61507f.png)
3. Go to the APIs section and create and deploy the sample PizzaShack API.
4. Go to the Policies section of the PizzaShackAPI and add your created policy (AMyPolicy v1) as a request flow for the resource **GET /order/{orderId}**. (Give the propertyName and propertyValue as "v1PropertyName" and "v1PropertyValue")
5. Save and deploy a revision of the API.
6. Now go to the Developer portal, create an application, subscribe to this API, generate keys and invoke the **GET /order/{orderId}** resource of the API. You may see a log as shown below will be printed on the server which is coming from the enforced policy.
```
[2022-11-17 08:27:23,954]  INFO - LogMediator {api:PizzaShackAPI:v1.0.0} v1PropertyName = v1PropertyValue, VALUE IS:  = 456
```
7. Now, create another common API Policy (global operation policy) by uploading the policy here [AMyPolicy_v2.j2.txt](https://github.com/wso2/api-manager/files/10027383/AMyPolicy_v2.j2.txt) as shown below (Make sure to give the details as shown in the screenshot and before uploading, make sure the change the extension **.j2.txt** to **.j2**). 
![image](https://user-images.githubusercontent.com/25246848/202344680-0fbed877-a24b-4390-a3ea-44a399947602.png)
8.  Go to the Policies section of the PizzaShackAPI and add your created policy (AMyPolicy v2) as a response flow for the resource **GET /menu**. (Give the propertyName and propertyValue as "v2PropertyName" and "v2PropertyValue")
9. Now hover the cursor near the added policy of menu resource, you can see it as **AMyPolicy v1 not v2**. This is a bug.
![image](https://user-images.githubusercontent.com/25246848/202345355-0b66038a-1f79-4153-aeb0-918952c17595.png)
10. Save and deploy a new revision of the API. Now you may see an error as below logged on the server.
```
[2022-11-17 08:37:01,006] ERROR - SynapseArtifactGenerator Error while creating Synapse configurations
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.SynapsePolicyAggregator.populatePolicyCaseList(SynapsePolicyAggregator.java:106) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.SynapsePolicyAggregator.generatePolicySequenceForUriTemplateSet(SynapsePolicyAggregator.java:65) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.TemplateBuilderUtil.retrieveOperationPolicySequence(TemplateBuilderUtil.java:1243) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.TemplateBuilderUtil.setCustomSequencesToBeAdded(TemplateBuilderUtil.java:826) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.TemplateBuilderUtil.createAPIGatewayDTOtoPublishAPI(TemplateBuilderUtil.java:720) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.TemplateBuilderUtil.retrieveGatewayAPIDto(TemplateBuilderUtil.java:444) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.TemplateBuilderUtil.retrieveGatewayAPIDto(TemplateBuilderUtil.java:477) ~[?:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.common.SynapseArtifactGenerator.generateGatewayArtifact(SynapseArtifactGenerator.java:121) ~[?:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.RuntimeArtifactGeneratorUtil.generateRuntimeArtifact_aroundBody0(RuntimeArtifactGeneratorUtil.java:57) ~[org.wso2.carbon.apimgt.impl_9.27.3.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.RuntimeArtifactGeneratorUtil.generateRuntimeArtifact(RuntimeArtifactGeneratorUtil.java:1) ~[org.wso2.carbon.apimgt.impl_9.27.3.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.internal.service.impl.RuntimeArtifactsApiServiceImpl.runtimeArtifactsGet(RuntimeArtifactsApiServiceImpl.java:61) ~[?:?]
	at org.wso2.carbon.apimgt.internal.service.RuntimeArtifactsApi.runtimeArtifactsGet(RuntimeArtifactsApi.java:47) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[?:?]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[?:?]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[?:?]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[?:?]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222) ~[?:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[tomcat-servlet-api_9.0.58.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[?:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119) ~[org.wso2.carbon.identity.context.rewrite.valve_1.7.1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:116) ~[org.wso2.carbon.identity.context.rewrite.valve_1.7.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:165) ~[org.wso2.carbon.identity.authz.valve_1.7.1.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:111) ~[org.wso2.carbon.identity.auth.valve_1.7.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137) ~[org.wso2.carbon.tomcat.ext_4.8.0.m1.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat_9.0.58.wso2v1.jar:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat_9.0.58.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[2022-11-17 08:37:01,009] ERROR - InMemoryAPIDeployer Error retrieving artifacts for API 74a2877b-a062-4e34-a0db-633e947b0b22. Storage returned null
[2022-11-17 08:37:01,009] ERROR - InMemoryAPIDeployer Error deploying 74a2877b-a062-4e34-a0db-633e947b0b22 in Gateway
org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.exception.ArtifactSynchronizerException: Error retrieving artifacts for API 74a2877b-a062-4e34-a0db-633e947b0b22. Storage returned null
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact_aroundBody2(InMemoryAPIDeployer.java:133) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact(InMemoryAPIDeployer.java:1) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:92) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:1) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run_aroundBody0(GatewayJMSMessageListener.java:175) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run(GatewayJMSMessageListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[2022-11-17 08:37:01,009] ERROR - InMemoryAPIDeployer Error deploying 74a2877b-a062-4e34-a0db-633e947b0b22 in Gateway
org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.exception.ArtifactSynchronizerException: Error deploying 74a2877b-a062-4e34-a0db-633e947b0b22 in Gateway
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact_aroundBody2(InMemoryAPIDeployer.java:138) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact(InMemoryAPIDeployer.java:1) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI_aroundBody0(InMemoryAPIDeployer.java:92) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.deployAPI(InMemoryAPIDeployer.java:1) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run_aroundBody0(GatewayJMSMessageListener.java:175) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayJMSMessageListener$1.run(GatewayJMSMessageListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.wso2.carbon.apimgt.impl.gatewayartifactsynchronizer.exception.ArtifactSynchronizerException: Error retrieving artifacts for API 74a2877b-a062-4e34-a0db-633e947b0b22. Storage returned null
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.retrieveArtifact_aroundBody2(InMemoryAPIDeployer.java:133) ~[org.wso2.carbon.apimgt.gateway_9.27.3.SNAPSHOT.jar:?]
	... 10 more
[2022-11-17 08:37:01,009] ERROR - GatewayJMSMessageListener Error in deploying artifacts for 74a2877b-a062-4e34-a0db-633e947b0b22in the Gateway
```
12. Now go to the Developer portal and invoke the **GET /menu** resource of the API. You may not see any coming from the enforced server as we saw in step 6, this time.

### Affected Component

APIM

### Version

4.2.0-M1

**Comment by wasuradananjith** [comment]
Closing since all the PRs are merged.
