### ISSUE TITLE
Cannot login to MI-Dashboard after update level 68 in MI

### ISSUE THREAD

**Issue by asithamadhushanka12** [wso2/api-manager#959]
### Description

Cannot login to the MI-Dashboard when enabling Correlation logs after update level 68 in MI and observed the below error.

```
[2022-11-08 14:51:50,761] ERROR {org.apache.axis2.transport.base.threads.NativeWorkerPool} - Uncaught exception java.lang.NoSuchMethodError: org.apache.log4j.MDC.put(Ljava/lang/String;Ljava/lang/String;)V
        at org.wso2.carbon.inbound.endpoint.protocol.http.InboundCorrelationEnabledHttpServerWorker.run(InboundCorrelationEnabledHttpServerWorker.java:54)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to Reproduce

- Update MI server to U2 level 68. 
- Enable correlation logs in the MI server. 
- Configure Mi-dashboard with Mi server and try to login to the dashboard. 

### Affected Component

MI

### Version

mi 4.0.0.68

### Suggested Labels

mi

**Comment by dulithsenanayake** [comment]
Hi All,

Closing this ticket as the update is released.

Thanks,
Dulith
