### ISSUE TITLE
Changing the Owner of an Application feature is not working 

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/api-manager#961]
### Description

Changing the Owner of an Application feature[1] is not working as expected. When we changed the owner of an application and delete the previous owner, the application key will not display in the Deportal UI. After that, we are not even allowed to re-generate new application keys. When we try to regenerate the Client Credentials it prints a set of ERRORs and will not allow us to regenerate.
```
[2022-11-10 16:35:28,122] ERROR - AbstractKeyManager Cannot retrieve service provider for the given consumer key : IQm8nWpkLiThVNV0afZSkJgSLmIa
org.wso2.carbon.apimgt.impl.kmclient.KeyManagerClientException: Received status code: 403 Reason: 
        at org.wso2.carbon.apimgt.impl.kmclient.KMClientErrorDecoder.decode_aroundBody0(KMClientErrorDecoder.java:29) ~[org.wso2.carbon.apimgt.impl_9.0.174.245.jar:?]
        at org.wso2.carbon.apimgt.impl.kmclient.KMClientErrorDecoder.decode(KMClientErrorDecoder.java:27) ~[org.wso2.carbon.apimgt.impl_9.0.174.245.jar:?]
        at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96) ~[io.github.openfeign.feign-core_11.0.0.jar:?]
```
[1] - https://apim.docs.wso2.com/en/4.0.0/consume/manage-application/advanced-topics/changing-the-owner-of-an-application/

### Steps to Reproduce

1. Create two users called "niran" and "krishan".
2. Log into the Devportal using "krishan".
3. Create an Application called "app1".
4. Subscribe to an API.
5. Generate Keys and invoke the API.
6. After that change the ownership of the Application to "niran".
7. Log into the Devportal using "niran".
8. I can invoke the API using "app1".
9. Then delete the user "krishan"
10. Log into the Devportal using "niran".
11. Try to generate a new token. 

### Affected Component

APIM

### Version

4.0.0

**Comment by hisanhunais** [comment]
Public fix done via https://github.com/wso2-extensions/apim-km-wso2is/pull/64 and https://github.com/wso2/carbon-apimgt/pull/10845
