### ISSUE TITLE
EI 6.5.0 docker images error - Unable to find JDBC when updating the docker image from 6.5.0.16 to 6.5.0.75 all docker alpine images

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#970]
### Description

Unable to find JDBC when updating the docker image from 6.5.0.16 to 6.5.0.75 all docker alpine images.

activator cannot start user manager core bundle
Caused by: javax.naming.NameNotFoundException: Name [jdbc/WSO2UMDB] is not bound in this Context. Unable to find [jdbc].
at org.apache.naming.NamingContext.lookup(NamingContext.java:824)
at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
at org.wso2.carbon.context.internal.CarbonContextDataHolder$CarbonInitialJNDIContext.lookup(CarbonContextDataHolder.java:709)
at javax.naming.InitialContext.lookup(InitialContext.java:417)
at javax.naming.InitialContext.doLookup(InitialContext.java:290)
at org.wso2.carbon.user.core.util.DatabaseUtil.lookupDataSource(DatabaseUtil.java:89)

### Steps to Reproduce

It seems that something went wrong with the EI 6.5.0 docker images and all level are failing while starting with or without customised configuration with the above error message.

### Affected Component

Analytics

### Version

6.5.0

**Comment by PasanT9** [comment]
This issue is only reproducing in U2 updated packs. Hence closing the issue.
