### ISSUE TITLE
Release build failure due to test location issues in SI

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/api-manager#980]
### Description

SI throw following error message and get failed the release build:
```
[INFO] testOccupancyOfServerRuntimePorts(org.wso2.si.osgi.test.StreamingIntegratorOpenedPortTestcase)  Time elapsed: 0.003 sec  <<< FAILURE!
[INFO] org.ops4j.pax.exam.TestContainerException: Problem starting container
[INFO] 	at org.wso2.carbon.container.CarbonTestContainer.start(CarbonTestContainer.java:175)
[INFO] 	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.setUp(EagerSingleStagedReactor.java:86)
[INFO] 	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.beforeClass(EagerSingleStagedReactor.java:136)
[INFO] 	at org.ops4j.pax.exam.spi.reactors.ReactorManager.beforeClass(ReactorManager.java:448)
[INFO] 	at org.ops4j.pax.exam.testng.listener.PaxExam.runByDriver(PaxExam.java:443)
[INFO] 	at org.ops4j.pax.exam.testng.listener.PaxExam.run(PaxExam.java:308)
[INFO] 	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:209)
[INFO] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[INFO] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
[INFO] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
[INFO] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
[INFO] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
[INFO] 	at org.testng.TestRunner.privateRun(TestRunner.java:782)
[INFO] 	at org.testng.TestRunner.run(TestRunner.java:632)
[INFO] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
[INFO] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
[INFO] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
[INFO] 	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
[INFO] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[INFO] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[INFO] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
[INFO] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
[INFO] 	at org.testng.TestNG.run(TestNG.java:1064)
[INFO] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
[INFO] 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
[INFO] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
[INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
[INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
[INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[INFO] Caused by: java.io.FileNotFoundException: Source 'target/wso2si-test-4.2.0-SNAPSHOT' does not exist
[INFO] 	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1034)
[INFO] 	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:927)
[INFO] 	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:896)
[INFO] 	at org.wso2.carbon.container.CarbonTestContainer.start(CarbonTestContainer.java:132)
[INFO] 	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.setUp(EagerSingleStagedReactor.java:86)
[INFO] 	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.beforeClass(EagerSingleStagedReactor.java:136)
[INFO] 	at org.ops4j.pax.exam.spi.reactors.ReactorManager.beforeClass(ReactorManager.java:448)
[INFO] 	at org.ops4j.pax.exam.testng.listener.PaxExam.runByDriver(PaxExam.java:443)
[INFO] 	at org.ops4j.pax.exam.testng.listener.PaxExam.run(PaxExam.java:308)
[INFO] 	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:209)
```
During the osgi-tests, it try to read wso2si-test-4.2.0-SNAPSHOT, but it could not find it.

### Affected Component

SI

### Version

4.2.0-alpha

**Comment by madushadhanushka** [comment]
Fix https://github.com/wso2/streaming-integrator/pull/294
